### ISSUE TITLE
 How to call method inside tabview to call api and reload content inside the current tab using bloc?

### ISSUE THREAD

**Issue by VickyPrajapati24** [felangel/bloc#3778] opened 2023-03-24 04:33 UTC
I have screen with search bar on top and tabbar with tabviews. I have written my API call using call within tabview's widget. So whenever I switch the tab it call initState method and api call will get called and data will be loaded in the list.
Now the problem is I have searchbar, on user type I want to call method of tabview so I can call the api and reload list with searched results.... But I'm not able to understand how to access tabview's widget to call it's method???

**Here is container page which have search and tab bar with it's views..**

`class _ContainerPageState extends State<ContainerPage>
    with SingleTickerProviderStateMixin {
  final GlobalKey<ScaffoldState> _key = GlobalKey();

  late TabController _tabController;
  String searchText = '';

  @override
  initState() {
    super.initState();

    _tabController = TabController(length: 4, vsync: this, initialIndex: 0);
    _tabController.addListener(() {
    });
  }

  @override
  deactivate() {
    super.deactivate();
    _tabController.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async => false,
      child: Scaffold(
        key: _key,
        backgroundColor: Colors.white,
        body: SafeArea(
            child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 15),
          child: Column(
            children: [
              TextField(
                decoration: InputDecoration(
                  hintText: "Search...",
                  hintStyle: TextStyle(color: Colors.grey.shade600),
                  prefixIcon: Icon(
                    Icons.search,
                    color: Colors.grey.shade600,
                    size: 20,
                  ),
                  border: InputBorder.none,
                  filled: true,
                  fillColor: Colors.grey.shade100,
                  contentPadding: const EdgeInsets.all(8),
                  enabledBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(20),
                      borderSide: BorderSide(color: Colors.grey.shade100)),
                  focusedBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(20),
                      borderSide: BorderSide(color: Colors.grey.shade100)),
                ),
                onSubmitted: (value) {
                  searchText = value;
///////////////Want to call api from here///////////////
                },
              ),
              const SizedBox(height: 20),
              Container(
                height: 40,
                decoration: BoxDecoration(
                    color: Colors.grey[300],
                    borderRadius: BorderRadius.circular(20.0)),
                child: TabBar(
                  isScrollable: true,
                  indicator: BoxDecoration(
                      color: const Color.fromRGBO(89, 147, 189, 1),
                      borderRadius: BorderRadius.circular(20.0)),
                  labelColor: Colors.white,
                  unselectedLabelColor: Colors.black,
                  controller: _tabController,
                  tabs: const [
                    Tab(
                      text: "Tab1",
                    ),
                    Tab(
                      text: 'Tab2',
                    ),
                    Tab(
                      text: 'Tab3',
                    ),
                    Tab(
                      text: 'All',
                    ),
                  ],
                ),
              ),
              Expanded(
                  child: TabBarView(
                controller: _tabController,
                physics: const NeverScrollableScrollPhysics(),
                children: [
                  UserListPage(
                    objTypeEnum: TypeEnum.type1,
                    searchText: searchText,
                  ),
                  UserListPage(
                    objTypeEnum: TypeEnum.type2,
                    searchText: searchText,
                  ),
                  UserListPage(
                    objTypeEnum: TypeEnum.type3,
                    searchText: searchText,
                  ),
                  UserListPage(
                    objTypeEnum: TypeEnum.typeAll,
                    searchText: searchText,
                  ),
                ],
              )),
            ],
          ),
        )),
      ),
    );
  }
}`

**This is tabview's children page**

`class _UserListPageState
    extends State<ContainerPage> {

  String? get searchText => widget.searchText;

  final RefreshController _refreshController =
      RefreshController(initialRefresh: false);

  @override
  initState() {
    super.initState();

    fetchUserList();
  }

  @override
  deactivate() {
    super.deactivate();
  }

  List<TodoDataEntity>? arrTodoDataEntity;

  void fetchUserList() {
 
    Future.microtask(
      () => BlocProvider.of<TodoListBloc>(
        context,
        listen: false,
      ).add(
        TodoListUser(
            objTypeEnum!.rawValue,
            searchText ?? ''),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<TodoListBloc, TodoListState>(builder: (context, state) {
    
      if (state is TodoListInProgress) {
        EasyLoading.show(status: 'Fetching User list...');
      } else if (state is TodoListCallSuccess) {
        EasyLoading.dismiss();

        List<TodoDataEntity> tempArrTodoDataEntity =
            state.arrTodoDataEntity ?? [];
arrTodoDataEntity?.addAll(tempArrTodoDataEntity);
     
      } else if (state is TodoListCallFailed) {
        EasyLoading.dismiss();
      }

      // UI
      if ((state is TodoListCallFailed || state is TodoListInitial) && (arrTodoDataEntity?.isEmpty ?? true)) {
        return Container();
      } else {
        return Column(
          children: <Widget>[
            const SizedBox(height: 15),
            Expanded(
              child: ListView.separated(
                  itemCount: arrTodoDataEntity?.length ?? 0,
                  itemBuilder: (BuildContext context, int index) {
                    return ToDoCell(
                      objTypeEnum: objTypeEnum,
                      onCardClick: () {
                      },
                    );
                  },
                  separatorBuilder: (BuildContext context, int index) =>
                      const Padding(padding: EdgeInsets.symmetric(vertical: 3)),
                ),
          ],
        );
      }
    });
  }
}
`

How to call fetchUserList method from container page's search box typing completion using flutter-bloc????

**Comment by Gene-Dana** [comment] 2023-03-24 14:52
Hey @VickyPrajapati24 may you share with us a repo? it will help us make better suggestions

**Comment by felangel** [comment] 2023-04-15 19:06
Closing for now since there is no minimal reproduction sample. If this is still an issue, please share a link to a minimal reproduction sample and we're happy to take a closer look, thanks! 👍

**Closed by felangel** 2023-04-15 19:06 UTC
Labels: refactor
