### ISSUE TITLE
Sub event in bloc not triggered

### ISSUE THREAD

**Issue by GM-Alex** [felangel/bloc#2431] opened 2021-04-28 22:58 UTC
First I want to say thank you for your awesome work. I have the following problem. I have two blocs a authentication bloc and a login bloc, the authentication blocs only handles the authentication and the login blocs loads the user if.

The AuthenticationBloc class looks like this:

```dart
class AuthenticationBloc extends Bloc<AuthenticationEvent, AuthenticationState> {
  final AuthenticationRepository _authenticationRepository;

  AuthenticationBloc({
    required AuthenticationRepository authenticationRepository
  }) : _authenticationRepository = authenticationRepository,
      super(Uninitialized());

  @override
  Stream<AuthenticationState> mapEventToState(
    AuthenticationEvent event,
  ) async* {
    if (event is Initialize) {
      yield* _mapInitializeToState();
    } else if (event is Unauthenticate) {
        yield* _mapUnauthenticateToState();
    } else if (event is AuthenticateWithGoogle) {
      yield* _mapLoginWithGoogleToState();
    }
  }

  Future<String> _getUserId() async {
    return await _authenticationRepository.getUserId();
  }

  Stream<AuthenticationState> _mapInitializeToState() async* {
    try {
      final isSignedIn = await _authenticationRepository.isSignedIn();

      if (isSignedIn) {
        yield Authenticated(await _getUserId());
      } else {
        yield Unauthenticated();
      }
    } catch (_) {
      yield Unauthenticated();
    }
  }

  Stream<AuthenticationState> _mapUnauthenticateToState() async* {
    await _authenticationRepository.signOut();
    yield Unauthenticated();
  }

  Stream<AuthenticationState> _mapLoginWithGoogleToState() async* {
    yield AuthenticationInProgress();
    
    try {
      await _authenticationRepository.signInWithGoogle();
      yield Authenticated(await _getUserId());
    } catch (_) {
      yield AuthenticationError();
    }
  }
}
```

and the LoginBloc class like that

```dart
class LoginBloc extends Bloc<LoginEvent, LoginState> {
  final UserRepository _userRepository;
  final AuthenticationBloc _authenticationBloc;
  late StreamSubscription _authenticationBlocSubscription;

  LoginBloc({
    required UserRepository userRepository,
    required AuthenticationBloc authenticationBloc
  }) : _userRepository = userRepository,
      _authenticationBloc = authenticationBloc,
      super(LoggedOut())
  {
    _authenticationBlocSubscription = _authenticationBloc.stream.listen((state) {
      if (state is Authenticated) {
        add(Login(state.userId));
      }
    });
  }

  @override
  Future<void> close() {
    _authenticationBlocSubscription.cancel();
    return super.close();
  }

  @override
  Stream<LoginState> mapEventToState(LoginEvent event) async* {
    if (event is Login) {
      yield* _mapLoginToState(userId: event.userId);
    } else if (event is Logout) {
      yield* _mapLogoutToState();
    }
  }

  Stream<LoginState> _mapLoginToState({required String userId}) async* {
    try {
      final User user = await _userRepository.getUser(userId);
      yield LoggedIn(user);
    } on EntityMissingException catch (_) {
      yield NeedsRegistration(userId);
    } catch (_) {
      yield LoggedOut();
    }
  }

  Stream<LoginState> _mapLogoutToState() async* {
    _authenticationBloc.add(Unauthenticate());
    yield LoggedOut();
  }
}
```

Everything works as expected expect the Logout, so the _eventController of the AuthenticationBloc is closed and the event is never triggered. How can I achieve that the Unauthenticate event is triggered at the authentication bloc?

**Comment by narcodico** [comment] 2021-04-29 06:58
Hi @GM-Alex 👋

You should probably not handle the concept of logout in both auth and login features.
They seem like they stepping on each other's toes.
You'd be better of adding a logout event to your auth bloc since it's state is the one controlling where the user is navigated to based on the auth state/status.

**Comment by GM-Alex** [comment] 2021-04-29 07:07
@narcodico I see your point but I'm not a fan of mixing logics within separated "units". I usually try to keep  thinks as small and simple as possible, I was also thinking of making a "big" bloc for the authentication, login  and registry logic but that is not my preferred way, I would like to keep them separated. So in Symfony I would make a service for everything, here authentication, login and registration and subscribe to the events. So maybe my normal pattern will not work here, or is there a way, because I'm not seeing that the are stepping on each other's toes. :)

**Comment by narcodico** [comment] 2021-04-29 07:17
I'd definitely recommend a bloc per feature instead of dropping everything in a single bloc.
The conflict I'm seeing from the partial code you've shared is that you both have an `Unauthenticate` and `Logout` event. So which of the resulting states(`Unauthenticated` and `LoggedOut`) will control navigation ? You only need one for that, so then what's the point of the second one ?

**Comment by GM-Alex** [comment] 2021-04-29 07:29
The login bloc should be the one which decides if a user is logged in because in my case an authenticated user doesn't means that the user is logged in, because like above it could be that the user isn't registered completely. So in the ui part the LoginBloc decides if a user is logged in or not, so in this case `LoggedOut `. So the flow is Auth > Login and vice versa it should be Logout > Unauth. I was also thinking about that before too and by subscribing to the Unauthenticated state of the authentication bloc in the login bloc, but as I said it fells unnatural to me. And if I only use `LoggedOut` I would to need to add the `await _authenticationRepository.signOut();` to the LoginBloc which would mix logics again.

**Comment by narcodico** [comment] 2021-04-29 07:40
This should solve your problem with the auth bloc, that is if you're not doing something else which ends up in it being disposed.

```
 Stream<LoginState> _mapLogoutToState() async* {
    _authenticationBloc.add(Unauthenticate());
    await _authenticationBloc.stream.first;
    yield LoggedOut();
  }
```

**Comment by GM-Alex** [comment] 2021-05-01 22:25
Sorry for the late response. I'm getting the following error with your suggested code:

> [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Unhandled error Bad state: No element occurred in Instance of 'LoginBloc'.

**Comment by GM-Alex** [comment] 2021-05-03 06:13
@narcodico Could it be that if the bloc is not active in any widget it get's closed? So if the user is authenticated and the widget gets destroyed I'm not able to add an event to the authentication bloc? I think that is the case and my mistake, right?

**Comment by narcodico** [comment] 2021-05-03 07:04
My suggestion was based on the assumption that somehow your `LoggedOut` state ended up in removing your `AuthenticationBloc` from the tree. You'd have to share a minimal reproduction sample so that I could see your entire approach.

**Comment by felangel** [comment] 2021-05-19 22:16
Closing for now since there isn't a minimal reproduction sample available. Feel free to provide one and I'm happy to continue the conversation 👍

**Closed by felangel** 2021-05-19 22:16 UTC
Labels: question, waiting for response
