### ISSUE TITLE
Each event awaits for the previous event for completing

### ISSUE THREAD

**Issue by dshukertjr** [felangel/bloc#761] opened 2020-01-03 12:35 UTC
First of all, I love this library and I use it in my every flutter project! 
I think what I am reporting here is a bug, but if it is caused because I missed something, I apologize in advance. 

**Describe the bug**
I have a TextField that emits a event inside onChange method like the following in my Flutter app:

```
TextField(
  onChanged: (query) {
    BlocProvider.of<ShopSearchBloc>(context).add(KeyWordShopsSearchEvent(query));
  },
)
```

Then in my bloc file, I have the following method that will convert this event to state:

```
  Stream<ShopSearchState> _mapKeyWordShopsSearchEventToState(String query) async* {

    // This takes 1 sec
    final shops = await shopRepository.getShops(query: query);

    yield LoadedQueryResultsState(shops: shops);
  }

```

As written in the comment within the code above, I need to get data from a server, which takes about 1 second. 

The problem is that when I type like a word into my TextField, the event is emitted several times in short period of time, and each event seem to wait for the previous event to complete. In another words, when I type "chicago" into my TextField, the event is emitted 7 times and it takes about 7 seconds for the UI to update to the final result. 

**Expected behavior**
Each event should not wait for the previous event, and only the newest event should complete the process when a new event is emitted during execution of an event.

In the above example, the search results should be shown to the UI after approximately 1 sec after the final letter "o" was pressed when searching for the word "chicago".

**Comment by felangel** [comment] 2020-01-03 13:12
Hi @dshukertjr 👋
Thanks for opening an issue and for the positive feedback!

I believe this is a duplicate of https://github.com/felangel/bloc/issues/517. Also with bloc >= 3.0.0 you don't need to cast to Observable. Hope that helps 👍

**Closed by felangel** 2020-01-03 13:12 UTC
