### ISSUE TITLE
BlocProvider for each list item

### ISSUE THREAD

**Issue by SergejSachs** [felangel/bloc#2445] opened 2021-05-05 20:45 UTC
**Description**
Looks like previous values between siblings for the same index at the list from the bloc gets loaded.
But how is this possible If I create the bloc provider inside a list item widget?

Pretty hard to describe but maybe its a more obvious error.

**To Reproduce**

- Create 3 buttons that load different products
- Create a list where this items will be rendered (from BlocA, blocbuilder above the list registered)
- In the list item widget register a bloc provider at any point in the build method (BlocB)

```
return BlocProvider<MarketCurrentPriceBloc>(
      create: (context) => new MarketCurrentPriceBloc(
        RepositoryProvider.of<IMarketService>(context),
        RepositoryProvider.of<ICurrencyExchangeService>(context),
      ),
      child: Align(
        child: BalanceTrend(widget.cryptoBalance),
        alignment: Alignment.centerRight,
      ),
    );
```

- call inside BalanceTrend Widget oninit to get the the value for this position (its specific for each item, changes from time to time), there will be a timer as well to get the current value.

```
context.read<MarketCurrentPriceBloc>().add(GetCurrentMarketPrice(
          widget._balance.assetId,
          isReload: true,
        ));
```

- When you click one of this buttons above always the last value from the previous positions gets loaded

**Expected behavior**
Each item in the  list gets his own bloc created and market price loaded

**Comment by SergejSachs** [comment] 2021-05-05 20:56
The weird thing is If I add a Key to the ListView everything works as excected.
This Id would represent the content of each of the 3 Buttons.

key: Key(state.CustomerId),

**Comment by SergejSachs** [comment] 2021-05-05 21:06
Maybe its because the widgets does not get rebuild for some case because I pass the model to the list item card.

```
return ListView.separated(
      key: Key(state.portfolioId),
      separatorBuilder: (context, index) => Divider(height: 1),
      shrinkWrap: false,
      itemCount: state.cryptoBalances.length,
      scrollDirection: Axis.vertical,
      itemBuilder: (context, index) {
        return CryptoBalanceCard(state.cryptoBalances[index]);
      },
    );
```
With the Key its working like expected but im not sure why.

**Comment by felangel** [comment] 2021-05-08 15:00
Hi @SergejSachs 👋 
Thanks for opening an issue!

Can you please create a minimal reproduction sample which illustrates the problem you're facing? It's hard to say what the issue is without a complete reproduction sample, thanks! 🙏

**Comment by felangel** [comment] 2021-05-19 22:10
Closing for now since there is no reproduction sample.

**Closed by felangel** 2021-05-19 22:10 UTC
Labels: question, waiting for response
