### ISSUE TITLE
onError default implementation should throw an exception 

### ISSUE THREAD

**Issue by guitcastro** [felangel/bloc#494] opened 2019-08-29 19:43 UTC
**Is your feature request related to a problem? Please describe.**
onError does not have a default implementation, which lead do exception getting swallow on mapEventToState or in bloc Delegate
**Describe the solution you'd like**
The default implementation should throw the exception to help users diagnostic erros
**Describe alternatives you've considered**
A nonaggressive approach would be: log the exception instead of throwing it.

**Comment by felangel** [comment] 2019-08-29 22:54
Hi @guitcastro 👋 
Thanks for opening an issue!

The reason why the default onError does not throw is because if an exception is thrown in mapEventToState, the entire stream will be closed and the bloc will stop working. Since blocs are making asynchronous requests pretty frequently, it is fairly common for a developer to omit a try/catch and simply await an operation that can throw.

```dart
mapEventToState(event) async* {
  if (event is MyEvent) {
    final data = await _repository.getData();
    yield MyState(data: data);
  }
}
```

The `getData` call might always succeed during development giving the developer the impression that the code is safe but after the app is deployed to the app store it could start failing (the server could be down etc...).

In cases like that, the consequences of `onError` throwing an exception would be that the app breaks. The bloc would no longer be able to process any other events and from the user's perspective the app might appear to be frozen.

In my opinion, it is better to swallow the unhandled exceptions to enable the blocs to continue functioning. The developer is in full control over if/how they want to implement onError (both at the bloc level and at the BlocDelegate level).

Let me know if that helps 👍

**Comment by felangel** [comment] 2019-09-01 00:22
Closing for now but feel free to comment and I'm happy to continue the conversation 👍

**Comment by timrijckaert** [comment] 2019-09-01 07:15
Maybe when we detect the user is running in debug mode we could throw an Error?

**Comment by felangel** [comment] 2019-09-03 00:27
@timrijckaert that's true I will do a poc and discuss with the team 👍 
Thanks for the suggestion!

**Comment by felangel** [comment] 2019-09-25 02:47
Hey @guitcastro and @timrijckaert I'm not sure how to proceed because I think if this change is made, it should be done in the core bloc library rather than at the flutter layer. The problem is I have not found a reliable way in all platforms (Dart CLI, Flutter, AngularDart) to detect whether the app in running in release/debug mode. Furthermore, it seems like a Dart CLI application until recently was not able to be compiled with AOT (https://github.com/dart-lang/sdk/issues/34343). It was introduced, in Dart v2.3 and would introduce backward compatibility issues.

Did you have anything in mind for this?

**Comment by felangel** [comment] 2019-09-27 00:37
Marking won't fix for now for lack of a universal solution. If anyone has suggestions feel free to comment and I'm happy to reopen this 👍

**Comment by craiglabenz** [comment] 2020-12-16 00:58
@felangel This is possibly a little inelegant, but I think merely _printing_ exceptions as they are being swallowed would help a lot. I spend an inordinate amount of time wondering why my page has stopped responding during development or a test is failing, and it's usually that I added a required field to a model, but not the fixtures, so now I have fake-problems. And so just seeing _something_ about the exception printed would save lots of time.

**Comment by jasonjtyler** [comment] 2021-02-17 05:44
I'm a little confused on this one. I read the comments on why exceptions are consumed, and I totally respect where that decision comes from, but is there no way to find a middle ground between no error at all and the app "breaking"? I stumbled on this because I had a case where I had a silly indexing error in my bloc logic. Problem was it was a data dependent error. I didn't see it in development, it was only reported to me by clients. The silly error took a long time to find however, because I had no information to go off of. I didn't even know about it until someone mentioned it to me. It was only though dialog with the customer that I figured out why that data caused that indexing error. Yikes, right?

Is there some way logging can be attached to blocs in some global way? So, yeah, handle the error, but make a note of it. I'm thinking something like the flutter framework's FlutterError.onError. If there were a way to just log "non-critical" errors, that would would really help save me from myself. Can something like that be done?

By the way, this is a fantastic library. This has been a little hitch for me, but overall I have been very happy using it.

**Comment by felangel** [comment] 2021-02-17 05:51
@jasonjtyler thanks for the feedback! I'm working through a few potential solutions and intend to address this as part of the stable v7.0.0 release 👍

**Comment by felangel** [comment] 2021-03-10 19:22
@craiglabenz @jasonjtyler sorry for the delayed response!

So currently, if an uncaught exception occurs within a bloc, it will trigger `onError` in the `BlocObserver` and when running in debug mode it will also result in an exception.

```dart
enum CounterEvent { increment }
class CounterBloc extends Bloc<CounterEvent, int> {
  CounterBloc() : super(0);

  @override
  Stream<int> mapEventToState(CounterEvent event) async* {
    throw Exception('oops');
  }
}

void main() {
  CounterBloc()..add(CounterEvent.increment);
}
```

This will result in:

```sh
Unhandled error Exception: oops occurred in Instance of 'CounterBloc'. 
#0      CounterBloc.mapEventToState
example/main.dart:111
<asynchronous suspension>

...

Exited (255)
```

In release mode, no exception will be visible but errors will still continue to be reported to the `BlocObserver`.

Does this behavior address your use-cases and if not could you please provide some more context regarding the particular scenario in which you're losing visibility in exceptions within the bloc? Thanks! 🙏

**Comment by craiglabenz** [comment] 2021-03-10 21:05
This is soooooo dreamy, @felangel!

**Comment by jasonjtyler** [comment] 2021-03-15 04:42
This is perfect @felangel, thank you very much!

**Comment by felangel** [comment] 2021-03-15 14:30
Awesome, closing for now but feel free to comment with any questions/concerns and I'm happy to continue the conversation 👍

**Closed by felangel** 2021-03-15 14:30 UTC
Labels: enhancement, pkg:bloc, waiting for response

**Comment by D-James-GH** [comment] 2021-06-01 21:09
Hi, sorry to ask a question after this has closed but, is there any way to use `addError()` in a bloc without it throwing a BlocUnhandledException.  I am handling the error in the BlocObserver in the same way as the counter example here: https://pub.dev/packages/flutter_bloc/example. I need to capture an API exception from all blocs and react to it. It works right now but still throws even though i am handling the error.
