### ISSUE TITLE
Map<> as bloc's state field doesn't work?

### ISSUE THREAD

**Issue by Jaykocha** [felangel/bloc#3331] opened 2022-04-19 17:51 UTC
**Description**
No matter what I tried, it seemed long impossible to emit a new state that will be recognized as such. The state changes before an event is added to the bloc, and therefore the UI does not get updated. 

**Steps To Reproduce**
Minimal code to reproduce the issue: 
```dart

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Mapstate Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => MapBloc(),
      child: const MyHomePageView(),
    );
  }
}

class MyHomePageView extends StatelessWidget {
  const MyHomePageView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final myMap = context.select((MapBloc bloc) => bloc.state.myMap);
    return Scaffold(
      body: Column(
        children: [
          Expanded(
              child: Center(
            child: MaterialButton(
              onPressed: () {
                final randomText = Random().nextInt(1000).toString();
                final newMap = myMap;
                // final newMap = <String,String>{}..addEntries(myMap.entries);  <------ This works
                newMap['key'] = randomText;  // state changes here already when: final newMap = myMap
                context.read<MapBloc>().add(MapBlocEvent(map: newMap));
              },
              child: BlocBuilder<MapBloc, MapBlocState>(
                builder: (context, state) {
                  if (state.myMap.isNotEmpty) {
                    return Text(state.myMap['key'] as String);
                  } else {
                    return const Text('Start');
                  }
                },
              ),
            ),
          )),
        ],
      ),
    );
  }
}
```

With a bloc component as such: 

```dart
class MapBloc extends Bloc<MapBlocEvent, MapBlocState> {
  MapBloc() : super(MapBlocState.initial()) {
    on<MapBlocEvent>(_onMapBlocEvent);
  }

  void _onMapBlocEvent(MapBlocEvent event, Emitter<MapBlocState> emit) {
    emit(state.copyWith(event.map));
  }
}

class MapBlocEvent extends Equatable {
  const MapBlocEvent({required this.map});

  final Map<String, String> map;

  @override
  List<Object> get props => [map];
}

class MapBlocState extends Equatable {
  const MapBlocState({required this.myMap});

  MapBlocState.initial() : this(myMap: {});

  final Map<String, String> myMap;

  @override
  List<Object> get props => [myMap];

  MapBlocState copyWith(Map<String, String>? myMap) {
    return MapBlocState(myMap: myMap ?? this.myMap);
  }
}
```

**Expected Behavior**
I expected the state to change after an event has been added and not before, and therefore the button text should update with a new number.

**Additional Context**
I wanted to use a map, because the objects I have to query from a database have 200+ fields of different (and changing) types and out of them I have to construct some kind of conditional form. The best solution for my case seems to be a state with multiple Map fields representing different categories of the form. 

Is this even a bug, or is this intended behavior? Maybe I lack some basic understanding here? I found a workaround, as I commented in my code snippet, but still wanted to file the issue to get maybe some additional info and possibly help someone in the future struggling with this.

**Comment by marcossevilla** [comment] 2022-04-19 20:46
hey, @Jaykocha 👋 I put up this snippet to dartpad.dev and it seems to work well, you can actually see the transitions on console and they are working as expected. I'm thinking that if it's still not working for you, there's probably another issue that the sample you provided doesn't cover/have. Anyway, here's the working sample, try it on DartPad to see if it works for you:
```dart
import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

class AppBlocObserver extends BlocObserver {
  @override
  void onTransition(Bloc bloc, Transition transition) {
    super.onTransition(bloc, transition);
    print('onTransition ${bloc.runtimeType}: $transition');
  }
}

void main() {
  BlocOverrides.runZoned(
    () => runApp(const MyApp()),
    blocObserver: AppBlocObserver(),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Mapstate Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => MapBloc(),
      child: const MyHomePageView(),
    );
  }
}

class MyHomePageView extends StatelessWidget {
  const MyHomePageView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final myMap = context.select<MapBloc, Map<String, String>>(
      (bloc) => bloc.state.myMap,
    );

    return Scaffold(
      body: Column(
        children: [
          Expanded(
            child: Center(
              child: MaterialButton(
                onPressed: () {
                  final randomText = math.Random().nextInt(1000).toString();
                  final newMap = {'key': randomText};
                  context.read<MapBloc>().add(MapBlocEvent(map: newMap));
                },
                child: myMap.isNotEmpty
                    ? Text(myMap['key'] as String)
                    : const Text('Start'),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class MapBloc extends Bloc<MapBlocEvent, MapBlocState> {
  MapBloc() : super(MapBlocState.initial()) {
    on<MapBlocEvent>(_onMapBlocEvent);
  }

  void _onMapBlocEvent(MapBlocEvent event, Emitter<MapBlocState> emit) {
    emit(state.copyWith(event.map));
  }
}

class MapBlocEvent {
  const MapBlocEvent({required this.map});

  final Map<String, String> map;
}

class MapBlocState {
  const MapBlocState({required this.myMap});

  MapBlocState.initial() : this(myMap: {});

  final Map<String, String> myMap;

  MapBlocState copyWith(Map<String, String>? myMap) {
    return MapBlocState(myMap: myMap ?? this.myMap);
  }

  @override
  String toString() => 'keys: ${myMap.keys}\nvalues: ${myMap.values}';
}

```

**Comment by Jaykocha** [comment] 2022-04-19 21:13
Hey I appreciate your answer! And your example does work fine. But for my case it is important only to update the map and not construct a total new one: 

So instead of `final newMap = {'key': randomText};` I want to do something like:

```dart
final newMap = myMap;
newMap['key'] = randomText;
```

If I replace this in your example, the button does not update.

**Comment by marcossevilla** [comment] 2022-04-19 22:51
but you still create a new map keeping the reference of the one from the state, by creating a new one you just overwrite the current map value. that's working as intended as the bloc's state should be immutable and when it changes it should be through a copyWith or reassigning the value. another thing you can do is to implement an event that updates a value based on a key and emit that new state, but let me know if I need more context on that!

**Comment by Jaykocha** [comment] 2022-04-20 09:01
Ok, thanks, I get it. You can close the "issue". It was actually just a lack of understanding on my side. I didn't really know how provider works and that `final myMap = context.select<MapBloc, Map<String, String>>` is not returning a new map whenever the exposed value changes, but actually it is keeping a reference to that specific map (which in this case is the bloc's state). Then, when I manipulate the myMap variable I am manipulating the state directly, which causes all kind of problems. Ah, I just messed up :D 

Thank you for your time!

**Closed** 2022-04-20 09:02 UTC
Labels: question, waiting for response
