### ISSUE TITLE
How to deal with assert(false) in blocTest?

### ISSUE THREAD

**Issue by danielRi** [felangel/bloc#4199] opened 2024-07-01 07:08 UTC
**Description**
I want to test an event that throws an assertion error, here is how I tried it:

```dart
blocTest<UpdateHistoryBloc, UpdateHistoryState>(
        'WHEN selected is null'
        'THEN emit nothing, expect assertion error',
        seed: () => const UpdateHistoryState.initial(),
        build: () => bloc,
        setUp: () {
          when(selectedRepo.getSelected()).thenReturn(null);
        },
        act: (bloc) => bloc.add(Init()), // will execute assert(false) in this scenario
        expect: () => [],
        verify: (bloc) {
          verify(throwsAssertionError);
        });
```

The test fails with the following output:

```
/Users/Documents/flutter/bin/flutter --no-color test --machine --start-paused test/check_status/update_history_bloc_test.dart
Testing started at 08:58 ...

dart:core                                                                                 _AssertionError._throwNew
package:mobile_flutter/core/vehicles/helper/helper.dart 14:16                    Helper.getSerNo
package:mobile_flutter/widgets/check_status/bloc/update_history_bloc.dart 48:15  UpdateHistoryBloc._handleInit
package:mobile_flutter/widgets/chec_status/bloc/update_history_bloc.dart 42:48  new UpdateHistoryBloc.<fn>
package:bloc/src/bloc.dart 229:26                                                         Bloc.on.<fn>.handleEvent
package:bloc/src/bloc.dart 238:9                                                          Bloc.on.<fn>
===== asynchronous gap ===========================
dart:async                                                                                _CustomZone.registerBinaryCallback
package:bloc/src/bloc.dart 229:13                                                         Bloc.on.<fn>.handleEvent
package:bloc/src/bloc.dart 238:9                                                          Bloc.on.<fn>
===== asynchronous gap ===========================
dart:async                                                                                _ForwardingStream.listen
package:bloc/src/bloc.dart 313:40                                                         _FlatMapStreamTransformer.bind.<fn>
dart:async                                                                                _StreamImpl.listen
package:bloc/src/bloc.dart 241:7                                                          Bloc.on
package:mobile_flutter/widgets/check_status/bloc/update_history_bloc.dart 42:5   new UpdateHistoryBloc
test/check_status/update_history_bloc_test.dart 22:12                                 main.<fn>
Used on a non-mockito object
package:matcher                                            fail
package:mockito/src/mock.dart 1074:7                       _makeVerify.<fn>
test/check_status/update_history_bloc_test.dart 43:17  main.<fn>.<fn>
package:bloc_test/src/bloc_test.dart 230:21                testBloc.<fn>
===== asynchronous gap ===========================
dart:async                                                 _Completer.completeError
package:bloc_test/src/bloc_test.dart 257:43                _runZonedGuarded.<fn>
===== asynchronous gap ===========================
dart:async                                                 _CustomZone.registerBinaryCallback
package:bloc_test/src/bloc_test.dart 254:5                 _runZonedGuarded.<fn>
dart:async                                                 runZonedGuarded
package:bloc_test/src/bloc_test.dart 253:3                 _runZonedGuarded
package:bloc_test/src/bloc_test.dart 200:11                testBloc
package:bloc_test/src/bloc_test.dart 156:13                blocTest.<fn>

'package:mobile_flutter/core/vehicles/helper/helper.dart': Failed assertion: line 14 pos 16: 'selectedRepo.getSelected() != null': No way of obtaining serial. Forgot to call selectedRepo.select(object) somewhere?
```

**Expected Behavior**
The test should succeed because an assertion error is thrown

**Screenshots**

**Additional Context**
Im using bloc_test 9.1.4 with mockito 5.4.4

flutter doctor:

❯ flutter doctor                                                                                                       
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 15.4)
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.89.1)
[✓] Connected device (4 available)
[✓] Network resources

**Comment by felangel** [comment] 2024-07-02 04:13
Hi @danielRi 👋 
Thanks for opening an issue!

First off, I recommend using `package:mocktail` instead of `package:mockito` since `bloc_test` uses `package:mocktail` internally so the intergration is more seamless and you don't need to rely on code generation.

Second, it would be super helpful if you could create a minimal reproduction sample that illustrates the issue you're facing -- that way I can reproduce the problem locally and provide suggestions/fixes directly to the source code, thanks!

**Comment by felangel** [comment] 2024-07-05 19:54
Closing for now but let me know if the above suggestions didn't help and I'm happy to take a closer look 👍

**Closed by felangel** 2024-07-05 19:54 UTC
Labels: bug, question, waiting for response, needs repro info
