### ISSUE TITLE
BlocBuilder partially update ListView

### ISSUE THREAD

**Issue by prankhazard** [felangel/bloc#684] opened 2019-11-20 04:07 UTC
Hi, I'm trying to use a bloc pattern to create a list view that can be filtered by a `TextField`

Here is my **code**

bloc:

    class HomeBloc extends Bloc<HomeEvent, HomeState> {
    
      List<Book> displayList = [];
    
      .... 
    
      @override
      HomeState get initialState => UnfilteredState();
    
      @override
      Stream<HomeState> mapEventToState(
        HomeEvent event,
      ) async* {
    
        .... 
    
        //handle filter by input
        if(event is FilterListByTextEvent) {
    
          displayList = displayList.where((book){
            return book.title.toLowerCase().contains(event.filterString.toLowerCase());
          }).toList();
    
          yield FilteredState();
        }
    
      }
    
    }

view

    class BookList extends StatelessWidget {
    
      @override
      Widget build(BuildContext context) {
        return BlocBuilder<HomeBloc, HomeState>(
          builder: (context, state) {
            final HomeBloc bloc = Provider.of<HomeBloc>(context);
            print(bloc.displayList);
            return ListView.builder(
              shrinkWrap: true,
              itemCount: bloc.displayList.length,
              itemBuilder: (context, index) {
                return Dismissible(
                  key: UniqueKey(),
                  background: Container(
                    color: selectedColor,
                  ),
                  child: Container(
                    height: 120,
                    padding: const EdgeInsets.fromLTRB(20, 4, 20, 4),
                    child: BookCard(
                      book: bloc.displayList[index],
                    ),
                  ),
                  onDismissed: (DismissDirection direction) {
                  },
                );
              },
            );
          },
        );
      }
    }

I've read some other discussion about bloc pattern and List view but the issue I'm facing here is different. 

Every time my Filter event is called, bloc correctly generate a new `displayList` but, when `BlocBuilder` rebuild my UI, listview is not correctly updated. 
The new filtered list is rendered but old results do not disappear. It seems like the new list is simply stacked on top of the old one.

In order to understand what was happening I tried printing the list that has to be rendered, inside the BlocBuilder before the build method is called.

The printed result was correct. In the console I see only the new filtered elements while in the UI I see both the new one and the old one, one below the other.

What am I missing here?

Thanks

**Comment by felangel** [comment] 2019-11-20 06:19
Hi @prankhazard 👋 
Thanks for opening an issue!

Are you able to share a link to a sample app which illustrates the issue you're having? It would be much easier to help if I can run/debug the code locally 👍 Thanks!

**Comment by felangel** [comment] 2019-11-21 23:16
Closing for now since there is no sample app to reproduce the issue. Feel free to add a link to a sample app and I'm happy to reopen the issue 👍

**Closed by felangel** 2019-11-21 23:16 UTC
Labels: question, waiting for response
