### ISSUE TITLE
fix: Cannot access Bloc in imported Widgets

### ISSUE THREAD

**Issue by ConnorDykes** [felangel/bloc#3995] opened 2023-11-14 17:42 UTC
**Description**
I cannot access the bloc if the widget is being imported from another file, I can only access the bloc if the widget is in the same file

**Steps To Reproduce**

**Expected Behavior**
Should be able to access bloc from sub widgets even if importing

**Screenshots**

**Additional Context**

This is what my Home.dart looks like, but if I try to put the DashBoard or Account widgets in their own file then import them, they cannot access the bloc . the even more confusing thing is that I copies my bloc pattern from another app that is set up the exact same way and it does not have this import problem. The AppBloc is provided to the Home widget in the main.dart

```
class Home extends StatelessWidget {
  const Home({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return BlocBuilder<AppBloc, AppState>(
      builder: (context, state) {
        final appBloc = context.read<AppBloc>();

        final body = [
          const Dashboard(),
          const AllAthletesView(),
          const Leagues(),
          const Events(),
        ];
        return Scaffold(
          bottomNavigationBar: BottomNavigationBar(
              items: <BottomNavigationBarItem>[
                BottomNavigationBarItem(
                  icon: state.navBarIndex == 0
                      ? const Icon(Icons.home)
                      : const Icon(Icons.home_outlined),
                  label: 'Dashboard',
                ),
                BottomNavigationBarItem(
                  icon: state.navBarIndex == 1
                      ? const Icon(Icons.group)
                      : const Icon(Icons.group_outlined),
                  label: 'Athletes',
                ),
                BottomNavigationBarItem(
                  icon: state.navBarIndex == 2
                      ? const Icon(Icons.emoji_events)
                      : const Icon(Icons.emoji_events_outlined),
                  label: 'Leagues',
                ),
                BottomNavigationBarItem(
                  icon: state.navBarIndex == 3
                      ? const Icon(Icons.calendar_month)
                      : const Icon(Icons.calendar_month_outlined),
                  label: 'Events',
                ),
              ],
              currentIndex: state.navBarIndex,
              showUnselectedLabels: true,
              selectedItemColor: theme.colorScheme.primary,
              unselectedItemColor: Colors.grey,
              onTap: (index) =>
                  appBloc.add(AppEvent.updateNavBarIndex(index: index)),
              type: BottomNavigationBarType.fixed),
          body: body[state.navBarIndex],
        );
      },
    );
  }
}

class Dashboard extends StatelessWidget {
  const Dashboard({super.key});

  @override
  Widget build(BuildContext context) {
    final appBloc = context.read<AppBloc>();
    return Scaffold(
      appBar: AppBar(
        title: Text('Dashboard'),
        actions: [
          IconButton(
              onPressed: () => Navigator.push(
                  context, MaterialPageRoute(builder: (_) => Account())),
              icon: Icon(
                Icons.account_circle_outlined,
                size: 30,
              ))
        ],
      ),
      body: Center(
          child: ElevatedButton(
        child: Text('getTopRankedAthletesID'),
        onPressed: () => AthleteRepo().uploadToFirebase(
            url:
                "https://www.ifsc-climbing.org/index.php/world-competition/calendar?task=ranking-complete&cup=90&category=6&year=2023"),
      )),
    );
  }
}

class Account extends StatelessWidget {
  const Account({super.key});

  @override
  Widget build(BuildContext context) {
    final appBloc = BlocProvider.of<AppBloc>(context);
    return Scaffold(
      appBar: AppBar(title: Text('Account')),
      body: Column(children: [
        ElevatedButton(
            onPressed: () {
              appBloc.add(AppEvent.logout());
            },
            child: Text('Logout'))
      ]),
    );
  }
}


```

**Comment by ConnorDykes** [comment] 2023-11-14 17:43
for additional context this code does allow me to access the bloc. `class Home extends StatelessWidget {
  const Home({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return BlocBuilder<AppBloc, AppState>(
      builder: (context, state) {
        final appBloc = context.read<AppBloc>();

        final body = [
          const Dashboard(),
          const AllAthletesView(),
          const Leagues(),
          const Events(),
        ];
        return Scaffold(
          bottomNavigationBar: BottomNavigationBar(
              items: <BottomNavigationBarItem>[
                BottomNavigationBarItem(
                  icon: state.navBarIndex == 0
                      ? const Icon(Icons.home)
                      : const Icon(Icons.home_outlined),
                  label: 'Dashboard',
                ),
                BottomNavigationBarItem(
                  icon: state.navBarIndex == 1
                      ? const Icon(Icons.group)
                      : const Icon(Icons.group_outlined),
                  label: 'Athletes',
                ),
                BottomNavigationBarItem(
                  icon: state.navBarIndex == 2
                      ? const Icon(Icons.emoji_events)
                      : const Icon(Icons.emoji_events_outlined),
                  label: 'Leagues',
                ),
                BottomNavigationBarItem(
                  icon: state.navBarIndex == 3
                      ? const Icon(Icons.calendar_month)
                      : const Icon(Icons.calendar_month_outlined),
                  label: 'Events',
                ),
              ],
              currentIndex: state.navBarIndex,
              showUnselectedLabels: true,
              selectedItemColor: theme.colorScheme.primary,
              unselectedItemColor: Colors.grey,
              onTap: (index) =>
                  appBloc.add(AppEvent.updateNavBarIndex(index: index)),
              type: BottomNavigationBarType.fixed),
          body: body[state.navBarIndex],
        );
      },
    );
  }
}
`

**Comment by ConnorDykes** [comment] 2023-11-14 22:33
As a final note it turns out as long as   name the bloc anything except AppBloc it works. No idea why, even changing it to ApplicationBloc works but can't use AppBloc for some reason

**Comment by felangel** [comment] 2023-11-15 02:35
Hi @ConnorDykes 👋
Thanks for opening an issue!

Are you sure you don’t already have a different class called AppBloc? Can you please share a link to a minimal reproduction sample and I’m happy to take a closer look, thanks!

**Comment by felangel** [comment] 2023-11-23 06:49
Closing for now since there aren't any actionable next steps without further information/reproduction samples. If this is still an issue please provide a minimal reproduction sample and I'm happy to take a closer look, thanks!

**Closed by felangel** 2023-11-23 06:49 UTC
Labels: question, waiting for response
