### ISSUE TITLE
BlocProvider.of<AuthenticationBloc>(context).add(AuthenticationLoggedIn()) Does not redirect to HomeScreen

### ISSUE THREAD

**Issue by selvesandev** [felangel/bloc#1395] opened 2020-07-04 21:36 UTC
I have created three screens Register, Login and a Welcome Screen. First the welcome screen is loaded with a login button when clicked will redirect to the login screen. `Navigator.of(context).pushReplacementNamed('login')`  I am using the `pushReplacementNamed` to change the pages.

**At the login screen i have this code** 

```
BlocListener<LoginBloc, LoginState>(
                      listener: (context, state) {
                    if (state.isSuccess == true) {
                      BlocProvider.of<AuthenticationBloc>(context).add(AuthLoggedInEvent());
                    }
                    if (state.isFailure && state.failResponse != null) {
                     //scaffold
                    }
  } child: //... 

);
                
```

`BlocProvider.of<AuthenticationBloc>(context).add(AuthenticationLoggedIn());` at the listener is not being able to redirect to the home screen even if the event is successfully executed and the `AuthSuccessState` is called.

However if i remove the Register and the Welcome page and only use the Login page the behaviour is as aspected i.e i get redirected to the HomeScreen after login success.

**Note** This won't work if i go the the login page from the WelcomeScreen or the RegisterScreen.

I am using `Navigator.of(context).pushReplacementNamed('login');` to switch to the login screen from Welcome and Register screens.

I have followed the tutorials from flutter_bloc **Flutter Firebase Login Tutorial** the only difference is i have three screen instead on only the login screen.

**Comment by felangel** [comment] 2020-07-04 22:07
Hi @selvesandev 👋 
Thanks for opening an issue!

I'm guessing the problem is you're using `pushReplacementNamed` which is removing the BlocListener from the widget tree. You should ensure that the BlocListener is always mounted in order to ensure the navigation occurs properly. I am in the process of reworking the examples so I would recommend using [this](https://github.com/felangel/fresh/tree/master/packages/fresh_dio/example) as an example for now 👍 

Sorry for the inconvenience and hope that helps!

**Comment by selvesandev** [comment] 2020-07-05 04:25
@felangel thanks for the quick response. I will go through the latest example. Please let me know if there's any way I can achieve this while using the `pushReplacementNamed`.

**Comment by felangel** [comment] 2020-07-05 04:30
The example should outline how because it used a nested `Navigator` 👍 
Closing for now but feel free to comment with any additional questions and I'm happy to continue the conversation 😄

**Closed by felangel** 2020-07-05 04:30 UTC
Labels: example, question
