### ISSUE TITLE
Best way to create stopwatch/timer in Cubit Bloc?

### ISSUE THREAD

**Issue by Lix-ai** [felangel/bloc#2532] opened 2021-06-16 08:13 UTC
Hi,
Thanks again for the awesome flutter state attitude infrastructure,
What is the best way to create a stopwatch/timer in **Cubit** Bloc?

I saw 'https://bloclibrary.dev/#/fluttertimertutorial', is this tutorial is good enough in general and for:
- Getting the timer/timing time.
- Pause and get pause event.
- Stop and get stop event.
- Use the timer with fix time to run (i.e., start for example from 00:00 to 00:30, and then get the time and stop it and not from 00:30 to 00:00).

What do you say?

Thanks in advance! =]

**Comment by felangel** [comment] 2021-06-17 15:41
Hi @Lix-ai 👋 
Thanks for opening an issue!

Yes, I think the timer tutorial is a great place to get started. You will need to make modifications to fit your requirements but it should be a good foundation 👍 

Let me know if that helps!

**Comment by Lix-ai** [comment] 2021-06-20 19:31
Thanks @felangel  =],
I actually tried to use but I don't really sure how to connect it to a 'Model'.
I used only cubit so far with model and 'copywith' options.

Because i want to set the duration and don't want it to be constant .
Methods are the same with bloc, this is i understand.


Thanks in advance! 👍

**Comment by Lix-ai** [comment] 2021-06-23 08:42
@felangel Thanks :),
I will add the code ASAP, but the issue i am facing with is regarding several subjects of how cubit works with subscription/stream:

1. I must initial the Ticker as part of the cubit? or i can call/initialize it only when i want to start the timer?

2. As in:
```
    _tickerSubscription = _ticker
        .tick(ticks: start.duration)
        .listen((duration) => add(TimerTicked(duration: duration)));
```
  - What is 'add'?
  - What is exactly the 'ticks', what data it takes? the current duration?
  - The listen is emit the 'duration' to the state i want to, right?
 
 3. In the View area, i don't need to use the changing of the states at the 'BlocBuilder' if i use 1 state for it, right? and does Timer work with 1 state?
 
 4.  In the View area, does i/shall need BlocConsumer for using the Timer?

5. In the View area, does i/shall need 'context.select' for using the Timer (get new update from the subscriber/stream)?


Thanks in advance! +1

**Comment by Lix-ai** [comment] 2021-06-24 14:05
Fix it,
By the way, saw weird memory leak when using radial animation, familiar with this?

**Comment by felangel** [comment] 2021-07-03 16:12
> Fix it,
> By the way, saw weird memory leak when using radial animation, familiar with this?

Glad you fixed it and no I'm not. If you believe it is related to bloc can you open a new issue with a reproduction sample?
Closing for now since it sounds like you managed to address the issue 🎉

**Closed by felangel** 2021-07-03 16:12 UTC
Labels: question, waiting for response

**Comment by Lix-ai** [comment] 2021-07-05 20:27
I will check deeply and will, thanks =]
