### ISSUE TITLE
BlocBuilder does not rebuild Widget ( when its a column widget that uses spread operators)

### ISSUE THREAD

**Issue by basnetjiten** [felangel/bloc#1839] opened 2020-10-17 13:37 UTC
Stateful widget
     inside state 
     ===>declare List<Widget> myWidgetList
     inside  initState
      =======> myWidgetList=[ ];

     inside builder(buildContext)
      ======> BlocBuilder(){
      if(state is success){
      myWidgetList= List.generate(8,i)=>MyAwesomeWidget(somedata(i));
     return Column(children:[ 
         ...myWidgetList.map(e)=> return e.toList()]
        }
    }

Here myWidgetList is created every time with new data coming from the api list from the state, I  can print that the state is rebuilding multiple time within the state, but Column widget with the child of myWidgetList is not updated/refected.

**Comment by felangel** [comment] 2020-10-18 04:17
Hi @basnetjiten 👋 
Thanks for opening an issue!

Can you please provide a link to a sample app which reproduces the issue? Thanks 👍

**Comment by felangel** [comment] 2020-10-20 16:33
Closing for now since there isn't enough information to reproduce the issue. Feel free to comment with a link to a reproduction sample and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-10-20 16:33 UTC
Labels: question, waiting for response
