### ISSUE TITLE
[BUG] flutter_bloc 3.1 context not updated

### ISSUE THREAD

**Issue by EArminjon** [felangel/bloc#763] opened 2020-01-04 14:03 UTC
Hello,

I fow a while a old version of flutter_bloc. Today i start with flutter_bloc 3.1.0
I'm got a bug or I didn't understand something :/

This is the build method of my StatefullWidget :
```dart
@override
  Widget build(BuildContext context) {
    return BlocProvider<MapBloc>(
      create: (context) => MapBloc(),
      child: BlocListener<MapBloc, MapState>(
        bloc: BlocProvider.of<MapBloc>(context),
        listener: (context, MapState state) {
          print("test");
        },
        child: Material(),
      ),
    );
}
```
BlocListener use the context provided by the build method. The BlocProvider under it  didn't update the context and my BlocListener didn't have access to the bloc....

```bash
BlocProvider.of() called with a context that does not contain a Bloc of type MapBloc.
```

Can you help me :'( ?

**Comment by tenhobi** [comment] 2020-01-04 15:03
You don't need to provide that `bloc` argument explicitly. It will do an automatic lookup.

```dart
@override
  Widget build(BuildContext context) {
    return BlocProvider<MapBloc>(
      create: (context) => MapBloc(),
      child: BlocListener<MapBloc, MapState>(
        // bloc: BlocProvider.of<MapBloc>(context), // remove this
        listener: (context, MapState state) {
          print("test");
        },
        child: Material(),
      ),
    );
}
```

Either way, I believe it should work.

Cc @felangel

**Comment by EArminjon** [comment] 2020-01-04 15:07
Problem still here : 

```dart
Widget build(BuildContext context) {
    return BlocProvider<MapBloc>(
      create: (context) => MapBloc(),
      child: BlocListener<MapBloc, MapState>(
        listener: (context, MapState state) {
          if (state is MapStateDoRefresh) setState(() {});
        },
        child: Scaffold(
          body: Center(
            child: IconButton(
              icon: Icon(Icons.map),
              onPressed: () {
                BlocProvider.of<MapBloc>(context);
              },
            ),
          ),
        ),
      ),
    );
}
```

Same error on onPressed callback :'(

```bash
 BlocProvider.of() called with a context that does not contain a Bloc of type MapBloc.
```

**Comment by tenhobi** [comment] 2020-01-04 15:14
@EArminjon can you extract that BlocListener and it's subtree to another widget and try if that passes?

```dart
Widget build(BuildContext context) {
    return BlocProvider<MapBloc>(
      create: (context) => MapBloc(),
      child: ThatNewWidget(), // extract to new widget
    );
}
```

**Comment by EArminjon** [comment] 2020-01-04 15:17
It works.

So, it's a bug :'(

This trix will create a lot of boiler-plate : i will need to create an other widget each time I need use BlocProvider...

**Comment by tenhobi** [comment] 2020-01-04 15:25
I don't think it's a bug per se. It's more how Flutter works. To be able to access some provided thing, you have to look up from someplace in the subtree.

That is theoretically done here too, bud you use the same context variable, and I am not sure how that affects all of that. @felangel might know more about this tho.

---

Also, what happens when you wrap that `BlocListener` in another widget, like `Container`?

```dart
Widget build(BuildContext context) {
    return BlocProvider<MapBloc>(
      create: (context) => MapBloc(),
      child: Container( // add this
        child: BlocListener<MapBloc, MapState>( ... ),
      ),
    );
}
```

**Comment by felangel** [comment] 2020-01-04 15:28
@EArminjon this is not a bug because you can't access a bloc from the same context in which it was provided. If you don't want to create another widget then you can wrap the BlocProvider.of in a Builder to get a new context.

```dart
Builder(
  builder: (context) {
    BlocProvider.of<MyBloc>(context);
  }
)
```

**Comment by EArminjon** [comment] 2020-01-04 15:30
Thank you @felangel, I will use Builder :) !

**Comment by tenhobi** [comment] 2020-01-04 15:31
So it was like I thought.

Btw. you are not able to access things from any widget, but here is the "issue" that you are using the context (which is used for lookups) not from those widgets, but as you are the widget where is this build function placed, right?

**Comment by felangel** [comment] 2020-01-04 15:33
No problem! @tenhobi made a suggestion to extract the code that needs access to the bloc into a separate widget and I personally recommend that as well because it allows you to inject a mock bloc when you are doing widget tests and also keeps your code more modular and reusable. Hope that helps and closing for now but feel free to comment with additional questions or comments and I'm more than happy to continue the conversation 👍

**Closed by felangel** 2020-01-04 15:33 UTC
