### ISSUE TITLE
flutter_bloc - State Change not updating the UI

### ISSUE THREAD

**Issue by karthikeyanp307** [felangel/bloc#1946] opened 2020-11-19 11:02 UTC
Hi @felangel ,

This issue is related to flutter_bloc - Notification 0nResume redirect to new page #1488. Based on your comments for #1488, I am able to redirect the application to a new page while receiving a notification. This works fine. Thanks. 

Now I am facing another issue. While receiving multiple notifications, on clicking one of the notifications the above flow works well. But on clicking the second notification, the application stays as it is and not redirecting as expected. The state is being called but the return NewPage() is not getting called again. 

I am following the https://github.com/felangel/bloc/tree/master/examples/flutter_login as the base app for this. In fcm notification onMessage, I am calling an AuthenticationBloc - Event. This in turn calls the required state based on the implemented functionality but the UI is not rendered based on this state change. Please help me with this.

Thanks in advance.

**Comment by felangel** [comment] 2020-11-20 21:28
Hi @karthikeyanp307 👋 
Thanks for opening an issue!

Are you able to share a link to a reproduction sample? Have you taken a look at the [FAQs](https://bloclibrary.dev/#/faqs?id=state-not-updating)?

**Comment by felangel** [comment] 2020-11-24 21:37
Closing for now since there isn't enough information to reproduce the issue.

**Closed by felangel** 2020-11-24 21:37 UTC
Labels: question, waiting for response
