### ISSUE TITLE
Sucess turns true multiple times

### ISSUE THREAD

**Issue by samsheldin** [felangel/bloc#995] opened 2020-03-31 20:04 UTC
[Screen.txt](https://github.com/felangel/bloc/files/4411265/Screen.txt)

[schedule_appointments_event.txt](https://github.com/felangel/bloc/files/4411266/schedule_appointments_event.txt)
[schedule_appointments_state.txt](https://github.com/felangel/bloc/files/4411267/schedule_appointments_state.txt)
[schedule_appointments_bloc.txt](https://github.com/felangel/bloc/files/4411268/schedule_appointments_bloc.txt)

Hi in this Screen in the listener section
```
 if (state.isSaved) {
            pr.dismiss();
            SchedulerBinding.instance.addPostFrameCallback((_) {
              Navigator.of(context).pop();
              //  Navigator.popUntil(context, ModalRoute.withName("/coach_home_screen"));
            });

            //  Navigator.of(context).pop();
            Fluttertoast.showToast(
                msg: "Record saved succesfully",
                toastLength: Toast.LENGTH_LONG,
                gravity: ToastGravity.CENTER,
                timeInSecForIos: 2,
                backgroundColor: WHITE_COLOR,
                textColor: CHART_GREEN,
                fontSize: 16.0);
          }
```
error; Future already completed on   Navigator..pop;
the isSaved part is being true multiple times after an api turns success(logically it should be called one time, only if the api returns a success)..thereby the pop() is called several times and causes a screen of death, can you point out where i Have gone wrong @felangel @tenhobi

**Comment by felangel** [comment] 2020-04-02 15:04
Hi @samsheldin 👋 
Thanks for opening an issue!

Can you please provide a link to a sample app which reproduces the issue you're facing? It'd be much easier to help if I have a runnable app which I can debug 👍

**Comment by felangel** [comment] 2020-04-03 23:12
Closing for now since there isn’t a sample which reproduces the issue. Feel free to comment with additional information or a link to a repro sample and I’m happy to continue the conversation 👍

**Closed by felangel** 2020-04-03 23:12 UTC
Labels: question, waiting for response

**Comment by samsheldin** [comment] 2020-04-10 13:50
thanks for your help i will upload it today

**Comment by samsheldin** [comment] 2020-04-11 15:38
Hi sir please delete this comment if you can,, i think that issue is solved
