### ISSUE TITLE
Version 6.0.3, BlocBuilder does not work properly

### ISSUE THREAD

**Issue by LBXjixiangniao** [felangel/bloc#1687] opened 2020-09-01 08:27 UTC
class MyApp extends StatelessWidget {
  CounterCubit _cubit = CounterCubit();
  @override
  Widget build(BuildContext context) {
    Future.delayed(Duration(seconds: 1),(){
      _cubit.emit(1);
      _cubit.emit(2);
      _cubit.emit(3);
    });
    return MaterialApp(
      home: Scaffold(
        body: BlocBuilder(
          cubit: _cubit,
          buildWhen: (preState, currentState) => currentState == 2,
          builder: (BuildContext context, state) {
            return Text(state.toString());
          },
        ),
      ),
    );
  }
}

Text show 3。I think the reason for the error is that _cubit.state was used when rebuilding, instead of currentState in the buildWhen method。The source code is below

class _BlocBuilderBaseState<C extends Cubit<S>, S>
    extends State<BlocBuilderBase<C, S>> {
  C _cubit;

  @override
  void initState() {
    super.initState();
    _cubit = widget.cubit ?? context.bloc<C>();
  }

  @override
  void didUpdateWidget(BlocBuilderBase<C, S> oldWidget) {
    super.didUpdateWidget(oldWidget);
    _cubit = widget.cubit ?? context.bloc<C>();
  }

  @override
  Widget build(BuildContext context) {
    return BlocListener<C, S>(
      cubit: _cubit,
      listenWhen: widget.buildWhen,
      listener: (context, state) => setState(() {}),
      child: widget.build(context, _cubit.state),
    );
  }
}

**Comment by felangel** [comment] 2020-09-01 14:54
Hi @LBXjixiangniao 👋 
Thanks for opening an issue!

This is a duplicate of #1682 and is being fixed as part of #1684 👍

**Closed by felangel** 2020-09-01 14:54 UTC
Labels: duplicate
