### ISSUE TITLE
fix: after the update requires to implement the interface   @override   NavState get state => throw UnimplementedError();

### ISSUE THREAD

**Issue by OlgaDevCom** [felangel/bloc#3764] opened 2023-03-14 09:38 UTC
![Screenshot 2023-03-14 at 11 37 07](https://user-images.githubusercontent.com/13676374/224959293-3e68e11e-9c66-4040-acb9-7a66858e1b7e.png)

How to properly implement interface @override
   NavState get state, or how to fix it?

**Comment by tenhobi** [comment] 2023-03-14 10:01
That's weird because the getter is implemented, as seen here https://github.com/felangel/bloc/blob/master/packages/bloc/lib/src/bloc_base.dart#L69

Which version of Bloc do you have problems with?

**Comment by OlgaDevCom** [comment] 2023-03-14 10:11
flutter_bloc: ^8.1.2
  bloc: ^8.1.1

> https://github.com/felangel/bloc/blob/master/packages/bloc/lib/src/bloc_base.dart#L69

**Comment by OlgaDevCom** [comment] 2023-03-14 10:11
flutter_bloc: ^8.1.2
  bloc: ^8.1.1
>

**Comment by felangel** [comment] 2023-03-14 13:03
> flutter_bloc: ^8.1.2 bloc: ^8.1.1
> 
> > 
> 
> Error /.pub-cache/hosted/pub.dev/bloc-8.1.1/lib/src/bloc_base.dart:12:13: Context: 'StateStreamable.state' is defined here. State get state;

Can you clear your pub cache and try again? I’m guessing you accidentally modified your local bloc source code.

**Comment by Gene-Dana** [comment] 2023-03-14 18:29
> Can you clear your pub cache and try again? I’m guessing you accidentally modified your local bloc source code.

This definitely has happened to me before

**Comment by tenhobi** [comment] 2023-03-15 06:00
Yea. I also did not reproduce this issue, as assumed. Les us know if clearing the cache helped.

**Comment by OlgaDevCom** [comment] 2023-03-15 08:49
> clear your pub cache

I cleared the flutter pub cache repair command, but the error did not disappear

**Comment by tenhobi** [comment] 2023-03-15 09:55
Since you are talking about repair, did you try clean: `dart pub cache clean`?

Could you also try creating an empty project if the issue remains?

**Comment by OlgaDevCom** [comment] 2023-03-15 15:42
I try it on a clean project, there is an error in Bloc version 8, there is no such error in version 7


> Since you are talking about repair, did you try clean: `dart pub cache clean`?
> 
> Could you also try creating an empty project if the issue remains?

**Comment by tenhobi** [comment] 2023-03-16 14:11
@OlgaDevCom sorry, I cannot reproduce that. Could you make a minimal reproducible example so I can test that on the exact project that doesn't work for you?

**Comment by felangel** [comment] 2023-04-15 19:01
Closing for now since there is no minimal reproduction sample provided. Feel free to provide one and I'm happy to take a closer look, thanks! 👍

**Closed by felangel** 2023-04-15 19:01 UTC
Labels: bug, waiting for response
