### ISSUE TITLE
Child screen can't find bloc from parent context

### ISSUE THREAD

**Issue by jamie1192** [felangel/bloc#475] opened 2019-08-15 05:15 UTC
I have a home screen where I'm initialising a bloc, and am trying to hook into it from a separate child screen, but the child screen can't seem to find a provided bloc through it's context.

Home (parent) screen-
```dart
class Home extends StatelessWidget {

  final RemindersBloc _remindersBloc = RemindersBloc()
    ..dispatch(LoadRemindersEvent());

  @override
  Widget build(BuildContext context) {

    return BlocProvider<RemindersBloc>(
      builder: (context) => _remindersBloc,
        child: Scaffold(
          body: Container(

			  ...
			// further down the tree, an onTap triggers the Navigator.push as such -
			Navigator.pushNamed(context, '/reminders');
		  )
		)
	  )
	);
  }
}
```

Child screen-
```dart
class ReminderSliver extends StatelessWidget {

  @override
  Widget build(BuildContext context) {

    final _remindersBloc = BlocProvider.of<RemindersBloc>(context);

    return Scaffold(
      body: SafeArea(
        child: BlocBuilder(
          bloc: _remindersBloc,
          builder: (context, state) {
            if(state is RemindersLoadedState) {
              
				....
			  
			}
			else {
				return Container();
			}
		  }
		)
	  )
	);
  }

}
```

But no matter what I try, I continue to get the exception - 
`The following assertion was thrown building ReminderSliver(dirty):
BlocProvider.of() called with a context that does not contain a Bloc of type RemindersBloc. No ancestor could be found starting from the context that was passed to BlocProvider.of<RemindersBloc>().` when navigating to the child screen/new scaffold, yet I am explicitly defining the bloc type.

Does the new scaffold use it's own context separate to the context that is being used to initialise the bloc, is it a bug, or am I doing something super dumb?

Thanks!

**Comment by felangel** [comment] 2019-08-15 05:21
Hi @jamie1192 👋 
Thanks for opening an issue!

I think this is a duplicate of #474. Hope that helps and feel free to comment with any additional questions if the explanation there is unclear. Thanks! 👍

**Closed by felangel** 2019-08-15 05:21 UTC

**Comment by jamie1192** [comment] 2019-08-15 05:38
Hey @felangel, thanks for the quick response!

Oh cool I missed that issue when I was searching before posting, navigating to the ReminderSliver page and passing in the reference to the existing bloc solved it ->
```dart
Navigator.of(context).push(
  MaterialPageRoute<ReminderSliver>(
  builder: (context) {
    return BlocProvider(
      builder: (BuildContext context) => _remindersBloc,
        child: ReminderSliver(),
      );
    },
  ),
);
```

What's the reason for having to explicitly provide the bloc through this way to the child when in my snippet above, the bloc exists higher in the widget tree within the same context?

**Comment by felangel** [comment] 2019-08-15 12:31
No problem! It’s because unless your BlocProvider is above MaterialApp, when you push a new route its BuildContext is detached from the previous ones. You should think of pushing routes as creating new disconnected widget trees because the new route is not a child of the one pushing it 👍

**Comment by jamie1192** [comment] 2019-08-15 22:57
Ah perfect, thank you!
