### ISSUE TITLE
Implement eventbus pattern

### ISSUE THREAD

**Issue by zombie6888** [felangel/bloc#2443] opened 2021-05-04 09:56 UTC
According to this question https://stackoverflow.com/questions/67379427/manage-global-events-by-bloc i found that bloc's instances are tight coupled. In order to subscribe events from one instance in another, i have to inject it. It becomes a headache when you should manage many async queries. Redux uses redux-saga package to solve this problem. In dart packages, i found event-bus package https://pub.dev/packages/event_bus which is also resolved my problem. It also uses dart streams. What if implement this pattern to flutter bloc?

**Comment by zombie6888** [comment] 2021-05-08 16:19
Hi @felangel, thank you for your answer and your job. This pattern helps me to decouple blocs. I've created mixin:
`
EventBus eventBus = EventBus();

mixin EventBusMixin {
  StreamSubscription<T> listenEvent<T>(void Function(T) subscription) =>
      eventBus.on<T>().listen(subscription);

  void shareEvent<S>(S event) => eventBus.fire(event);
}
`
Now, if i need to subscribe for some events/data from one bloc in another i can do this:
`
class Bloc1<Bloc1Event, Bloc1State> with EventBusMixin {
  CityBloc() : super(InitialState());  

  @override
  Stream<Bloc1Event> mapEventToState(Bloc1Event event) async* {
    ...
	shareEvent(SharedEvent event);	
  }  
}

class Bloc2<Bloc2Event, Bloc2State> with EventBusMixin {
  CityBloc() : super(InitialState()) {	
     listenEvent<SharedEvent>((e) {
        // do something
     );	
  }; 
  ...
}
`
With this approach bloc2 doesn't depend on bloc1 instance, but can be subscribed to events which you can fire in bloc1.
What do you think? If this approach good, maybe implement it in bloc?

**Comment by felangel** [comment] 2021-05-19 22:11
@zombie6888 the problem with this approach is that it relies on a global event bus. I personally don't recommend that and in most cases I recommend avoiding bloc-to-bloc communication entirely by creating independent blocs which each manage a separate feature state. Hope that helps 👍

**Comment by felangel** [comment] 2021-05-21 13:27
Closing for now but feel free to comment any additional thoughts or [join the discord](https://discord.gg/bloc) 👍

**Closed by felangel** 2021-05-21 13:27 UTC
Labels: question, waiting for response

**Comment by otto-dev** [comment] 2022-09-09 21:36
> feel free to comment any additional thoughts

I am running into this problem @felangel . The issue is application events that affect multiple blocs which may or may not be currently instantiated and rendered on the screen.

Say, a user receives a new message over the network. Now I want to update the "chat-messages" bloc on the chat screen, and the "last-message" bloc on the channel overview screen - if one or both of them currently exist. A global message bus as @zombie6888 described would be a viable solution to this. What's the practical alternative in such situations?

**Comment by felangel** [comment] 2022-09-10 12:44
> > feel free to comment any additional thoughts
> 
> I am running into this problem @felangel . The issue is application events that affect multiple blocs which may or may not be currently instantiated and rendered on the screen.
> 
> Say, a user receives a new message over the network. Now I want to update the "chat-messages" bloc on the chat screen, and the "last-message" bloc on the channel overview screen - if one or both of them currently exist. A global message bus as @zombie6888 described a-la `redux` would be a viable solution to this. What's the practical alternative in such situations in the bloc paradigm?

I recommend exposing the stream of updates from a repository which one or more blocs can subscribe to. You can refer to the todos example to see this in action — multiple blocs subscribe to the todos stream from the TodosRepository and emit new states in response.

**Comment by zombie6888** [comment] 2023-05-24 16:07
Since almost 2 years passed, i can share some thoughts and experience. 
At first i've noticed that docs were updated: https://bloclibrary.dev/#/architecture?id=bloc-to-bloc-communication.
There are 2 approaches and for now i think it's more clear. 

But i found that keep data as stream on domain layer is inconvenient for me. You have to manage a lot of stream based logic in repository and bloc to repository communications, otherwise bloc is useless.
You could get data from repository directly by using StreamBuilder. And if you also need to manage network statuses and error exceptions i think first approach is better. 

If you want to completely separate buisness layer from presentation layer, you would prefer to add one more layer like View model or Delegate, which will comunicate with blocs, 
listen for state updates and pass data to widgets. It could be a regular widget with bloc builders, listeners and handlers for user interaction callbacks. With this approach, 
if your buisness logic was changed, you don't need to make changes in ui widgets: reorder, move or remove bloc builders, providers, change listeners etc..
And with this approach you can share same logic for different views. Of course with additional abstraction layer, it's more boilerplate. 
You don't need it, if your app is small or you apply changes rarely. 

Maybe more complex example will help me considering domain layer approach
