### ISSUE TITLE
BlocProvider with Builder widget

### ISSUE THREAD

**Issue by fernando-s97** [felangel/bloc#1979] opened 2020-11-29 05:27 UTC
Why the following code will fail with "Could not find the correct Provider<HomeBloc> above this HomePage Widget" if the BlocListener is inside a Builder widget?

The error tip even points to this solution:

> You used a `BuildContext` that is an ancestor of the provider you are trying to read.
> 
>   Make sure that HomePage is under your MultiProvider/Provider<HomeCubit>.
>   This usually happen when you are creating a provider and trying to read it immediately.
> 
>   For example, instead of:
> 
>   ```dart
>   Widget build(BuildContext context) {
>     return Provider<Example>(
>       create: (_) => Example(),
>       // Will throw a ProviderNotFoundError, because `context` is associated
>       // to the widget that is the parent of `Provider<Example>`
>       child: Text(context.watch<Example>()),
>     ),
>   }
>   ```
> 
>   consider using `builder` like so:
> 
>   ```dart
>   Widget build(BuildContext context) {
>     return Provider<Example>(
>       create: (_) => Example(),
>       // we use `builder` to obtain a new `BuildContext` that has access to the provider
>       builder: (context) {
>         // No longer throws
>         return Text(context.watch<Example>()),
>       }
>     ),
>   }
>   ```

**My Code**

```dart
return BlocProvider(
  create: (context) => HomeBloc(context.read<IRepository>()),
  child: Builder(
    builder: (context) => BlocListener<HomeBloc, HomeState>(
      listener: (_, __) {},
      listenWhen: (previous, current) {
        ...
      },
      child: Scaffold(
        body: SafeArea(
          child: Column(
            children: [
              if (context.select<HomeBloc, bool>((v) => v.state.events.isEmpty))
                Container()
              else
                Expanded(
                  flex: 35,
                  child: _buildEventSection(context),
                ),
              Expanded(
                flex: 65,
                child: _buildPartnerSection(context),
              ),
            ],
          ),
        ),
        floatingActionButton: _buildFab(context),
      ),
    ),
  ),
);
```

**Comment by felangel** [comment] 2020-12-01 16:13
Hi @fernando-s97 👋 
Thanks for opening an issue!

Are you able to share a link to a sample app that reproduces the issue? Are you sure the `HomeBloc` is being created successfully? It could be failing if the `context.read<IRepository>()` lookup fails. Are you providing the repository higher up in the widget tree?

**Comment by felangel** [comment] 2020-12-04 17:25
Closing for now since there isn't enough information to reproduce the issue. Feel free to comment with a reproduction sample and I'm happy to take another look 👍

**Closed by felangel** 2020-12-04 17:25 UTC
Labels: question, waiting for response

**Comment by fernando-s97** [comment] 2020-12-06 00:49
Here is a gist with a reproducible sample: https://gist.github.com/fernando-s97/245f727d37e2ab1f979dfc370779afc4

**Comment by felangel** [comment] 2021-01-06 06:21
Hi @fernando-s97 thanks for providing a reproduction sample. The reason this doesn't work is because you cannot access the repository from a context above the one in which it is provided. On https://gist.github.com/fernando-s97/245f727d37e2ab1f979dfc370779afc4#file-non_working_sample-dart-L15 the context being used to do the lookup doesn't contain the repository because it is provided later on in the build method. I would highly recommend checking out the following video to help clarify this concept: https://youtu.be/iNgwFMm3opE

**Comment by fernando-s97** [comment] 2021-01-10 23:53
I don't know how I missed that. My bad! Thank you!!
