### ISSUE TITLE
fix: 

### ISSUE THREAD

**Issue by ziobudda** [felangel/bloc#3493] opened 2022-08-12 14:55 UTC
**Description**
There is an error in plugins.xml that not permit to install this module in phpstorm sine 2019 version: 
modules com.intellij.modules.java is com.intellij.java since 2019. 

"The [Java language functionality](https://blog.jetbrains.com/platform/2019/06/java-functionality-extracted-as-a-plugin/) was extracted as a plugin in version 2019.2 of the IntelliJ Platform. This refactoring separated the Java implementation from the other, non-language portions of the platform. Consequently, [dependencies](https://plugins.jetbrains.com/docs/intellij/plugin-dependencies.html) on Java functionality are expressed differently in plugin.xml depending on the version of the IntelliJ Platform being targeted".

**Comment by felangel** [comment] 2022-12-27 01:46
Hi @ziobudda 👋 
Thanks for opening an issue!

Can you please provide detailed reproduction steps as well as detailed information regarding your installation of phpstorm? Thanks!

**Comment by felangel** [comment] 2023-01-30 00:00
Closing for now since there is no reproduction sample. Please feel free to provide one and I'm happy to revisit this, thanks!

**Closed by felangel** 2023-01-30 00:00 UTC
Labels: bug, waiting for response, extension
