### ISSUE TITLE
Second event doesn't trigger mapEventToState

### ISSUE THREAD

**Issue by rabyunghwa** [felangel/bloc#1723] opened 2020-09-13 04:25 UTC
In **didChangeDependencies**, I attempt to add two events to the BLoC in a row. The first event can trigger **mapEventToState**. However, the second event doesn't trigger it. Not sure if this is a bug.

```
abstract class EventBase extends Equatable {
  @override
  List<Object> get props => [];
}

class EventA extends EventBase {}

class EventB extends EventBase {}

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    dispatchConcrete();
  }

  void dispatchConcrete() {
    BlocProvider.of<SomeBloc>(context).add(EventA());
    BlocProvider.of<SomeBloc>(context).add(EventB());
  }
```

**Comment by felangel** [comment] 2020-09-13 05:04
Hi @rabyunghwa 👋 
Thanks for opening an issue!

You should be adding an instance of the event so. please update your code:

```dart
void dispatchConcrete() {
  BlocProvider.of<SomeBloc>(context).add(EventA());
  BlocProvider.of<SomeBloc>(context).add(EventB());
}
```

If that still doesn't help please provide the complete bloc implementation, thanks! 👍

**Comment by rabyunghwa** [comment] 2020-09-13 05:36
Hello! Thanks for the response.

```
class SomeBloc
    extends Bloc<EventBase, StateBase> {
  final UseCaseA usecaseA;
  final UseCaseB usecaseB;

  SomeBloc({@required useCaseA, @required useCaseB})
      : assert(useCaseA != null),
        assert(useCaseB != null),
        usecaseA = useCaseA,
        usecaseB = useCaseB, super(StateA());

  @override
  Stream<StateBase> mapEventToState(
      EventBase event,) async* {
    if (event is EventA) {
      ... ...
      yield(StateA());
    } else if (event is EventB) {
      ... ...
      yield StateB();
    }
  }
}

abstract class StateBase extends Equatable {
  @override
  List<Object> get props => [];
}

class StateA extends StateBase {}

class StateB extends StateBase {
  final Data data;
  StateB({@required this.data});

  @override
  List<Object> get props => [data];
}
```

**Comment by rabyunghwa** [comment] 2020-09-13 06:00
```
class SomePage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text(APP_NAME),
      ),
      // body: buildBody(context),
      body: MultiBlocProvider(
        providers: [
          BlocProvider(
            create: (BuildContext context) {
              return sl<SomeBloc>();
            },
          ),
          BlocProvider(
            create: (BuildContext context) {
              return sl<... ...>();
            },
          ),
        ],
        child: Container(...)),
      ),
    );
  }
}
```

```
  sl.registerFactory<SomeBloc>(
    () => SomeBloc(useCaseA: sl(), useCaseB: sl()),
  );
```

**Comment by felangel** [comment] 2020-09-13 06:14
@rabyunghwa are you sure you want to use `registerFactory` rather than `registerSingleton`?

**Comment by rabyunghwa** [comment] 2020-09-13 06:38
I followed a tutorial and it said that we should always use `registerFactory` instead of `registerSingleton` when dealing with BLoCs. Anyways, does this have to do with the issue? I just changed it to `registerLazySingleton` and it made no difference.

**Comment by rabyunghwa** [comment] 2020-09-13 22:58
I can build a demo project if you want. But please help. I've been trying to come up with a fix for days.

**Comment by felangel** [comment] 2020-09-14 01:40
@rabyunghwa yes it would be easiest to help if you can provide a link to a sample github repo which illustrates the problem 👍

**Comment by rabyunghwa** [comment] 2020-09-14 23:11
Hello!

[Here](https://drive.google.com/file/d/1CRxVowOsJlPmarfiVMuWJqR2EPt8FOSL/view?usp=sharing) is the sample project. When I attempt to follow the election, **GetElectionByIdBloc**'s **mapEventToState** doesn't get triggered. Please help.

**Comment by rabyunghwa** [comment] 2020-09-17 07:27
Hello, @felangel !

I'm wondering if you need anything else. If you think that the sample project is incomplete, please let me know. Thanks!

**Comment by narcodico** [comment] 2020-10-01 08:34
Hi @rabyunghwa 👋

Thanks for being so patient about this!

Would you mind sharing the repository through github rather than a zip ? It would be a lot easier for us to help you and start a PR with fixes. Thanks ! 👍

**Comment by rabyunghwa** [comment] 2020-10-01 13:24
Hello, @narcodico !

Thanks for the response!

The project is located [here](https://github.com/rabyunghwa/bloc_test_app). 

Thanks in advance!

**Comment by narcodico** [comment] 2020-10-01 16:15
I created a small PR with a basic start but unfortunately it's impossible for me to work with the app since it throws a bunch of db related errors.
I suggest you create a minimal reproduction app without the extra noise like sqflite and stuff. Thanks 👍

**Comment by rabyunghwa** [comment] 2020-10-02 13:12
Hello, @narcodico !

I just updated the project. Surprisingly, **mapEventToState** can get called this time. Could it have to do with Moor (Sqflite)? Does Bloc work well with Moor?

**Comment by narcodico** [comment] 2020-10-02 13:19
Well your app was throwing a bunch of uncaught errors so very likely it was interfering with everything.
Glad you solved it!

**Comment by rabyunghwa** [comment] 2020-10-02 13:27
Actually, the issue still remains for the real app. Not sure if it has to do with Moor.

**Comment by narcodico** [comment] 2020-10-02 13:29
You definitely need to handle those errors since they were crashing your code.

**Comment by rabyunghwa** [comment] 2020-10-02 13:33
@narcodico There might have been some missing files. I'll upload an updated version. Thanks for being patient!

**Comment by rabyunghwa** [comment] 2020-10-03 04:06
Hello, @narcodico !

[Here](https://github.com/rabyunghwa/bloc_test_app_final) is an updated version of the demo project. I ran the app on a physical Android device and it worked fine. If it still crashes on your end, would you mind specifying the specific device (Android or iOS) and API level? Thanks in advance!

**Comment by narcodico** [comment] 2020-10-04 13:38
I get 
```
Unhandled Exception: DatabaseException(UNIQUE constraint failed: d_b_elections.id (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY[1555])) sql 'INSERT INTO d_b_elections (id, name, electionDay, divisionId, followed) VALUES (?, ?, ?, ?, ?)' args [2000, VIP Test Election, 2021-06-06, ocd-division/country:us, 24]}
```
Samsung A10, 2019, API level 29

Hope that helps 👍

Since this issue is not bloc related I think it's safe to close but if you're still encountering bloc related obstacles feel free to create a minimal sample app that reproduces your issues and share it.

**Comment by rabyunghwa** [comment] 2020-10-22 07:34
Hello! I have a question and I really need your help. So is the BLoC automatically closed after an event is added? I suspect that the reason why the second event doesn't trigger mapEventToState is that the BLoC has already been closed. If this is the case, then what should I do to fix it? Thanks in advance!

**Comment by amorenew** [comment] 2020-10-23 02:38
@rabyunghwa I have a similar case, Dio post makes content-type as null somewhere so await Future Dio post was kept awaiting and not return anything.
So by adding timeout and fix content-type I was able to fix my issue
Confirm if you have the same case otherwise you need to provide a sample to @felangel

**Comment by amorenew** [comment] 2020-10-23 02:40
@rabyunghwa maybe similar 
https://github.com/felangel/bloc/issues/1853
@felangel But why in my case event is not triggering if there is an awaiting for a Future call??

**Comment by amorenew** [comment] 2020-10-23 05:07
Actually, my root issue was in an interceptor which has a Future call waiting forever.
I found that no need for await there so I removed it.
https://github.com/eyeem/dio_firebase_performance/blob/88aeb48fa7d2f03957fcae38aed83c682a73588d/lib/src/dio_firebase_performance.dart#L34

**Comment by felangel** [comment] 2020-10-23 16:44
@rabyunghwa a bloc is closed automatically if it was created by a BlocProvider when the BlocProvider is unmounted from the widget tree. You can override `close` on the bloc and add a log statement to test whether it's being closed. If that's the case then likely it means you've scoped the bloc too low in the widget tree and you need to provide it higher up.

Closing for now and hope that helps! Feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-10-23 16:44 UTC
Labels: question, waiting for response

**Comment by rabyunghwa** [comment] 2020-10-24 23:35
@felangel Thanks for the response. However, the issue still remains, which has been driving me nuts. It seems that this issue only exists if BLoC is used together with Moor. Would it be possible for me to provide a demo app where Moor is also implemented? I think that it's their combination that is causing the issue.

**Comment by rabyunghwa** [comment] 2020-10-25 00:03
@amorenew Thank you for your help! However, that didn't fix the issue. I'm still searching around for a fix.

**Comment by rabyunghwa** [comment] 2020-10-25 00:06
@narcodico The issue you mentioned earlier, in my opinion, doesn't have anything to do with **mapEventToState** not being called. Could you try ignoring that issue?

**Comment by amorenew** [comment] 2020-10-25 05:24
@rabyunghwa I solved my case by using print('') everywhere which lead me to know it better

**Comment by Abiri99** [comment] 2021-08-10 07:42
Actually I have this problem too, and the thing is that I have a list which every item in it dispatches its own event but only every other one of them is updated by the state.
