### ISSUE TITLE
BlocListener invokes regardless which page is navigated

### ISSUE THREAD

**Issue by pslamka** [felangel/bloc#1082] opened 2020-04-21 09:34 UTC
Hi,
thank you for this neat library!

It seems that BlocListener which is constructed somewhere under the material app home: property (the '/' route) invokes on state change even when I push another route '/detail'. I roughly understand why this works this way, since all the routes are still part of the navigation stack.

I use BlocListener for displaying a warning dialog when some state changes. Say I have pages A, B, and C and push them in A/B/C order, but would like to display the dialog only on pages A and C. So I would place bloc listeners to top of page A and C widget trees. However, when the state changes, the dialog would pop-up once on page A (correct), once on page B (should not at all), and twice on page C (should only pop-up once).

Is there a way to achieve BlocListener functionality to be specific for a given page? Right now my pages are always influenced by other listeners that exist on the navigation stack. It may be worth mentioning that my blocs are provided globally at the very top of the widget tree above the MaterialApp because that is suitable for my needs.

Thanks for the ideas!

**Comment by felangel** [comment] 2020-04-22 05:02
Hi @pslamka 👋 
Thanks for opening an issue!

This is expected behavior because when you use `Navigator.of(context).push(...)` you are not removing the underlying widgets so BlocListeners will continue to listen. The way to solve this is to move the `BlocListeners` into the respective pages so that when a page is popped, the `BlocListener` is also unmounted from the widget tree and no longer reacting to state changes.

Hope that helps and closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-04-22 05:02 UTC
Labels: question
