### ISSUE TITLE
bloc_test too old dependencies

### ISSUE THREAD

**Issue by bartekwk** [felangel/bloc#3472] opened 2022-08-04 18:49 UTC
When should we expect new release of bloc_test library with upgraded dependencies. When I am trying to import the newest version I am getting this beautifull error. Downgrading bloc_test doesnt help and I dont want to downgrade other libraries. Please provide this update as soon as possible. Cheers.

![image](https://user-images.githubusercontent.com/48072101/182930073-a47b0c4f-b9a1-400a-9f16-f5cd19214df4.png)

**Comment by felangel** [comment] 2022-08-04 19:30
Hi @bartekwk 👋 
Thanks for opening an issue!

This looks like it's a conflict between `injectable_generator` and `flutter_test` based on the error. If you remove `bloc_test` does the error go away?

**Comment by bartekwk** [comment] 2022-08-05 06:59
Yes, it occurred only after adding bloc_test. I've tried to add different version of this package but every one is conflicted.

**Comment by felangel** [comment] 2022-08-05 12:53
> Yes, it occurred only after adding bloc_test. I've tried to add different version of this package but every one is conflicted.

Can you share your `pubspec.yaml`?

**Comment by felangel** [comment] 2022-08-13 16:06
@bartekwk any update? Were you able to resolve the issue? If not, can you provide link to a minimal reproduction sample? Thanks!

**Comment by bartekwk** [comment] 2022-08-14 10:34
name: mobile
description: A new Flutter project.

publish_to: "none"
version: 2.0.4+20


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: "2.10.5"

dependencies:
  amplitude_flutter: ^3.10.0
  app_settings: ^4.1.6
  app_tracking_transparency: ^2.0.2+4
  auto_route: ^4.0.0
  auto_size_text: ^3.0.0
  awesome_notifications: ^0.6.21
  cached_network_image: ^3.2.0
  chewie: ^1.3.3
  crypto: ^3.0.2
  cupertino_icons: ^1.0.5
  devicelocale: ^0.5.2
  dio: ^4.0.6
  easy_localization: ^3.0.0
  expandable_page_view: ^1.0.13
  file_picker: ^4.6.1
  firebase_analytics: ^9.1.10
  flutter_calendar_week: ^2.1.1
  firebase_core: ^1.18.0
  firebase_crashlytics: ^2.8.2
  firebase_dynamic_links: ^4.2.6
  flutter_inappwebview: ^5.4.3+7
  firebase_messaging: ^11.4.2
  firebase_remote_config: ^2.0.9
  firebase_storage: ^10.2.18
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_facebook_sdk: 1.0.0
  flutter_hooks: ^0.18.3
  flutter_html: ^3.0.0-alpha.5
  flutter_markdown: ^0.6.10
  flutter_multi_formatter: ^2.5.7
  flutter_native_timezone: 2.0.0
  flutter_staggered_grid_view: ^0.6.1
  flutter_svg: ^1.0.3
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  hive: ^2.2.2
  image_picker: ^0.8.5+3
  in_app_purchase: ^3.0.6
  in_app_review: ^2.0.4
  injectable: ^1.5.3
  intercom_flutter: ^7.2.0
  json_annotation: ^4.5.0
  mockito: ^5.2.0
  open_file: ^3.2.1
  package_info: 2.0.2
  path_provider: ^2.0.11
  pdf: ^3.8.1
  permission_handler: ^8.2.6
  platform_device_id: ^1.0.1
  platform_info: ^3.2.0
  provider: ^6.0.3
  printing: ^5.9.1
  random_color: ^1.0.5
  retrofit: ^3.0.1+1
  rxdart: ^0.27.4
  shared_preferences: ^2.0.15
  share_plus: ^4.0.8
  shimmer: 2.0.0
  showcaseview: ^1.1.7
  step_progress_indicator: ^1.0.2
  store_redirect: ^2.0.1
  syncfusion_flutter_charts: 19.2.55
  syncfusion_flutter_core: 19.2.55
  syncfusion_flutter_datepicker: 19.2.55
  touchable: ^1.0.2
  uni_links: 0.5.1
  url_launcher: ^6.1.3
  validators: 3.0.0
  visibility_detector: ^0.3.2
  webview_flutter: ^3.0.4

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.1.5
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  hive_generator: ^1.1.3
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0
  lint: ^1.8.2
  retrofit_generator: ^4.0.1

flutter_icons:
  image_path: "assets/images/app_icon/full_icon.png"
  adaptive_icon_background: "assets/images/app_icon/icon_background.png"
  adaptive_icon_foreground: "assets/images/app_icon/icon_content.png"
  ios: true
  android: true

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/svg/
    - assets/images/svg/lines/
    - assets/images/png/
    - assets/images/png/courses/
    - assets/images/png/quiz/
    - assets/images/video/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

**Comment by felangel** [comment] 2022-08-15 00:33
@bartekwk I think the issue is you're on an older version of Flutter which causes an incompatibility between `injectable_generator` and `flutter_test`.

I was unable to reproduce the issue on Flutter 3.0.5 (stable) with the following `pubspec.yaml`

```yaml
name: example

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.4
```

**Comment by bartekwk** [comment] 2022-08-15 10:19
This pubspec was not generating any problems because it hasnt got bloc_test package.So it couldnt be issue with incompatibility between injectable_generator and flutter_test. When I added bloc test error was thrown.

**Comment by bartekwk** [comment] 2022-08-15 10:20
No matter what version, after adding bloc_test error was shown.

**Comment by bartekwk** [comment] 2022-08-20 10:26
@felangel what do you think about that ?

**Comment by felangel** [comment] 2022-08-20 14:26
> @felangel what do you think about that ?

Can you use the pubspec.yaml I referenced above and check whether you’re able to install the dependencies?

**Comment by felangel** [comment] 2022-09-28 05:21
Closing for now since there is still no actionable next steps on my end. Feel free to comment with additional information and I'm happy to continue the conversation 👍

**Closed by felangel** 2022-09-28 05:21 UTC
Labels: question, waiting for response

**Comment by ramanverma2k** [comment] 2022-11-03 14:33
Hi, I was also facing similar issue when adding ``bloc_test``. In my case the real culprit was ``build_runner``.

2.3.1 & 2.3.2 version isn't working.

This fixed my issue:
```yaml
build_runner: ^2.3.0
```

It seems like ``build_runner`` from version 2.3.1 and above depends on flutter_test as well. Hence the dependency resolving error.

Hopefully this will be helpful for anyone who is facing the same issue.
