### ISSUE TITLE
fix: BlocBuilder rebuilds on navigation return but there is no event in the logs about it

### ISSUE THREAD

**Issue by Soliardi-Chyngyz** [felangel/bloc#3769] opened 2023-03-18 06:29 UTC
Hello everyone.

The situation is the following: I have 5 blocks on one page and each one returns a widget, however, when navigating to a new page (even if it is empty Scaffold () and I definitely don’t update any block there!), And returning back, the blocks start to rebuild (and not only blocks but also widgets are static on the same level with the block). When I comment out the problem block, the problem disappears in this case and none of the blocks are rebuilt. I write print, log(msg, name: 'Bug') but those events are not fired.

The problem block is quite standard. I try the navigation template Navigation ... -> the reaction is the same.

flutter_bloc: ^8.1.2 (also tried earlier version)

request:
`BlocProvider<RestaurantsCubit>(
               create: (_) => sl<RestaurantsCubit>()..getRestaurants(),
             ),`

request method:
```
void getRestaurants() async {
     emit(state.copyWith(status: CubitStatus.loading));
     final failureOrRestaurants = await fetchRestaurants(
       FetchRestaurantsParams(),
     );
     failureOrRestaurants.fold(
         (l) => emit(state.copyWith(
               status: CubitStatus.error,
               message: l.message,
             )), (r)async {
       emit(state.copyWith(
         status: CubitStatus.success,
         restaurants: r,
       ));
     });
   }
```

listener:
```
Column(children: [
  BlocBuilder(retun: AnyButton(navigate ... ))... //rebuild too
  Row( child: AnyButton(navigate ... )) // rebuild too

  BlocBuilder<RestaurantsCubit, RestaurantsState>(
    builder: (context, state) {
     print('HEY! ! ! I REBUILDED! - ${state.status}');
      if (state.status.isLoading) {
          return CustomShimmerWidget(width: 156.w, height: 100.h);}
      if (state.status.isSuccess) {
          r.eturn state.restaurants.isEmpty
              ? Text('empty(')
              : Listview(...) });

  BlocBuilder.. // rebuild too
```

**Comment by tenhobi** [comment] 2023-03-18 09:03
Hi. It would be best if you would link a minimal reproducible example. 

However most often these "issues" with bloc and routes might be caused by not providing blocs at the right places or using wrong type of route navigation.

Sounds like you are replacing your route stack, meaning using `go` rather than `push`. 

Aka routes stack is like this (go)

- bloc route
- empty scaffold route

and not like this (push)

- bloc route
  - empty scaffold

Is this the case? 

If you are replacing the stack (go), the new route is rebuilt. If you want to preserve the bloc state, you would have to move the bloc providers above the router.

If this is not the case, please add more details or add a link to the minimal repository.

**Comment by felangel** [comment] 2023-04-15 19:02
Closing for now since there are no actionable next steps and there is no minimal reproduction sample provided. Feel free to provide a minimal reproduction sample if this is still an issue and I'm happy to take a closer look, thanks 👍

**Closed by felangel** 2023-04-15 19:02 UTC
Labels: question, waiting for response
