### ISSUE TITLE
fix: 

### ISSUE THREAD

**Issue by shabeerseeroo1** [felangel/bloc#3898] opened 2023-07-02 17:07 UTC
**Description**
when defining bloc in the root widget and whenever re-enters the corresponding class the previous widget shows for a few milliseconds and then the bloc triggering
**Steps To Reproduce**

**Expected Behavior**
when we re-enter the page I don't want to show the previous widget for a few milliseconds

**Screenshots**

**Additional Context**
/// bloc state class
![image](https://github.com/felangel/bloc/assets/68379664/813bfce9-a748-485c-afd0-2da060645cd8)
![image](https://github.com/felangel/bloc/assets/68379664/5543bb81-d47a-4d7b-99f8-7a6ce9d3346b)

///bloc event class
![image](https://github.com/felangel/bloc/assets/68379664/ea94e22f-6316-4d79-b8b0-02d5a3266281)

///bloc class
![image](https://github.com/felangel/bloc/assets/68379664/50927243-ec0a-4545-aa36-6756a05c852c)
![image](https://github.com/felangel/bloc/assets/68379664/45fb9911-f505-4a91-83c8-2c8d200410d3)
in here calling the initial state and define a series of events

///page
![image](https://github.com/felangel/bloc/assets/68379664/2fb2a986-b624-44fa-b388-56b84bc96de0)
in there adding bloc event

**Comment by felangel** [comment] 2023-07-15 05:43
Hi @shabeerseeroo1 👋 
Thanks for opening an issue!

Unfortunately, it's really hard to help with just the screenshots you've provided. Can you please create a minimal reproduction sample and share the link so that we can run/debug the issue locally? Thanks!

**Comment by felangel** [comment] 2023-08-02 02:26
Closing for now since there is no link to a reproduction sample. Feel free to provide one and I'm happy to take a closer look 👍

**Closed by felangel** 2023-08-02 02:26 UTC
Labels: bug, waiting for response, needs repro info
