### ISSUE TITLE
MultiBlocBuilder?

### ISSUE THREAD

**Issue by EdsonOnildoJR** [felangel/bloc#841] opened 2020-02-02 23:44 UTC
A case of use when this feature is helpful is when we have a widget that responses at two or more independents external events. In this case, the widget is wrapped with two or more bloc builder that managed this events. Nested blocs can't be a really problem, but is expressive to write, like that as create another bloc which has dependencies on the two blocs.

A example where this feature can be helpful.

```dart
return BlocBuilder<BlocA, bool>(
  builder: (context, stateA) {
    return BlocBuilder<BlocB, int>(
      builder: (context, stateB) {
        if (stateA || stateB == 1) {
          // do something
        }
        // do another thing
      }
    );
  },
);
```

Some help?

Thanks for this unbelievable lib!!!

**Comment by felangel** [comment] 2020-02-02 23:51
Hi @EdsonOnildoJR 👋
Thanks for opening an issue and for the positive feedback!

This is a duplicate of https://github.com/felangel/bloc/issues/538 and we decided against it because in order for it to work we'd need MultiBlocBuilder2, MultiBlocBuilder3, ..., MultiBlocBuilderN and the API would be very verbose to the point where it's actually more readable to just nest BlocBuilders. Another option is to create another bloc which composes the states of the two blocs so you have just a single BlocBuilder which your UI responds to. Let me know what you think.

**Comment by EdsonOnildoJR** [comment] 2020-02-03 00:28
I don't fluent in dart, something like that it's possible?

```dart
MultiBlocBuilder(
  blocs: [Bloc1, Bloc2, BlocN],
  states: [State1, State2, StateN],
  builder: (context, stateA, stateB, stateN) {
    // ...
  }
);
``` 

I'm thinking in this widget just returns a nested BlocBuilder.

Thanks for the fast answer and feedback!!

**Comment by felangel** [comment] 2020-02-03 01:55
@EdsonOnildoJR what you're suggesting would only be possible if the states were dynamically typed. You would then have to cast your states like:

```dart
MultiBlocBuilder(
  blocs: [Bloc1, Bloc2, BlocN],
  states: [State1, State2, StateN],
  builder: (context, stateA, stateB, stateN) {
    // stateA, stateB, stateN are dynamic at this point.
    if ((stateA as StateA) is InitialStateA) { ... }
  }
);
```

**Comment by EdsonOnildoJR** [comment] 2020-02-03 02:47
It's sounds good for me! Better that another solutions available in this moment (nested BlocBuilder, etc...)

I can't think anything better, maybe pass the states through the generics, but that would limit the number of blocs...

What would you think about that?

**Comment by felangel** [comment] 2020-02-03 03:32
I really don't want to introduce functionality in the library that isn't type-safe. If you'd like I can put together an implementation that you can use within your own project but I would prefer not to include that in the library. If you don't mind can you share your use case? There might be a better way to approach the issue which doesn't rely on many nested BlocBuilders.

**Comment by felangel** [comment] 2020-02-03 19:38
Closing for now but feel free to comment with additional info and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-02-03 19:38 UTC
Labels: duplicate
