### ISSUE TITLE
fix: Storage is null with `flutter test` and `MaterialApp.router()` with auto_route

### ISSUE THREAD

**Issue by DriesCruyskens** [felangel/bloc#3225] opened 2022-02-14 13:43 UTC
**Description**

While running `flutter test`, when using a `HydratedCubit` below the `MaterialApp.router()` widget together with the [`auto_route`](https://pub.dev/packages/auto_route) package. An error is thrown:
```
Storage was accessed before it was initialized.
Please ensure that storage has been initialized.

For example:

final storage = await HydratedStorage.build();
HydratedBlocOverrides.runZoned(
  () => runApp(MyApp()),
  storage: storage,
);
```
For some strange reason, `_overrides` is `null` in this specific circumstance so it thinks the storage has not been initialized yet. This does not occur when running the app with `flutter run`, nor when `HydratedCubit` is used above `MaterialApp.router()` (with auto_route), nor when any other `MaterialApp()` (without auto_route) is used.

**Steps To Reproduce error**

1. clone reproducable example <https://github.com/DriesCruyskens/hydrated_bloc_auto_route_bug_minimal_example>
2. run `flutter test integration_test/integration_test.dart`

**Steps To Avoid error**

1. clone reproducable example
2. run `flutter run lib/main.dart`
OR 
2. run `flutter test integration_test/integration_test.dart` with any of the other commented out `MaterialApp`s 
OR 
2. run `flutter test integration_test/integration_test.dart` with `ProfileCubit().fetchProfile();` above `MaterialApp.router()`

**Expected Behavior**

`_overrides` should not be null or the behaviour should at least be the same whether `flutter run` or `flutter test`  is run.

**Comment by felangel** [comment] 2022-02-14 14:17
Hi @DriesCruyskens 👋
Thanks for opening an issue!

This looks like a duplicate of #3078. We’re working on a solution and apologize for the inconvenience!

**Closed by felangel** 2022-02-14 14:17 UTC
Labels: duplicate
