### ISSUE TITLE
Yield new state manually

### ISSUE THREAD

**Issue by hawkinsjb1** [felangel/bloc#845] opened 2020-02-04 20:32 UTC
Sometimes I find myself using states to trigger a certain listener, and once the listener has been triggered I would like to go back to an 'Idle' state. I know I can create empty events that meet this purpose, but I was wondering if we could do this inline from a BlocProvider.of(context) reference.
For example:

```
listener: (context, state) {
  if (state is AddedItem) {
    // do something
    BlocProvider.of(context).yield(InitialState())
  }
}
```

I realize this may go against the BLoC pattern, but it would also reduce unnecessary boilerplate

**Comment by tenhobi** [comment] 2020-02-04 20:34
Hi, could you provide more context?

**Comment by hawkinsjb1** [comment] 2020-02-04 20:42
I guess there would also have to be some added protection to avoid infinite loops

**Comment by tenhobi** [comment] 2020-02-04 20:47
This goes against the very basics of architecture an app. With BLoC or any other state management solution, you are trying to separate your code to layers - view and logic. Try rather architecture-out your problem, so you would keep your code nice and clean. 💙

**Comment by hawkinsjb1** [comment] 2020-02-04 21:02
As far as I can tell, blocbuilder's purpose is to create a 1-to-1 view of a logical state. Bloclistener's purpose is to allow for a visual reaction to a state change, however doesn't this mean that a blocbuilder's view may no longer accurately represent the current logical state due to a change created by the listener? Idk I feel like there are edge cases when combining reactive and representative state management that makes things out of sync and this can only be fixed by creating multiple UI-based events. And once you are using events to handle UI only and not 
business logic, then you are essentially combining the UI/logical layers anyway (UI states inside of bloc). Maybe I need more experience with the library to create architecture that avoids cirumstances

**Comment by hawkinsjb1** [comment] 2020-02-04 21:23
Let's say I create some new object from a form, send it to the server, retrieve the json response, and want to push a page using that response's details. I would usually go about this
by using an 'AddedObject' state which triggers a listener to push a new page using the object. Once I push this page, I no longer think the 'AddedObject' state is neccesary. The current
solution would be to either manually pass in a navigation function to the bloc so it can activate the function on data load (bad solution), or checking for the 'AddedObject' state on the new page's 
load and switch back in initState (doesn't work in StatelessWidgets). What is the recommended way to handle this situation

**Comment by felangel** [comment] 2020-02-04 21:39
Hi @hawkinsjb1 👋 
Thanks for opening an issue!

As @tenhobi mentioned this violates the bloc library paradigm. I think in this case, the problem is it seems you're thinking of states as triggers when the events should be the triggers.

Rather than having an `AddedObject` state I would recommend having an `AddedObject` event which triggers an update in the bloc's state. Hope that helps!

**Comment by felangel** [comment] 2020-02-05 15:46
Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-02-05 15:46 UTC
Labels: question, waiting for response
