### ISSUE TITLE
CircularProgressIndicator background black not transporter (flutter_login example)

### ISSUE THREAD

**Issue by Al-Hussein-96** [felangel/bloc#1130] opened 2020-05-06 04:33 UTC
![844359c9-e5c8-43ce-8e2a-8d429f435060](https://user-images.githubusercontent.com/31496257/81138781-de2d3a00-8f6b-11ea-8d55-ff54c095a2c0.jpg)

**Comment by heshaShawky** [comment] 2020-05-07 00:22
Change the UI code brother, I'm sure you are not using `Scaffold` as a parent `Widget` for the  `CircularProgressIndicator`. 

The Login example just a sample for `logic` and how you use the Bloc Library in action.

**Comment by felangel** [comment] 2020-05-07 01:38
Hi @Al-Hussein-96 👋 
Thanks for opening an issue!

As @heshaShawky mentioned, this is just because there is no `Scaffold` as a parent. The primary focus of the example was on using bloc with login and not on the UI but I can update the example 👍

**Comment by Al-Hussein-96** [comment] 2020-05-07 02:49
thank you for your response,
yes I'm trying to apply bloc with login everything work, good example no problem except this small problem 

when I wrap Center with parent Scaffold
```
class LoadingIndicator extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
    body: Center(
      child: CircularProgressIndicator(),
    ),
  );
}
```
same problem but white screen not transporter 

![Screenshot_20200507_054211_com sportstartup cap10](https://user-images.githubusercontent.com/31496257/81249052-62dc8e80-9026-11ea-8f49-315f99dbd37c.jpg)

**Comment by felangel** [comment] 2020-05-07 05:10
@Al-Hussein-96 do you mean the app is stuck on the loading screen? Are you running the exact code from the example or have you written your own version?

**Comment by felangel** [comment] 2020-05-10 16:37
Closing for now since it’s unclear what the issue is.

Feel free to comment with more information and I’m happy to continue the conversation 👍

**Closed by felangel** 2020-05-10 16:37 UTC
Labels: question, waiting for response
