### ISSUE TITLE
Flutter bloc null safety is not able to generate dynamic button in form ? 

### ISSUE THREAD

**Issue by newbieflutter** [felangel/bloc#2734] opened 2021-09-10 13:21 UTC
I am currently migrating my old codes to all new version of flutter to support null safety. In my login form I have this logic. Before this it works fine. Now when I run this codes I get this error "`This Form widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.`" How it works is basically when the bloc is ready will value only then I will build the button but the text boxes are build first.

```
What I have tried is WidgetsBinding.instance?.addPostFrameCallback(
                        (_) => but it does not give any error but the button is not shown up there.


Here is part of my codes below.

```
Widget loginForm(BuildContext context1) {
    final _auth = Provider.of<AuthModel>(context, listen: true);
    return Form(
      key: _formKey,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(height: getProportionateScreenHeight(10)),
          Text(
            'USERNAME',
            style: loginFontStyle,
            textAlign: TextAlign.left,
          ),
          SizedBox(height: getProportionateScreenHeight(10)),
          buildEmailFormField(),
          SizedBox(height: getProportionateScreenHeight(20)),
          Text(
            'PASSWORD',
            style: loginFontStyle,
            textAlign: TextAlign.left,
          ),
          SizedBox(height: getProportionateScreenHeight(10)),
          buildPasswordFormField(),
          SizedBox(height: getProportionateScreenHeight(20)),
          
          Row(
            crossAxisAlignment: CrossAxisAlignment.center,
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              BlocBuilder<LoginBloc, LoginApiState>(
                  builder: (BuildContext context, LoginApiState state) {
                print("Build login  " + state.toString());
                if (state is LoginApiStateInitial) {
                  return CircularProgressIndicator();
                }
                if (state is SetIDState) {
                  
                  if (localID != "" &&
                      localID != null) {
                    return Expanded(
                        child: DefaultButton(
                      text: "LOGIN",
                      press: () {
                        print("Form Validate Status" +
                            _formKey.currentState!.validate().toString());
                        if (_formKey.currentState!.validate()) {
                          _formKey.currentState!.save();
                          if (email != "" &&
                              password != "" &&
                              password.length >= 8 &&
                              emailValidatorRegExp.hasMatch(email) &&
                              localID != "") {
                            loginBLoC.loginVerify(
                                email, password, localID);
                           
                          }
                          
                        }
                      },
                    ));
                  } else {
                    return CircularProgressIndicator();
                  }
                }

```
What can I do to make it work like the previous version where it was perfectly working?

**Comment by felangel** [comment] 2021-09-10 16:24
Hi @newbieflutter 👋 
Thanks for opening an issue!

Can you please share a link to a minimal reproduction sample on GitHub that illustrates the problem you're facing? It would be a lot easier to help if you could provide a link that I can run/debug locally, thanks! 🙏

**Comment by felangel** [comment] 2021-09-19 22:57
Closing for now since there is no reproduction sample. Feel free to include a link to a reproduction sample and I'm happy to revisit this 👍

**Closed by felangel** 2021-09-19 22:57 UTC
Labels: question, waiting for response
