### ISSUE TITLE
blocbuilder is triggering first time but not yielding updated data after triggering event again

### ISSUE THREAD

**Issue by ZAT90** [felangel/bloc#1704] opened 2020-09-06 10:17 UTC
1. I am working with sqflite to add data to a table and then add, update or retrieve all the data from the table. I am using blocbuilder  and triggering "getCartProducts" event to retrieve the values from the database. I am getting the data only for the first time. But when am triggering "addToCart" event, right after that I want to get the updated table by triggering "getCartProducts" event again. But it is not updating on the go except i am navigating to other screen and coming back. May I know if I am doing something wrong here or there has to be a different workaround?  Below is the code .
Issue is about when working with DbBloc. ProductBloc is alright.

class ProductPage extends StatefulWidget {
  // ProductPage({Key key, this.title}) : super(key: key);

  // final String title;
  @override
  _ProductPageState createState() => _ProductPageState();
}

class _ProductPageState extends State<ProductPage> {
  @override
  void initState() {
    super.initState();
    initalizePreferences().then((value) =>
        debugPrint('langhome ${PreferenceManager.instance.langCode}'));
  }

  Future<String> addToCart(Products product) async {
    DbBloc()..add(DbEvents(product: product, status: DbEvStatus.addToCart));
    return product.name;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text("Products"),
        ),
        body: MultiBlocProvider(
            providers: [
              BlocProvider<ProductBloc>(
                lazy: false,
                create: (context) => ProductBloc()
                  ..add(ProductEvents(status: ProductEvStatus.getProducts)),
              ),
              // ------ I AM CREATING THE BLOC HERE --------
              BlocProvider<DbBloc>(
                lazy: false,
                create: (context) =>
                    DbBloc()..add(DbEvents(status: DbEvStatus.getCartProducts)),
              )
            ],
            child: BlocBuilder<ProductBloc, List<Products>>(
                builder: (context, products) {
              debugPrint('data: ${products.length}');
              return BlocBuilder<DbBloc, List<CartDbModel>>(
                    
                  builder: (context, cartProducts) {
                // THIS IS NOT UPDATING WHEN I AM TRIGGERING THE EVENT IN THE ADD BUTTON
                debugPrint('cartproducts: ' + cartProducts.length.toString());
                return Container(
                  color: Color(0xf8f8ff),
                  padding: EdgeInsets.all(10),
                  child: new ListView.builder(
                      itemCount: products.length,
                      itemBuilder: (BuildContext ctxt, int index) {
                        return Card(
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(10.0),
                          ),
                          child: new ListTile(
                            title: Text(products[index].name),
                            subtitle: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Container(
                                  margin: EdgeInsets.only(top: 5),
                                  child: Row(
                                    children: [
                                      Container(
                                        width:
                                            MediaQuery.of(context).size.width /
                                                1.5,
                                        child: Text(
                                          products[index].description,
                                          maxLines: 2,
                                          overflow: TextOverflow.ellipsis,
                                        ),
                                      ),
                                      GestureDetector(
                                          onTap: () => debugPrint('remove'),
                                          child: Icon(Icons.remove,
                                              color: Colors.black)),
                                      Text('0'),
                                     // THIS IS THE ADD BUTTON EVENT
                                      GestureDetector(
                                          onTap: () {
                                            addToCart(products[index])
                                                .then((value) {
                                              
                                                Future.delayed(const Duration(milliseconds: 500), () {
                                                this.setState(() {
                                         // I AM TRIGGERING THE EVENT HERE BUT cartproducts not updating 
                                                DbBloc()
                                                  ..add(DbEvents(
                                                      status: DbEvStatus
                                                          .getCartProducts));
                                              });
                                              });
                                            });
                                          },
                                          child: Icon(Icons.add,
                                              color: Colors.black))
                                    ],
                                  ),
                                ),
                                Container(
                                  margin: EdgeInsets.only(top: 5),
                                  child: Text(
                                    'MYR ${products[index].price.toString()}',
                                    style: TextStyle(
                                        color: Colors.purple,
                                        fontWeight: FontWeight.bold),
                                  ),
                                )
                              ],
                            ),
                          ),
                        );
                      }),
                );
              });
            })));
  }
}

**Comment by ZAT90** [comment] 2020-09-06 10:51
this is the bloc:
import 'package:timeMachine/model/cartDb.dart';
import 'package:timeMachine/model/products.dart';
import 'package:dio/dio.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:timeMachine/storage/dbCart.dart';

enum DbEvStatus { getCartProducts, addToCart, updateCartProducts }

class DbEvents {
  final int id;
  final DbEvStatus status;
  final Products product;
  final List<CartDbModel> carts;

  const DbEvents({this.id, this.carts, this.product, @required this.status});
}

class DbBloc extends Bloc<DbEvents, List<CartDbModel>> {
  DbBloc() : super(List<CartDbModel>());
  //ProductApi productApi = ProductApi();
  DatabaseCart databaseCart = DatabaseCart();
  List<CartDbModel> cartProducts = [];
  CartDbModel cartItem = CartDbModel();
  Response response;


  @override
  Stream<List<CartDbModel>> mapEventToState(DbEvents event) async* {
    switch (event.status) {
      case DbEvStatus.getCartProducts:
        databaseCart.getAllCarts().then((value) {
          // if (value != null) {
          debugPrint('bloc get all: $value');
          value.forEach((element) {
            debugPrint('cart element ${element.id}');
            cartProducts.add(element);
          });
          // }
        });
        yield cartProducts;
        break;
      case DbEvStatus.addToCart:
        databaseCart.getAllCarts().then((value) {
          debugPrint('bloc add to cart value: $value');
          cartItem.id = event.product.id;
          cartItem.name = event.product.name;
          cartItem.availableQuantity = event.product.availableQuantity;
          cartItem.price = event.product.price;
          cartItem.description = event.product.description;
          if (value.length > 0) {
            List<CartDbModel> findCart = value
                .where((element) => element.id == event.product.id)
                .toList();
            debugPrint('findcart ${findCart.length}');
            if (findCart.length > 0) {
              cartItem.dbQty = (int.parse(findCart[0].dbQty) + 1).toString();
              if (int.parse(cartItem.dbQty) <=
                  event.product.availableQuantity) {
                databaseCart.updateCart(cartItem);
              }
            } else {
              cartItem.dbQty = "1";
              databaseCart.saveToCart(cartItem);
            }
          } else {
            cartItem.dbQty = "1";
            databaseCart.saveToCart(cartItem);
            // debugPrint('db quantity: ${int.parse(cartItem.dbQty)}');
          }
          //cartProducts = value == null ? [] : value;
        });
        //debugPrint('this is the addtoCart event:${event.product.id}');
        break;
      case DbEvStatus.updateCartProducts:
        debugPrint('this is the postproduct event:}');
        break;
      default:
        addError(Exception('unsupported event'));
    }
  }
}

**Comment by felangel** [comment] 2020-09-07 21:54
Hi @ZAT90 👋 
Thanks for opening an issue!

The problem is you are mutating state and maintaining internal state in your bloc as opposed to creating new instances of state and keeping all state as part of the bloc's state class. I would highly recommend doing the following:

1. Change your bloc state type to something more specific than `List` (`List<dynamic>`)
2. Remove `cartProducts` from your bloc and instead create a new list of products based on the current state and the incoming event. See the [todos example](https://github.com/felangel/bloc/blob/master/examples/flutter_todos/lib/blocs/todos/todos_bloc.dart) for a reference.
3. Check out the [FAQs](https://bloclibrary.dev/#/faqs?id=state-not-updating) for more information about why the state isn't updating.

Hope that helps! 👍 

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 😄

**Closed by felangel** 2020-09-07 21:54 UTC
Labels: question

**Comment by ZAT90** [comment] 2020-09-09 02:31
https://github.com/felangel/bloc/issues/1712
sorry to bother you but just came across another issue on the way. a bit stuck with this. would be nice if u could do some help. Thanks a lot man
