### ISSUE TITLE
feat: ui one time callback action

### ISSUE THREAD

**Issue by AlexanderShniperson** [felangel/bloc#3527] opened 2022-09-09 08:09 UTC
**Description**

in our projects, we have the need to perform some actions with the user interface on a user action and these actions do not affect the state of the screen. in these situations, we use a separately created StreamController to which we subscribe in screens, we would like to have a built-in ability to perform such operations.

Example of action:
user tap on some button at the screen to request forgot password flow, we send some event to Bloc where we send some request to API that resulting with Failure (user can't do that) or with Success (returned some FlowId that mean he can continue), then we send some action to StreamController that listened at Screen to show an Error or Navigate to the next page with needed parameters.

we in the team decided that such actions cannot be saved in the state because on certain events the screen can be rebuilt and this action can be called again, so this "should be done once and forgotten"

**Desired Solution**

expand the Bloc in such a way that you can send actions to screens without changing the state, just like it is done with events that come to the block from the user interface.
what i mean: `Bloc<Event, Action, State>`

**Alternatives Considered**

currently we create separate StreamController which we subscribe from the Screen

**Additional Context**

non

**Comment by felangel** [comment] 2022-09-11 19:26
Hi @AlexanderShniperson 👋 
Thanks for opening an issue!

I recommend using a BlocListener for performing side-effects in response to a state change. You can refer to the [SnackBar Recipe](https://bloclibrary.dev/#/recipesfluttershowsnackbar) for more details/information. This also sounds a duplicate of https://github.com/felangel/bloc/issues/3178 so I recommend reading through that discussion. Closing for now but feel free to comment with any additional thoughts and I'm happy to continue the conversation 👍

**Closed by felangel** 2022-09-11 19:26 UTC
