### ISSUE TITLE
feat: Add `maybeOf` in BlocProvider

### ISSUE THREAD

**Issue by SuhwanCha** [felangel/bloc#3666] opened 2022-12-19 03:34 UTC
**Description**

Static method `BlocProvider.of` returns `Provider` when context contains bloc, and throw error when doesn’t.
When we are not sure context contains bloc or not, we should wrap `BlocProvider.of` with try/catch.
But like `Navigator.maybeOf`, `BlocProvider.maybeOf` returns nullable provider should be better if we don't know there is bloc in context.

**Desired Solution**

Add static method maybeOf, that returns nullable `Provider?` in `BlocProvider`

Currently, we should

```dart
try {
      BlocProvider.of<SomeBloc>(context).add(SomeEvent());
    } catch (e) {
      // something
    }
```

And with `BlocProvider.maybeOf`,
```dart
// It returns Provider?
final bloc = BlocProvider.maybeOf<SomeBloc>(context).add(SomeEvent());
if(bloc != null) {
      bloc.add(someEvent());
} else {
      // handle something
}
```

**Additional context**

`Navigator.of`

https://github.com/flutter/flutter/blob/1233fc979be591894b62343f43acc45d53e9b1a3/packages/flutter/lib/src/widgets/navigator.dart#L2590-L2593

`Navigator.maybeOf`

https://github.com/flutter/flutter/blob/1233fc979be591894b62343f43acc45d53e9b1a3/packages/flutter/lib/src/widgets/navigator.dart#L2640-L2643

**Comment by felangel** [comment] 2022-12-19 03:36
Hi @SuhwanCha 👋
Thanks for opening an issue!

This is a duplicate of https://github.com/felangel/bloc/issues/3661.

**Closed** 2022-12-27 00:57 UTC
Labels: duplicate
