### ISSUE TITLE
question: Error when add new event inside list

### ISSUE THREAD

**Issue by gilangsatria09** [felangel/bloc#3164] opened 2022-01-23 13:42 UTC
Hello, sir. how can i add new event inside listview.builder? because i tried to implement like this but the error appeared, thanks!

![image](https://user-images.githubusercontent.com/52986068/150681296-27eff307-2141-4107-b0a0-915466e36e61.png)
![image](https://user-images.githubusercontent.com/52986068/150681337-813abec2-cadd-4d5b-9dd8-96ca6b1b98cd.png)
![image](https://user-images.githubusercontent.com/52986068/150681243-c59bacdc-9872-4e54-b985-3408981766f7.png)
![image](https://user-images.githubusercontent.com/52986068/150681260-399b5851-d1aa-4f3b-806e-3a5aeaa4e8f4.png)
![image](https://user-images.githubusercontent.com/52986068/150681271-a3b9215e-5082-4d3f-9217-7500dba2e886.png)
![image](https://user-images.githubusercontent.com/52986068/150681305-2b5e84a8-a75a-4970-909a-f971baed801f.png)

**Comment by alestiago** [comment] 2022-01-24 10:38
Hi @gilangsatria09 ! Thank you for submitting this issue.

It is somewhat hard to resolve with the provided images. Could you provide an example of minimal code that reproduces the issue?

However, from the error message, it seems that you might have called `.close` on your bloc. The source code states that `close` "closes the event and state Streams. This method should be called when a [Bloc] is no longer needed. Once [close] is called, events that are [add]ed will not be processed."

**Comment by felangel** [comment] 2022-02-01 01:34
Closing for now since there isn't a minimal reproduction sample and it doesn't appear there are any actionable next steps. Feel free to provide a link to a reproduction sample and I'm happy to continue the conversation 👍

**Closed by felangel** 2022-02-01 01:34 UTC
Labels: question, waiting for response
