### ISSUE TITLE
fix: Flutter Weather Tutorial won't run

### ISSUE THREAD

**Issue by holdenhinkle** [felangel/bloc#3306] opened 2022-03-31 20:19 UTC
**Description**
Just a quick note to say that there's a bug with the [Flutter Weather Tutorial](https://bloclibrary.dev/#/flutterweathertutorial):

```
Launching lib[/main.dart]() on macOS in debug mode...
package:flutter_weather/main.dart:1
Connecting to VM Service at ws://127.0.0.1:50482[/7QdIE0A98A8]()=[/ws]()
[ERROR:flutter[/lib/ui/ui_dart_state.cc]()(198)] Unhandled Exception: Binding does not extend BindingBase
An instance of ServicesBinding was created but the BindingBase constructor was not called.
This could happen because the binding was implemented using "implements" rather than "extends" or "with". Concrete binding classes must extend or mix in BindingBase.
#0      BindingBase.checkInstance.<anonymous closure>
package:flutter/…/foundation/binding.dart:353
#1      BindingBase.checkInstance
package:flutter/…/foundation/binding.dart:363
#2      ServicesBinding.instance
package:flutter/…/services/binding.dart:48
#3      MethodChannel.setMethodCallHandler
package:flutter/…/services/platform_channel.dart:387
#4      RestorationManager.initChannels
package:flutter/…/services/restoration.dart:169
#5      new RestorationManager
package:flutter/…/services/restoration.dart:157
#6      ServicesBinding.createRestorationManager
package:flutter/…/services/binding.dart:296
#7      ServicesBinding.initInstances
package:flutter/…/services/binding.dart:34
#8      new _StandaloneBindingBase
package:flutter_services_binding[/src/flutter_services_binding.dart]():31
#9      new _FlutterServicesBinding&_StandaloneBindingBase&SchedulerBinding (package:flutter_services_binding[/src/flutter_services_binding.dart]())
package:flutter_services_binding[/src/flutter_services_binding.dart]():1
#10     new _FlutterServicesBinding&_StandaloneBindingBase&SchedulerBinding&ServicesBinding (package:flutter_services_binding/src/flutter_services_binding.dart)
package:flutter_services_binding/src/flutter_services_binding.dart:1
#11     new FlutterServicesBinding._ (package:flutter_services_binding/src/flutter_services_binding.dart)
package:flutter_services_binding/src/flutter_services_binding.dart:1
#12     new FlutterServicesBinding.ensureInitialized
package:flutter_services_binding/src/flutter_services_binding.dart:22
#13     main
package:flutter_weather/main.dart:11
#14     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui[/hooks.dart:130:25]())
#15     _rootRun (dart:async[/zone.dart:1426:13]())
#16     _CustomZone.run (dart:async[/zone.dart:1328:19]())
#17     _runZoned (dart:async[/zone.dart:1861:10]())
#18     runZonedGuarded (dart:async[/zone.dart:1849:12]())
#19     _runMainZoned.<anonymous closure> (dart:ui[/hooks.dart:126:5]())
#20     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch[/isolate_patch.dart:297:19]())
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch[/isolate_patch.dart:192:12]())
Application finished.
Exited
```

Thanks

**Comment by felangel** [comment] 2022-03-31 21:06
Thanks this is a duplicate of #3230 👍

**Closed by felangel** 2022-03-31 21:06 UTC
Labels: bug
