### ISSUE TITLE
FelixAngelov.bloc

### ISSUE THREAD

**Issue by Bro9090** [felangel/bloc#3419] opened 2022-07-04 02:45 UTC
Issue Type: <b>Bug</b>

The cubit name must not be empty

Extension version: 6.6.1
VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.90GB (0.36GB free)|
|Process Argv|--crash-reporter-id cbc4243e-ec87-412e-80a5-aaa605a583be|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30520716
vsclangdc:30486549

```

</details>

**Comment by felangel** [comment] 2022-07-08 04:44
Hi @Bro9090 👋
Thanks for opening an issue!

Can you please provide more information regarding what the exact issue is and how to reproduce it? Thanks!

**Comment by felangel** [comment] 2022-07-11 04:19
Closing for now since there isn’t enough information to take any next steps.

**Closed by felangel** 2022-07-11 04:19 UTC
Labels: question, waiting for response
