### ISSUE TITLE
BlocBuilder not update if i navigate to new page and goes back to previous page

### ISSUE THREAD

**Issue by mohammednabil95** [felangel/bloc#842] opened 2020-02-03 17:21 UTC
I am building an app which has a notification icon, so far what i have done is displaying the notification icon and when i click the icon the icon should change to "Icons.notifications_active". But it only change to notification icon active if i navigate to new screen and goes back to previous screen and if i add setstate() inside onpressed function then it change to active notification icon. Below is the code

>     HomePage.dart
```
class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();}
class _HomePageState extends State<HomePage> {
NotificationBloc notificationBloc;
  @override
  void initState() {
    super.initState();
    notificationBloc = BlocProvider.of<NotificationBloc>(context);
notificationBloc.add(FetchNotificationEvent());
}
  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
Column(
                                  children: <Widget>[
                                    BlocListener<NotificationBloc,
                                        NotificationState>(
                                      listener: (context, state) {},
                                      child: BlocBuilder<NotificationBloc,
                                          NotificationState>(
                                        builder: (context, state) {
                                          if (state is InitialNotificationState) {
                                            return buildLoading();
                                          } else if (state is NotificationLoadedState) {
                                            return NotificationIconBuild(state.notification);
                                          } else if (state is NotificationErrorState) {
                                            return buildErrorUi(state.message1);}},),),],)]
  Widget NotificationIconBuild(NotificationModel notification) {
    return Column(
      children: <Widget>[
        notificationIcon("Apple", notification),],);}
  Widget notificationIcon(String notification, NotificationModel notificationModel){
        if(notificationModel.Apple== false)
          return IconButton(
            icon: Icon(Icons.notifications),
            onPressed: (){
              notificationModel.Apple= true;
                notificationBloc.add(SelectNotificationEvent(notificationModel));},);
        else return IconButton(
          icon: Icon(Icons.notifications_active),
          onPressed: (){
            notificationModel.Apple= false;
              notificationBloc.add(SelectNotificationEvent(notificationModel));},);
```

>     Notification_state.dart
```
class NotificationLoadedState extends NotificationState {
  NotificationModel notification;
  NotificationLoadedState({@required this.notification});
  @override
  List<Object> get props => [notification];
}
```

>     NotificationEvent.dart
```
class SelectNotificationEvent extends NotificationEvent {
  NotificationModel notificationModel;
  SelectNotificationEvent(this.notificationModle);
  @override
  List<Object> get props => null;
}
```

>     NotificationBloc.dart
```
class NotificationBloc extends Bloc<NotificationEvent, NotificationState> {
  NotificationsRepositoryImp notificationsRepository;
  NotificationBloc({@required this.notificationsRepository});
  @override
  NotificationState get initialState => InitialNotificationState();
  @override
  Stream<NotificationState> mapEventToState(
    NotificationEvent event,
  ) async* {if(event is SelectNotificationEvent){
      await notificationsRepository.saveNotifications(event.notificationModle);}}}
```

>     NotificationModel.dart
```
class NotificationModel{
  bool Apple;
  NotificationModel(this.Apple);}
```

>     NotificationsRepository.dart
```
class NotificationsRepositoryImp{
  @override
  Future<void> saveNotifications(NotificationModel notification) async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    await prefs.setBool('n_Apple', notification.Apple); }}
```

**Comment by felangel** [comment] 2020-02-03 19:37
Hi @mohammednabil95 👋 
Thanks for opening an issue!

Can you please share a link to a sample app which illustrates the issue you're having? Also, it looks like #843 is related to this so I'm going to close it as a duplicate for now and we can address these rebuild issues in a single ticket.

**Comment by Thioby** [comment] 2020-02-04 10:00
It seems like you are pushing multiple times the same state. 
You can use `BlockListener` and override property `condition` or use BlocConsumer and override `listenWhen`.

But it seems that this solution also not work because in `bloc` itself there is small piece of code that ignore those 2 properties. 

Line 173 bloc.dart:
` if (state == nextState || _stateController.isClosed) return;`

**Comment by felangel** [comment] 2020-02-04 15:42
@Thioby yup you can use condition to control how often listener/builder is called and blocs will ignore duplicate states. If a Bloc yields State nextState where state == nextState, then no transition will occur and no change will be made to the Stream<State>. Check out the [docs](https://bloclibrary.dev/#/coreconcepts) for more details.

Closing for now as there isn't enough information to identify the root cause(s). Feel free to provide a link to a sample app and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-02-04 15:42 UTC
Labels: question, waiting for response
