### ISSUE TITLE
blocTest expect is failing but verify shows the correct state.

### ISSUE THREAD

**Issue by vadrian89** [felangel/bloc#3414] opened 2022-06-29 13:10 UTC
Hello,

Sorry for asking the question here but I could not find anything related to bloc_test package and my issue.
I have tried the example from bloc_test and it works on my machine but my own code doesn't work.

From the documentation:
`expect is an optional Function that returns a Matcher which the bloc under test is expected to emit after act is executed.`

What I understand is that: it should work as the normal expect and return the emitted states of the block. Have I understood it wrongly?

My testing code

```
blocTest<AuthenticationCubit, AuthenticationState>(
      "Test the initial state",
      build: () => AuthenticationCubit(fcmBloc, authRepo: repository),
      expect: () => [
        const AuthenticationState.initial(),
        const AuthenticationState.unauthenticated(),
      ],
      verify: (bloc) {
        print("bloc.state ${bloc.state}");
      },
    );
```

When instancing the object I make a call to the following method:
```
void checkSession() {
    if (SharedPrefs().userExists) {
      emit(AuthenticationState.authenticated(SharedPrefs().user));
    } else {
      emit(const AuthenticationState.unauthenticated());
    }
  }
```

Basically the bloc should first have const AuthenticationState.initial() and then const AuthenticationState.unauthenticated() because SharedPrefs().userExists returns false.

Inside verify callback bloc.state returns AuthenticationState.unauthenticated() which should be the case.

Calling checkSession()  inside "act" callback it shows on print, but still nothing in expect.

This is what I get:
```
00:00 +0 -1: AuthenticationCubit test: Test the initial state [E]
  Expected: [
              _$_Initial:AuthenticationState.initial(),
              _$_Unauthenticated:AuthenticationState.unauthenticated(email: null)
            ]
    Actual: []
     Which: at location [0] is [] which shorter than expected
  
  ==== diff ========================================
  
  [[-AuthenticationState.initial(), AuthenticationState.unauthenticated(email: null)-]]
  
  ==== end diff ====================================
  
  package:bloc_test/src/bloc_test.dart 219:15  testBloc.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                   _asyncThenWrapperHelper
  package:bloc_test/src/bloc_test.dart         testBloc.<fn>.<fn>
  dart:async                                   runZonedGuarded
  package:bloc_test/src/bloc_test.dart 192:13  testBloc.<fn>
  package:bloc_test/src/bloc_test.dart 191:5   testBloc.<fn>
  dart:async                                   runZoned
  package:bloc/src/bloc_overrides.dart 46:26   BlocOverrides.runZoned
  package:bloc_test/src/bloc_test.dart 190:23  testBloc
  package:bloc_test/src/bloc_test.dart 156:13  blocTest.<fn>
  package:bloc_test/src/bloc_test.dart 155:5   blocTest.<fn>
```

It also work if I try the standard way:
```
  final bloc = AuthenticationCubit(fcmBloc, authRepo: repository);
  expect(bloc.state, const AuthenticationState.unauthenticated());
```

**Comment by felangel** [comment] 2022-07-21 13:48
Hi @vadrian89 👋 
Thanks for opening an issue!

Can you please share a link to a minimal reproduction sample? Thanks! 🙏

**Comment by felangel** [comment] 2022-08-05 03:27
Closing for now since there isn't enough information to help. Feel free to provide a link to a minimal reproduction sample and I'm happy to take a look 👍

**Closed by felangel** 2022-08-05 03:27 UTC
Labels: question, waiting for response, pkg:bloc_test
