### ISSUE TITLE
Load more not working because "Transition" not running again

### ISSUE THREAD

**Issue by rrifafauzikomara** [felangel/bloc#978] opened 2020-03-22 12:03 UTC
Hall @felangel 

I try this library with implemented with load more like u share on readme with the title is `Infinite List`. I try that in my project in [here](https://github.com/rrifafauzikomara/MovieCatalogue) and implemented `load more`. After I try, the `load more` not working and then I check the log, that `Transition` is not running again when I scroll from the bottom from load more. This is the report of my logcat.

```
I/flutter (11440): LoadNowPlaying
I/flutter (11440): Transition { currentState: InitialMoviesState, event: LoadNowPlaying, nextState: MoviesLoading }
I/flutter (11440): Transition { currentState: MoviesLoading, event: LoadNowPlaying, nextState: MoviesLoaded }
I/flutter (11440): LoadMoreMovies
```

**Comment by felangel** [comment] 2020-03-22 19:06
Hi @rrifafauzikomara 👋 
Thanks for opening an issue!

I believe this is a duplicate of https://github.com/felangel/bloc/issues/778. Let me know if that helps 👍

**Closed by felangel** 2020-03-22 19:06 UTC

**Comment by rrifafauzikomara** [comment] 2020-03-26 11:41
Hallo @felangel sorry for late response.

I still don't understand where I mush change my code to fix this issue in my code. Can you help me?

**Comment by felangel** [comment] 2020-03-26 13:38
Can you share a link to a sample app which illustrates the problem you’re facing?

**Comment by rrifafauzikomara** [comment] 2020-03-27 10:17
Hi @felangel 

This is the bloc that I created: https://github.com/rrifafauzikomara/MovieCatalogue/blob/master/lib/bloc/movies/movies_bloc.dart

And this is the implemented the BLoC in the UI with `load more` : https://github.com/rrifafauzikomara/MovieCatalogue/blob/master/lib/ui/now_playing/now_playing_screen.dart
