### ISSUE TITLE
Bloc don't emit the same state with updated props

### ISSUE THREAD

**Issue by mohamedmahmoud9** [felangel/bloc#2157] opened 2021-02-16 16:06 UTC
I have created `AuthBloc` with State `Authorized` 
```
class Authorized extends AuthState {
  final User user;

  Authorized({@required this.user});
  @override
  List<Object> get props => [user];
}
```
I need to Update Authorized state with an new user update
I created UpdateUser event that have updated user 
```
class UpdateCompleted extends AuthEvent {
  final User user;

  UpdateCompleted(this.user);
  @override
  List<Object> get props => [user];
}
```
This from Function `mapEventToState`
```
else if (event is UpdateCompleted) {
      
      final user = event.user;
      yield Authorized(user: user);
    }
```
This is `User` model
```
class User extends Equatable {
  final int status;
  final Info info;
  final List<Courses> courses;
  final List<Experience> experience;
  final List<Edu> edu;
  final List<Skills> skills;
  final List<Buttons> buttons;
  final List<SubButtons> subButtons;
  final List<FromRecommendation> fromRecommendation;
  final List<ToRecommendation> toRecommendation;
  User(
      {@required this.status,
      @required this.info,
      @required this.courses,
      @required this.experience,
      @required this.edu,
      @required this.skills,
      @required this.buttons,
      @required this.subButtons,
      @required this.fromRecommendation,
      @required this.toRecommendation});

  @override
  List<Object> get props => [
        status,
        info,
        List.from(courses),
        List.from(experience),
        List.from(edu),
        List.from(skills),
        List.from(buttons),
        List.from(subButtons),
        List.from(fromRecommendation),
        List.from(toRecommendation)
      ];
}
```
The Problem is `Bloc` do not update the State and get the previous state 

i expect that is because the previous state is `Authorized`

**Comment by mohamedmahmoud9** [comment] 2021-02-16 16:45
i debug the code then i see that 
State Updated in BlocAuth But did not update in BlocBuilder
`main`
```
MultiBlocProvider(
        providers: [
          BlocProvider(
            create: (context) => di.sl<AuthBloc>(),
          ),
          BlocProvider(
            create: (context) => ThemeBloc(),
          ),
        ],
```
BlocBuilder Widget in another screen 
```
@override
  Widget build(BuildContext context) {
    return BlocBuilder<AuthBloc, AuthState>(
      builder: (context, state) {
        
        if (state is Authorized) {
       // I add skill but length still 
        print(state.user.skills.length);
          return Scaffold(
              appBar: _buildAppBar(context,state.user), body: _buildBody(context,state.user));
        }
        return Container();
      },
    );
```

**Comment by jurej1** [comment] 2021-02-16 20:48
Your current Widget Looks like this:
```
@override
  Widget build(BuildContext context) {
    return BlocBuilder<AuthBloc, AuthState>(
      builder: (context, state) {
        
        if (state is Authorized) {
       // I add skill but length still 
        print(state.user.skills.length);
          return Scaffold(
              appBar: _buildAppBar(context,state.user), body: _buildBody(context,state.user));
        }
        return Container();
      },
    );

```
Since you only have one state you can do it like this

```
@override
  Widget build(BuildContext context) {
    return BlocBuilder<AuthBloc, AuthState>(
      builder: (context, state) {
          return Scaffold(
              appBar: _buildAppBar(context, state.user), 
              body: _buildBody(context, state.user)
             );
        },
    );

```
`BlocBuilder` also has another useful method called `buildWhen`. In your usecase it may be usefull to do:
`buildWhen: (previousState, currentState) => previousState.user != currentState.user;`

SInce you also have only one State there is no need to have an `abstract class Auth State`. Simply have a bloc like this: `class AuthBloc extends Bloc<AuthEvent, Authorized>`

**Comment by mohamedmahmoud9** [comment] 2021-02-17 03:31
Dear, thanks for your reply I tried this But problem still.
I have many States in bloc 
I tried this 
```
abstract class AuthState extends Equatable {
  final User user;
  const AuthState(this.user);
}

class IntroductionState extends AuthState {
  IntroductionState(User user) : super(user);

  @override
  List<Object> get props => [];
}

class SignupState extends AuthState {
  SignupState(User user) : super(user);

  @override
  List<Object> get props => [];
}

class LoginState extends AuthState {
  LoginState(User user) : super(user);

  @override
  List<Object> get props => [];
}

class Unauthorized extends AuthState {
  Unauthorized(User user) : super(user);

  @override
  List<Object> get props => [];
}

class Authorized extends AuthState {
  final User user;

  Authorized({@required this.user}) : super(user);
  @override
  List<Object> get props => [user];
}


class AuthorizedIncompletedUser extends AuthState {
  final User user;

  AuthorizedIncompletedUser({@required this.user}) : super(user);
  @override
  List<Object> get props => [user];
}

class LoginLoading extends AuthState {
  LoginLoading(User user) : super(user);

  @override
  List<Object> get props => [];
}

class Error extends AuthState {
  final String message;

  Error({@required this.message}) : super(null);
  @override
  List<Object> get props => [message];
}

class LoginError extends AuthState {
  final String message;

  LoginError({@required this.message}) : super(null);
  @override
  List<Object> get props => [message];
}

class InitialState extends AuthState {
  InitialState(User user) : super(user);

  @override
  List<Object> get props => [];
}

class SignupError extends AuthState {
  final String message;

  SignupError({@required this.message}) : super(null);
  @override
  List<Object> get props => [message];
}

class SignupLoading extends AuthState {
  SignupLoading(User user) : super(user);

  @override
  List<Object> get props => [];
}
```
UI 
```
 @override
  Widget build(BuildContext context) {
    return BlocBuilder<AuthBloc, AuthState>(
        buildWhen: (previousState, currentState) =>
            previousState.user != currentState.user,
        builder: (context, state) {
          return Scaffold(
              appBar: _buildAppBar(context, state.user),
              body: _buildBody(context, state.user));
        });
```
This Method to pass Event to AuthBloc to Update user
```
 BlocConsumer<InsertBloc, InsertState>(
                listener: (context, state) {
                  if (state is InsertSkillDone) {
                    BlocProvider.of<AuthBloc>(
                      context,
                    ).add(UpdateCompleted(state.updatedUser));
                    Toast.show("Your Skill added successfully !", context,
                        textColor: Colors.white, backgroundColor: Colors.green);
                    // Navigator.of(context).pushReplacementNamed('/');
                  } else if (state is InsertError) {
                    Toast.show(state.message, context,
                        textColor: Colors.white,
                        backgroundColor: Theme.of(context).errorColor);
                  }
                }
```
This in to emit change `mapEventToState`
```
else if (event is UpdateCompleted) {
      final user = event.user;
      yield Authorized(user: user);
    }
```

**Comment by felangel** [comment] 2021-02-19 22:02
Hi @mohamedmahmoud9 👋 
Thanks for opening an issue!

I believe the issue you're facing is covered in the [FAQs](https://bloclibrary.dev/#/faqs?id=state-not-updating). Please make sure that if you're using `Equatable`, all properties on your state (for example, `User`) also extend `Equatable`. Also make sure that you are always yielding a **new** state instance instead of modifying an existing state within your bloc.

Hope that helps!

Closing for now but if you're still stuck feel free to comment with a complete reproduction sample and I'm happy to take a closer look 👍

**Closed by felangel** 2021-02-19 22:02 UTC
Labels: question
