### ISSUE TITLE
BlocBuilder condition is not firing in the very first time

### ISSUE THREAD

**Issue by welderknaf** [felangel/bloc#746] opened 2019-12-27 12:45 UTC
Condition (BlocBuilderCondition) is not firing in the very first time. So, it's not filtering states properly.

![image](https://user-images.githubusercontent.com/10700471/71517543-4c127800-288d-11ea-9ca2-0de1322a16e8.png)

[blocbuilderconditiontest.zip](https://github.com/felangel/bloc/files/4005279/blocbuilderconditiontest.zip)

**Comment by felangel** [comment] 2019-12-27 19:03
Hi @welderknaf 👋 
Thanks for opening an issue!

`BlocBuilder's` condition is called once for each state change. The initial state is not considered a state change so condition will not be called. As far as I can tell, this is working as designed. I'm more than happy to help if you have a specific use-case.

I'm not sure I understand the goal of the example you shared; you aren't adding any events to the bloc and also have nested BlocBuilders for the exact same bloc which is unnecessary.

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Closed by felangel** 2019-12-27 19:03 UTC

**Comment by welderknaf** [comment] 2019-12-30 21:33
Thanks for your answer @felangel 

How can i filter a state in condition builder to prevent building state if it is an initial state?

If you look at my example screenshot, i'm filtering and handling only Event2. How can be possible another state has been caught but Event2?

Thanks in advance,

**Comment by felangel** [comment] 2019-12-30 21:35
@welderknaf you can't prevent the build of initialState because a widget must always be rendered. Hope that helps 👍

**Comment by welderknaf** [comment] 2019-12-30 21:41
Ok. Thank you @felangel
