### ISSUE TITLE
Update not immediate state in Example Counter - BloC Flutter

### ISSUE THREAD

**Issue by souzaleandror** [felangel/bloc#1753] opened 2020-09-21 22:56 UTC
My pubspec.yml:
```
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  equatable: ^1.2.5
```

I created my CounterBloc:
```
class CounterBloc extends Bloc<CounterEvent, int> {
  @override
  int get initialState => 0;

  @override
  Stream<int> mapEventToState(event) async* {
    if (event.status == EventStatus.INCREMENT) {
      yield state + event.value;
    } else if (event.status == EventStatus.DECREMENT) {
      yield state - event.value;
    }
  }
}
```

```
enum EventStatus { INCREMENT, DECREMENT }

class CounterEvent {
  final int value;
  final EventStatus status;

  const CounterEvent({this.value, this.status});
}
```

```
void main() => runApp(CounterApp());

class CounterApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'BLoC Demo',
      home: BlocProvider<CounterBloc>(
        create: (context) => CounterBloc(),
        lazy: false,
        child: TestBlocWidget(),
      ),
    );
  }
}
```

```
class TestBlocWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final counterBloc = BlocProvider.of<CounterBloc>(context);
    return Scaffold(
      body: Center(
        child: BlocBuilder<CounterBloc, int>(
          builder: (ctx, state) {
            return Text(
              'count: $state',
              style: TextStyle(fontSize: 28),
            );
          },
        ),
      ),
      floatingActionButton: Align(
        alignment: Alignment.bottomRight,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            FloatingActionButton(
              onPressed: () async {
                print("test 0 = " + counterBloc.state.toString());
                counterBloc.add(CounterEvent(value: 1, status: EventStatus.INCREMENT));
                print("test 1 = " + counterBloc.state.toString());
              },
              child: Icon(Icons.add_circle),
            ),
            FloatingActionButton(
              onPressed: () {
                print("test 2 = " + counterBloc.state.toString());
                counterBloc
                    .add(CounterEvent(value: 1, status: EventStatus.DECREMENT));
                print("test 3 = " + counterBloc.state.toString());
              },
              child: Icon(Icons.remove_circle),
            ),
          ],
        ),
      ),
    );
  }
}
````

Then my question is:
Inside FloatingActionButton, I increment value to my state;
But I print before increment and after increment and the state is the same value;

**Comment by felangel** [comment] 2020-09-21 23:11
Hi @souzaleandror 👋 
Thanks for opening an issue!

That's because `add` is not synchronous. When you call `add` the event is added to the bloc and is processed asynchronously so what you're doing is expected behavior. If you really want to wait for the update you could do something like:

```dart
onPressed: () async {
  print('test 2 = ${counterBloc.state}');
  counterBloc.add(...);
  await counterBloc.first;
  print('test 3 = ${counterBloc.state}');
}
```

But I don't recommend that approach and instead recommend using `BlocBuilder` and `BlocListener` to react to state changes asynchronously. Hope that helps!

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-09-21 23:11 UTC
Labels: question
