### ISSUE TITLE
[Help] SubBloC doesn't change when reordering list - solved -> good/intended solution?!

### ISSUE THREAD

**Issue by bridystone** [felangel/bloc#2629] opened 2021-07-29 10:33 UTC
Hi - I seem to have a wrong thinking when using a listview with BloC.

I have a listview populated by a BloC (dataBloc) and this list is ordered by a ViewBloc.
When I tap on the item, a SubDataBloc is updated and the result displayed in the trailing of the list tile

dataBloc/viewBloc:
- ListTileA - SubdataBlocA 
- ListTileB - SubDataBlocB
- ListTileC - SubDataBlocC

When I reorder the list - only the ListTiles are reordered, but not the SubdataBloc results
video:
https://gitlab.com/bridystone/bloc_test/-/blob/main/BloC-ListTile.mov

the whole example is here:
https://gitlab.com/bridystone/bloc_test

any idea, on how to make this happen?

ListView.builder
``` dart
      body: BlocBuilder<ViewBloc, ViewState>(
        builder: (context, state) {
          if (state is ViewInitial) {
            return CircularProgressIndicator();
          } else if (state is ViewReadyForUI) {
            return ListView.builder(
              itemCount: state.sortedData.length,
              itemBuilder: (context, index) => BlocProvider(
                create: (context) => SubDataBloc(),
                child: MyTile(
                  dataItem: state.sortedData[index],
                ),
              ),
            );
          }
          return Text('should not happen');
        },
      ),
```
ListTile:
```dart
 Widget build(BuildContext context) {
    //BlocProvider.of<SubDataBloc>(context).add(SubDataRequest(dataItem.id));
    return BlocBuilder<SubDataBloc, SubDataState>(
      builder: (context, state) {
        return ListTile(
          leading: Text(dataItem.id.toString()),
          title: Text(dataItem.text),
          trailing: (state is SubDataReceived)
              ? Text('items: ${state.subdata.length}')
              : (state is SubDataUpdating)
                  ? Text('${state.percent}')
                  : Text('initial'),
          onTap: () => BlocProvider.of<SubDataBloc>(context)
              .add(SubDataRequest(dataItem.id)),
        );
      },
    );
  }
```

**Comment by Gene-Dana** [comment] 2021-07-29 15:45
Hey there 👋🏼 I so the problem is that you when you filter, only the left side is filtering and not the right ! 

There are a few things here that stick out. First off, Blocs ideally should be named by feature - not by data - which may be the root of the issue here.

Deeper than that, the approach that I follow is I display a list of objects. Meaning, instead of a list of independent blocs for each piece of data, I have a list of objects which is held in the bloc state.

For an example of what I'm talking about, check out[ this ](https://github.com/Team-Crushing-It/wine_game_admin)

To see it live, see [here](https://firestore-bloc-crud-demo.netlify.app)

Here, you see a list of objects that are being displayed in a list view, and although I have multiples pieces of data in that state, the listview updates the one piece accordingly.

![2021-07-29 11 40 17](https://user-images.githubusercontent.com/45580241/127522551-45562a59-5c97-4d25-9fbf-60d87647a2ea.gif)

What I have is a [listview building a list of question objects ](https://github.com/Team-Crushing-It/wine_game_admin/blob/f8de5d239f8b0543fc45294b3eba407c6e2fa1db/lib/home/_features/questions/widgets/question_list.dart#L20-L47) which are supplied to by the[ state of the Questions Cubit](https://github.com/Team-Crushing-It/wine_game_admin/blob/f8de5d239f8b0543fc45294b3eba407c6e2fa1db/lib/home/_features/questions/view/questions_view.dart#L17-L18)

**Comment by bridystone** [comment] 2021-07-29 19:47
Hi @Gene-Dana,

Thanks for the fast reply!

I have the feeling, that you misunderstood my problem. The whole update process is working fine.
However, I have a long running update and I would like to inform the user about the process. Therefore percentage should be presented.
Have a look at my "production" example:
https://gitlab.com/bridystone/bloc_test/-/blob/main/BloC-RockCarrot.mov
Maybe this will make it more clear.

With the example code I just wanted to focus on the problematic part.
I actually don't understand, why the ListTile is only updating the title, but not the part that is handled by the subdata-BloC.

I have the feeling that I made a mistake - but I don't understand it... :(

Maybe you (or someone else) have an idea what's wrong here?

**Comment by bridystone** [comment] 2021-07-30 09:37
Hi @Gene-Dana ,

your comments now brought me to a solution for this problem:
I've transferred the SubdataBloc to the dataModel of the MainBloc.
So for each data, a corresponding SubBloc is stored.

I've now added the subDataBloc to the DataModel

```dart
class BlocModel {
  final Model model;
  SubDataBloc subDataBloc;

  BlocModel(this.model, this.subDataBloc);
}
```
and added the BloC during generation to the Model
```dart
    var modelData = List<BlocModel>.generate(
        event.requestId,
        (index) => BlocModel(
            Model(Random().nextInt(event.requestId), "BLABLABLA $index"),
            SubDataBloc())); // <-- added here
```
then I could just add the subbloc to the BlocBuilder with the bloc attribute
``` dart
    return BlocBuilder<SubDataBloc, SubDataState>(
      bloc: dataItem.subDataBloc,      //<-- using the data model-BloC
      builder: (context, state) {
        return ListTile(
            leading: Text(dataItem.model.id.toString()),
            title: Text(dataItem.model.text),
            trailing: (state is SubDataReceived)
                ? Text('items: ${state.subdata.length}')
                : (state is SubDataUpdating)
                    ? Text('${state.percent}')
                    : Text('initial'),
            onTap: () =>
                dataItem.subDataBloc.add(SubDataRequest(dataItem.model.id)));
      },
    );
```

And now it is working as [intended](https://gitlab.com/bridystone/bloc_test/-/blob/3913a76d04565c0b2a96bc382e33ece0a69d985e/BloC-working.mov).

Thanks

**Comment by Gene-Dana** [comment] 2021-07-30 12:48
Well I'm glad my comments helped, even if I'm still working to understand your approach 😄 I'm going to close this now and feel free to leave any more comments!

**Closed** 2021-07-30 12:50 UTC
Labels: question

**Comment by bridystone** [comment] 2021-07-30 14:57
I'm also not 100% sure if this is an intended way to solve this.
Fact is that I have 5 different screen with dependent Lists. (Country/Area/Subarea/Rocks/Routes)

Retrieving the underlaying lists from the web takes some time and I want to show progress (percentage), while the user is still able to sort and filter on the current list.

So I have 5 different DataBlocs + FilteredBlocs [like in the Todos example] .

So while the country-Bloc data is shown (with the help of FilteredBloc) the AreasBloc can be triggered to fetch the data.
When you change the Areas Bloc is the Main Bloc with SubareasBloc to get triggered
etc.

for the Progress I just emit UpdateInProgress States for the Sub-Data-Bloc - that is then shown in the trailing column.

If you see a different approach here, I'd be glad to try it out!
I just started developing in Flutter and this is my first time using BloC

**Comment by Gene-Dana** [comment] 2021-08-02 13:22
The todos example is in desperate need of an update and that's what I'm working on right now ! When I post a refactored example, I can share with you how the approach likens to a feature-driven delivery which directly affects how we think and implement blocs.
