### ISSUE TITLE
how to read bloc state and send events from within CustomPainter method?  

### ISSUE THREAD

**Issue by callagga** [felangel/bloc#2093] opened 2021-01-18 04:05 UTC
Is there a way to use flutter_bloc within a customer painter class (extending CustomPainter) and the paint(Canvas _canvas, Size size) method?  For example you may have drawing a specific Circle or Rect on the canvas within the paint method only depending to some state from a bloc.  Also when using the Touchable package you may want to send an 'event' to the bloc after the user clicked on a particular item on the canvas.    i.e. having this support to avoid having to pass state and callback functions from the parent Widget file to the CustomPainter class (i.e. could just do it within the CustomPainter class)

So questions are how to, within a customer painter class (extending CustomPainter) within paint method:
a) How to access some state from a block?   (programmatic equivalent of BlocBuilder?)
b) How to send an event back to a block from within a CustomPainter class.  (noting use of Touchable - https://pub.dev/packages/touchable)

**Comment by felangel** [comment] 2021-01-26 00:41
Hi @callagga 👋 
Thanks for opening an issue and sorry for the delayed response!

Are you able to share a link to a sample app which reproduces the problem you're facing? It would be great if you could share a link to a sample app with your attempt and I'm happy to take a look and open a pull request with suggestions 👍

**Comment by callagga** [comment] 2021-01-26 00:56
Hi @felangel  - perhaps code to look at is that in my separate question here (https://stackoverflow.com/questions/65856448/flutter-bloc-and-how-a-bloc-state-change-can-then-trigger-a-2nd-async-call-befor).  In this code I have to get state from Bloc in my flutter widget and then pass this to my custom CustomPainter class via passing cubit variables.  Was wondering if there is a better way, so I don't have to pass these items into the CustomPainter?

Copy/Paste of Code (which isn't fully working per my post on stackoverflow) but it shows what I'm trying to do:


Logging:

```
    Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
    lib/main.dart:1
    Xcode build done.                                           29.5s
    Connecting to VM Service at ws://127.0.0.1:49364/lyUIDblZgmY=/ws
    flutter: game_main.build ----------------------------
    flutter: trying to get room data for current room: room2
    flutter: About to load imagename:plane.png
    flutter: game_main.build ----------------------------
    flutter: trying to get room data for current room: room2
    flutter: About to load imagename:plane.png
    flutter: game_main.build ----------------------------
    flutter: trying to get room data for current room: room2
    flutter: About to load imagename:plane.png
    flutter: game_main.build ----------------------------
    ETC ETC
```

Code:
```

    import 'dart:async';
    import 'dart:typed_data';
    import 'dart:ui' as ui;
    import 'package:adventure/ui/widgets/game_painter.dart';
    import 'package:flutter/services.dart';
    import 'package:flutter_bloc/flutter_bloc.dart';
    import 'package:adventure/bloc/settings_cubit.dart';
    import 'package:adventure/game_design/room.dart';
    import 'package:flutter/material.dart';
    import 'package:touchable/touchable.dart';
    
    class GameMain extends StatefulWidget {
      GameMain({Key key}) : super(key: key);
      @override
      _GameMainState createState() => _GameMainState();
    }
    
    class _GameMainState extends State<GameMain> {
      final RoomsData roomsData = RoomsData.getPopulated();
      ui.Image _backgroundImage;
    
      Future<ui.Image> _loadImageAsync(imageString) async {
        ByteData bd = await rootBundle.load(imageString);
        final Uint8List bytes = Uint8List.view(bd.buffer);
        final ui.Codec codec = await ui.instantiateImageCodec(bytes);
        final ui.Image image = (await codec.getNextFrame()).image;
        return image;
      }
    
      Future<void> _updateBackgroundImageState(String imagename) async {
        print('About to load imagename:$imagename');
        final image = await _loadImageAsync('assets/images/$imagename');
        setState(() {
          _backgroundImage = image;
        });
      }
    
      @override
      Widget build(BuildContext context) {
        print('game_main.build ----------------------------');
    
        // Get Persistant Data Settings 
        SettingsCubit settingsCubit = context.watch<SettingsCubit>();
    
        // Get Room Configuration (for room we're now in)
        print('Trying to get room data for current room: ${settingsCubit.state.currentRoom}');
        Room roomData = roomsData.getRoom(settingsCubit.state.currentRoom);
    
        // Update Background Image
        _updateBackgroundImageState(roomData.backgroundImage);
        
        // Create and return Canvas
        return Container(
          child: BlocBuilder<SettingsCubit, SettingsState>(
            builder: (context, state) {
              return Stack(children: <Widget>[
    
                CanvasTouchDetector(
                  builder: (context) => CustomPaint(
                    painter: GamePainter(context, settingsCubit, roomData, _backgroundImage)
                  )
                ),
    
                FlatButton(
                  // For testing changes to background image
                  color: Colors.blue,
                  textColor: Colors.white,
                  onPressed: () {
                    var newRoomString = settingsCubit.state.currentRoom == 'room1' ? 'room2' : 'room1';
                    settingsCubit.setRoom(newRoomString);
                  },
                  child: Text(
                    "Flat Button",
                    style: TextStyle(fontSize: 20.0),
                  ),
                ),
    
              ]);
            }
          )
        );
    
      }
    }







```

**Comment by felangel** [comment] 2021-01-26 01:06
@callagga thanks for the additional details. Unfortunately, because `CustomPainter` does not have a `BuildContext` I don't think there's a way around injecting the necessary props via constructor.

**Comment by felangel** [comment] 2021-01-26 01:40
Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Closed by felangel** 2021-01-26 01:40 UTC
Labels: question, waiting for response
