### ISSUE TITLE
Wrong argument of MultiBlocProvider function

### ISSUE THREAD

**Issue by Allviss0211** [felangel/bloc#2479] opened 2021-05-26 07:59 UTC
i think that's syntax of function was wrong. That causes argument of function is different with document

![Screen Shot 2021-05-26 at 14 57 14](https://user-images.githubusercontent.com/48901671/119623725-aa50db00-be32-11eb-8b79-b049729d1a44.png)

and this is code of lib
![Screen Shot 2021-05-26 at 14 57 48](https://user-images.githubusercontent.com/48901671/119623810-bd63ab00-be32-11eb-9736-6fba1623b8ef.png)

i'm using  flutter_bloc: ^7.0.0

**Comment by robsonsilv4** [comment] 2021-05-26 13:10
Could you post the code or an example to reproduce error?

I tested now with same version and worked as expected:
![multibloc](https://user-images.githubusercontent.com/17673296/119664736-05baa300-be0a-11eb-9ee0-3a85ef109451.jpg)

_Sometimes Dart analyzer die, try to restart the editor._

**Comment by felangel** [comment] 2021-05-28 05:33
Closing for now since there is no reproduction sample. Feel free to provide additional information and I'm happy to continue the discussion 👍

**Closed by felangel** 2021-05-28 05:33 UTC
Labels: question, waiting for response
