### ISSUE TITLE
Android Studio Bloc Generator extension does not retain the upper case letter in the name of the bloc

### ISSUE THREAD

**Issue by schatekar** [felangel/bloc#300] opened 2019-05-15 12:23 UTC
For example, if the name of the bloc I enter in the Block Generator extension dialog is `MyFirst` then the bloc class is created with the name `MyfirstBloc`. Notice the `F` that changes from upper case to lower case.

**Comment by felangel** [comment] 2019-05-16 01:35
@schatekar this is working as intended. In order to get the result you're expecting you should input: "My First".

Hope that helps 👍

**Comment by felangel** [comment] 2019-05-17 01:14
#306 will address this in order to make it consistent with the VSCode Extension.
In order generate `MyFirstBloc` you should need to enter `My First`.

**Comment by schatekar** [comment] 2019-05-17 08:43
Is the consistency with VSCode extension really needed? 

IMHO - Developers using Android Studio and VSCode are most likely doing to be a mutually exclusive set for the most part. From their point of view, it does not make sense to have an undesirable feature in Android Studio extension because of limitations of VSCode.

However, if that is what you prefer, it needs to be documented somewhere.

**Comment by felangel** [comment] 2019-05-17 13:15
@schatekar I don’t think there are limitations in VSCode. Can you please elaborate on why it’s an undesirable feature? Thanks 👍

**Comment by schatekar** [comment] 2019-05-17 13:19
@felangel I did not mean to say it is an undesirable feature. What I was trying to say was - most people would be using either Android Studio or VSCode. I use Android Studio for App development. I am expecting this extension to behave in a certain way which I would like it to be consistent with how other extensions in the Android Ecosystem work. You, as the author of the extension, for the right reasons, may have decided to make it consistent with the same extension in another developer ecosystem i.e. VSCode. But I do not work in that ecosystem so that decision does not benefit me. If there is another extension in Android Studio that retains upper case letters without having to enter spaces then I would like this extension on Android Studio to behave like that irrespective of how it behaves on VSCode.

**Comment by felangel** [comment] 2019-05-17 13:21
Got it. Thanks for clarifying 👍

That makes sense and I’m happy to make the change later today. Thanks!

**Comment by felangel** [comment] 2019-05-19 23:54
Fixed in #306 and will be available in v1.4.

**Closed by felangel** 2019-05-19 23:54 UTC
Labels: bug, extension
