### ISSUE TITLE
Mock problem and state null in flutter bloc + widget testing

### ISSUE THREAD

**Issue by reinaldomoreira** [felangel/bloc#796] opened 2020-01-22 14:32 UTC
**Describe the bug**
Sorry but I'll try to report possibly two bugs in this post, I'll leave the code in zip and text in here.

1- When I'm using testWidgets, I create a mock of the bloc and do the properly when (or I think). Then, I pump the widget and the first emission of state is a null one. This makes me checks for null in my BlocBuilder.

2- When I use whenListen() from `bloc_test` lib, the first emission is always ignored.

**To Reproduce**
1. Run the code sent attached or in the end of this issue
2.1. To test issue 1: Just run the test, it will throw a exception by this code in the widget (lines 21 to 24)
`          if (state == null) {
//            return Container();
            throw Exception('state is null');
          }`
2.2. To test issue 2: Comment the line `            throw Exception('state is null');` and uncomment 
line 22 `//            return Container();`, and see that first emission is never seen on screen.
But, if you replace the test to emit two times, the second one is seen:
`  testWidgets('Test', (WidgetTester tester) async {
    final testBloc = TestBlocMock();
    when(testBloc.initialState).thenReturn(TestState('Initial mocked'));
    whenListen<TestEvent, TestState>(
      testBloc,
      Stream.fromIterable([
        TestState('First emission'),
        TestState('Second emission'),
      ]),
    );
    await tester.pumpWidget(
        BlocProvider<TestBloc>(create: (c) => testBloc, child: MyApp()));
    await tester.pump(Duration.zero);
//    expect(find.text('First emission'), findsOneWidget);
    expect(find.text('State: Second emission'), findsOneWidget);
  });`

**Logs **
`❯ flutter analyze
Analyzing fluttebloc...                                                 
No issues found! (ran in 2.2s)
`

Paste the output of running `flutter doctor -v` here.
`❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.10.14, on Mac OS X 10.14.6 18G103, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
[✓] Android Studio (version 3.6)
[✓] Android Studio
[✓] IntelliJ IDEA Community Edition (version 2019.3)
[✓] Connected device (1 available)

• No issues found!
`

**Additional context**

Code:
`main.dart

import 'package:bloc/bloc.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

void main() => runApp(BlocProvider<TestBloc>(
      create: (c) => TestBloc(),
      child: MyApp(),
    ));

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: BlocBuilder<TestBloc, TestState>(builder: (context, state) {
          if (state == null) {
//            return Container();
            throw Exception('state is null');
          }
          return Builder(builder: (c) {
            return Center(
              child: Text('State: ${state.text}'),
            );
          });
        }),
      ),
    );
  }
}

class TestBloc extends Bloc<TestEvent, TestState> {
  @override
  TestState get initialState => TestState('initialState');

  @override
  Stream<TestState> mapEventToState(TestEvent event) async* {
    yield TestState('yield from mapEvent');
  }
}

class TestEvent {}

class TestState {
  TestState(this.text);

  final String text;
}
`
`
widget_test.dart

import 'package:bloc_test/bloc_test.dart';
import 'package:fluttebloc/main.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/mockito.dart';

class TestBlocMock extends Mock implements TestBloc {}

void main() {
  testWidgets('Test', (WidgetTester tester) async {
    final testBloc = TestBlocMock();
    when(testBloc.initialState).thenReturn(TestState('Initial mocked'));
    whenListen<TestEvent, TestState>(
      testBloc,
      Stream.fromIterable([
        TestState('First emission'),
//        TestState('Second emission'),
      ]),
    );
    await tester.pumpWidget(
        BlocProvider<TestBloc>(create: (c) => testBloc, child: MyApp()));
    await tester.pump(Duration.zero);
    expect(find.text('First emission'), findsOneWidget);
//    expect(find.text('State: Second emission'), findsOneWidget);
  });
}

`
[fb.zip](https://github.com/felangel/bloc/files/4097757/fb.zip)

**Comment by reinaldomoreira** [comment] 2020-01-22 16:47
@felangel I don't know if I'm doing something wrong, but, is it possible to be bug?

**Comment by felangel** [comment] 2020-01-22 21:36
Hi @reinaldomoreira you should use `whenListen` to avoid the null state issue and with `whenListen` you need to make sure you're factoring in the initial state of the bloc as well so instead of doing something like:

```dart
whenListen(myBloc, Stream.fromIterable([MyState()]));
```

You should do:

```dart
whenListen(myBloc, Stream.fromIterable([MyInitialState(), MyState()]));
```

This is due to `BlocBuilder` and `BlocListener` skipping the first state since under the hood blocs use a BehaviorSubject.

Closing for now but feel free to comment with additional information if that doesn't help and it would be most helpful if you could provide a link to a github repo or gist which reproduces the problem you're having. Thanks!

**Closed by felangel** 2020-01-22 21:36 UTC

**Comment by reinaldomoreira** [comment] 2020-01-23 13:25
So you saying that it will always ignore first emit of `whenListen`, right?

What about the other issue the state being null in BlocBuilder in the first frame?
