### ISSUE TITLE
fix: Cubit updates state without using emit.  

### ISSUE THREAD

**Issue by Caldarie** [felangel/bloc#3541] opened 2022-09-15 14:32 UTC
**Description**
Hi, i am looking to implement dynamic forms with bloc. For example, when the user clicks on the plus button, a new text form will show up. For example:

<img width="738" alt="Screen Shot 2022-09-15 at 23 27 19" src="https://user-images.githubusercontent.com/42107315/190430117-18b11af1-842f-4fa5-b3f3-fcd018ca39ce.png">

However, I have encountered a few issues when implementing this feature. The code below updates the state despite commenting out the emit

``` dart
 void supportRequiredRemoved(int index) {
    log('Before state update');
    log(state.supportRequired?.value.toString() ?? '');

    final supports = state.supportRequired?.value;
    supports?.removeAt(index);
    supports?.add(null);
    const reset = SupportRequiredList.pure();
    final supportRequired = SupportRequiredList.dirty(supports);

    log('After state updates');
    log("State: ${state.supportRequired?.value ?? 'null'}");
    log("Filtered list: $supports");

    // emit(state.copyWith(supportRequired: reset));
    // emit(
    //   state.copyWith(
    //       supportRequired: supportRequired,
    //       formStatus: Formz.validate([
    //         state.participant!,
    //         state.supportWorker!,
    //         state.bookingStart!,
    //         state.bookingEnd!,
    //         state.bookingType!,
    //         supportRequired,
    //         state.riskAlert!,
    //         state.bookingStatus!,
    //       ])),
    // );
  }
```

When the code is run, it returns this in the terminal:

<img width="421" alt="Screen Shot 2022-09-15 at 23 29 12" src="https://user-images.githubusercontent.com/42107315/190430664-5dcf0c35-9c18-4145-ab7e-c395eab7a545.png">

As you can see on the picture above, the cubit state has been updated.

However, if i was to run a similar code on another text form, for example a regular text input or drop down menu, this issue does not occur.

 Could you help me with this issue?

**Comment by felangel** [comment] 2022-09-15 14:34
Hi @Caldarie 👋 
Thanks for opening an issue!

It would be much easier to help if you could provide a link to a minimal reproduction sample which we can run/debug locally. Thanks! 🙏

**Comment by Caldarie** [comment] 2022-09-15 15:00
@felangel  Understood. I will write a minimal reproduction sample and get back to you.

**Comment by Caldarie** [comment] 2022-09-16 09:03
Hi @felangel 

I have found a strange behaviour where if i was to call the list value from the state, and modify it. It will unconditionally update the state from the bloc.

``` dart
   final supports = state.supportRequired?.value;
    supports?.removeAt(index);
    supports?.add(null);
```

However, if was to clone the list value from the state, and modify that value, it will work as intended.

``` dart
   final supports  = [...?state.supportRequired?.value];
    supports?.removeAt(index);
    supports?.add(null);
```

Is this normal behaviour?

**Comment by felangel** [comment] 2022-09-17 17:23
@Caldarie can you please share a DartPad or GitHub link with a minimal reproduction sample? Thanks!

**Comment by Caldarie** [comment] 2022-09-18 03:12
@felangel Sorry for the late reply. I had been busy with my job.

Please look at the following code below. The plus button shouldn't modify the state, while the minus button modifies the state without using `emit`.

Once the button is pressed, please look at the terminal for state changes. Otherwise, reload the emulator to check for state changes.

```dart
import 'dart:developer';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

void main() {
  Bloc.observer = AppBlocObserver();
  runApp(const AppView());
}

/// Custom [BlocObserver] that observes all bloc and cubit state changes.
class AppBlocObserver extends BlocObserver {
  @override
  void onChange(BlocBase bloc, Change change) {
    super.onChange(bloc, change);
    if (bloc is Cubit) print(change);
  }

  @override
  void onTransition(Bloc bloc, Transition transition) {
    super.onTransition(bloc, transition);
    print(transition);
  }
}

class AppView extends StatelessWidget {
  /// {@macro app_view}
  const AppView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: TestPage(),
    );
  }
}

class TestPage extends StatelessWidget {
  const TestPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => TestBloc(),
      child: const TestView(),
    );
  }
}

class TestView extends StatelessWidget {
  const TestView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Counter')),
      body: Center(
        child: BlocBuilder<TestBloc, List<String?>?>(
          builder: (context, list) {
            return Text('$list');
          },
        ),
      ),
      floatingActionButton: Column(
        crossAxisAlignment: CrossAxisAlignment.end,
        mainAxisAlignment: MainAxisAlignment.end,
        children: <Widget>[
          FloatingActionButton(
            child: const Icon(Icons.add),
            onPressed: () {
              context.read<TestBloc>().add(CorrectStatePressed());
            },
          ),
          const SizedBox(height: 4),
          FloatingActionButton(
            child: const Icon(Icons.remove),
            onPressed: () {
              context.read<TestBloc>().add(IncorrectStatePressed());
            },
          ),
        ],
      ),
    );
  }
}

abstract class CounterEvent {}

///State incorrectly returns a value in array, i.e. ['Value should not be here']
class IncorrectStatePressed extends CounterEvent {}

///State should return empty array, i.e. []
class CorrectStatePressed extends CounterEvent {}

class TestBloc extends Bloc<CounterEvent, List<String?>?> {
  TestBloc() : super([]) {
    on<IncorrectStatePressed>((event, emit) {
      final test = state;
      test?.add('Value should not be here');
      log('state: $state');
    });
    on<CorrectStatePressed>((event, emit) {
      final test = [...?state];
      test.add('Value should not be here');
      log('state: $state');
    });
  }
}

```

**Comment by LeonardoRosaa** [comment] 2022-09-19 00:40
For one reason the Dart language did pass the state reference instead of the value. According to the example above, you can do something like this:
```
final test = List.from(state);
```

**Comment by Caldarie** [comment] 2022-09-19 04:59
Thank you for the response @LeonardoRosaa 

Yeah, as shown from the example i have provided, `List.from(state);` is more or less similar to `[...?state]`

**Comment by LeonardoRosaa** [comment] 2022-09-19 09:35
> Thank you for the response @LeonardoRosaa
> 
> You're absolutely right. I have been using `[...?state]` which is more or less similar to `List.from(state)` to circumvent this problem

I think that in this case `[...?state]` doesn't work as well.

**Comment by Caldarie** [comment] 2022-09-28 13:19
> > Thank you for the response @LeonardoRosaa
> > You're absolutely right. I have been using `[...?state]` which is more or less similar to `List.from(state)` to circumvent this problem
> 
> I think that in this case `[...?state]` doesn't work as well.

@LeonardoRosaa Appreciate the input.

As I am not an expert with dart, would you be willing to explain why that's the case?

**Comment by LeonardoRosaa** [comment] 2022-10-03 10:17
Honestly, I don't know why yet. I believe it may be a bug.

I did some tests in the [DartPad](https://dartpad.dev/?) and this works as well. 

```dart
void main() {
  final a = [1, 2, 3];
  final b = [...a];
  
  b.add(4);
  
  print(a); /// [1, 2, 3]
  print(b); /// [1, 2, 3, 4]
}
```

**Comment by felangel** [comment] 2022-10-15 14:05
> Honestly, I don't know why yet. I believe it may be a bug.
> 
> I did some tests in the [DartPad](https://dartpad.dev/?) and this works as well.
> 
> ```dart
> void main() {
>   final a = [1, 2, 3];
>   final b = [...a];
>   
>   b.add(4);
>   
>   print(a); /// [1, 2, 3]
>   print(b); /// [1, 2, 3, 4]
> }
> ```

That’s working as expected. Since b contains a copy of a not a reference to a. Closing for now since there are no actionable next steps in the context of the bloc repo.

**Closed by felangel** 2022-10-15 14:05 UTC
Labels: question, waiting for response
