### ISSUE TITLE
fix: Impossible to Install bloc_test, Version Solving Faile

### ISSUE THREAD

**Issue by LahaLuhem** [felangel/bloc#3663] opened 2022-12-12 16:54 UTC
**Description**
It is impossible to install bloc_test, it fails with the latest stable version of Flutter.

**Steps To Reproduce**

1. Add bloc_test to dev_dependencies. You can add the latest 9.0.2 version or even do any to let the pub deal with latest compatible version.
2. Use the following pubspec stack:
[pubdev stack.txt](https://github.com/felangel/bloc/files/10210190/pubdev.stack.txt)

**Expected Behavior**
For it to install without any problem.

**Screenshots**

**Additional Context**
The following is the error log using `bloc_test: any`
[pubspec error.log](https://github.com/felangel/bloc/files/10210209/pubspec.error.log)
[pubspec error (fixed ver - 9.1.0).log](https://github.com/felangel/bloc/files/10210231/pubspec.error.fixed.ver.-.9.1.0.log)

`flutter --version`:
```
Flutter 3.3.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b8f7f1f986 (3 weeks ago) • 2022-11-23 06:43:51 +0900
Engine • revision 8f2221fbef
Tools • Dart 2.18.5 • DevTools 2.15.0
```

**Comment by felangel** [comment] 2022-12-12 16:57
This is a duplicate of https://github.com/flutter/flutter/issues/115284 which should be fixed on the master channel. Please feel free to comment if the issue persists on the master channel, thanks!

**Closed by felangel** 2022-12-12 16:57 UTC
Labels: bug

**Comment by LahaLuhem** [comment] 2022-12-12 17:15
It still persists, as I just installed it.

Also it seems to be having a conflict with `analyzer` and not `flutter_test` (as is the case with the duplicate).

**Comment by felangel** [comment] 2022-12-12 17:18
> It still persists, as I just installed it.
> 
> Also it seems to be having a conflict with `analyzer` and not `flutter_test` (as is the case with the duplicate).

Ah sorry wrong issue -- I believe this is the relevant issue: https://github.com/felangel/mocktail/issues/152.

**Comment by LahaLuhem** [comment] 2022-12-14 16:26
But my it's `bloc_test: ^9.1.0` that has issues with `analyzer: ^5.2.0`. In any case the issue still persists.

**Comment by felangel** [comment] 2022-12-14 16:28
> But my it's `bloc_test: ^9.1.0` that has issues with `analyzer: ^5.2.0`. In any case the issue still persists.

I believe this is fixed on the Flutter master channel. Can you please let me know if you're experiencing the same issue on the master channel?
