### ISSUE TITLE
GetIt: The compiler could not infer the type. You have to provide a type and optionally a name. Did you accidentally do `var sl=GetIt.instance();` instead of var sl=GetIt.instance;fix: Failed assertion: line 333 pos 7: 'type != null || const Object() is! T'

### ISSUE THREAD

**Issue by hesham060** [felangel/bloc#3593] opened 2022-10-24 13:36 UTC
**Description**

**Steps To Reproduce**

**Expected Behavior**

**Screenshots**

**Additional Context**

**Comment by felangel** [comment] 2022-11-03 02:45
Closing for now since there isn't enough information to help and this doesn't appear to be related to the bloc library. I highly recommend opening an issue on the get_it repository with additional context or a reproduction sample.

**Closed by felangel** 2022-11-03 02:45 UTC
Labels: bug
