### ISSUE TITLE
Issue testing Hydrated Bloc

### ISSUE THREAD

**Issue by muhammadarslannasr** [felangel/bloc#3171] opened 2022-01-25 13:10 UTC
Hi 

I am new one in flutter facing issue adding code using flutter_bloc but when adding and it works fine but issue is its not working when checking offline means internet not connected.

I am getting data from api and get error (OS Error: No address associated with hostname, errno = 7).

My bloc code class is:

```dart
class FlutterTestingBloc
    extends HydratedBloc<FlutterTestingEvent, FlutterTestingState> {
  final Repository repository;
  int paginationLimit = 20;

  FlutterTestingBloc({required this.repository})
      : super(FlutterTestingInitialState());

  @override
  Stream<FlutterTestingState> mapEventToState(
      FlutterTestingEvent event) async* {
    if (event is TestingFetchEvent) {
      yield FlutterTestingLoadingState();

      try {
        final response = await repository.fetchPersonsApi(paginationLimit);
        if (response[0] == true) {
          yield FlutterTestingLoadedState(personsModel: response[1]);
        } else {
          yield FlutterTestingErrorLoadingState(
              error: 'Sorry there is some issue!');
        }
      } catch (e) {
        yield FlutterTestingErrorLoadingState(error: e.toString());
      }
    }
  }

  @override
  FlutterTestingState? fromJson(Map<String, dynamic> json) {
    try {
      final persons = PersonsModel.fromJson(json);
      return FlutterTestingLoadedState(personsModel: persons);
    } catch (_) {
      return null;
    }
  }

  @override
  Map<String, dynamic>? toJson(FlutterTestingState state) {
    if (state is FlutterTestingLoadedState) {
      return state.personsModel.toJson();
    } else {
      return null;
    }
  }
}`

**Comment by felangel** [comment] 2022-01-27 17:08
Hi @muhammadarslannasr 👋 
Thanks for opening an issue!

Based on the error it seems the issue is within the `fetchPersonsApi` implementation. There isn't enough information to help beyond that so I'm closing for now but feel free to provide a reproduction sample if you're unable to resolve the issue and I'm happy to take a closer look 👍

**Closed by felangel** 2022-01-27 17:08 UTC
Labels: question
