### ISSUE TITLE
Issue in using same Bloc for multiple pages

### ISSUE THREAD

**Issue by GaneshSingaravelu** [felangel/bloc#2406] opened 2021-04-19 10:57 UTC
Hi,

I have created one bloc to access the two screens (like Register Account screen and Complete profile screen) and I want to maintain the states and send all the data (master & details data) to API in one hit. But I facing some issues while implementing this logic. 

Please let me know how to implement this in my real-time scenario.

Note: I have already declared few blocs globally to access all over the pages. So, I don't want more blocs declared globally. Please let me know any other options exist to achieve this or kindly some sample code.

_**Sign up:**_

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:foodapp/businesslogic/bloc/useraccount/signup/signup_bloc.dart';
import 'package:foodapp/businesslogic/generic_state/formstate.dart';
import 'package:foodapp/core/config/size_config.dart';
import 'package:foodapp/core/constants/constants.dart';
import 'package:foodapp/core/helpers/common/loader.dart';
import 'package:foodapp/core/helpers/common/snackbar.dart';
import 'package:foodapp/presentation/components/custom_surfix_icon.dart';
import 'package:foodapp/presentation/components/default_button.dart';
import 'package:foodapp/presentation/router/app_router.dart';
import 'package:foodapp/presentation/views/useraccount/complete_profile/complete_profile_view.dart';
import 'package:websafe_svg/websafe_svg.dart';

class SignupBody extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: double.infinity,
      child: SingleChildScrollView(
        child: Padding(
          padding: EdgeInsets.symmetric(
              horizontal: getProportionateScreenHeight(20)),
          child: Column(
            children: [
              Text('Register Account', style: headingStyle),
              Text(
                'Complete your details',
                textAlign: TextAlign.center,
              ),
              SizedBox(height: getProportionateScreenHeight(30)),
              SignupForm()
            ],
          ),
        ),
      ),
    );
  }
}

class SignupForm extends StatefulWidget {
  @override
  _SignupFormState createState() => _SignupFormState();
}

class _SignupFormState extends State<SignupForm> {
  final _formSignupKey = GlobalKey<FormState>();
  //SignupBloc signupBloc;

  // @override
  // void initState() {
  //   super.initState();
  // }

  // @override
  // void dispose() {
  //   signupBloc.close();
  //   super.dispose();
  // }

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => SignupBloc(),
      child: signupForm(),
    );
  }

  Widget signupForm() {
    return BlocListener<SignupBloc, SignupState>(
      listener: (context, state) {
        final formStatus = state.formStatus;
        if (formStatus is FormSubmissionFailed) {
          showSnackBar(context, formStatus.error.toString());
        } else if (formStatus is FormSubmissionSuccess) {
          //Navigator.pushNamed(context, AppRouter.complete_profile);
          Navigator.push(
            context,
            MaterialPageRoute(
              builder: (context) => BlocProvider<SignupBloc>.value(
                value: BlocProvider.of<SignupBloc>(context),
                child: CompleteProfileView(),
              ),
            ),
          );
        }
      },
      child: Form(
        key: _formSignupKey,
        child: Column(
          children: [
            buildEmailFormField(),
            SizedBox(height: getProportionateScreenHeight(30)),
            buildPasswordFormField(),
            SizedBox(height: getProportionateScreenHeight(30)),
            buildConfirmPasswordFormField(),
            SizedBox(height: getProportionateScreenHeight(30)),
            // buildErrorMsg(),
            // SizedBox(height: getProportionateScreenHeight(30)),
            buildSignupContinueButton(),
          ],
        ),
      ),
    );
  }

  Widget buildEmailFormField() {
    return BlocBuilder<SignupBloc, SignupState>(builder: (context, state) {
      return TextFormField(
        keyboardType: TextInputType.emailAddress,
        decoration: InputDecoration(
          labelText: "Email",
          hintText: "Enter your Email id",
          floatingLabelBehavior: FloatingLabelBehavior.always,
          suffixIcon: CustomSurffixIcon(
            svgIcon: "assets/icons/Mail.svg",
          ),
        ),
        validator: (value) =>
            state.isValidEmailID ? null : 'Email id is invalid',
        onChanged: (value) =>
            context.read<SignupBloc>().add(SignupEmailChanged(emailID: value)),
      );
    });
  }

  Widget buildPasswordFormField() {
    return BlocBuilder<SignupBloc, SignupState>(
      builder: (context, state) {
        return TextFormField(
          obscureText: true,
          keyboardType: TextInputType.emailAddress,
          decoration: InputDecoration(
            labelText: "Password",
            hintText: "Enter your password",
            floatingLabelBehavior: FloatingLabelBehavior.always,
            suffixIcon: CustomSurffixIcon(
              svgIcon: "assets/icons/Lock.svg",
            ),
          ),
          validator: (value) =>
              state.isValidPassword ? null : "Password is too short.",
          onChanged: (value) => context
              .read<SignupBloc>()
              .add(SignupPasswordChanged(password: value)),
        );
      },
    );
  }

  Widget buildConfirmPasswordFormField() {
    return BlocBuilder<SignupBloc, SignupState>(
      builder: (context, state) {
        return TextFormField(
          obscureText: true,
          keyboardType: TextInputType.emailAddress,
          decoration: InputDecoration(
            labelText: "Confirm Password",
            hintText: "Re-enter your password",
            floatingLabelBehavior: FloatingLabelBehavior.always,
            suffixIcon: CustomSurffixIcon(
              svgIcon: "assets/icons/Lock.svg",
            ),
          ),
          validator: (value) => state.isValidConfirmPassword
              ? null
              : "Confirm Password  and password is not matched.",
          onChanged: (value) => context
              .read<SignupBloc>()
              .add(SignupConfirmPasswordChanged(confirmPassword: value)),
        );
      },
    );
  }

  Widget buildErrorMsg() {
    return BlocBuilder<SignupBloc, SignupState>(
      builder: (context, state) {
        return state.formStatus is FormValidationError
            ? Row(
                children: [
                  WebsafeSvg.asset(
                    "assets/icons/Error.svg",
                    height: getProportionateScreenWidth(14),
                    width: getProportionateScreenWidth(14),
                  ),
                  SizedBox(
                    width: getProportionateScreenWidth(10),
                  ),
                  Text(''),
                ],
              )
            : Container();
      },
    );
  }

  Widget buildSignupContinueButton() {
    return BlocBuilder<SignupBloc, SignupState>(
      builder: (context, state) {
        return state.formStatus is FormSubmitting
            ? loader('Please wait...') //CircularProgressIndicator()
            : DefaultButton(
                text: 'Continue',
                press: () {
                  if (_formSignupKey.currentState.validate()) {
                    context.read<SignupBloc>().add(SignupContinue());
                  }
                },
              );
      },
    );
  }
}

_**Compete Profile:**_

class CompleteProfileBody extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: double.infinity,
      child: SingleChildScrollView(
        child: Padding(
          padding: EdgeInsets.symmetric(
              horizontal: getProportionateScreenHeight(20)),
          child: Column(
            children: [
              Text('Complete Profile', style: headingStyle),
              Text(
                'Complete your details',
                textAlign: TextAlign.center,
              ),
              SizedBox(height: getProportionateScreenHeight(30)),
              CompleteProfileForm()
            ],
          ),
        ),
      ),
    );
  }
}

class CompleteProfileForm extends StatefulWidget {
  @override
  _CompleteProfileFormState createState() => _CompleteProfileFormState();
}

class _CompleteProfileFormState extends State<CompleteProfileForm> {
  final _formCompleteProfileKey = GlobalKey<FormState>();
  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => context.read<SignupBloc>(),
      child: signupForm(),
    );
  }

  Widget signupForm() {
    return BlocListener<SignupBloc, SignupState>(
      listener: (context, state) {
        final formStatus = state.formStatus;
        if (formStatus is FormSubmissionFailed) {
          showSnackBar(context, formStatus.error.toString());
        } else if (formStatus is FormValidationSuccess) {
          Navigator.pushNamed(context, AppRouter.complete_profile);
        }
      },
      child: Form(
        // key: _formCompleteProfileKey,
        child: Column(
          children: [
            buildFirstNameFormField(),
            SizedBox(height: getProportionateScreenHeight(30)),
            buildLastNameFormField(),
            SizedBox(height: getProportionateScreenHeight(30)),
            buildMobileNoFormField(),
            SizedBox(height: getProportionateScreenHeight(30)),
            buildSignupButton(),
          ],
        ),
      ),
    );
  }

  Widget buildFirstNameFormField() {
    return BlocBuilder<SignupBloc, SignupState>(builder: (context, state) {
      return TextFormField(
        keyboardType: TextInputType.name,
        decoration: InputDecoration(
          labelText: "Firstname",
          hintText: "Enter your Firstname",
          floatingLabelBehavior: FloatingLabelBehavior.always,
          suffixIcon: CustomSurffixIcon(
            svgIcon: "assets/icons/User Icon.svg",
          ),
        ),
        validator: (value) =>
            state.isValidFirstname ? null : 'Firstname is invalid',
        onChanged: (value) => context
            .read<SignupBloc>()
            .add(SignupFirstnameChanged(firstname: value)),
      );
    });
  }

  Widget buildLastNameFormField() {
    return BlocBuilder<SignupBloc, SignupState>(builder: (context, state) {
      return TextFormField(
        keyboardType: TextInputType.emailAddress,
        decoration: InputDecoration(
          labelText: "Lastname",
          hintText: "Enter your Lastname",
          floatingLabelBehavior: FloatingLabelBehavior.always,
          suffixIcon: CustomSurffixIcon(
            svgIcon: "assets/icons/User Icon.svg",
          ),
        ),
        validator: (value) =>
            state.isValidLastname ? null : 'Lastname is invalid',
        onChanged: (value) => context
            .read<SignupBloc>()
            .add(SignupLastnameChanged(lastname: value)),
      );
    });
  }

  Widget buildMobileNoFormField() {
    return BlocBuilder<SignupBloc, SignupState>(builder: (context, state) {
      return TextFormField(
        keyboardType: TextInputType.phone,
        decoration: InputDecoration(
          labelText: "Mobile Number",
          hintText: "Enter your Mobile No.",
          floatingLabelBehavior: FloatingLabelBehavior.always,
          suffixIcon: CustomSurffixIcon(
            svgIcon: "assets/icons/Phone.svg",
          ),
        ),
        validator: (value) =>
            state.isValidMobileNumber ? null : 'Mobile No is invalid',
        onChanged: (value) => context
            .read<SignupBloc>()
            .add(SignupMobileNumberChanged(mobileNumber: value)),
      );
    });
  }

  Widget buildSignupButton() {
    return BlocBuilder<SignupBloc, SignupState>(
      builder: (context, state) {
        return state.formStatus is FormSubmitting
            ? loader('Please wait...') //CircularProgressIndicator()
            : DefaultButton(
                text: 'Register',
                press: () {
                  if (_formCompleteProfileKey.currentState.validate()) {
                    context.read<SignupBloc>().add(SignupSubmitted());
                  }
                },
              );
      },
    );
  }
}

_**SignState:**_

part of 'signup_bloc.dart';

class SignupState {
  // Page 01
  final String emailID;
  bool get isValidEmailID => emailValidatorRegExp.hasMatch(emailID);

  final String password;
  bool get isValidPassword => password.length > 5;

  final String confirmPassword;
  bool get isValidConfirmPassword => password == confirmPassword;

  bool get isRegisterPageValid =>
      (emailID != null && password != null && confirmPassword != null);

  // Page 02
  final String firstname;
  bool get isValidFirstname => firstname.length > 5;

  final String lastname;
  bool get isValidLastname => lastname.length > 5;

  final String mobileNumber;
  bool get isValidMobileNumber =>
      (mobileNumber.length > 9 && mobileNumber.length < 11);

  final FormSubmissionState formStatus;

  SignupState(
      {this.emailID = '',
      this.password = '',
      this.confirmPassword = '',
      this.firstname = '',
      this.lastname = '',
      this.mobileNumber = '',
      this.formStatus = const InitialFormStatus()});

  SignupState copyWith(
      {String emailID,
      String password,
      String confirmPassword,
      String firstname,
      String lastname,
      String mobileNumber,
      FormSubmissionState formStatus}) {
    return SignupState(
      emailID: emailID ?? this.emailID,
      mobileNumber: mobileNumber ?? this.mobileNumber,
      confirmPassword: confirmPassword ?? this.confirmPassword,
      firstname: firstname ?? this.firstname,
      lastname: lastname ?? this.lastname,
      password: password ?? this.password,
      formStatus: formStatus ?? this.formStatus,
    );
  }
}

SignEvent:

part of 'signup_bloc.dart';

@immutable
abstract class SignupEvent {}

class SignupEmailChanged extends SignupEvent {
  final String emailID;
  SignupEmailChanged({this.emailID});
}

class SignupPasswordChanged extends SignupEvent {
  final String password;
  SignupPasswordChanged({this.password});
}

class SignupConfirmPasswordChanged extends SignupEvent {
  final String confirmPassword;
  SignupConfirmPasswordChanged({this.confirmPassword});
}

class SignupContinue extends SignupEvent {}

class SignupFirstnameChanged extends SignupEvent {
  final String firstname;
  SignupFirstnameChanged({this.firstname});
}

class SignupLastnameChanged extends SignupEvent {
  final String lastname;
  SignupLastnameChanged({this.lastname});
}

class SignupMobileNumberChanged extends SignupEvent {
  final String mobileNumber;
  SignupMobileNumberChanged({this.mobileNumber});
}

class SignupSubmitted extends SignupEvent {}

_**SignupBloc:**_

import 'dart:async';
import 'dart:io';

import 'package:bloc/bloc.dart';
import 'package:foodapp/businesslogic/generic_state/formstate.dart';
import 'package:foodapp/core/constants/constants.dart';
import 'package:foodapp/core/exceptions/api_exceptions.dart';
import 'package:foodapp/data/models/app/app_model.dart';
import 'package:foodapp/data/models/useraccount/signup/signup_model.dart';
import 'package:foodapp/data/repositories/useraccount/signup/signup_repository.dart';
import 'package:meta/meta.dart';

part 'signup_event.dart';
part 'signup_state.dart';

class SignupBloc extends Bloc<SignupEvent, SignupState> {
  final SignupRepository repository;
  SignupBloc({this.repository}) : super(SignupState());

  @override
  Stream<SignupState> mapEventToState(
    SignupEvent event,
  ) async* {
    if (event is SignupEmailChanged) {
      yield state.copyWith(emailID: event.emailID);
    } else if (event is SignupPasswordChanged) {
      yield state.copyWith(password: event.password);
    } else if (event is SignupConfirmPasswordChanged) {
      yield state.copyWith(confirmPassword: event.confirmPassword);
    } else if (event is SignupMobileNumberChanged) {
      yield state.copyWith(mobileNumber: event.mobileNumber);
    } else if (event is SignupContinue) {
      yield state.copyWith(formStatus: FormSubmitting());
      if (state.isRegisterPageValid) {
        yield state.copyWith(formStatus: FormSubmissionSuccess());
      } else {
        yield state.copyWith(
            formStatus: FormSubmissionFailed(
                error: ValidationException("Please fill all the details")));
      }
    } else if (event is SignupSubmitted) {
      yield state.copyWith(formStatus: FormSubmitting());
      try {
        final signupData = SignupModel(
            username: "Ganesh@gmail.com",
            mobilenumber: '1234567890',
            password: "Welcome@123");
        ResultModel resultInfo = await repository.signup(signupData);
        if (resultInfo.resultID == 1) {
          yield state.copyWith(formStatus: FormSubmissionSuccess());
        } else {
          yield state.copyWith(
              formStatus: FormSubmissionFailed(
                  error: ValidationException(resultInfo.result)));
        }
      } on SocketException {
        yield state.copyWith(
            formStatus: FormSubmissionFailed(
                error: NoInternetException('No Internet')));
      } on HttpException {
        yield state.copyWith(
            formStatus: FormSubmissionFailed(
                error: NoServiceFoundException('No Service Found')));
      } on FormatException {
        yield state.copyWith(
            formStatus: FormSubmissionFailed(
                error: InvalidFormatException('Invalid Response format')));
      } catch (e) {
        yield state.copyWith(
            formStatus:
                FormSubmissionFailed(error: UnknownException(e.toString())));
      }
    }
  }
}

**Comment by felangel** [comment] 2021-04-20 14:25
Hi @GaneshSingaravelu 👋 
Thanks for opening an issue!

Can you please provide a link to a complete reproduction sample that illustrates the issue you're facing? It's very difficult to parse and interpret the incomplete code you've shared. Thanks!

**Comment by GaneshSingaravelu** [comment] 2021-04-22 18:42
Hi felangel,

Below I have mentioned my requirements and issue details and I have made a sample application and attached the same here. Please do the needful

**Demo Project Attached**
[demoapp.zip](https://github.com/felangel/bloc/files/6360562/demoapp.zip)

**Requirement**
 - I need to use the same bloc (Signup bloc)  in two pages (Register Account & complete profile)
 - I need to maintain the state/instances on the two pages (either push or pop the page)
 
**Issue**
- The values get removed, whenever I have entered the value on the second page.
- My values are empty on the screen When I go back to the first page "Complete Profile" from the second page "Sign up". But values remain in the state and not shown on the screen.

**Doubt**

- If I declare more blocs globally then will it impact the performance of my app?

Thanks

**Comment by felangel** [comment] 2021-05-08 15:08
@GaneshSingaravelu can you please create a minimal reproduction sample and provide a link to a github repo rather than a zip? This will allow me to more easily look at the code and potentially create a pull request with suggestions/fixes. Thanks 🙏

**Comment by felangel** [comment] 2021-05-19 22:13
Closing for now since there isn't a link to a simple reproduction sample available. Feel free to provide one and I'm happy to take a closer look, thanks!

**Closed by felangel** 2021-05-19 22:13 UTC
Labels: question, waiting for response
