### ISSUE TITLE
mockito dose not know startwith method of rxdart

### ISSUE THREAD

**Issue by samin-fs** [felangel/bloc#1863] opened 2020-10-26 12:50 UTC
**Describe the bug**
Hi there @felangel ,
I just migrate to a new version of the bloc(flutter_bloc: ^6.0.1) and I used startwith method of rxdart to listen to the initial state of the bloc, but it seems mockito get null when I call this.
would you please help to found out what should I do? thank you.

**To Reproduce**
1. use flutter_bloc: ^6.0.1 
2. write a test for a bloc with mockito
3. run test to see the error

**Comment by felangel** [comment] 2020-10-26 14:09
Hi @samin-fs 👋 
Thanks for opening an issue!

Can you please provide a link to a sample app which reproduces the issue? Thanks! 🙏

**Comment by felangel** [comment] 2020-11-08 01:34
Closing for now since there is not reproduction sample. Feel free to provide a reproduction sample and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-11-08 01:34 UTC
Labels: pkg:bloc_test, question, waiting for response
