### ISSUE TITLE
EventHandler error when using freezed.

### ISSUE THREAD

**Issue by JUNGHUNKIM-7** [felangel/bloc#3800] opened 2023-04-25 07:19 UTC
ERROR:
```
// **BAD**
// E/flutter ( 4631):   on<Event>((event, emit) {
// E/flutter ( 4631):     future.whenComplete(() => emit(...));
// E/flutter ( 4631):   });
// E/flutter ( 4631):
// E/flutter ( 4631):   **GOOD**
// E/flutter ( 4631):   on<Event>((event, emit) async {
// E/flutter ( 4631):     await future.whenComplete(() => emit(...));
// E/flutter ( 4631):   });
```

Error Happend when i code like this
```dart
on<AuthEvent>((event, emit) {
  event.when(EVENTNAME: (ARG OR EMPTY) async => await logic.whenComplete(() => emit(..)));

// in this case, below code will not be compiled.

on<AuthEvent>((event, emit) async {
  await event.when(EVENTNAME: (ARG OR EMPTY) async => await logic.whenComplete(() => emit(..)));
```
so i changed to event.map as below, but still err happned, how do i fix code for asynchronous & event mapping via freezed?

```dart

on<AuthEvent>((event, emit) async {
  await event.map(
      findUser: (AuthEvent e) => e.whenOrNull(findUser: (id) async {
            await _catchUser(id).whenComplete(() {
              if (mongoHandler.authenticatedUser != null) {
                emit(AuthState.findUser(
                    user: mongoHandler.authenticatedUser));
              } else {
                emit(const AuthState.failedFound());
              }
            });
          }),
      expired: (e) async => emit(const AuthState.expired()));
});
```

**Comment by JUNGHUNKIM-7** [comment] 2023-04-25 08:43
```dart
on<AuthEvent>((event, emit) async {
      await event.map(
          findUser: (e) async => await e.whenOrNull(
                findUser: (id) async => await mongoHandler
                    .getAuth(Int64(int.parse(id ?? '0')))
                    .whenComplete(() {
                  if (mongoHandler.authenticatedUser != null) {
                    emit(...)
```
this is working. but i'm not sure that is best way. looks dirty than just plain bloc impl.

**Comment by felangel** [comment] 2023-05-05 05:21
Hi @JUNGHUNKIM-7 👋 
Thanks for opening an issue!

If I'm understanding correctly, the problem with this snippet is that you're not awaiting the resulting future:

```dart
on<AuthEvent>((event, emit) {
  event.when(EVENTNAME: (ARG OR EMPTY) async => await logic.whenComplete(() => emit(..)));
}
```

You need to await the future:

```dart
on<AuthEvent>((event, emit) async {
  await event.when(EVENTNAME: (ARG OR EMPTY) async => await logic.whenComplete(() => emit(..)));
}
```

**Comment by JUNGHUNKIM-7** [comment] 2023-05-05 06:07
@felangel
Thanks for feedback!, your code seems best way that i could do and tried it already before writing post.
-first section && second code (among 3 sections of codes)  / wrap event.when with async await 

- PROBLEM was it isn't compiled with build_runner. 

- btw, using event.map approach only worked (compiled, no async await err message from bloc lib). but too verbose you see.

i would double check later. thanks again.

**Comment by felangel** [comment] 2023-05-15 04:47
Closing for now since there aren't any actionable next steps. Feel free to provide a link to a minimal reproduction sample if this is still an issue and I'm happy to take a closer look, thanks! 👍

**Closed by felangel** 2023-05-15 04:47 UTC
Labels: question, waiting for response
