### ISSUE TITLE
Rendering other state and not the current state

### ISSUE THREAD

**Issue by gfiury** [felangel/bloc#1940] opened 2020-11-17 22:40 UTC
**Describe the bug**
I do not know if it is a bug, it is more like a question or a problem mis-handling the bloc and the states on different Tabs.

0) Bloc version 4.0
1) I'm changing a state based on an event
2) The states are not Equatable
3) The BlocConsumer triggers with the correct state
4) The Widgets are incorrect is like another state is present

**To Reproduce**
Look at the code

```
class TestBloc  extends Bloc<TestEvent, TestState> {
  @override
  TestState get initialState => TestInitial();

  @override
  Stream<TestState> mapEventToState(TestEvent event) async* {
        if (event is TestInitial) {
           yield TestLoading();
       }
    
       if (event is GetInfoFirst) {
          // Getting info from the Repo
          yield InfoFirstLoaded();
       }

       if (event is GetInfoSecond) {
           yield InfoSecondLoading();
           // Getting info from the Repo
           yield InfoSecondLoaded();
       }
  }
}

class TestPage extends StatefulWidget {
  static Widget withBloc() {
    return BlocProvider<TestBloc>(
      create: (c) => TestBloc(),
      child: TestPage(),
    );
  }

  @override
  TestPageState createState() => TestPageState();
}

class TestPageState extends State<TestPage>
    with SingleTickerProviderStateMixin {
  TabController _tabController;
  List<Tab> listTabs;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();

    listTabs = [
      Tab(text: 'First Tab'),
      Tab(text: 'Second Tab')
    ];

    _tabController = TabController(vsync: this, length: listTabs.length);

    context.bloc<TestBloc>().add(
          GetInfoFirst(),
    );
  }

  @override
  Widget build(BuildContext context) {
     return BlocConsumer<TestBloc, TestState>(
        listener: _onStateChange,
        builder: (context, state) {
          return WillPopScope(
              onWillPop: _willPopUp,
              child: Scaffold(
                  appBar: AppBar(
                      bottom: TabBar(
                        indicatorColor: Colors.white,
                        controller: _tabController,
                        tabs: listTabs,
                      ),
                      title:
                          Text('Title')),
                  body: TabBarView(
                      physics: NeverScrollableScrollPhysics(),
                      controller: _tabController,
                      children: [
                        buildFirst(state),
                        buildSecond(state)
                      ])));
        });
  }

void _onStateChange(BuildContext context, TestState state) {
    if (state is InfoSecondLoading) {
      _tabController.animateTo(1);
    }
}

Widget buildLoading() {
    return Center(child: CircularProgressIndicator());
  }

Widget buildFirst(TestState state) {
   if(state is InfoFirstLoaded) {
      return Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisSize: MainAxisSize.min,
                  children: <Widget>[
                    Text("INFO FIRST LOADED"),
                    FlatButton(
                              child: Text("GO TO SECOND TAB").
                     onPressed: () {
                              context.bloc<TestBloc>().add(GetInfoSecond());
                     }) 
                  ]);
   }

   return buildLoading();
}

Widget buildSecond(TestState state) {
    print('---------------');
    print(state);
    if (state is InfoSecondLoaded) {
         return Text("INFO SECOND LOADED");
    }

    if (state is ErrorSecondInfo) {
        return Text("INFO SECOND ERROR");
    }

    return buildLoading();
}
```

**Expected behavior**
The Second Tab should be showing the the "INFO SECOND LOADED" text, but instead it always shows the loading indicator.
The `print(state)`: Instance of 'InfoSecondLoaded'

I'm going nuts, because the logs shows the correct state, but looking at the screen it shows the loading indicator.

I tried even with the error state but nothing happens, the indicator is there.

There is some kind of racing between the InfoSecondLoading and InfoSecondLoaded. Because with a **breakpoint** at **print(state)**, it works.  I do not why yet, another thing I tried is removing the breakpoint of the print and adding a new one at `return Text("INFO SECOND LOADED");`. The last one doesn't work but the order of the states is correct.

**Comment by felangel** [comment] 2020-11-18 18:08
Hi @gfiury 👋 
Thanks for opening an issue!

Can you please provide a link to a sample app which reproduces the issue? Thanks 🙏

**Comment by felangel** [comment] 2020-11-24 21:37
Closing for now since there isn't a reproduction sample.

**Closed by felangel** 2020-11-24 21:37 UTC
Labels: question, waiting for response
