### ISSUE TITLE
BlocObserver onError is fired for Bloc objects, but not for Cubits

### ISSUE THREAD

**Issue by ebelevics** [felangel/bloc#2579] opened 2021-06-29 18:48 UTC
**Describe the bug**
When I throw error by using Bloc object, from BlocObserver onError function is called. When I try the same thing with Cubit it doesn't call onError on throw. I used two existing examples flutter_weather for Cubit and flutter_todos for Bloc testing.

**To Reproduce**
Steps to reproduce the behavior with Bloc objects:
1. Import flutter_todos project
2. remove try catch from _mapTodosLoadedToState() function
3. add throw to _mapTodosLoadedToState() function
4. onError function does print string as expected

Steps to reproduce the behavior with Cubit objects:
1. Import flutter_weather project
2. remove try catch from fetchWeather() function
3. add throw to fetchWeather() function
4. onError function does not print string as expected

**Expected behavior**
In https://pub.dev/packages/bloc version 7.0.0 it's stated that BlocObserver can observe errors for Cubits, not only Blocs.

**Additional context**
Bloc version 7.0.0 is used and given examples are already migrated to 7.0.0 by using BlocBase for Cubit.

**Comment by JigneshPatel23** [comment] 2021-07-03 07:38
Hi @ebelevics 

Yes I understood this concern and seems like yes it can be easily reproducible.. 

As with Bloc we are writing our code on `mapEventToState` stream and if that throws an error can be handled by `onError` on stream.
https://github.com/felangel/bloc/blob/f4015fe3fbb0bce3a4249d45092fb6c37499e54c/packages/bloc/lib/src/bloc.dart#L243

But with Cubit we are writing code on functions defined by us and for which `BlocBase` don't have any context and error handling for.. 
If needed we can wrap our function and call `onError` it will be forwarded to `BlocObserver`.
 
 e.g.
 ```
  Future<void> fetchWeather(String? city) async {
    try {
      ...
    } on Exception catch (e, s) {
      onError(e, s);
    }
  }  
  ```

**Comment by felangel** [comment] 2021-07-03 16:06
Hi @ebelevics 👋 
Thanks for opening an issue!

As @JigneshPatel23 mentioned with `Cubit` you are responsible for handling errors since the methods that are throwing are defined entirely by you.

```dart
Future<void> fetchWeather(String? city) async {
   try {
     ...
   } on Exception catch (e, s) {
     addError(e, s);
   }
 }  
```

Hope that helps! Closing for now but feel free to comment with additional questions/comments and I'm happy to continue the conversation 👍

**Closed by felangel** 2021-07-03 16:06 UTC
