### ISSUE TITLE
Bloc applies mapEventToState method to first event, but not to second event

### ISSUE THREAD

**Issue by vari** [felangel/bloc#1224] opened 2020-05-28 21:47 UTC
I'm new to flutter and started looking into using flutter_bloc for managing state in a hobby project.  The documentation is great and has been a great help in getting me started on setting up the project to use the BLoC pattern. Unfortunately things seem to break when I add a second event to the bloc.

When I add an event to the bloc the first time, the bloc responds to it and the mapEventToState method is called as expected. However, when I add the same event again, I see the `onEvent` method being called in the BlockDelegate, but I do not see the `mapEventToState` method called and consequently the state and UI do not update. 

I have set up my bloc and corresponding events and states as follows:

```dart
/* States */
abstract class LEDState extends Equatable {
  const LEDState();
  @override
  List<Object> get props => [];
}

class LEDEmpty extends LEDState {}
class LEDLoading extends LEDState {}
class LEDLoaded extends LEDState {}
class LEDLoadFailed extends LEDState {
  final String errorMsg;
  const LEDLoadFailed({@required this.errorMsg}) : assert(errorMsg != null);
  @override
  List<Object> get props => [errorMsg];
}

/* Events */
abstract class LEDEvent extends Equatable {
  const LEDEvent();
  @override
  List<Object> get props => [];
}

class GetLEDData extends LEDEvent {}

/* Bloc */
class LEDBloc extends Bloc<LEDEvent, LEDState> {
  final LEDRepository repository;
  LEDBloc({@required this.repository}): assert (repository != null);

  @override
  LEDState get initialState => LEDEmpty();

  @override
  Stream<LEDState> mapEventToState(LEDEvent event) async* {
    print('Received $event while state is $state');
    if (event is GetLEDData && (state is LEDEmpty || state is LEDLoadFailed)) {
      yield LEDLoading();
      try {
        final data = await repository.getData();
        yield LEDLoaded(); // TODO: hook this up with the data once things work
      } catch(e) {
        yield LEDLoadFailed(errorMsg: '$e');
      }
    }
  }
}
```

I use the `BlocProvider` widget to create and pass the bloc to my widget subtree. Inside my main widget I display different widgets depending on the state of the bloc as follows:

```dart
Widget build(BuildContext context) { 
  return SingleChildScrollView(
      child: BlocBuilder<LEDBloc, LEDState>(
        builder: (context, state) {
          return body(context, state);
        },
      ),
    );
}

Widget body(BuildContext context, LEDState state) {
    if (state is LEDEmpty || state is LEDLoading) {
      return Center(
        child: RaisedButton.icon(
          onPressed: () => BlocProvider.of<LEDBloc>(context).add(GetLEDData()),
          icon: Icon(Icons.star),
          label: Text('Get Data'),
        ),
      );
      // return Center(
      //   child: CircularProgressIndicator(),
      // );
    }

    if (state is LEDLoadFailed) {
      return Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text('There was an error getting LED data.\n${state.errorMsg}'),
            RaisedButton.icon(
              onPressed: () => BlocProvider.of<LEDBloc>(context).add(GetLEDData()),
              icon: Icon(Icons.refresh),
              label: Text("Retry")
            ),
          ],
        ),
      );
    }
    return null; // This should never happen
  }
```

What happens is that when I launch my app, I see the initial Get Data button and press it to grab the data. This calls the `onEvent` and the `mapEventToState`  methods as expected (based on the output of `onEvent` and `onTransition` in the bloc delegate). Since the network request is not yet setup properly, the request fails which is to be expected and the bloc enters the `LEDLoadFailed` state.

Once in the `LEDLoadState` the UI updates to show the error message and a retry button. Clicking Retry adds the `GetLEDData` event to the bloc (similar to the 'Get Data' button) however, I only see log output for the `onEvent` method of the bloc delegate and no UI updates occur so I'm fairly sure the bloc state is not being updated either.

I am aware that this type of issue seems to have come up before based on some of the results I found while googling. Unfortunately the results did not apply to my situation (most solutions involved incorrect state transitions - e.g. transitioning from state X to state X again when the state classes extend Equatable). In my case, the added event should trigger a state change to a completely different state so this does not apply. Nonetheless, to eliminate this as a possibility, I added debug print to the `mapEventToState` method to verify whether it is called when the second event is added - the method is not called so I don't think its a state transition error.

Any suggestions on what I can do to further debug this issue is appreciated!

Edit: For completeness, here is the log output I see when running my app:
```
onEvent GetLEDData
Received GetLEDData while state is LEDEmpty
onTransition Transition { currentState: LEDEmpty, event: GetLEDData, nextState: LEDLoading }
onTransition Transition { currentState: LEDLoading, event: GetLEDData, nextState: LEDLoadFailed }
onEvent GetLEDData
```

The second line of output is from the debug print I have in the `mapEventToState` method. As you can see, the second event is added to the bloc, but no state transition seems to occur after it is added.

**Comment by felangel** [comment] 2020-05-29 00:40
Hi @vari 👋 
Thanks for opening an issue!

Are you able to share a link to a sample app which illustrates the problem you're having? It would be much easier to help if I can debug the app locally. Thanks! 👍

**Comment by vari** [comment] 2020-05-29 03:13
Sure! I'll create a public repo with the sample app tomorrow and post the link to it.

**Comment by vari** [comment] 2020-05-29 05:01
Update: I tried running the android version of the sample app that I posted above on the emulator and it seems to work as expected for android. I suspect this is a bug specific to web only since when I run it on the web, I can always repro the issue.

I'm using the following versions of flutter_bloc and flutter:
`flutter_bloc`: 4.0.0
`bloc`: 4.0.0
`flutter`: 1.18.0-11.1.pre

**Comment by felangel** [comment] 2020-05-29 17:11
@vari thanks for sharing! I believe this is a duplicate of https://github.com/felangel/bloc/issues/957. It is a bug in dart which is tracked by https://github.com/dart-lang/sdk/issues/39994. You can work around this issue for now but running your web application in release mode 👍

**Closed by felangel** 2020-05-29 17:11 UTC
Labels: question, waiting for response

**Comment by vari** [comment] 2020-05-29 17:58
Until dart-lang/sdk#39994 is fixed, would it be possible to add some sort of warning to flutter bloc when it detects that the web version is running? I've spent a lot of time trying to figure out what was wrong - it would be nice to have `flutter_bloc` give me a warning saying that there is a known bug when running on web using debug compiler.

**Comment by felangel** [comment] 2020-05-29 19:44
@vari how would you like the warning to be presented?

**Comment by vari** [comment] 2020-05-29 21:54
A "Known Issues" section on the package readme which describes the issue would probably suffice.

It could also be a runtime thing where, upon the creation of a bloc/bloc delegate (anything that is usually only created once), you check to see if the platform is web and issue a warning (as a print/log statement) along the lines of 'Due to a bug with the dev dart compiler, in some cases Bloc events are not mapped to state changes on the web platform'. 

That way if a new user uses bloc and runs the app on Chrome, they will see the warning show up in the console.

(This might be a moot point soon though since it looks like a patch for the underlying issue has been committed as per dart-lang/sdk#39994)
