### ISSUE TITLE
Bloc state not updating, triggered by FCM 

### ISSUE THREAD

**Issue by ubaidillahSriyudi** [felangel/bloc#1987] opened 2020-12-03 03:04 UTC
**Describe the bug**
I have 2 bloc InitAppBloc and ListandOffersBloc
InitAppBloc is where FCM Initialized and when new notif received on onResume, i call `ListandoffersBloc()..add(GetAllOffers());` to trigger Listandoffers bloc to send new state to view, but unfortunately state not updating, i've tried remove Equatable but it seems BlocConsumer still not receive new state

**Expected behavior**
what i expect is when FCM onResume received message, then it call GetAllOffers event, then it trigger Listanddoffers Bloc to send new state to UI 

**InitAppBloc**
```
class InitappBloc extends Bloc<InitappEvent, InitappState> {
  InitappBloc() : super(InitappInitial());
  Repository _repository = Repository();
  FlutterLocalNotificationsPlugin _flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
  final FirebaseMessaging _fcm = FirebaseMessaging();
  ListandoffersBloc _listandoffersBloc = ListandoffersBloc();

  @override
  Stream<Transition<InitappEvent, InitappState>> transformEvents(
    Stream<InitappEvent> events, 
    TransitionFunction<InitappEvent, InitappState> transitionFunction){
    return super.transformEvents(
      events.debounceTime(const Duration(microseconds: 500)), 
      transitionFunction
    );
  }

  @override
  Stream<InitappState> mapEventToState(InitappEvent event ) async* {
    if (event is InitappEventInitial) {
      yield await ConstantSession().initializeLocalData().then((_) => _checkDriverSession(event));
      _onFCM(state);
      _onIntializeLocalNotifiication();
    }
  }

  Future<InitappState> _onFCM(InitappState state) async {
    _fcm.subscribeToTopic('customerGetReply_${ConstantSession().localID}');
    _fcm.configure(
      onMessage: (Map<String, dynamic> message) async {
        ListandoffersBloc()..add(GetAllOffers());
        _handleNotification(message, 'onMessage', state);
      },
      onLaunch: (Map<String, dynamic> message) async {
        _handleNotification(message, 'onLaunch', state);
      },
      onResume: (Map<String, dynamic> message) async {
        _handleNotification(message, 'onResume', state);
      },
      onBackgroundMessage: fcmBackgroundMessageHandler
    );
  }
}
```

**ListandOffersBloc**

```
class ListandoffersBloc extends Bloc<ListandoffersEvent, ListandoffersState> {
  ListandoffersBloc() : super( ListandoffersState());
  Repository _repository = Repository();
  BehaviorSubject<ModelOffersDetail> behavioursOffersDetail = BehaviorSubject<ModelOffersDetail>();
  ValueStream<ModelOffersDetail> get getModelOffersDetail => behavioursOffersDetail;

  @override
  Stream<Transition<ListandoffersEvent, ListandoffersState>> transformEvents(
    Stream<ListandoffersEvent> events, 
    TransitionFunction<ListandoffersEvent, ListandoffersState> transitionFn){
      return super.transformEvents(
        events.debounceTime(
          const Duration(milliseconds: 500)
        ), 
        transitionFn
      );
  }

  @override
  Stream<ListandoffersState> mapEventToState(ListandoffersEvent event) async* {
    if (event is ListandoffersEventAvailableDrivers) {
      yield state.copyWith(
        searchDriverStatus: SearchDriverStatus.availableDrivers,
        data: event.data
      );
    }

    if (event is SendOffers) {
      yield await _sendOffers(state, event);
    }

    if (event is GetAllOffers) {
      yield await _getAllOffers();
    }
  }
  

  Future<ListandoffersState> _getAllOffers() async {
    try {
      ResCustomerGetAllOffers blocRes = await _repository.order.getAllOffers(ConstantSession().localID);
      if (blocRes.status == 200) {
        print('_getAllOffers 200');
        print('blocRes length ${blocRes.data.length}');
        return state.copyWith(
          resCustomerGetAllOffers: blocRes,
          getAllOffersStatus: GetAllOffersStatus.completed
        );
      } else {
        print('_negotiatedDriver 404');
      }
    } catch (e) {
      print('catach $_getAllOffers');
    }
  }
}
```

**ListandoffersEvent**

```
part of 'listandoffers_bloc.dart';

class ListandoffersEvent{
  // const ListandoffersEvent();

  // @override
  List<Object> get props => [];
}

class ListandoffersEventAvailableDrivers extends ListandoffersEvent {
  final List<ListDriverSearchResult> data;

  ListandoffersEventAvailableDrivers({@required this.data});
} 

class SendOffers extends ListandoffersEvent {
  final String driverID;
  final double originLat;
  final double originLng;
  final double destinationLat;
  final double destinationLng;
  final double distanceCustomerDriverNumber;
  final String distanceCustomerDriverString;
  final String originAddress;
  final String destinationAddress;
  final double nominal;

  SendOffers({
    @required this.driverID,
    @required this.originLat, 
    @required this.originLng,
    @required this.destinationLat,
    @required this.destinationLng,
    @required this.distanceCustomerDriverNumber,
    @required this.distanceCustomerDriverString,
    @required this.originAddress,
    @required this.destinationAddress,
    @required this.nominal,
  });
}

class GetAllOffers extends ListandoffersEvent {
  // @override
  List<Object> get props => [];
}
```

**ListandoffersState**

```
part of 'listandoffers_bloc.dart';

enum ListandoffersStatus {offersSent, offersDuplicate}
enum GetAllOffersStatus {completed}

class ListandoffersState {
  final SearchDriverStatus searchDriverStatus;
  final ListandoffersStatus listandoffersStatus;
  final GetAllOffersStatus getAllOffersStatus;
  final ResCustomerGetAllOffers resCustomerGetAllOffers;
  final String resOffersFromServer;
  final List<ListDriverSearchResult> data;
  final double nominal;

  const ListandoffersState({
    this.searchDriverStatus,
    this.listandoffersStatus,
    this.getAllOffersStatus,
    this.resCustomerGetAllOffers,
    this.resOffersFromServer,
    this.data,
    this.nominal
  });
  

  ListandoffersState copyWith({
    SearchDriverStatus searchDriverStatus,
    ListandoffersStatus listandoffersStatus,
    GetAllOffersStatus getAllOffersStatus,
    ResCustomerGetAllOffers resCustomerGetAllOffers,
    String resOffersFromServer,
    List<ListDriverSearchResult> data,
    double nominal
  }){
    return ListandoffersState(
      searchDriverStatus: searchDriverStatus ?? this.searchDriverStatus,
      listandoffersStatus: listandoffersStatus ?? this.listandoffersStatus,
      getAllOffersStatus: getAllOffersStatus ?? this.getAllOffersStatus,
      resCustomerGetAllOffers : resCustomerGetAllOffers ?? this.resCustomerGetAllOffers,
      resOffersFromServer: resOffersFromServer ?? this.resOffersFromServer,
      data: data ?? this.data,
      nominal: nominal ?? this.nominal
    );
  }

  List<Object> get props => [
    searchDriverStatus, 
    listandoffersStatus,
    getAllOffersStatus,
    resCustomerGetAllOffers,
    resOffersFromServer,
    data, 
    nominal
  ];
}

// class ListandoffersInitial extends ListandoffersState {}
```

**UI**
```
 Widget build(BuildContext context) {
    // TODO: implement build
    return BlocConsumer<ListandoffersBloc, ListandoffersState>(
      listener: (context, state) {
        print('ListandoffersState recalled !');
      },
      builder: (context, state){
        print('ListandoffersState recalled !');
         switch (state.getAllOffersStatus) {
          case GetAllOffersStatus.completed:
            return Scaffold(
              body: ListView.builder(
                itemCount: state.resCustomerGetAllOffers.data.length,
                itemBuilder: (context, idx){
                  return Text('test widget receive state');
                },
              )
            );
            break;
          default: return Center(
            child: SpinLoader()
          );
        }
      } 
    );
  }
```

**Comment by felangel** [comment] 2020-12-04 17:21
Hi @ubaidillahSriyudi 👋 
Thanks for opening an issue!

Can you please create a reproduction sample on GitHub and share the link? It would be much easier for me to help if I can reproduce the issue locally. Thanks 🙏

**Comment by ubaidillahSriyudi** [comment] 2020-12-08 16:10
thanks for the attention, i'll try make some sample project

**Comment by felangel** [comment] 2020-12-18 07:35
Closing for now since there is no reproduction sample. Feel free to add a link to a sample and I'm happy to take a closer look 👍

**Closed by felangel** 2020-12-18 07:35 UTC
Labels: question, waiting for response
