### ISSUE TITLE
Adding multiBlocBuilder interface

### ISSUE THREAD

**Issue by mohammadne** [felangel/bloc#1347] opened 2020-06-27 14:57 UTC
if it is possible , please add ```MultiBlocBuilder``` like ```MultiBlocProvider```.
I think it is necessary.

and then we can have sth like ```Rx.combine```

**Comment by felangel** [comment] 2020-06-27 15:06
Hi @mohammadne 👋
Thanks for opening an issue!

This is a duplicate of https://github.com/felangel/bloc/issues/538 so I will close this but feel free to continue the discussion on the original issue, thanks 🙏

**Closed by felangel** 2020-06-27 15:06 UTC
