### ISSUE TITLE
mockito dose not recognize startwith method of rxdart

### ISSUE THREAD

**Issue by horam-fs** [felangel/bloc#1909] opened 2020-11-10 07:12 UTC
**Description:**
I  have created dependency injection between out blocs by using `startWith` method of `rxDart`. Everything is working fine in the bloc but when I want to debug its test, I face `NoSuchMethodError: The method 'listen' was called on null.`  error message.
 

**output of running `flutter doctor -v`:**
```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale en)
    • Flutter version 1.22.1 at /Users/horam/Documents/flutter
    • Framework revision f30b7f4db9 (5 weeks ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/horam/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.10.0.rc.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Users/horam/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**advert_bloc.dart**
```dart
class AdvertBloc extends Bloc<AdvertEvent, AdvertState> {
  final ConnectionBloc connectionBloc;
  final AccountBloc accountBloc;
  final AdvertiserBloc advertiserBloc;
  SecureStorage storage;
  Advertiser _advertiser;

  StreamSubscription _streamSubscription;

  AdvertBloc({
    this.connectionBloc,
    this.accountBloc,
    this.advertiserBloc,
    this.storage,
  }) : super(AdvertUninitialized()) {
    if (storage == null) storage = SecureStorage();
    if (advertiserBloc != null) {
      _streamSubscription = advertiserBloc
          .startWith(advertiserBloc.state)
          .listen((advertiserState) {
        if (advertiserState is AdvertiserLoaded &&
            this.state is! AdvertLoaded) {
          _advertiser = advertiserState.advertiser;
          this.add(
              Fetch(onlyFetchAdvertiserAdverts: true, shouldRefresh: true));
        }
      });
    } else {
      _streamSubscription =
          accountBloc.startWith(accountBloc.state).listen((accountState) {
        if (accountState is AccountLoaded && this.state is! AdvertLoaded) {
          this.add(
              Fetch(onlyFetchAdvertiserAdverts: false, shouldRefresh: true));
        }
      });
    }
  }
.......
.......
.......
}
```

**advert_bloc_test.dart**
```dart
void main() {
  MockAccountBloc _accountBloc;
  MockConnectionBloc _connectionBloc;
  MockSecureStorage _storage;
  MockAPI _api;
  MockAdvertiserBloc _advertiserBloc;
  final Duration _commonDelay = const Duration(milliseconds: 50);
  ........ 
  ........

  setUp(() {
    _connectionBloc = MockConnectionBloc();
    _accountBloc = MockAccountBloc();
    _advertiserBloc = MockAdvertiserBloc();
    _storage = MockSecureStorage();
    _api = MockAPI();
  });

  tearDown(() {
    _connectionBloc?.close();
    _accountBloc?.close();
    _advertiserBloc?.close();
    _storage?.clearAllAccounts();
    _api?.close();
  });

  AdvertBloc _buildBloc({
    MockConnectionBloc connectionBloc,
    MockAccountBloc accountBloc,
    MockAdvertiserBloc advertiserBloc,
    MockSecureStorage secureStorage,
  }) =>
      AdvertBloc(
        connectionBloc: connectionBloc ?? _connectionBloc,
        accountBloc: accountBloc ?? _accountBloc,
        advertiserBloc: advertiserBloc ?? _advertiserBloc,
        storage: secureStorage ?? _storage,
      );

  .........
  .........
  .........
    blocTest<AdvertBloc, AdvertState>(
      'emits [] when [connectionBloc.state] is [InitialConnectionState].',
      build: () {
        when(_connectionBloc.state).thenReturn(InitialConnectionState());
        return _buildBloc(
          connectionBloc: _connectionBloc,
        );
      },
      act: (_advertBloc) =>
          _advertBloc.add(Fetch(onlyFetchAdvertiserAdverts: true)),
      wait: _commonDelay,
      expect: [],
    );
  ......
  ......
  ......
}
```

**output:**
```
NoSuchMethodError: The method 'listen' was called on null.
Receiver: null
Tried calling: listen(Closure: (AdvertiserState) => Null)
dart:core                                            Object.noSuchMethod
package:otc_cashier/advert/advert_bloc.dart 42:12    new AdvertBloc
test/bloc_tests/advert/advert_bloc_test.dart 59:7    main._buildBloc
test/bloc_tests/advert/advert_bloc_test.dart 124:26  main.<fn>.<fn>
package:bloc_test/src/bloc_test.dart 153:26          runBlocTest.<fn>
dart:async                                           runZoned
package:bloc_test/src/bloc_test.dart 150:9           runBlocTest
package:bloc_test/src/bloc_test.dart 122:11          blocTest.<fn>
===== asynchronous gap ===========================
dart:async                                           _AsyncAwaitCompleter.completeError
package:bloc_test/src/bloc_test.dart                 runBlocTest.<fn>
dart:async                                           runZoned
package:bloc_test/src/bloc_test.dart 150:9           runBlocTest
package:bloc_test/src/bloc_test.dart 122:11          blocTest.<fn>
```

**Comment by felangel** [comment] 2020-11-10 15:28
Hi @horam-fs 👋 
Thanks for opening an issue!

I believe the issue is you aren't stubbing the `startWith`

```dart
when(accountBloc.startWith(any)).thenAnswer((_) => Stream.value(...));
```

Let me know if that helps 👍

**Comment by felangel** [comment] 2020-11-12 03:35
Closing for now but feel free to comment with additional questions and I’m happy to continue the conversation 👍

**Closed by felangel** 2020-11-12 03:35 UTC
Labels: question, waiting for response

**Comment by horam-fs** [comment] 2020-11-15 10:46
> Hi @horam-fs 👋
> Thanks for opening an issue!
> 
> I believe the issue is you aren't stubbing the `startWith`
> 
> ```dart
> when(accountBloc.startWith(any)).thenAnswer((_) => Stream.value(...));
> ```
> 
> Let me know if that helps 👍


sorry for my delayed follow up.
I have tested your suggestion and I got another type of error:


```
Invalid argument(s): An argument matcher (like `any`) was used as a named argument, but did not use a Mockito "named" API. Each argument matcher that is used as a named argument needs to specify the name of the argument it is being used in. For example: `when(obj.fn(x: anyNamed("x")))`.
package:mockito/src/mock.dart 332:7                   _InvocationForMatchedArguments._reconstitutePositionalArgs
package:mockito/src/mock.dart 249:31                  new _InvocationForMatchedArguments
package:mockito/src/mock.dart 217:18                  _useMatchedInvocationIfSet
package:mockito/src/mock.dart 114:18                  Mock.noSuchMethod
package:bloc_test/src/mock_bloc.dart 31:34            MockBloc.noSuchMethod
package:bloc/src/cubit.dart 52:16                     ConnectionBloc.transform
package:rxdart/src/transformers/start_with.dart 95:7  StartWithExtension.startWith
test/bloc_tests/advert/advert_bloc_test.dart 123:30   main.<fn>.<fn>
package:bloc_test/src/bloc_test.dart 153:26           runBlocTest.<fn>
dart:async                                            runZoned
package:bloc_test/src/bloc_test.dart 150:9            runBlocTest
package:bloc_test/src/bloc_test.dart 122:11           blocTest.<fn>
===== asynchronous gap ===========================
dart:async                                            _AsyncAwaitCompleter.completeError
package:bloc_test/src/bloc_test.dart                  runBlocTest.<fn>
dart:async                                            runZoned
package:bloc_test/src/bloc_test.dart 150:9            runBlocTest
package:bloc_test/src/bloc_test.dart 122:11           blocTest.<fn>
```

**Comment by felangel** [comment] 2020-11-15 21:55
@horam-fs no problem! Are you sure you’re importing rxdart in your test? Are you able to share a link to a complete reproduction sample? Thanks!
