### ISSUE TITLE
If the Whole BlocBuilder Got Rebuilt from Its Parent, It Will Be Based on the Last State Was Emitted to It before the Building

### ISSUE THREAD

**Issue by TN888** [felangel/bloc#2043] opened 2020-12-24 08:59 UTC
Let's say I've a BlocBuilder and I emitted to it a particular state.

```
BlocBuilder(
  builder: (context, state) {
    if (state is Initial) {
      return ...;
    } else if (state is Error) {
      return ...;
    }
  }
);
```

Now for some reason, the build method of its parent got called, the BlocBuilder will rebuild itself based on the last state was emitted to it, not on the initial one. 

```
Widget build(...) {
  ...
  BlocBuilder(...);
}
```

I see this as a problem, let's say I've emitted an error state, and for some reason the build method of its parent got called, that error state will be reflected again on the BlocBuilder after the building, not the initial one.

**Comment by felangel** [comment] 2020-12-30 04:07
Hi @TN888 👋 
Thanks for opening an issue and sorry for the delayed response!

This is working as intended. `BlocBuilder` can rebuild at any time (you should treat it like the `build` method of your widget) and each time it is called it will have the latest state of the bloc at the moment in time. The scenario you described should not be a problem and is likely only an issue because your `builder` has side-effects. `builder` should never have side-effects and should only return the appropriate widget based on the bloc state. If you wish to perform side-effects you should use `BlocListener` instead as `listener` is guaranteed to only be called once per state change. Hope that helps!

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-12-30 04:07 UTC
Labels: question
