### ISSUE TITLE
BlocBuilder not being triggered on state change

### ISSUE THREAD

**Issue by spidgorny** [felangel/bloc#745] opened 2019-12-26 18:37 UTC
I've followed the tutorial: [Flutter NoSQL Database – SEMBAST Tutorial (w/ BLoC)](https://resocoder.com/2019/04/06/flutter-nosql-database-sembast-tutorial-w-bloc/)
I've made adjustments to make it compatible with Bloc v2.

I can see that my states change, but BlocBuilder does not react on the changes - the UI is not being updated.

Spent hours googling trying to find the reason. Please help.

Reproducible code: https://github.com/spidgorny/flutter_teacher_logbook

**Comment by felangel** [comment] 2019-12-27 05:11
Hi @spidgorny 👋 
Thanks for opening an issue!

I opened a [pull request](https://github.com/spidgorny/flutter_teacher_logbook/pull/1) to fix several problems in your application. The root cause was you weren't using `Equatable` properly and setting the props to the actual `Fruit` property. Also, `Fruit` itself was not extending `Equatable`.

Closing for now but feel free to comment if you have additional questions 👍

**Closed by felangel** 2019-12-27 05:11 UTC
Labels: investigating
