### ISSUE TITLE
something went wrong with firebase auth and bloc

### ISSUE THREAD

**Issue by gtxgat** [felangel/bloc#516] opened 2019-09-15 00:53 UTC
**Describe the bug**
I was using your article on medium with(  flutter_bloc: ^0.11.0 ) and every thing was excellent.
But today I try to use your article which depend on (  flutter_bloc: ^0.21.0 ). And When app start the screen still white.
I do every thing twice and same problem

**Screenshots**
** the error **
```
Installing build\app\outputs\apk\app.apk...
E/flutter (21440): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
E/flutter (21440): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
E/flutter (21440): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
E/flutter (21440): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:73:7)
E/flutter (21440): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:86:4)
E/flutter (21440): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
E/flutter (21440): #3      MethodChannel.setMethodCallHandler (package:flutter/src/services/platform_channel.dart:368:5)
E/flutter (21440): #4      new FirebaseAuth._ (package:firebase_auth/src/firebase_auth.dart:15:13)
E/flutter (21440): #5      FirebaseAuth.instance (package:firebase_auth/src/firebase_auth.dart:25:53)
E/flutter (21440): #6      FirebaseAuth.instance (package:firebase_auth/src/firebase_auth.dart:25:29)
E/flutter (21440): #7      new UserRepository (package:logintest/bloc_other/user_repository.dart:10:54)
E/flutter (21440): #8      main (package:logintest/main.dart:15:40)
E/flutter (21440): #9      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:229:25)
E/flutter (21440): #10     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (21440): #11     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (21440): #12     _runZoned (dart:async/zone.dart:1516:10)
E/flutter (21440): #13     runZoned (dart:async/zone.dart:1500:12)
E/flutter (21440): #14     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:221:5)
E/flutter (21440): #15     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
E/flutter (21440): #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
E/flutter (21440): 
Syncing files to device SM G975F...
Lost connection to device.
```

```
**Logs **
Analyzing logintest...
No issues found! (ran in 4.4s)
```

```
[√] Flutter (Channel master, v1.10.3-pre.39, on Microsoft Windows [Version 10.0.18362.356], locale en-US)
    • Flutter version 1.10.3-pre.39 at C:\src\flutter
    • Framework revision 0ef89bb969 (2 hours ago), 2019-09-14 15:34:29 -0700
    • Engine revision 00c8941dae
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 a554c8be6b)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Abdalla\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2
    • Flutter plugin version 38.2.4
    • Dart plugin version 192.6262.13

[√] Connected device (1 available)
    • SM G975F • R58M22SXNAH • android-arm64 • Android 9 (API 28)

• No issues found!
```

```
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+4
  cloud_firestore: ^0.12.9+1
  google_sign_in: ^4.0.7
  flutter_bloc: ^0.21.0
  equatable: ^0.2.0
  meta: ^1.1.6
  font_awesome_flutter: ^8.4.0

```
**Additional context**

**Comment by felangel** [comment] 2019-09-15 01:58
Hi @gtxgat 👋 
Thanks for opening an issue!

This is a duplicate of https://github.com/felangel/hydrated_bloc/issues/17. Hope that helps 👍

**Closed by felangel** 2019-09-15 01:58 UTC
Labels: duplicate
