### ISSUE TITLE
[Question] BlocProvider within BlocBuilder

### ISSUE THREAD

**Issue by MaxAuer** [felangel/bloc#2095] opened 2021-01-18 10:57 UTC
Hey,

is it possible to provide a `Cubit` within a `BlocBuilder` when the Builder manages the Data that is provided to a `Cubit`. 

To make it more clear, this is the basic Setup:

```
BlocBuilder<ACubit, AState>(
   builder: (context, state) {
      if(state is AStateNewFocusObject){
         return BlocProvider(
            create: (context) => BCubit(state.focusObject),
            child: BView(
               onComplete: () => context.read<ACubit>().getNextFocusObject(),
            );
      }
      return _buildError();
   }
),
```

The UI in `BView` does not update because the `BCubit` isn´t disposed. I know that I create a loop by changing Data from the `onComplete` callback.

Is there a pattern one should follow when a subview with a `Cubit` uses data from a parent `Cubit`? Can I dispose the current `BCubit` in this case? `BView` has a lot of logic in the `BCubit` that uses only that subset of Data. `ACubit` isnt responsible for the data manipulation. It just needs to know when it should supply the next blop of data.

**Comment by Mx-Tech** [comment] 2021-01-18 14:53
I'm new to state management using flutter_bloc. But I think the BlocProvider should be at least the parent referring to the BlocProvider/ BlocConsumer in the widget tree. Because BlocProvider is used to provide the bloc_data in any child of it. Here's a working example:
```
return WillPopScope(
      onWillPop: () async {
        Navigator.pop(context);
        return false;
      },
      child: Scaffold(
        appBar: CustomAppBar(titleWidget: TitleWidget(title: "Search", icon: titleIcon)),
        body: BlocProvider<SearchCubit>(
          create: (context) => SearchCubit(),
          child: BlocConsumer<SearchCubit, SearchState>(
            listener: (context, state) {
              // here navigation etc.
            },
            builder: (context, state) {
              log.d(state.toString());
              if (state is SearchInitial) {
                final searchCubit = BlocProvider.of<SearchCubit>(context);
                searchCubit.getClubs();
              } else if (state is SearchLoading) {
                return TennisLoading();
              } else if (state is SearchLoaded) {
                return SearchClubsBody(clubs: state.clubs);
              } else if (state is SearchError) {
                return Container(
                  child: Text("Error"),
                );
              }
              return Container();
            },
          ),
        ),
      ),
    );
```
Using BlocConsumer instead of BlocBuilder reduces the boilerplate code as the Consumer directly offers a listener. While using BlocBuilder you have to wrap it in a BlocListener. The advantage of the listener is, that it is called only once per state change and not every time the build function of the widget is called.

Also context.read is deprecated (I think) so you should upgrade to BlocProvider.of<>(context);

I think it could work if you would use something like this:
```
BlocProvider<ACubit>(
          create: (context) => ACubit(),
          child: BlocConsumer<ACubit, AState>(
            listener: (context, state) {
                   // here navigation etc.
               },
               builder: (context, state) {
                  if (state is AStateNewFocusObject) {
                     return BlocProvider<BCubit>(
                        child: BlocConsumer<BCubit, BState>(...),
                     ),
                 },
            ),
          ),
        ),
```
P.S. I don't know if my answer can help you in any way. But I thought it can't be bad if I try to help you.

**Comment by MaxAuer** [comment] 2021-01-18 15:44
In essence your example is exactly what I am doing.
The `BlocConsumer` for `BCubit` is in the build function of `BView`

```
Widget build(BuildContext context) {
   return BlocConsumer<BCubit, BState>(...);
}
```

The problem I have is that this `Consumer` consumes the wrong `Cubit` because the old `BCubit` isn not disposed yet.

The `onComplete` callback calls a function in the `ACubit` that provides a new Object the `BView` works on. But because this all happens before the builder of `ACubit` completes, the old `BCubit` is still around. The Consumer uses the first instance of the type it can find (at least that is what I think it does) which is still the old `BCubit`.

The specific issue I have is definitely a fault in my architecture. I will try to find a cleaner solution for my problem. I think in a way its the same as having a `Cubit`(`Bloc`) that provides values to a list just that the ListView is not only a view but has its own `Cubit` because it has a complex business logic behaviour.

**Comment by Mx-Tech** [comment] 2021-01-19 07:00
That sounds really complex :grinning:. But as the flutter_bloc library also provides a MultiBlocProvider it should work fine to distinguish between the different providers.

Did you try to set the types of your providers to BlocProvider<ACubit> and BlocProvider<BCubit>? 
This is from the flutter_bloc documentation:
```
MultiBlocProvider(
  providers: [
    BlocProvider<BlocA>(
      create: (BuildContext context) => BlocA(),
    ),
    BlocProvider<BlocB>(
      create: (BuildContext context) => BlocB(),
    ),
    BlocProvider<BlocC>(
      create: (BuildContext context) => BlocC(),
    ),
  ],
  child: ChildA(),
)
```
As you already mentioned in your first post, you created a loop by triggering the ACubit to re-render. Isn't there a possibility to change the state on user input? I tried to think about a use case having such a chained provider. Something like, passing an URL to the BCubit to fetch data, maybe movie wallpapers, load them, then display them and after a few seconds, set BState to NextWallPaperState and then trigger the ACubit to provide the next set of data.

Maybe cubit isn't the right thing for you and you should go for bloc to make use of events to handle your states in a more differentiated way.

So, I hope you will find a solution or a more adapted user can help.

**Comment by felangel** [comment] 2021-01-19 17:29
Hi @MaxAuer 👋 
Thanks for opening an issue!

I agree that the root cause of this issue is most likely the current architecture but if you're still unsure of how to solve the issue can you please provide a link to a complete reproduction sample which illustrates the issue you're facing?

Closing for now but feel free to comment with additional information and a reproduction sample and I'm happy to continue the conversation 👍

**Closed by felangel** 2021-01-19 17:29 UTC
Labels: question
