### ISSUE TITLE
Website: Flutter Bloc Counter example has lint warning that the Bloc should have close method on dispose

### ISSUE THREAD

**Issue by ram231** [felangel/bloc#878] opened 2020-02-16 01:16 UTC
**Is your feature request related to a problem? Please describe.**

Example should be clear and have no errors/warnings when following the tutorial. Following the example tutorial code here
![image](https://user-images.githubusercontent.com/10434746/74597608-39523d80-509d-11ea-83ef-62e834d2837d.png)

![bloc_lint_warning](https://user-images.githubusercontent.com/10434746/74597581-ba5d0500-509c-11ea-96c2-eceae646e38d.png)

**Describe the solution you'd like**

In the [Counter Example](https://bloclibrary.dev/#/fluttercountertutorial). We are accessing the bloc inside of a build function, but the dart linter shouts to our IDE that the bloc must be closed. Of course, the simple solution would be in the `dispose` method.

**Describe alternatives you've considered**
It's just a minor change of documentation. Since it's just a simple tutorial. 
```dart

class _MyHomePageState extends State<MyHomePage> {
  /// Add bloc variable outside
  /// the build function.
  CounterBloc _counterBloc;

  @override
  void dispose() {
    /// Just like streams
    /// We should always close the event so that
    /// the dart linter won't shout to our IDE
    _counterBloc.close();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    _counterBloc = BlocProvider.of<CounterBloc>(context);
    return Scaffold(...);
   }
}
```

**Additional context**

**Comment by felangel** [comment] 2020-02-16 01:24
Hi @ram231 👋
Thanks for opening an issue!

This is a duplicate of https://github.com/felangel/bloc/issues/587.

This is a bug in the dart linter not in bloc. BlocProvider handles closing the bloc so it is not necessary to call close manually.

**Closed by felangel** 2020-02-16 01:24 UTC
