### ISSUE TITLE
State not updating in realtime.

### ISSUE THREAD

**Issue by shaan-saz** [felangel/bloc#2008] opened 2020-12-11 08:01 UTC
**Describe the bug**

The thing is when I change any field data in my firestore documents, data don't get updated in real-time.
It's updating the list and card object though, not rebuilding the state in ListTile.

**To Reproduce**

[Demo Repo](https://github.com/shaan-saz/reactive_bloc)
Check this repo for reproducing an issue.

**Expected behavior**

I want my ListTile data to be updated in realtime without rebuilding other list items.

**Comment by felangel** [comment] 2020-12-15 16:33
Hi @shaan-saz 👋 
Thanks for opening an issue!

I am unable to run the sample you provided because there is not GoogleServices file. Can you please provide a sample app which I can run locally to reproduce the issue? Thanks 🙏

**Comment by shaan-saz** [comment] 2020-12-16 17:08
@felangel Thanks for taking a look into this. I've added the file and also solved the issue by having a BlocListener on HomePageBloc.
`
if (state is HomePageUpdated) {
          state.cardList.singleWhere((element) => element.id == cardData.id) !=
                  cardData
              ? context.read<CardBloc>().add(
                    CardOpen(
                      cardData: state.cardList
                          .singleWhere((element) => element.id == cardData.id),
                    ),
                  )
              // ignore: avoid_print
              : print('No Changes in ${cardData.id}');
        }
      },`
      
It would be a lot more better if you recommend me a good way to accomplish this.

**Comment by shaan-saz** [comment] 2020-12-16 17:13
@felangel Thanks for taking a look into this. I've added the file and also solved the issue by having a BlocListener on HomePageBloc.
```dart
if (state is HomePageUpdated) {
          state.cardList.singleWhere((element) => element.id == cardData.id) !=
                  cardData
              ? context.read<CardBloc>().add(
                    CardOpen(
                      cardData: state.cardList
                          .singleWhere((element) => element.id == cardData.id),
                    ),
                  )
              // ignore: avoid_print
              : print('No Changes in ${cardData.id}');
        }
```
It would be a lot more better if you recommend to me a good way to accomplish this.

**Comment by felangel** [comment] 2021-01-06 06:14
@shaan-saz did you forget to push your changes? The reproduction sample still is missing a Google Services configuration file so I'm unable to run it locally.

**Comment by shaan-saz** [comment] 2021-01-06 14:07
@felangel Oops, I forgot to push it, sorry for that. Now you can check it.

**Comment by felangel** [comment] 2021-02-10 03:27
I am still unable to connect to firestore unfortunately :(

Closing for now but if you have a chance to provide a simple reproduction sample (ideally no dependency on firebase) I'm happy to take another look. Alternatively, if you haven't already you can [join the bloc discord server](https://discord.gg/Hc5KD3g) and we can setup a debug session 👍

**Closed by felangel** 2021-02-10 03:27 UTC
Labels: question, waiting for response
