### ISSUE TITLE
Populate the TextEditingController's text value while editing a form.

### ISSUE THREAD

**Issue by selvesandev** [felangel/bloc#1702] opened 2020-09-05 05:42 UTC
I am trying to create a edit form where my `TextField` is using `TextEditingController` to handle the values. To display the fetched api's data in the `TextField` with the controller i'm trying to follow these steps.

1) Make a api call to fetch the data when screen loads.

```
return MultiBlocProvider(
      providers: [
        BlocProvider(
          create: (context) => BusinessBloc(
              businessRepository: BusinessRepository(),
              categoryRepository: CategoryRepository())
            ..add(FetchBusinessCategories()),
        ),
      ],
      body: SellerProfileForm()
.....

// this fetches the categories and business info and update it to the state
```

2) The `TextField` in the `SellerProfileForm` widget is wrapped by the BlockBuilder to display the state's value.

```
BlocBuilder<BusinessBloc, BusinessState> buildBusinessTitleInput() {
    return BlocBuilder<BusinessBloc, BusinessState>(
      builder: (context, state) {
        if (state.business != null)
          _businessTitleCtrl.text = state.business.title;
        return InputFieldContainer(
          ctrl: _businessTitleCtrl,
          label: "Business Title",
          placeholder: "Business Title",
        );
      },
    );
  }

// Here the InputFieldContainer is a custom widget which has the `TextField` widget and works with controller
``` 

The `_businessTitleCtrl` has a event listener which is making call to a bloc event.

```
_businessTitleCtrl.addListener(() {
      _businessBloc.add(BusinessNameChanged(_businessTitleCtrl.text));
    });
// this is updating the state's `title` property from the business_bloc
```

Everything is working fine except that whenever the state is changed the `_businessTitleCtrl.text` get's reinitialized with the old value due to this.
```
if (state.business != null)
          _businessTitleCtrl.text = state.business.title;
```
Because of which the `TextField` initial value is not changing and stuck with the old value that was received from the api call.

**Please let me know what should be the correct way of handling such scenarios.**

I've also tried to update the `_businessTitleCtrl.text` inside the `initState` of `SellerProfileForm` but the `initState` receives a `null` state since the api call is still not complete when the screen loads.

Thank you

**Comment by felangel** [comment] 2020-09-05 14:49
Hi @selvesandev 👋 
Thanks for opening an issue!

Are you able to share a link to a sample app which illustrates the issue? I'm happy to open a pull request 👍

**Comment by felangel** [comment] 2020-09-09 02:46
Closing for now since there isn't a reproduction sample. Feel free to provide a link to a sample app and I'm happy to take a look and open a pull request with suggestions 👍

**Closed by felangel** 2020-09-09 02:46 UTC
Labels: question, waiting for response
