### ISSUE TITLE
Only one event fired (or considered). when adding event to Two different Bloc

### ISSUE THREAD

**Issue by Devlonoah** [felangel/bloc#3665] opened 2022-12-16 23:13 UTC
**Description**
I have two Bloc that I send events to on tapping on a widget.
However only one of the two blocs respond to the event.

Here is the code(snippet):
`GestureDetector
onTap: () {
BlocProvider.of<
ShowAudioControlCubit>( context)
[hideAudioControl();
BlocProvider.of<
AudioPlayerActionBloc> ( context)
add (PauseSoundEvent ( ) ) ;
}, child: Icon( Icons. close, sizes 34,
), // Icon
// GestureDetector
1)`

<img width="447" alt="Screenshot 2022-12-17 at 00 11 24" src="https://user-images.githubusercontent.com/55284278/208203478-c0a52827-895e-46aa-9062-beae3f35900d.png">

Is there something I can do to fix this issue?

**Comment by felangel** [comment] 2023-01-02 22:31
Hi @Devlonoah 👋 
Thanks for opening an issue!

Can you please provide a link to a GitHub repo or DartPad which contains a minimal reproduction sample? Thanks!

**Comment by felangel** [comment] 2023-01-12 14:15
Closing for now since there is no reproduction sample. Feel free to provide one and I’m happy to revisit this.

**Closed by felangel** 2023-01-12 14:15 UTC
Labels: question, waiting for response
