### ISSUE TITLE
chore: calling multiple events inside a widget that resets states to initial values

### ISSUE THREAD

**Issue by Micro-Prog** [felangel/bloc#4053] opened 2024-02-01 02:49 UTC
Hello,

I have set the flutter_bloc in my app which controls multiple states, the problems is that when calling two states inside my widget, the one of them resets the other one to {} value. is there any solution to overcome this? 
note that all states are read properly without any problem by looking at the console log, but one of them is reset after a while.

**Comment by felangel** [comment] 2024-02-01 03:21
Hi @Micro-Prog 👋 
Thanks for opening an issue!

It's really difficult to help without a link to a minimal reproduction sample that I can run locally to see the issue. Can you please provide a link to a minimal reproduction sample on either GitHub or DartPad? Thanks!

**Comment by Micro-Prog** [comment] 2024-02-01 10:35
> Hi @Micro-Prog 👋 Thanks for opening an issue!
> 
> It's really difficult to help without a link to a minimal reproduction sample that I can run locally to see the issue. Can you please provide a link to a minimal reproduction sample on either GitHub or DartPad? Thanks!


** 

sorry, i pushed the minimal version to my github: https://github.com/Micro-Prog/myapp-flutter
please note that the app is a testing app, i've created 2 dynamic pages called presentation (which reads data from bloc --> sqlite database and shows test types(grammer or vocab)) and levels (which reads data from database and shows language levels). the problems is that when reading 2 events inside the levels widget (), the state.testStructures is read correctly but then turns into {}. this causes the expanded tile in the levels screen to be 'no info'.
i tested many times and i noticed the issue is when calling 2 events in the initState() of the widget, and when calling one event, there is no problem.

**Comment by Micro-Prog** [comment] 2024-02-04 10:54
> Hi @Micro-Prog 👋 Thanks for opening an issue!
> 
> It's really difficult to help without a link to a minimal reproduction sample that I can run locally to see the issue. Can you please provide a link to a minimal reproduction sample on either GitHub or DartPad? Thanks!


is there any solution?

**Comment by tenhobi** [comment] 2024-10-30 16:41
@Micro-Prog so it seems your bloc is really confusing. For example, you have 3 getters 

```dart
  get defaultLevels => {};
  get testTypes => {};
  get testStructures => {};
```

but like 10 (not really important) classes to represent state while i.e. testStructures is only represented in one of them, that is DefaultTestTypesForAllGetSuccess.

That means when you add an event to your bloc, and if you emit some state like DefualtLevelsGetSuccess, it drops the previous state with testStructures which is now {} since DefualtLevelsGetSuccess only has defaultLevels. That is the reason why you keep loosing the data, because of the poor design.

The correct solution would be to either split bloc per one concern, if these getters/data are unrelated. Or just create Loding, Loaded, Error states with the data being all in Loaded and maybe potentially in Error as well if you still want to preserve old data from Loaded, but show some message in the meanwhile.

**Comment by felangel** [comment] 2024-11-19 05:12
Closing this for now but happy to continue the discussion if it's still an issue, thanks!

**Closed by felangel** 2024-11-19 05:12 UTC
Labels: question, waiting for response, needs repro info
