### ISSUE TITLE
[HELP] event does not trigger on my websocket bloc

### ISSUE THREAD

**Issue by b14cknc0d3** [felangel/bloc#2628] opened 2021-07-29 10:15 UTC
this is my bloc,that connect to ws
```class WsBloc extends Bloc<WsEvent, WsState> {
  WsBloc({
    @required this.channel,
  }) : super(WsStateConneting());
  WebSocketChannel channel;

  StreamSubscription _subscription;
  @override
  Stream<WsState> mapEventToState(
    WsEvent event,
  ) async* {
    if (event is WsEventConnect) {
      yield* _mapWsEventConnectToState(event);
    } else if (event is WsEventReceive) {
      yield* _mapEventReceiveToState(event.message);
    }
  }

  @override
  Future<void> close() {
    _subscription?.cancel();
    channel.sink?.close();
    return super.close();
  }

  Stream<WsState> _mapWsEventConnectToState(WsEventConnect event) async* {
    await _subscription?.cancel();
    channel.sink.add('{"command":"fetch_messages"}');
    yield WsStateConnected(channel.stream);
    try {
      _subscription = channel.stream.listen((response) {
        final parsedJson = json.decode(response);
        if (parsedJson.containKey("type")) {
          print("---type----");
          add(WsEventReceive(parsedJson));

          // return WsEventConnect();
        } else {
          add(WsEventReceive(response));
        }
      }, onError: () async {
        await Future.delayed(Duration(seconds: 3));
        add(WsEventConnect());
      });
    } catch (e) {
      yield WsStateConnectFail();
    }
  }

  Stream<WsState> _mapEventReceiveToState(Map<String, String> message) async* {
    if (message != null) {
      yield WsStateRecevied(message);
    }
  }
}
```
calling from blocprovider
```
return BlocProvider(
      create: (context) => WsBloc(channel: _channel),
      child: BlocBuilder<WsBloc, WsState>(
        builder: (context, state) {
          if (state is WsStateConneting) {
            // context.read<WsBloc>().add(WsEventConnect());
            var message = '{"command":"fetch_messages"}';
            context.read<WsBloc>().add(WsEventSend(message));
            return Container(
              child: Center(
                child: CircularProgressIndicator(),
              ),
            );
          } else if (state is WsStateConnected) {
            return Text("a");
          } else if (state is WsStateRecevied) {
            return Container(
              child: Text("state received"),
            );
          }
          return Container();
        },
      ),
    );
  }
```
**THIS IS LOG**
```

flutter: onCreate -- WsBloc
flutter: onEvent -- WsBloc, Sending Message : {"command":"fetch_messages"}

```

**Question why it does not change to WsSocketRecieved State**

**Comment by Gene-Dana** [comment] 2021-07-29 15:53
Hi there 👋🏼 Looking at your code it's tough to tell what the problem is, although generally state changes do not occur if the framework compares the before and present state and thinks they are the same.

This is why the examples go through the labors of defining models with equatable (or you can manually override the equality and hashcode) rather than working with primitives. 

I see this `  var message = '{"command":"fetch_messages"}';` and I wonder if perhaps this is the root of the problem

**Comment by felangel** [comment] 2021-08-07 21:48
Hi @b14cknc0d3 👋 
Thanks for opening an issue!

If you're still having trouble, can you please share a complete, minimal reproduction sample to illustrate the problem. The code you have shared is not enough to reproduce the issue locally.

On a side note, your `build` method should be `pure` (not contain any side effects). In the code you shared, you are adding an event (a side effect) as part of the `build` method (within the `BlocBuilder`).

**Comment by felangel** [comment] 2021-08-12 04:32
Closing for now since there is not a minimal reproduction sample. Feel free to comment with a link to a reproduction sample and I'm happy to take a closer look, thanks! 🙏

**Closed by felangel** 2021-08-12 04:32 UTC
Labels: question, waiting for response
