### ISSUE TITLE
State is not always sent to the BlocBuilder

### ISSUE THREAD

**Issue by angel1st** [felangel/bloc#1434] opened 2020-07-09 19:16 UTC
**Describe the bug**
`BlocBuilder` does not receive all of the states from time to time.

**Steps to reproduce it**
Below are the steps to reproduce it, using [the sample](https://github.com/angel1st/bloc_sample):
1. Set a breakpoint in `presentation/widgets/image_widget.dart` - line 85 - to catch `PlantStateImageSet` state
1. Set a breakpoint in `presentation/widgets/image_widget.dart` - line 90 - to catch `PlantStateImageIsLoading` state
1. Run the app in DEBUG mode - you can make it on Android emulator as well
1. When the app loads, click on FAB button => it opens `add_plant_page.dart`
1. Click on **camera** icon - it is located on the bottom left default image corner - it will open device camera
1. Make a picture and confirm => this will return to the app and will send `PlantEventNewImage` event - `presentation/widgets/image_widget.dart` - line 24
1. The app should break at line 90 `PlantStateImageIsLoading` => this is the correct behaviour
1. The app breaks at line 85 `PlantStateImageSet` state => this is the correct behaviour

You should repeat the last 4 steps several times and combine them with updating the name as well. At some point, step 7 (break at line 90) will be omitted, which is the BUG.

**Expected behavior**
When I `yield` a specific state e.g. `PlantStateImageIsLoading` I expect the state to be received by the respective `BlocProvider`, which is not the case always.

**Logs **
Run `flutter analyze` and attach any output of that command below.
>   info - The declaration '_imageFromBase64String' isn't referenced - lib\local_data_sources\plant_table.dart:8:9 - unused_element
   info - Close instances of `dart.core.Sink` - lib\main.dart:67:21 - close_sinks
   info - Unused import: 'dart:io' - lib\presentation\blocs\plant_event.dart:2:8 - unused_import
   info - Unused import: 'package:reminder/utils/global_translations.dart' - lib\presentation\pages\add_plant_page.dart:5:8 - unused_import
   info - Unused import: 'dart:math' - lib\presentation\widgets\add_plant_app_bar_widget.dart:1:8 - unused_import
   info - Close instances of `dart.core.Sink` - lib\presentation\widgets\add_plant_app_bar_widget.dart:24:21 - close_sinks
   info - Close instances of `dart.core.Sink` - lib\presentation\widgets\theme_brightness_picker_widget.dart:10:21 - close_sinks
   info - The declaration '_getHeight' isn't referenced - lib\repositories\admob_repository.dart:70:10 - unused_element

Paste the output of running `flutter doctor -v` here.
>[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18362.900], locale en-US)
    • Flutter version 1.17.5 at d:\DevTools\flutter
    • Framework revision 8af6b2f038 (9 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

>[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\DevTools\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_SDK_ROOT = D:\DevTools\Android\Sdk
    • Java binary at: D:\DevTools\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

>[√] Android Studio (version 4.0)
    • Android Studio at D:\DevTools\android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

>[!] Connected device
    ! No devices available

>! Doctor found issues in 1 category.

**Additional context**
Have a look at [the gist](https://gist.github.com/angel1st/986c038587273158c94b8de1eab868d4) and more specifically to lines 37 and 55 from **plant_bloc.dart** file - as you can see, the only workaround which somehow fixes the issue is if I add `await Future.delayed(Duration(milliseconds: 500));` - this gives some time and allows `BlocBuilder` to receive the state. I don't feel however this is the right way to handle the case.

**Comment by YeungKC** [comment] 2020-07-10 00:02
Hi, @angel1st 

Maybe you should add event first, then await? Because await will block.


https://gist.github.com/angel1st/986c038587273158c94b8de1eab868d4#file-image_widget-dart-L22

**Comment by angel1st** [comment] 2020-07-10 03:53
@YeungKC - actually, the event I am not able to receive is the one, I have sent/yielded prior to make `await`. To be more specific- I added `await` on line 37, to ensure `PlantStateImageIsLoading` on line 36, will be received on `BlocBuilder` end. If I remove `await` from line 37, I will NOT receive `PlantStateImageIsLoading` in `BlocBuilder` - `image_widget.dart` - line 51. In this `await` is the workaround, not the issue.

**Comment by angel1st** [comment] 2020-07-10 04:00
@YeungKC - the state I `yield` is `PlantStateImageIsLoading` and I did it from `plant_bloc.dart` - line 36, right after I recevied `PlantEventNewImage` event. 
I need `pickedFile` as a parameter of `PlantEventNewImage`, so I am not sure what do you mean.

**Comment by YeungKC** [comment] 2020-07-10 05:38
Hi, @adsonpleal 
This is my mistake, sorry.
could you provide your a minimal reproducible code sample?

**Comment by angel1st** [comment] 2020-07-10 07:16
@YeungKC - while I was preparing the sample, I found the issue :-). It was that `PlantStateImageIsLoading` didn't differ from the previous state - the `PlantStateImageIsLoading` implementation was wrong. Once I fixed it to:

```
class PlantStateImageIsLoading extends PlantState {
  const PlantStateImageIsLoading({@required PlantsCompanion plantsCompanion})
      : super(plantsCompanion: plantsCompanion);
  @override
  List<Object> get props => [plantsCompanion.image]; // <= the fix
}
```
everything works just as it should be.

**Comment by angel1st** [comment] 2020-07-10 08:04
@YeungKC - it seems my joy was a bit premature :-(. The issue is still present. Below are the steps to reproduce it, using [the sample](https://github.com/angel1st/bloc_sample):
1. Set a breakpoint in `presentation/widgets/image_widget.dart` - line 85 - to catch `PlantStateImageSet` state
1. Set a breakpoint in `presentation/widgets/image_widget.dart` - line 90 - to catch `PlantStateImageIsLoading` state
1. Run the app in DEBUG mode - you can make it on Android emulator as well
1. When the app loads, click on FAB button => it opens `add_plant_page.dart`
1. Click on **camera** icon - it is located on the bottom left default image corner - it will open device camera
1. Make a picture and confirm => this will return to the app and will send `PlantEventNewImage` event - `presentation/widgets/image_widget.dart` - line 24
1. The app should break at line 90 `PlantStateImageIsLoading` => this is the correct behaviour
1. The app breaks at line 85 `PlantStateImageSet` state => this is the correct behaviour

You should repeat the last 4 steps several times and combine them with updating the name as well. At some point, step 7 (break at line 90) will be omitted, which is the BUG.

**Comment by angel1st** [comment] 2020-07-10 14:45
@felangel - any chances you to have a look at this?

**Comment by felangel** [comment] 2020-07-11 03:07
Hi @angel1st 👋 
Thanks for opening an issue and sorry for the delay! Can you please share a link to a complete sample app which I can run locally to reproduce the issue? The gist appears incomplete and it would make it much easier for me to help you if you could provide a working sample, thanks! 🙏

**Comment by YeungKC** [comment] 2020-07-11 03:20
Hi, @angel1st 

The dart event loop prevents us from simply doing large calculations. If you use Isolate to run calculations, it should not block UI refresh.

**Comment by angel1st** [comment] 2020-07-11 04:03
@felangel - thanks for answering. I have added steps and a sample app yesterday during the discussion with @YeungKC. You can find them [here](https://github.com/felangel/bloc/issues/1434#issuecomment-656544534), but it seems they are not so obvious.
Hence I updated the issue with **Steps to reproduce section as well**.
Let me know, shall you need any further info.

**Comment by angel1st** [comment] 2020-07-11 04:07
@YeungKC - many thanks for the feedback. Any suggestions (backed up with an example preferably), how I can resolve the issue? Feel free to update the Github code I submitted yesteday. Thanks!

**Comment by YeungKC** [comment] 2020-07-11 14:22
Use isolates to do CPU intensive work.

**Comment by felangel** [comment] 2020-07-12 05:39
Hi @angel1st 👋 
Sorry for the delay! I just took a look and I'm not sure I understand the issue, if multiple states are yielded back-to-back faster than the rate at which the widgets are rebuilt, then `BlocBuilder` will not receive the intermediate state because the states changed too quickly. This is a duplicate of https://github.com/felangel/bloc/issues/173 and you can see this clearly in the following example:

```dart
import 'package:flutter/material.dart';

import 'package:bloc/bloc.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

void main() => runApp(CounterApp());

class CounterApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: BlocProvider(
        create: (_) => CounterBloc(),
        child: CounterPage(),
      ),
    );
  }
}

class CounterPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Counter')),
      body: BlocBuilder<CounterBloc, int>(
        builder: (_, count) {
          return Center(
            child: Text('$count', style: Theme.of(context).textTheme.headline1),
          );
        },
      ),
      floatingActionButton: Column(
        crossAxisAlignment: CrossAxisAlignment.end,
        mainAxisAlignment: MainAxisAlignment.end,
        children: <Widget>[
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 4.0),
            child: FloatingActionButton(
              child: const Icon(Icons.add),
              onPressed: () =>
                  context.bloc<CounterBloc>().add(CounterEvent.increment),
            ),
          ),
        ],
      ),
    );
  }
}

enum CounterEvent { increment }

class CounterBloc extends Bloc<CounterEvent, int> {
  CounterBloc() : super(0);

  @override
  Stream<int> mapEventToState(CounterEvent event) async* {
    switch (event) {
      case CounterEvent.increment:
        yield state + 1;
        yield state + 1;
        yield state + 1;
        break;
    }
  }
}
```

If you run it and tap the floating action button you will not see `BlocBuilder` rebuild with `1`, then `2, `then `3` because they happen faster than the widget can rebuild. Instead, you'll just see it jump to 3.

Hope that clarifies things!

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-07-12 05:39 UTC
Labels: question, waiting for response

**Comment by angel1st** [comment] 2020-07-12 06:19
@felangel - I respectfully disagree with your conclusion.
Have a look at [line 36](https://github.com/angel1st/bloc_sample/blob/master/lib/presentation/blocs/plant_bloc.dart#L36) - this is where I **yield** state `PlantStateImageIsLoading`. Then I have a part with image processing (lines 38 - 48), and after that at [line 49](https://github.com/angel1st/bloc_sample/blob/master/lib/presentation/blocs/plant_bloc.dart#L49), I **yield** state `PlantStateImageSet`. So I am pretty sure, there is plenty of time between these two states being yielded. 
I am more inclined to accept what @YeungKC [suggested above](https://github.com/felangel/bloc/issues/1434#issuecomment-656977318) - since the image processing work (lines 38 - 48) is CPU intensive, it blocs `buildScope`.
I would appreciate your opinion on the topic as well. 
Thanks!

**Comment by angel1st** [comment] 2020-07-12 10:31
If someone is interested - have a look at [the updated code](https://github.com/angel1st/bloc_sample/blob/master/lib/presentation/blocs/plant_bloc.dart#L47). As long as I moved the image processing to `isolate` (in fact I am using the simplified `compute` call), everything goes just well - each state is sent properly and received by the `BlocBuilder`.
Thanks, @YeungKC!

**Comment by felangel** [comment] 2020-07-12 15:15
> @felangel - I respectfully disagree with your conclusion.
> Have a look at [line 36](https://github.com/angel1st/bloc_sample/blob/master/lib/presentation/blocs/plant_bloc.dart#L36) - this is where I **yield** state `PlantStateImageIsLoading`. Then I have a part with image processing (lines 38 - 48), and after that at [line 49](https://github.com/angel1st/bloc_sample/blob/master/lib/presentation/blocs/plant_bloc.dart#L49), I **yield** state `PlantStateImageSet`. So I am pretty sure, there is plenty of time between these two states being yielded.
> I am more inclined to accept what @YeungKC [suggested above](https://github.com/felangel/bloc/issues/1434#issuecomment-656977318) - since the image processing work (lines 38 - 48) is CPU intensive, it blocs `buildScope`.
> I would appreciate your opinion on the topic as well.
> Thanks!

Ah sorry I overlooked that and didn’t have time to properly take a look due to the v6.0.0 work that is currently in progress. Thanks so much to @YeungKC for helping you out and glad everything is sorted out now 😊

**Comment by houssam15** [comment] 2025-02-20 16:55
I was missing to add State params in Equatable props , so Bloc can't find different between State instance because of missing params

```dart

part of 'file_uploader.bloc.dart';

enum FileUploaderStatus{initial,success,failure,progress,loading,picking}

final class FileUploaderState extends Equatable{

  const FileUploaderState({
    this.status = FileUploaderStatus.initial
  });


  final FileUploaderStatus status;

  FileUploaderState copyWith({
    FileUploaderStatus? status
  }) {
    return FileUploaderState(
      status: status ?? this.status
    );
  }


  @override
  List<Object> get props => [status]; //Fix : add status to props
}
```
