### ISSUE TITLE
emit doesn't called BlocListener in widget tests

### ISSUE THREAD

**Issue by irwansyahwii** [felangel/bloc#3790] opened 2023-04-06 08:03 UTC
**Description**
I have two cubits. `AppCubit` and `SplashCubit`. AppCubit responsible to emit any state changes to the UI and also run any code based on the changes of the state. I wrote an article [here](https://irwansyah.medium.com/writing-easy-to-understand-easy-to-test-and-robust-flutter-app-478035bb9706). In the UI I have a `BlocListener` that will respond based on the changes of the state:

```
class SplashScreen extends StatelessWidget {
  const SplashScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocListener<AppCubit, AppState>(
      listener: (context, state) {
        final navigationService = GetIt.I.get<NavigationService>();
        switch(state.runtimeType){          
          case AppStateDisplayMainScreen:
            navigationService.navigateTo(context, '/mainscreen');
            break;
          case AppStateDisplayLoginScreen:
            navigationService.navigateTo(context,'/loginscreen');
            break;
          case AppStateDisplayLoadingErrorScreen:
            navigationService.navigateTo(context,'/loadingerrorscreen');
            break;
        }
      },
```

Now the problem is, sometimes the emit is not triggering the code inside the `BlocListener` so when the state changed, the app failed to display the correct screen. This problem happened only when executing the code in the widget tests.

**Steps To Reproduce**

1. Go to https://github.com/irwansyahwii/flutter-solid-dependency-injection/tree/main/flutter_solid
2. Execute the widget tests
3. The emit for the second and third tests doesn't triggered the listeners

**Expected Behavior**
The `emit` calls should always triggered the code inside `BlocListener`

**Screenshots**

**Additional Context**

**Comment by Gene-Dana** [comment] 2023-04-08 15:30
Normally when the state management does not trigger events based on state changes it's because of mutation. 

I highly suggest the approach from the examples.

See how the Firebase Login tutorial manages the selection of routes depending on an AppStatus enum?

```
List<Page<dynamic>> onGenerateAppViewPages(
  AppStatus state,
  List<Page<dynamic>> pages,
) {
  switch (state) {
    case AppStatus.authenticated:
      return [HomePage.page()];
    case AppStatus.unauthenticated:
      return [LoginPage.page()];
  }
}
```

https://github.com/felangel/bloc/blob/master/examples/flutter_firebase_login/lib/app/routes/routes.dart

**Comment by irwansyahwii** [comment] 2023-04-09 01:31
I am sorry, I forgot to state that this bug happening in widget test but it is not happening in normal app run

**Comment by Gene-Dana** [comment] 2023-04-11 13:51
> I am sorry, I forgot to state that this bug happening in widget test but it is not happening in normal app run. I already updated the issue.

Being that you are using a separate dependency injection mechanism and a separate routing package perhaps you need to reach out to help from those communities

**Comment by felangel** [comment] 2023-04-15 19:17
@irwansyahwii can you please provide a link to a minimal reproduction sample? The sample you shared has a ton of unrelated code and it's not clear what the issue is. I ran the tests and they are all passing. It would be much more helpful if you could create a minimal reproduction sample with clear steps to reproduce the issue you're seeing, thanks!

**Comment by felangel** [comment] 2023-05-05 05:15
Closing for now but if this is still an issue then please provide a link to a minimal reproduction sample and I'm happy to take a closer look, thanks!

**Closed by felangel** 2023-05-05 05:15 UTC
Labels: question, waiting for response

**Comment by Nikzed** [comment] 2023-07-10 18:36
I have a simple onboarding event and this is not triggers listener with emit(state)

```
Future<void> _startOnboarding(StartOnboardingEvent event, Emitter emit) async {
    try {
      await Future.delayed(const Duration(milliseconds: 50));

      if (state is LoadedState || state is EmptyState) {
        isOnboarding = true;
      }
      emit(state);
    } catch (e) {
      print('Така ось ПОМИЛКА: $e');
    }
  }
```
I expect it to trigger listener in UI
