### ISSUE TITLE
docs: not enough information on event transformers

### ISSUE THREAD

**Issue by vogdb** [felangel/bloc#3520] opened 2022-09-02 08:42 UTC
Hi! It's not clear from the [API docs](https://pub.dev/documentation/bloc/latest/bloc/EventTransformer.html) how to write a custom transformer on your own. There are some examples in tutorials like [Infinite List](https://bloclibrary.dev/#/flutterinfinitelisttutorial?id=post-bloc) or in the [migration guide](https://verygood.ventures/blog/how-to-use-bloc-with-streams-and-concurrency). However it's not clear how to write a transformer without `bloc_concurrency` package.

Let's consider a typical example from the docs:

```dart
EventTransformer<E> throttleDroppable<E>(Duration duration) {
  return (events, mapper) {
    return droppable<E>().call(events.throttle(duration), mapper);
  };
}
```

- Why one can't just use `events.throttle(duration)` directly like this?

```dart
EventTransformer<E> throttleDroppable<E>(Duration duration) {
  return (events, mapper) {
    return events.throttle(duration);
  };
}
```

- What's the purpose of `mapper`?

Where can I find answers to these questions? Could've I missed some docs? Currently I've read all https://bloclibrary.dev.

**Comment by vinczebalazs** [comment] 2022-09-24 12:54
Looking for the exact same answer too.

**Comment by maxbaird** [comment] 2023-08-04 15:18
I have this exact issue myself. I'm wondering if I missed it in the documentation somewhere.

**Comment by vinczebalazs** [comment] 2023-08-04 22:16
@felangel any insights on this? Thanks

**Comment by c0pp1ce** [comment] 2023-08-15 16:17
If you check the implementation for the ``on<Event>`` method you can see that the ``mapper`` method that gets passed to transformers is where all the event handling logic happens (onEmit, handleEvent etc.). 

But ``mapper`` is not part of the ``bloc_concurrency`` package. You can write your own transformers without it, e.g. like this:

```dart
import 'package:bloc/bloc.dart';
import 'package:stream_transform/stream_transform.dart';

EventTransformer<Event> debounceSequential<Event>({
  Duration duration = const Duration(seconds: 1),
  bool leading = false,
  bool trailing = true,
}) {
  return (events, mapper) => events
      .debounce(
        duration,
        leading: leading,
        trailing: trailing,
      )
      .asyncExpand(mapper);
}
```

**Comment by felangel** [comment] 2023-10-14 21:29
This looks like a duplicate of #3248

**Closed by felangel** 2023-10-14 21:29 UTC
Labels: good first issue, documentation
