### ISSUE TITLE
use named routes with bloc

### ISSUE THREAD

**Issue by maxime-aubry** [felangel/bloc#1737] opened 2020-09-17 11:07 UTC
**Describe the bug**
Hello.
I try to use named routes with bloc. I use your example project **flutter_firebase_login**, and I modified it.
When I launch th application, the state is updated and I go to LoginPage, but the SplashPage is displayed.
I don't understand the reason.

**To Reproduce**
Launch the application.

Thanks

**Comment by felangel** [comment] 2020-09-18 05:15
Hi @maxime-aubry 👋 
Thanks for opening an issue!

Are you able to share a link to a sample app which reproduces the issue you're seeing? Thanks! 👍

**Comment by felangel** [comment] 2020-09-22 14:20
@maxime-aubry closing for now since there isn't enough information to reproduce the issue you're facing. Feel free to comment with a link to a sample app and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-09-22 14:20 UTC
Labels: question, waiting for response
