### ISSUE TITLE
Is there any known issue for web?

### ISSUE THREAD

**Issue by vinnytwice** [felangel/bloc#1125] opened 2020-05-05 16:20 UTC
@felangel Hi Angel, I hope you're all well. Here I am again with a new question :) 
I'm porting my app to the web as I see flutter_bloc is compatible (I'm on 3.2.0 still)  but in the login process after login in with Google (code is from your examples and tutorial ) the `AuthenticationBloc` doesn't yield the `Authenticated` state when running app on the web but it works properly on both Android and iOs devices. 
```
Stream<AuthenticationState> mapEventToState(
      AuthenticationEvent event) async* {
    if (event is StartApp) {
      yield* _startAppToState();
    }
    if (event is AppStarted) {
      yield* _mapAppStartedToState();
    } else if (event is LoggedIn) {
      print('AuthenticationBloc: LoggedIn event received');
      yield* _mapLoggedInToState();
    } else if (event is LoggedOut) {
      yield* _mapLoggedOutToState();
    }
  }
```

Before I put together a sample app I thought of asking you for known problems with the web version. Is there anything I should look at?
Thank you very much.
Cheers.

**Comment by vinnytwice** [comment] 2020-05-05 19:06
ok..forget it.. in release mode it works..
`flutter run -d chrome --release --web-hostname localhost --web-port 5000`

**Comment by felangel** [comment] 2020-05-05 19:20
Hi @vinnytwice 👋 
This is a duplicate of https://github.com/felangel/bloc/issues/957 👍

**Closed by felangel** 2020-05-05 19:20 UTC
Labels: duplicate
