### ISSUE TITLE
How to control multiple bloc builder on different screen ( buildwhen doesn't work everytime )

### ISSUE THREAD

**Issue by kartikmalhotra** [felangel/bloc#3691] opened 2023-01-18 12:11 UTC
**Description**

I have multiple BlocBuilder for the same bloc on different screens but the problem is if I add buildwhen to control which BlocBuilder should be called, on some screens build when is not getting called. 

**Desired Solution**

To have a full control over BlocBuilder buildwhen should be called every time

**Comment by bambinoua** [comment] 2023-01-18 12:51
I presume that you have nested `BlocBuilder`s? So to force inner `BlocBuilder` to call `bulder` the outer `BlocBuilder`'s `buildWhen` should allow this. 

I use few `BlocBuilder`s on the same widget with different `buildWhen` and all works fine.

To have a full control over BlocBuilder buildwhen should be called every time
`BlocBuilder` with default `buildWhen` (returns `true`) re-builds **each time when state is changed**.

**Comment by tenhobi** [comment] 2023-02-16 17:08
Hi @kartikmalhotra, could you provide a minimal reproduction sample?

**Comment by felangel** [comment] 2023-02-25 18:50
Closing for now since there is no minimal reproduction sample. Feel free to provide one and I'm happy to take a closer look 👍

**Closed by felangel** 2023-02-25 18:50 UTC
Labels: question, waiting for response

**Comment by erlangparasu** [comment] 2023-08-26 00:02
@kartikmalhotra 
i guess because the widget is not mounted yet
