### ISSUE TITLE
VSCode Intellisense suggestions do not work with state.copyWith() method

### ISSUE THREAD

**Issue by popay34** [felangel/bloc#2517] opened 2021-06-06 13:37 UTC
Hi Felix! I have been observing this problem for a very long time. 

This is test_state freezed class, that contains two variables: 'nickname' and 'emailAddress'.
![test_state](https://user-images.githubusercontent.com/60180239/120926123-45c03680-c6e4-11eb-8038-9bc380a9fad1.png)
This is bloc class with copyWith() method
![Скрин 1](https://user-images.githubusercontent.com/60180239/120926214-ac455480-c6e4-11eb-9857-6af91444d699.png)
This is bloc class without copyWith() method
![Скрин 2](https://user-images.githubusercontent.com/60180239/120926220-b10a0880-c6e4-11eb-827a-33f51cc977fd.png)
Why there are no Intellisense suggestions when i use state.copyWith() method?

**Comment by felangel** [comment] 2021-06-06 15:18
Hi @popay34 👋
Thanks for opening an issue!

Are you able to provide a minimal reproduction sample? It also looks like this is most likely an issue related to freezed and not bloc so I would suggested taking a look at issues in the freezed repo 👍

**Comment by KlausJokisuo** [comment] 2021-06-07 07:12
@popay34 What Flutter & Dart version you are running? I had similar problems with IntelliJ and it seems like it's fixed on the latest Stable.

**Comment by popay34** [comment] 2021-06-07 07:54
> @popay34 What Flutter & Dart version you are running? I had similar problems with IntelliJ and it seems like it's fixed on the latest Stable.

Dart version 2.12.3
Flutter version 2.0.6
I have been observing this problem since 2019, when i started to use Frezzed and Bloc.

**Comment by popay34** [comment] 2021-06-07 08:22
Yes. This seems to be a problem on the freezed side. Here another example. This is simple freezed class which is located outside of bloc.
![1](https://user-images.githubusercontent.com/60180239/120983490-6939be80-c782-11eb-9088-2e33ebf1f2e8.png)

**Comment by felangel** [comment] 2021-06-07 22:10
@popay34 have you [created an issue in freezed](https://github.com/rrousselGit/freezed/issues)? I think there's nothing we can do in the bloc repo to address this.

**Comment by popay34** [comment] 2021-06-08 08:00
> @popay34 have you [created an issue in freezed](https://github.com/rrousselGit/freezed/issues)? I think there's nothing we can do in the bloc repo to address this.

Yes , i have. Thank you!

**Closed** 2021-06-08 13:05 UTC
Labels: dependency, question, waiting for response
