### ISSUE TITLE
FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by MRANASSPRO** [felangel/bloc#397] opened 2019-07-06 17:24 UTC
**Describe the bug**
Execution of `flutter run` in VS code returns and Exception

**To Reproduce**
1. `flutter run`
2. Build output is : 
`Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug
 com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:`

**Screenshots**
![exep](https://user-images.githubusercontent.com/25827669/60759321-324d5200-a01b-11e9-87aa-beb4c575cd29.png)

**Additional context**
Running in Ubuntu 16.04.5 LTS, with an Android Emulator Pixel 3

**Comment by felangel** [comment] 2019-07-06 18:02
Hi @MRANASSPRO 👋 
Thanks for opening an issue!

Can you please provide detailed steps to reproduce the issue? Also, please make sure the issue is a bloc library issue and not a general flutter issue. Thanks! 👍

**Comment by felangel** [comment] 2019-07-07 21:58
Closing for now but feel free to comment with additional details and I'm happy to continue the conversation 👍

**Closed by felangel** 2019-07-07 21:58 UTC
Labels: question, waiting for response
