### ISSUE TITLE
Timeline inspecting 

### ISSUE THREAD

**Issue by amreniouinnovent** [felangel/bloc#442] opened 2019-07-29 05:04 UTC
I wonder if in the future we will have a bloc inspector tool like redux timeline tools?
I just ask for the possibility ..just a discussion if after 1 year it is possible we could have similar tools for bloc pattern.

Sample:
https://github.com/infinitered/reactotron

I ask a lot of questions because I feel you are a friendly developer and there is no other channel than GitHub issue for simple questions.

**Comment by felangel** [comment] 2019-07-30 00:34
Hi @amreniouinnovent 👋 
Thanks for opening an issue!

I believe this is a duplicate of #440 and the answer is yes 😄 

I'm wrapping up a couple of things currently and the dev tools will be my next focus 👍

**Closed** 2019-07-30 00:35 UTC
Labels: question
