### ISSUE TITLE
How to properly use `BlocConsumer`

### ISSUE THREAD

**Issue by AcarFurkan** [felangel/bloc#3119] opened 2022-01-07 15:22 UTC
when l use blocConsumer if l take context From blocConsumer,  MediaQuery.of(context).viewInsets.bottom doesnt work

**Comment by Gene-Dana** [comment] 2022-01-08 20:33
👋🏼 Hi there ! It's hard to give you much feedback without more context (pun intended). Do you have a minimal example / repo you can share with us?

**Comment by AcarFurkan** [comment] 2022-01-08 21:06
![2](https://user-images.githubusercontent.com/65075121/148659823-5d569f49-77b4-40e3-b274-341f5d0fa859.png)
when l use like this, l coundt take viewInsets.bottom correctly. everytime (when keyboard open) it returns 0.0 but
![3](https://user-images.githubusercontent.com/65075121/148659855-e0feb3c0-6898-4c09-a5b6-f0d82de3f4b4.png)
 when l use like this l could take. it return normal number. 
if you want you can try. 
(context.mediaquery isnt problem also l tried with Mediaquery.of(context). l think problem is blocconsumer dont hold viewinset  or something go wrong but also l tried with change consumer base code l coundt take viewinset.bottom value )

**Comment by felangel** [comment] 2022-01-10 00:32
Hi @AcarFurkan 👋 
Thanks for opening an issue!

It would be much easier to help if you could provide a link to a minimal reproduction sample (ideally a [DartPad](https://dartpad.dev)) and I'm happy to take a closer look, thanks!

**Comment by felangel** [comment] 2022-01-12 19:12
Closing for now since there is no link to a minimal reproduction sample. Feel free to provide one and I'm happy to take a closer look, thanks!

**Closed by felangel** 2022-01-12 19:12 UTC
Labels: question, waiting for response
