### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: In latest bloc version

### ISSUE THREAD

**Issue by newbieflutter** [felangel/bloc#3271] opened 2022-03-08 11:32 UTC
I have the following codes which used to work perfectly fine here is the bloc part.

```
@override
  Stream<EditApiState> mapEventToState(EditApiEvent event) async* {
    if (event is EditPassword) {
      try {
        yield EditApiLoadingState();
        var result = await apiCall(event.existingPassword, event.newPassword,
                event.confirmedPassword);

        if (result == null) {
            if (errorType == "AuthError") {
            yield EditApiStateAuthError(
              errorMessage: errorMessage,
            );
          } else if (errorType == "UnknownError") {
            yield EditApiStateUnknownError(
              errorMessage: errorMessage,
            );
          } else if (errorType == "Error4xx") {
            yield EditApiStateError4xx(
              errorMessage: errorMessage,
            );
          } else if (errorType == "GeneralError") {
            yield EditApiStateGeneralError(
              errorMessage: errorMessage,
            );
          }
        }
        if (result != null) {
          yield EditSuccessState(
            insertMessage: result.toString(),
          );
        }
      } catch (exception) {      
        yield EditApiStateUnknownError(
          errorMessage: exception.toString(),
        );
      }
    }
  }
```
Below is the apiCall function.
```
Future<dynamic> apiCall(String existingPassword, String newPassword,
      String confirmedPassword) async {
   var future = repository
        .editData(
      existingPassword: existingPassword,
      newPassword: newPassword,
      confirmedPassword: confirmedPassword,
    )
        .catchError((err, stackTrace) {
      if (err is AuthError) {
        errorType = "AuthError";
        errorMessage = err.message;
      } else if (err is UnknownError) {
        errorType = "UnknownError";
        errorMessage = err.message;
      } else if (err is Error4xx) {
        errorType = "Error4xx";
        errorMessage = err.message;
      } else {
        errorType = "GeneralError";
        errorMessage = "Something went wrong reason:unknown";
      }
    });
    cancelableCall = CancelableOperation.fromFuture(future);
    return cancelableCall.valueOrCancellation(null);
  }
```
Then recently I have upgrade with new bloc which requires the emit functions. So here is my latest function.

```
class EditApiBloc extends Bloc<EditApiEvent, EditApiState>
    with TransitionMixin {
  EditApiBloc(this.repository) : super(EditPasswordStill()) {
    on<EditPassword>((event, emit) async {
      try {
         emit(EditApiLoadingState());
        var result = await apiCall(event.existingPassword, event.newPassword,
                event.confirmedPassword)
            .then((value) { 
           emit(EditSuccessState(
            insertMessage: result.toString(),
          ));
})
            .catchError((err, stackTrace) {
          if (err is AuthError) {            
            emit(EditApiStateAuthError(
              errorMessage: errorMessage,
            ));
          } else if (err is UnknownError) {
            emit(EditApiStateUnknownError(
              errorMessage: errorMessage,
            ));
          } else if (err is Error4xx) {
             emit(EditApiStateError4xx(
              errorMessage: errorMessage,
            ));
          } else {
           emit(EditApiStateUnknownError(
              errorMessage: errorMessage,
            ));
          }
        });

      } catch (exception) {        
        emit(EditApiStateUnknownError(
          errorMessage: exception.toString(),
        ));
      }
    });
  }
```
Here is my latest apicall function

```
Future<dynamic> apiCall(String existingPassword, String newPassword,
      String confirmedPassword) async {
    var future = repository
        .editData(
      existingPassword: existingPassword,
      newPassword: newPassword,
      confirmedPassword: confirmedPassword,
    )
        .catchError((err, stackTrace) {
       if (err is AuthError) {       
        return Future.error(AuthError(err.message));
      } else if (err is UnknownError) {
        return Future.error(UnknownError(err.message));
      } else if (err is Error4xx) {      
        return Future.error(Error4xx(err.message));
      } else {
        return Future.error(UnknownError(err.message));
      }
    });

    cancelableCall = CancelableOperation.fromFuture(future);
    return cancelableCall.valueOrCancellation(null);
  }
```
First I have this error handler of Future.catchError must return a value of future's type?.

So my fix was in this in the bloc function 

```
var result = await apiCall(event.existingPassword, event.newPassword,
                event.confirmedPassword)
            .then((value) { 
           emit(EditSuccessState(
            insertMessage: result.toString(),
          ));
})
            .catchError((err, stackTrace) {
```
Then in the apicall function I had each return like this 
```
 if (err is AuthError) {       
        return Future.error(AuthError(err.message));
      } else if (err is UnknownError) {
        return Future.error(UnknownError(err.message));
      } else if (err is Error4xx) {      
        return Future.error(Error4xx(err.message));
      } else {
        return Future.error(UnknownError(err.message));
      }
```
But finally I still get this error now [ERROR:flutter[/lib/ui/ui_dart_state.cc]()(209)] Unhandled Exception: Instance of 'Error4xx'
I know the issue its expecting a future return but in that bloc I just got to emit and pass on. How can I resolve this issue in the latest version of the bloc?

**Comment by felangel** [comment] 2022-03-08 22:21
Hi @newbieflutter 👋 
Thanks for opening an issue!

Are you able to provide a link to a complete, minimal reproduction sample? It would be much easier to understand/help if I'm able to reproduce the issue locally, thanks! 🙏

**Comment by newbieflutter** [comment] 2022-03-09 13:27
Hi Felangel,
                    Sure I will create a mini application just with this form in it? Is that ok. How should I pass to you ?

**Comment by felangel** [comment] 2022-03-09 15:52
> Hi Felangel, Sure I will create a mini application just with this form in it? Is that ok. How should I pass to you ?

Yeah it'd be great if you could create the simplest possible project to illustrate the issue and provide a link to the GitHub repo. Please make sure the code compiles/runs so that I can run/debug it locally, thanks!

**Comment by newbieflutter** [comment] 2022-03-12 17:13
Hi Felangel,
                     I have managed to create a simple project here https://github.com/newbieflutter/testnewbloc. There is simple password based text input and just press the button edit you will enventualy need to wait for you to get network error then you will see the final error is printed with regards expecting a future return ...

**Comment by newbieflutter** [comment] 2022-03-15 17:42
Hi Felangel,
                    Would like to check with you is the simple project ok for you to test run ? Hopefully could run on your side.

**Comment by newbieflutter** [comment] 2022-03-29 05:55
Hi Felangel,
                    Any comments from you side will appreciate it. Thank you.

**Comment by felangel** [comment] 2022-06-06 16:03
Hi @newbieflutter sorry for the delayed response! Can you please provide detailed reproduction steps? Thanks!

**Comment by felangel** [comment] 2023-10-14 21:28
Closing this since it's quite old and has no minimal reproduction sample. Feel free to file a new issue with a reproduction sample if this is still an issue, thanks!

**Closed by felangel** 2023-10-14 21:28 UTC
Labels: question, investigating
