### ISSUE TITLE
question: does hydrated_bloc store all of the state changes?

### ISSUE THREAD

**Issue by mudlee** [felangel/bloc#3806] opened 2023-05-04 07:00 UTC
**Description**
I'm a noobie in this ecosystem and I'd like to use `hydrated_bloc` to auto-persist my actual states. What I observed that each and every time I emit a new state change, that will be **added** to the store, not updated.

**Expected Behavior**
I expect that the storage object contains only the actual state, not all historically.

**Screenshots**
Content of the hive seeing through mc viewer:
<img width="936" alt="Screenshot 2023-05-04 at 8 59 11" src="https://user-images.githubusercontent.com/1439334/236132796-0fb0a7d3-dc02-46d7-9dda-797e01a3ebd3.png">

**Additional Context**

This is one of the methods generated the update ot `productKeyStatus`, `checking` and other fields for example.

```dart
Future<void> setProductKey(String key) async {
    emit(state.copyWith(
      productKey: key,
      productKeyStatus: ProductKeyStatus.checking,
    ));
    try {
      final isValid = await _consoleApi.checkApiKeyValidity(key);
      emit(
        state.copyWith(
          productKeyStatus:
              isValid ? ProductKeyStatus.valid : ProductKeyStatus.invalid,
        ),
      );
    } on Exception {
      emit(state.copyWith(productKeyStatus: ProductKeyStatus.apiError));
    }
  }
```

**Comment by felangel** [comment] 2023-05-05 05:12
Hi @mudlee 👋 
Thanks for opening an issue!

The built-in `HydratedStorage implementation only stores the current states of each HydratedBloc. If you believe this is not happening can you please provide a minimal reproduction sample with detailed steps to reproduce the issue? Thanks! 🙏

**Comment by felangel** [comment] 2023-05-15 04:46
Closing for now since there aren't any actionable next steps. Feel free to provide a minimal reproduction sample and I'm happy to take a closer look, thanks 👍

**Closed by felangel** 2023-05-15 04:46 UTC
Labels: bug, question, waiting for response
