### ISSUE TITLE
fix: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4269 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true. in And      roid when I use lazy = false in BlocProvaider

### ISSUE THREAD

**Issue by alanfg120** [felangel/bloc#3045] opened 2021-12-05 22:42 UTC
**Description**
when I enable lazy in false of the BlocProvaider in the main.dart, this exception is thrown, this only happens in Android and sometimes only

**Steps To Reproduce**

` BlocProvider<EmpresasBloc>(
             lazy: false,
             create: (context) => EmpresasBloc(repositorio: EmpresaRepositorio(),prefs:PreferenciasUsuario())..add(GetEmpresas(empresas: homeCubit!.state.usuario!.empresas)),
             ),`

**Comment by felangel** [comment] 2021-12-06 21:06
Hi @alanfg120 👋 
Thanks for opening an issue!

Can you please provide a link to a minimal reproduction sample? Thanks!

**Comment by felangel** [comment] 2021-12-09 15:17
Closing for now since there is no reproduction sample. Feel free to comment with a link to a minimal reproduction sample and I'm happy to take a closer look 👍

**Closed by felangel** 2021-12-09 15:17 UTC
Labels: bug, question, waiting for response
