### ISSUE TITLE
fix: HydratedBloc clear is working but I can not remove the data in the state

### ISSUE THREAD

**Issue by data987** [felangel/bloc#3436] opened 2022-07-16 22:37 UTC
**Description**
Hi felangel, I'm trying to use different approaches to clean the cache but nothing works and I don't know if i'm doing something wrong

**Steps To Reproduce**

1. the first attempt into a widget to clean:

``` dart
onPressed: () async {
    context.read<LoginBloc>().add(UserLogout());
    context.read<LoginBloc>().clear();
},
``` 

2. second attempt into hydratedBloc class :

```dart
this.clear();
userCubit.clear();
```

3. third one 

```dart
await HydratedBlocOverrides.current?.storage.delete(this.storageToken);
```

It's like the storage is cleared because I reload the app and it keeps logging out but as soon as I log in the data is still there. 🤔 🤔 

**Additional Context**
here the inizialitation

```dart
void main() async {
  HydratedBlocOverrides.runZoned(
    () async {
      configureInjection(Environment.prod);
      runApp(MyApp());
    },
    blocObserver: BlocDelegate(),
    createStorage: () async {
      WidgetsFlutterBinding.ensureInitialized();
      return HydratedStorage.build(
        storageDirectory: await getTemporaryDirectory(),
      );
    },
  );
}
```

and here the `toJson` and `fromJson`

```dart
@override
  LoginState? fromJson(Map<String, dynamic> json) {
    try {
      if (json.isNotEmpty && json['church'] != null) {
        final model = model.fromJson(json);
        return (UserAuthenticated(elment: model));
      } else if (json.isNotEmpty && json['loggedIn']) {
        return UserAuthenticated(loggedIn: json['loggedIn']);
      } else {
        return UserUnauthenticated();
      }
    } catch (_) {
      return null;
    }
  }

  @override
  Map<String, dynamic>? toJson(LoginState state) {
    if (state is UserAuthenticated) {
      return {'element': state.element?.toJson(), 'loggedIn': state.loggedIn};
    } else {
      return null;
    }
  }
```

**Comment by felangel** [comment] 2022-08-06 05:32
Hi @data987 👋 
Thanks for opening an issue!

Can you please share a link to a minimal reproduction sample? It's hard to say what the issue is without being able to reproduce it locally. In general, if you want to clear the cache for a specific bloc, calling `clear` should work. I'm guessing the problem is you're calling `clear` and then another state change occurs and the new state is cached immediately.

You probably want to have a way to "reset" the state in addition to calling `clear` since clear just clears the cache:

```dart
/// In the widget
context.read<LoginBloc>().add(UserLogout());
```

```dart
/// In the bloc
this.clear();
emit(LoggedOut());
```

Hope that helps!

**Comment by felangel** [comment] 2022-08-13 16:08
Closing for now since there doesn’t appear to be any actionable next steps. Feel free to comment with any follow up questions and I’m happy to continue the conversation 👍

**Closed by felangel** 2022-08-13 16:08 UTC
Labels: question, waiting for response
