### ISSUE TITLE
Using bloc_test I have the next error: Bad state: Mock method was not called within when(). Was a real method called?

### ISSUE THREAD

**Issue by AyadLaouissi** [felangel/bloc#2133] opened 2021-02-06 20:45 UTC
**Describe the bug**
I'm using flutter_bloc and works fine in my app, but I'm having some issues using bloc_test and Mockito. I have a bloc that has a use case dependency and I'm creating a mock of the Use Case with values to test it with and passing the mock use case to the bloc and get the next error when executing the test "Bad state: Mock method was not called within when(). Was a real method called?".

**To Reproduce**
When I run my test fails with: "Bad state: Mock method was not called within when(). Was a real method called?".

**Expected behavior**
I expect to be able to run my test and can test the different outputs of the tests to be able to test my app.

**Logs **
No errors
Paste the output of running `flutter doctor -v` here.
flutter doctor -v

[✓] Flutter (Channel dev, 1.26.0-17.1.pre, on Linux, locale es_ES.UTF-8)
    • Flutter version 1.26.0-17.1.pre at /home/ayad/snap/flutter/common/flutter
    • Framework revision c40e5294dd (hace 8 días), 2021-01-29 08:44:18 -0800
    • Engine revision 5d3477eab4
    • Dart version 2.12.0 (build 2.12.0-259.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/ayad/Android/Sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 81.0.4044.138

! Doctor found issues in 2 categories.

**Additional context**

My pubspec.yaml

```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^6.1.1
  get_it: ^5.0.6
  dio: ^3.0.10
  rxdart: ^0.25.0
  dartz: ^0.9.2
  equatable: ^1.2.5
  pedantic: ^1.8.0+1
  intl: ^0.16.1
  provider: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.3.0
  bloc_test: ^7.0.0
  mockito: ^4.1.1
```

Here is my mock use case
```
class MockGetIssues extends Mock implements GetIssues {
  Future<Either<AppError, List<IssuesModel>>> call(
      PageParams pageParams) async {
    return Future.delayed(
      const Duration(
        milliseconds: 100,
      ),
      () => Right(
        [
          IssuesModel(id: 1),
          IssuesModel(id: 2),
          IssuesModel(id: 3),
          IssuesModel(id: 4),
          IssuesModel(id: 5),
          IssuesModel(id: 6),
          IssuesModel(id: 7),
          IssuesModel(id: 8),
          IssuesModel(id: 9),
          IssuesModel(id: 10),
          IssuesModel(id: 11),
          IssuesModel(id: 12),
          IssuesModel(id: 13),
          IssuesModel(id: 14),
          IssuesModel(id: 15),
          IssuesModel(id: 16),
          IssuesModel(id: 17),
          IssuesModel(id: 18),
          IssuesModel(id: 19),
          IssuesModel(id: 20),
        ].getRange(0, pageParams.take),
      ),
    );
  }
}
```

Here is my bloc class
```
class IssuesBloc extends Bloc<IssuesEvent, IssuesState> {
  final GetIssues _getIssues;

  IssuesBloc(this._getIssues) : super(IssuesInitial());

  @override
  Stream<IssuesState> mapEventToState(
    IssuesEvent event,
  ) async* {
     // here is my action code that is not the necesary for the issue because it works as expected in my app
    }
}
```

This is my test where the issues are showing and I have tried 3 different ways and returns the same exception
```
void main() {
  group('IssuesBloc', () {
    IssuesBloc issuesBloc;
    MockGetIssues mockGetIssues;

    setUpAll(() {
      mockGetIssues = MockGetIssues();
      issuesBloc = IssuesBloc(mockGetIssues);
    });

    tearDown(() {
      issuesBloc.close();
    });

    test('when: emits [IssuesInitial(), IssuesLoadedState(),] when successful', () {
      when(mockGetIssues(PageParams()))
          .thenAnswer((value) async => null);
      final bloc = IssuesBloc(mockGetIssues);
      bloc.add(LoadIssues());

      emitsExactly(bloc, [
        IssuesInitial(),
        isA<IssuesLoadedState>(),
      ]);
    });

    test("whenListen: emits [IssuesInitial(), IssuesLoadedState(),] when successful", () {

      whenListen(
        issuesBloc,
        Stream.fromIterable([IssuesInitial]),
      );

      expectLater(
        issuesBloc,
        emitsInOrder(
          [
            IssuesInitial,
            isA<IssuesLoadedState>()
          ],
        ),
      );
    });

    blocTest(
      'emits [IssuesInitial, isA<IssuesLoadedState>()]',
      build: () {

        whenListen(
            issuesBloc,
            Stream.fromIterable(
              [IssuesInitial, isA<IssuesLoadedState>()],
            ));

        return issuesBloc;
      },
      act: (bloc) => bloc.add(LoadIssues()),
      expect: [IssuesInitial, isA<IssuesLoadedState>()],
    );
  });
}
```

**Comment by felangel** [comment] 2021-02-08 05:47
Hi @AyadLaouissi 👋 
Thanks for opening an issue!

`whenListen` only works on `MockBloc` instances. In this case, `IssuesBloc` is a real bloc so you can't use `whenListen` and you also shouldn't use it because you should be testing the actual functionality of the real bloc instance when you are unit testing your bloc.

Typically, `whenListen` should be used when writing widget tests for widgets which rely on blocs so that you can mock the bloc state stream. When unit testing blocs you should only be mocking the bloc's dependencies and avoid `whenListen`.

I would recommend removing the `whenListen` from your `blocTests` 👍 

Closing for now and hope that helps!

Feel free to comment with additional questions and I'm happy to continue the conversation 😄

**Closed by felangel** 2021-02-08 05:47 UTC

**Comment by ron-brosh** [comment] 2021-11-17 12:58
@felangel Thanks for the answer, and @AyadLaouissi for the question!

I have a question on the same subject but slightly different.

I like to use mocked models in my tests to keep the tests robust and "correct".
For example if I test a use case that returns a list of items I don't want to test for every optional outcome list e.g. empty list, one item in a list, 100 items in a list, etc..
Instead I mock the list and assert that the mocked list is returned from the use case.

For example, using bloc, this is my test:
```
test("getCategories SHOULD emit correct states WHEN use case succeeds", () async {
   final categories = CategoryListMock();
   when(() => getPracticeCategoriesUseCase())
        .thenAnswer((invocation) => Future.value(ResultState.success(categories)));
    
   sut.add(PracticeCategoriesEvent.getCategories());

   expectLater(
        sut.stream,
        emitsInOrder(<PracticeCategoriesState>[
          PracticeCategoriesState.loading(),
          PracticeCategoriesState.success(categories),
        ]));
  });
```

You can see that I'm mocking the expected result (list of category items). 
By doing so I don't need to write any other unit test because this test cover all possible happy path scenarios.

Before playing with Bloc I had the same logic using value notifier and testing it this way was easy.

But when I run the above test I get this error:
`type 'Null' is not a subtype of type 'int'`

I think that it's caused by the bloc class trying to check equality on the mocked object.

Is there another way to assert with mocked results? I also tried to use blocTest and it's the same error.
It would be really nice if it's possible because sometimes the models can be pretty big and with nested of nested values..

Thanks!
