### ISSUE TITLE
Bloc VSCode update new Equatable v6

### ISSUE THREAD

**Issue by amreniouinnovent** [felangel/bloc#562] opened 2019-10-10 10:13 UTC
I found that the extension for VSC is not matched with the new changes in the Equatable library 
Could you check it to support Equatable V6?
Thanks a lot
https://marketplace.visualstudio.com/items?itemName=FelixAngelov.bloc

https://github.com/felangel/equatable/blob/master/doc/migration_guides/migration-0.6.0.md

**Comment by felangel** [comment] 2019-10-10 13:11
Hi @amreniouinnovent 👋 
Thanks for opening an issue!

Can you provide more information? What is not matching?

**Comment by felangel** [comment] 2019-10-10 16:41
@amreniouinnovent what version of vscode are you using and can you provide reproduction steps? Are you sure you have the latest version of the extension?

**Comment by felangel** [comment] 2019-10-11 15:48
@amreniouinnovent I'm closing this for now as I was unable to reproduce and I suspect you're using an outdated version of the VSCode extension.

Feel free to comment with additional information and I'm happy to reopen the issue 👍

**Closed by felangel** 2019-10-11 15:48 UTC
Labels: question, waiting for response

**Comment by amreniouinnovent** [comment] 2019-10-12 09:10
it works fine..my teammates he didn't update his extensions 
Thanks a lot
