### ISSUE TITLE
refactor: adding child parameter to bloc consumer/listener/builder

### ISSUE THREAD

**Issue by Abdurrahman98XX** [felangel/bloc#3745] opened 2023-02-19 14:34 UTC
**Description**

updating `BlocConsumer/Listener/Builder` to use child parameter that's found in `Consumer` in provider package

it would help for fine grained optimization as i know it don't rebuild the given child as it is just doesn't use/benifit bloc 

or completely remove provider dependency and use `InheritedNotifer` and refactor our `BlocConsumer/Listener/Builder` to be a wrapper around `AniamtedBuilder` that also provider a child

**Comment by felangel** [comment] 2023-02-19 15:52
Hi @Abdurrahman98XX 👋
Thanks for opening an issue!

Can you please provide more context regarding your use case (ideally with a minimal reproduction sample)? Thanks!

**Comment by Abdurrahman98XX** [comment] 2023-02-19 17:36
```dart
BlocBuilder<BlocA, BlocAState>(
  builder: (context, state, **child**) { // child is nullable
    return Scaffold(
      appBar: AppBar(title: Text(state.text)),
      body: child,
    );
  },
  child: Column(children:[...]), // new param that make given widget not rebuild
);
```
references: 

https://pub.dev/documentation/provider/latest/provider/Consumer-class.html#:~:text=widgets%20than%20needed.-,Here%27s%20an%20example,-%3A

https://api.flutter.dev/flutter/widgets/AnimatedBuilder-class.html#:~:text=Using%20this%20pre%2Dbuilt%20child%20is%20entirely%20optional

**Comment by tenhobi** [comment] 2023-02-20 16:48
The Consumer widget from the Provider package indeed allows this. It can also make some optimization because you don't rebuild the whole subtree, but only the wrapper, if that is your case, and the child can stay constant. 🤔 Yet it adds another "complexity" by having a third parameter.

But this is an API-breaking request, so I would be careful if or when we would release such a change.

**Comment by felangel** [comment] 2023-04-15 18:44
> @felangel here is what i mean
> 
> ### **imaginable BlocBuilder**
> ```dart
> BlocBuilder<BlocA, BlocAState>(
>   builder: (context, state, **child**) { // child is nullable
>     return Scaffold(
>       appBar: AppBar(title: Text(state.text)),
>       body: child,
>     );
>   },
>   child: Column(children:[...]), // new param that make given widget not rebuild
> );
> ```
> 
> references:
> 
> [Consumer - Provider](https://pub.dev/documentation/provider/latest/provider/Consumer-class.html#:~:text=widgets%20than%20needed.-,Here%27s%20an%20example,-%3A)
> 
> [AnimatedBuilder - Material](https://api.flutter.dev/flutter/widgets/AnimatedBuilder-class.html#:~:text=Using%20this%20pre%2Dbuilt%20child%20is%20entirely%20optional)

If you want to prevent unnecessary rebuilds in that scenario you can decompose the widget further and only use the `BlocBuilder` for the necessary sub-tree like:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: BlocProvider(
        create: (context) => CounterCubit(),
        child: const MyHomePage(),
      ),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: const MyAppBar(),
      body: Center(
        child: Column(
          children: const [Text('child 1')],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.add),
        onPressed: () => context.read<CounterCubit>().increment(),
      ),
    );
  }
}

class MyAppBar extends StatelessWidget implements PreferredSizeWidget {
  const MyAppBar({super.key});

  @override
  Size get preferredSize => const Size.fromHeight(kToolbarHeight);

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<CounterCubit, int>(
      builder: (context, state) {
        return AppBar(
          title: Text(state.toString()),
        );
      },
    );
  }
}

class CounterCubit extends Cubit<int> {
  CounterCubit() : super(0);

  void increment() => emit(state + 1);
}
```

Closing for now since I don't think introducing a breaking change is justified in this case. Feel free to comment with additional thoughts/questions and I'm happy to continue the conversation 👍

**Closed by felangel** 2023-04-15 18:44 UTC
Labels: question, waiting for response, refactor

**Comment by Abdurrahman98XX** [comment] 2023-04-17 18:23
decomposition is not always available, take a look
the `Container` is a true `StatelessWidget` but it will be rebuilt 60 times a second!
this is a simple animation, scaling up would be miserable 

```dart
.
.

late final AnimationController _controller = AnimationController(
    duration: const Duration(seconds: 10),
    vsync: this,
  )..repeat();

.
.

@override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: _controller,
      child: Container(
        width: 200.0,
        height: 200.0,
        color: Colors.green,
        child: const Center(
          child: Text('Whee!'),
        ),
      ),
      builder: (BuildContext context, Widget? child) {
        return Transform.rotate(
          angle: _controller.value * 2.0 * math.pi,
          child: child,
        );
      },
    );
  }
```
