### ISSUE TITLE
fix: TimeoutException when running tests with stream in close method

### ISSUE THREAD

**Issue by kevynrocha** [felangel/bloc#3692] opened 2023-01-19 02:58 UTC
**Description**

If any stream is used in the close method of the `bloc`, Timeout occurs when running tests:

**Steps To Reproduce**

1. Create `cubit`:
```dart
class ExampleState {}

class ExampleCubit extends Cubit<ExampleState> {
  ExampleCubit() : super(ExampleState());

  @override
  Future<void> close() async {
    await stream.drain();
    return super.close();
  }
}
```

2. Run test:
```dart
void main() {
  late ExampleCubit cubit;

  setUp(() {
    cubit = ExampleCubit();
  });

  blocTest<ExampleCubit, ExampleState>(
    'emits',
    build: () => cubit,
    expect: () => [],
  );
}
```

3. Result:
```dart
00:50 +0 -1: emits [E]
  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds. See https://pub.dev/packages/test#timeouts
  dart:isolate  _RawReceivePortImpl._handleMessage
```

**Expected Behavior**
Return a valid test.

**Comment by tenhobi** [comment] 2023-02-21 11:36
Hi @kevynrocha, could you provide a minimal reproducible example?

**Comment by kevynrocha** [comment] 2023-02-22 05:14
Hi @tenhobi, you can use the example I described above.

**Comment by felangel** [comment] 2023-02-22 05:16
> Hi @tenhobi, you can use the example I described above.

It would be much easier to help if you could provide a link to a minimal reproduction sample that someone could clone and run to reproduce the issue locally. Thanks!

**Comment by kevynrocha** [comment] 2023-02-22 22:21
@tenhobi @felangel Of course, you can clone this repository:

```bash
https://github.com/kevynrocha/bloc_example
```

And run tests:

```bash
flutter test
```

The current result is:

```bash
TimeoutException after 0:00:30.000000: Test timed out after 30 seconds. See https://pub.dev/packages/test#timeouts
  dart:isolate  _RawReceivePort._handleMessage
```

#### Minimum flutter version must be 3.7.0

**Comment by karimkod** [comment] 2023-02-28 18:15
I have the same issue :/

**Comment by karimkod** [comment] 2023-03-01 11:59
This issue is due to the fact that you are subscribing to the stream with a `drain()` function which subscribes to the stream until it's closed. 
The close function of the `bloc` is called by `blocTest` after the act is done. But since there is a drain in there, the closing will just hang waiting for the close signal, which will never come. 
In a nutshell the code is equivalent to this : 
`import 'dart:async';

StreamController _streamController = StreamController<int>.broadcast();

Future main() async {
  print("Start draining");
  await _streamController.stream.drain();
  print("Finished draining");
}
`
`drain` will never be done and so do main method. 

I see the need of draining the stream before closing it when the stream is finite. But for bloc streams, or any (infinite stream for that matter) I don't see any need to do so.

**Comment by felangel** [comment] 2023-03-06 05:38
Closing for now since there doesn't appear to be any actionable next steps. Feel free to comment with any follow-ups and I'm happy to continue the conversation 👍

**Closed by felangel** 2023-03-06 05:38 UTC
Labels: question, waiting for response
