### ISSUE TITLE
Events are not captured in mapEventToState function for Flutter Web

### ISSUE THREAD

**Issue by moniaS** [felangel/bloc#607] opened 2019-10-24 13:21 UTC
After specific action events are not captured anymore and new states are not emitted in mapEventToState method in bloc.

## Steps to reproduce the behavior:
1. I forked your project bloc. I was working only with flutter_firebase_login application.
2. I added web support using command: ‘flutter create .’ in the root of flutter_firebase_login application. 
3. I commented out all of the code related to cloud_firestore, firebase_auth and google_sign_in packages.
4. In login_bloc in _mapLoginWithCredentialsPressedToState method I replaced request to firebase auth with the following code:
`await Future.delayed(Duration(milliseconds: 1000), () {
       throw 'bloc';
});`
5. I started the app on web using Chrome browser.

## To reproduce the bug in app:
1. Enter valid but incorrect credentials in login and password form.
2. Submit the form.
3. The message that the login is failure should be displayed.
4. Submit the form again. Then the event LoginWithCredentialsPressed is dispatched, but it’s not captured in the mapEventToState function. You can also change something in the text fields and the events EmailChanged and PasswordChaned will be dispatched but they won’t be captured in mapEventToState method.
It happens only on Flutter Web because when I’m running the same application on mobile device then it’s working fine.

## Expected behaviour
After submitting form even if there was a failure I should be able to send events and receive new states.

### The output for flutter doctor:
```
flutter doctor -v
[√] Flutter (Channel master, v1.10.15-pre.218, on Microsoft Windows [Version 10.0.18362.418], locale pl-PL)
    • Flutter version 1.10.15-pre.218 at C:\src\flutter
    • Framework revision a817b4e6a4 (30 hours ago), 2019-10-23 03:14:06 -0400
    • Engine revision f0a2850b35
    • Dart version 2.6.0 (build 2.6.0-dev.8.1 17ed3cb5b3)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Monika\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Monika\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.5
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.2
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.8369

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.3
    • Flutter plugin version 40.2.4
    • Dart plugin version 192.7402

[√] VS Code (version 1.33.1)
    • VS Code at C:\Users\Monika\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.0.1

[√] Connected device (3 available)
    • HUAWEI VNS L21 • BUC4C16902008869 • android-arm64  • Android 7.0 (API 24)
    • Chrome         • chrome           • web-javascript • Google Chrome 78.0.3904.70
    • Web Server     • web-server       • web-javascript • Flutter Tools

! Doctor found issues in 3 categories.
```
The forked repository with reproduced bug is here: [https://github.com/moniaS/bloc](https://github.com/moniaS/bloc).

**Comment by felangel** [comment] 2019-10-24 14:16
Hi @moniaS 👋 
Thanks for opening an issue!

I believe this is a duplicate of https://github.com/felangel/bloc/issues/115. Have you tried running in release mode?

**Comment by moniaS** [comment] 2019-10-25 08:38
Now I tried running in release mode (`flutter run --release -d chrome`) and it's working. So there is a problem with debug mode.

**Comment by felangel** [comment] 2019-10-27 17:28
@moniaS I also re-tested the original issue after doing a `pub upgrade` and `pub run build_runner clean` and was unable to reproduce this so it seems like it was fixed.

`flutter doctor --verbose`

```sh
[✓] Flutter (Channel stable, v1.9.1+hotfix.6)
    • Flutter version 1.9.1+hotfix.6
    • Framework revision 68587a0916 (6 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0
```

**Closed by felangel** 2019-10-27 17:28 UTC
Labels: question, waiting for response

**Comment by dustin-graham** [comment] 2020-03-10 02:50
@felangel We're experiencing this same issue as we try and develop our flutter web project. in our case, we are catching an API error safely and yielding an error state in our bloc. After that point `mapEventToState` is never called again. We ran it in release mode and the problem goes away, but that's not a workable solution. Do you have any more information about this error and how we can work around it?

**Comment by felangel** [comment] 2020-03-10 04:19
@dustin-graham I've raised this issue with the Flutter team and you can follow/give it a 👍at https://github.com/flutter/flutter/issues/47858.
