### ISSUE TITLE
fix: MediaQuery.platformBrightnessOf(context) inside BlocBuilder not changing after theme changing at the platform (dark/light)

### ISSUE THREAD

**Issue by Oubi256** [felangel/bloc#3831] opened 2023-05-16 18:16 UTC
**Description**
MediaQuery.platformBrightnessOf(context) is not updated inside BlocBuilder, which causes themeMode.system to not work properly inside MaterialApp, causing the application theme to stop changing to system theme. 
If the check MediaQuery.platformBrightnessOf(context) is at a level above BlocBuilder-a, then the value changes as planned.

**Steps To Reproduce**

1. Define two themes and set themeMode to themeMode.system
2. Launch the application and switch the mode to the opposite (dark/light)
3. Return to the application and make sure the theme has not changed from dark to light or vice versa. To be sure, call the state update and again make sure that the topic has not changed.

**Expected Behavior**
The MediaQuery.platformBrightnessOf(context) inside the BlocBuilder should be updated on device theme change to reflect the current mode (dark/light).

**Additional Context**
```dart
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      designSize: const Size(1290, 2796), //1290 x 2796 //430 x 932
      builder: (BuildContext upperContext, _) {
        return MultiBlocProvider(
          providers: [
            BlocProvider<ThemeBloc>(
              create: (BuildContext context) => ThemeBloc()..add(const InitThemesEvent()),
            ),
          ],
          child: BlocBuilder<ThemeBloc, ThemeState>(
            builder: (context, state) {
              final ThemeData theme = ThemeData.light().copyWith(extensions: [state.tailorThemeMode.extension]);
              final ThemeData darkTheme = ThemeData.light().copyWith(extensions: [state.tailorThemeMode.extensionDark]);
              
              print("PLATFORM BRIGHTNESS ScreenUtilInit: ${MediaQuery.platformBrightnessOf(upperContext)}"); // WORKS WELL
              
              // NO CHANGES. Always shows the Brightness with which the app started and not changing anymore
              print("PLATFORM BRIGHTNESS BLOC: ${MediaQuery.platformBrightnessOf(context)}");
             
              return VRouter(
                title: 'CrtMinesweeper',
                theme: theme,
                darkTheme: darkTheme,
                themeMode: ThemeMode.system,
                debugShowCheckedModeBanner: false,
                showPerformanceOverlay: false,
                localizationsDelegates: context.localizationDelegates,
                supportedLocales: context.supportedLocales,
                locale: context.locale,
                mode: VRouterMode.history,
                initialUrl: "/home",
                onPop: (vRedirector) async {
                  vRedirector.stopRedirection();
                  print("STOP POP");
                },
                routes: [
                  VNester(
                    path: "/",
                    widgetBuilder: (Widget child) => ScreenScaffold(child: child),
                    nestedRoutes: [
                      VWidget(
                        path: 'home',
                        widget: const MenuScreen(),
                      ),
                    ],
                  ),
                ],
              );
            },
          ),
        );
      },
    );
  }

```

**Comment by AlexanderFarkas** [comment] 2023-05-18 14:26
Please, provide minimal reproducible example, which can be copy-pasted to reproduce the error.

**Comment by felangel** [comment] 2023-08-06 03:41
Closing this for now since there is no minimal reproduction sample.

**Closed by felangel** 2023-08-06 03:41 UTC
Labels: bug
