### ISSUE TITLE
fix: `Bloc` / `Cubit` shouldn't emit the first value if it is equal to the initial value

### ISSUE THREAD

**Issue by maRci002** [felangel/bloc#3514] opened 2022-08-29 13:11 UTC
**Description**
Whenever a `Bloc` / `Cubit` has an initial value and the `Bloc event` / `Cubit function` tries to `emit` the same value as the initial value the `onTransition` / `onChange` are called and even `BlocBase.stream` is fired.

**Steps To Reproduce**

```dart
import 'package:bloc/bloc.dart';
import 'package:meta/meta.dart';

class LoggerBlocObserver extends BlocObserver {
  @override
  void onCreate(BlocBase bloc) {
    print('onCreate -- ${bloc.runtimeType}');
    super.onCreate(bloc);
  }

  @override
  void onEvent(Bloc bloc, Object? event) {
    print('onEvent -- ${bloc.runtimeType}, $event');
    super.onEvent(bloc, event);
  }

  @override
  void onChange(BlocBase bloc, Change change) {
    print('''onChange -- ${bloc.runtimeType}, Change {
    currentState: ${change.currentState},
    nextState: ${change.nextState}
}''');
    super.onChange(bloc, change);
  }

  @override
  void onTransition(Bloc bloc, Transition transition) {
    print('''onTransition -- ${bloc.runtimeType}, Transition {
    currentState: ${transition.currentState},
    event: ${transition.event},
    nextState: ${transition.nextState}
}''');
    super.onTransition(bloc, transition);
  }

  @override
  void onError(BlocBase bloc, Object error, StackTrace stackTrace) {
    print('onError -- ${bloc.runtimeType}, $error');
    super.onError(bloc, error, stackTrace);
  }

  @override
  void onClose(BlocBase bloc) {
    print('onClose -- ${bloc.runtimeType}');
    super.onClose(bloc);
  }
}

class TestCubit extends Cubit<int> {
  TestCubit() : super(0);

  static var _called = 0;

  void emitZero() {
    _called++;

    print('emitZero ($_called): start');
    emit(0);
    print('emitZero ($_called): end');
  }
}

@immutable
class TestEvent {
  const TestEvent();

  @override
  String toString() {
    return 'TestEvent {}';
  }
}

class TestBloc extends Bloc<TestEvent, int> {
  TestBloc() : super(0) {
    on<TestEvent>(_onTestEvent);
  }

  static var _called = 0;

  void _onTestEvent(TestEvent event, Emitter<int> emit) {
    ++_called;
    print('TestEvent ($_called): start');
    emit(0);
    print('TestEvent ($_called): end');
  }
}

Future<void> main() async {
  Bloc.observer = LoggerBlocObserver();

  print('--- CUBIT ---');
  final cubit = TestCubit()
    ..stream.listen((event) {
      print('TestCubit stream: $event');
    });
  cubit.emitZero();
  cubit.emitZero();

  // make sure TestCubit's events are fired
  await null;

  print('\n--- BLOC ---');
  final bloc = TestBloc()
    ..stream.listen((event) {
      print('TestBloc stream: $event');
    });
  bloc.add(const TestEvent());
  bloc.add(const TestEvent());

  // make sure TestBloc's events are fired
  await null;
}
```

***Output***
```
--- CUBIT ---
onCreate -- TestCubit
emitZero (1): start
onChange -- TestCubit, Change {
    currentState: 0,
    nextState: 0
}
emitZero (1): end
emitZero (2): start
emitZero (2): end
TestCubit stream: 0

--- BLOC ---
onCreate -- TestBloc
onEvent -- TestBloc, TestEvent {}
onEvent -- TestBloc, TestEvent {}
TestEvent (1): start
onTransition -- TestBloc, Transition {
    currentState: 0,
    event: TestEvent {},
    nextState: 0
}
onChange -- TestBloc, Change {
    currentState: 0,
    nextState: 0
}
TestEvent (1): end
TestBloc stream: 0
TestEvent (2): start
TestEvent (2): end
```

**Expected Behavior**
`onTransition` / `onChange` shouldn't be called and `BlocBase.stream` shouldn't fire if the initial value and the first added value are the same.

***Expected Output***
```
--- CUBIT ---
onCreate -- TestCubit
emitZero (1): start
emitZero (1): end
emitZero (2): start
emitZero (2): end

--- BLOC ---
onCreate -- TestBloc
onEvent -- TestBloc, TestEvent {}
onEvent -- TestBloc, TestEvent {}
TestEvent (1): start
TestEvent (1): end
TestEvent (2): start
TestEvent (2): end
```

**Comment by felangel** [comment] 2022-08-29 13:44
Hi @maRci002 👋
Thanks for opening an issue!

This is working as expected as is a duplicate of https://github.com/felangel/bloc/issues/1829.

**Closed** 2022-08-29 13:45 UTC
Labels: duplicate
