### ISSUE TITLE
add bloc to BlocWidgetBuilder

### ISSUE THREAD

**Issue by RobertHeim** [felangel/bloc#2287] opened 2021-03-31 22:10 UTC
**Is your feature request related to a problem? Please describe.**
When using `BlocBuilder` I end up writing a lot of `context.read<MyBloc>()`. It would reduce the boilerplate if we could provide the bloc to the `BlocWidgetBuilder`

**Describe the solution you'd like**
Current implementation:
```
typedef BlocWidgetBuilder<S> = Widget Function(BuildContext context, S state);
```
Requested change:
```
typedef BlocWidgetBuilder<B extends Bloc<Object?, S>, S> = Widget Function(BuildContext context, S state, B bloc);
```

**Describe alternatives you've considered**
Creating a wrapper around `BlocBuilder` would also work I guess:

```
class MyBlocBuilder<B extends Bloc<Object?, S>, S> extends StatelessWidget {
  final Widget Function(BuildContext context, S state, B bloc) builder;
  final BlocBuilderCondition<S>? buildWhen;

  const BlocStatusBuilder({
    Key? key,
    required this.builder,
    this.buildWhen,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<B, S>(
        buildWhen: buildWhen,
        builder: (context, state) => builder(ctx, state, context.read<B>()),
    );
  }
}
```

**Additional context**

* I think this change could also be applied to the other builders,  listeners, and consumers.
* To not depend on extensions (`read<*>()`) the implementation could use `BlocProvider.of<BlocA>(context)`.

**Comment by felangel** [comment] 2021-04-01 05:19
Hi @RobertHeim 👋 
Thanks for opening an issue!

I believe this is a duplicate of https://github.com/felangel/bloc/issues/1143.

I still think there are plenty of cases where widgets don't need to notify blocs and are simply reacting to state changes. In my opinion, the breaking change accompanied by the required additional parameter of the `builder` is not worth it.

```dart
BlocBuilder<MyBloc, MyState>(
  builder: (context, state, bloc) {
    return ElevatedButton(
      onPressed: () => bloc.add(...),
      ...
    );
  },
)
```

```dart
BlocBuilder<MyBloc, MyState>(
  builder: (context, state) {
    return ElevatedButton(
      onPressed: () => context.read<MyBloc>().add(...),
      ...
    );
  },
)
```

Also, this change would make the API confusing in my opinion because the `state` would be redundant. You could theoretically access the state either via the `state` parameter in `builder` or via `bloc.state`.

```dart
BlocBuilder<MyBloc, MyState>(
  builder: (context, state, bloc) {
    // we can access the current state via `state` and `bloc.state`
    // `bloc.state` can potentially be different than `state` because it is a getter
    // this can lead to confusion and unexpected behavior
  },
)
```

Let me know what you think 👍

**Comment by RobertHeim** [comment] 2021-04-01 08:14
@felangel thanks for the details.

Yes I think it is a duplicate and your arguments are solid. I want to discuss it a bit more. This are the merged requirements of our arguments :

1. Do not introduce breaking changes :crossed_fingers:
2. Do not enable multiple ways to access state
3. Improve Developer Experience (DX) by reducing boilerplate

**1. Do not introduce breaking changes :crossed_fingers:**
I agree on this. :+1: Instead of having a breaking change, we could introduce a different Widget Builder for the use case.
* Either a `BlocBuilderWithBloc<...>` (with a better name maybe but similar to the wrapper I presented in the first post.)
* or an additional argument to the `BlocBuilder<...>(builderWithBloc: (c, s, b) => ...` that is  mutually exclusive with `builder: (c,s) =>...` :thinking: 

Both would prevent a breaking change.

**2. Do not enable multiple ways to access state**
I partly agree on it. For me as a developer I am aware of the difference between the `state` as passed to the builder and `bloc.state` and depending on my intentions I can decide for one or the other. If this is bad, than the current implementation suffers from the same problem, because I can use `state` and `context.read<SomeBloc>().state` :point_up: The difference is only the boilerplate around it. For me this is a weak argument, because as a developer I would always use the shortest way to access the state anyway and for this I already got it at hand by `state`. Using `bloc.state` or `context.read<..>.state` is for different and less common use cases in which I am fine with the the boilerplate.

**3. Improve Developer Experience (DX) by reducing boilerplate**
This is a tricky one, as some developers according to the other ticket report that accessing the bloc is boilerplate (like me) and other report that writing `(_, state, _)` would be their default use case and thereby the second `, _` is boilerplate.

Additionally, the current argument to leave it like it is, is accompanied by "it's only one line" and that it performs in O(1). But from my experience this one line increases the cognitive load on a regular basis during implementation. It breaks the workflow by requiring to think about "get the bloc" twice: first for BlocBuilder<....> to react to changes and then again to access the bloc. This just feels off and cumbersome. In my perception it has less cognitive load to ignore a parameter of a function, but this seems to just be a matter of taste.

**Alternative idea**
Even if I argue that having multiple ways to access state is fine, we could hide it from a new `BlocBuilderWithBloc` or th `builderWithBloc:` (as discussed in 1.), by providing the `add` method instead of the bloc - because this is what devs end up accessing a lot.
```
BlocBuilder<...>(
  builderWithAdd: (context, state, add) => ...`
)
```
Let me know what you think. I am fine with leaving stuff as it is, because we can write our own widget builders with the intended behavior and reduced boilerplate for our common use cases. I wanted to share the idea/approach so in case others feel the same we could bake it into the package.

**Comment by felangel** [comment] 2021-04-01 15:18
@RobertHeim At the moment, I would prefer not to introduce a new widget and instead encourage you to create your own wrapper.

> The difference is only the boilerplate around it.

In my opinion, one line to access a bloc is not boilerplate (especially when it isn't always needed).

```dart
context.read<MyBloc>().add(MyEvent());
```

There are plenty of scenarios where the widgets inside of `BlocBuilder` are not responsible for triggering updates to the state:

```dart
Scaffold(
  body: Column(
    children: [
      Text('Counter'),
      BlocBuilder<CounterBloc, int>(
        builder: (context, state) => Text('$state'),
      ),
    ],
  ),
  floatingActionButton: FloatingActionButton(
    child: Icon(Icons.add),
    onPressed: () => context.read<CounterBloc>().add(Increment()),
  ),
);
```

It feels wrong to introduce the bloc as part of the `builder` because then as a developer I might think it's better to lift the `BlocBuilder` above the entire `Scaffold` since it would be more convenient to access the bloc.

> It breaks the workflow by requiring to think about "get the bloc" twice: first for BlocBuilder<....> to react to changes and then again to access the bloc. 

The role of the `BlocBuilder` widget is analogous to `StreamBuilder`. The purpose of the widget is to help developers rebuild a portion of the widget tree based on changes in a bloc's state and has nothing to do with notifying blocs. I would argue that as a developer you don't have to think about getting the bloc with `BlocBuilder` as it performs the lookup automatically based on the `BuildContext`. The additional `context.read` should be used where you explicitly want to notify the bloc regardless of whether that widget is wrapped in a `BlocBuilder` or not.

I'll think some more about this but at the moment I'd prefer to leave this change out of the library and up to developers if they want to create these additional wrappers.

Would love to hear other people's thoughts 👍

**Comment by RobertHeim** [comment] 2021-04-01 16:54
@felangel 
Thanks for the details. I think you got an important point that the `BlocBuilder` is more about re-builds than about interacting with the bloc and I agree that putting the bloc parameter would encourage devs to lift up the `BlocBuilder` which is an antipattern regarding performance.

While some of the reasons hold true, I agree on closing the feature request in favor of the other arguments which seem more important in the trade off.

Thanks again for the great lib and your time answering all these discussions. :+1:

**Closed** 2021-04-05 05:21 UTC
Labels: duplicate, question, waiting for response
