### ISSUE TITLE
VSCode extension: command 'extension.new-bloc' not found

### ISSUE THREAD

**Issue by agordeev** [felangel/bloc#666] opened 2019-11-12 14:17 UTC
**Describe the bug**
`>Bloc: New Bloc` command returns `command 'extension.new-bloc' not found` error.
Reproducible only in Flutter projects. When I try to create a bloc on server-side project, it lets me to do so. Reinstalling Bloc extension and restarting VSCode didn't help.
Interesting it worked few days ago. I was able to create the first bloc.

Bloc extension version: 2.0.0
VS Code info:
Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:09:34.601Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

**To Reproduce**
1. CMD + Shift + P
2. Type `bloc`
3. Select `Bloc: New Bloc`

**Expected behavior**
I expect to see bloc name selector

**Screenshots**
<img width="1868" alt="Screenshot 2019-11-12 at 17 15 21" src="https://user-images.githubusercontent.com/2883524/68678970-0a916c00-0570-11ea-9636-48e8c750d7b7.png">

**Logs **
`flutter analyze`:
No issues found

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.15 19A602, locale en-RU)
    • Flutter version 1.9.1+hotfix.5 at /Users/andrey/flutter
    • Framework revision 1aedbb1835 (4 weeks ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/andrey/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 2 categories.
```

**Comment by felangel** [comment] 2019-11-12 23:13
Hi @agordeev 👋 
Thanks for opening an issue!

Can you please provide a link to a sample app in which the command fails? I am unable to reproduce locally in various flutter projects.

Thanks! 👍

**Comment by felangel** [comment] 2019-11-13 20:06
Closing for now but feel free to comment with additional details/reproduction steps and I"m happy to continue the conversation 👍

**Comment by agordeev** [comment] 2019-11-14 06:12
Unfortunately, I'm unable to share the project as it is a proprietary. The issue does not appear when I try to use on your examples from this repo.

VSCode dev tools console outputs this:
<img width="796" alt="Screenshot 2019-11-14 at 09 11 30" src="https://user-images.githubusercontent.com/2883524/68831228-d1b3dd00-06be-11ea-9929-4c46e9ce7b1a.png">

**Comment by felangel** [comment] 2019-11-14 06:20
Hmm it looks like the error is coming from within VSCode and not the bloc extension itself. I’ll try to investigate this further. In the meantime if you’re able to put together a sample app that reproduces the issue it would be awesome! Thanks 👍

**Comment by agordeev** [comment] 2019-11-14 06:40
Looks like this is exactly the same issue as this one: https://github.com/shanalikhan/code-settings-sync/issues/745

**Comment by agordeev** [comment] 2019-11-14 09:48
I've tried to disable all the extensions except of `Bloc`, but that didn't help

**Comment by felangel** [comment] 2019-11-15 14:24
@agordeev any updates? Have you tried a reinstall of VSCode?

**Comment by agordeev** [comment] 2019-11-15 15:52
No updates.
I haven't. It's too radical :)

**Comment by felangel** [comment] 2019-11-15 16:19
Haha might be good in case something got corrupt 😛

**Comment by agordeev** [comment] 2019-11-18 05:32
I'm going to close this for now. The issue still persist and I don't know how to fix it. Hopefully someone will provide more details how to fix or reproduce it, then we can reopen

**Comment by felangel** [comment] 2019-11-20 06:25
@agordeev can you re-test with v2.1.0 of the vscode extension? I updated the vscode extension dependencies and bundled the extension via webpack.

**Comment by agordeev** [comment] 2019-11-20 06:37
Nope, still the same error :(

**Comment by felangel** [comment] 2019-11-20 06:40
😢 I was hoping that would've helped. Do you think you'll have time to try to create a sample project which reproduces the problem?

**Comment by agordeev** [comment] 2019-11-25 17:27
I managed to fix the issue by simply replacing `any` version to actual version or a blank space:

    equatable: any

to this:

    equatable: ^1.0.1

or even

    equatable:

in `pubspec.yaml`.
Apparently VSCode extension subsystem somehow interferes with Flutter dependency manager.

**Comment by felangel** [comment] 2019-11-25 18:10
hmm very strange 🤔 ...

Thanks for sharing, I'll try to reproduce this and see if I can improve anything in the extension.

**Comment by agordeev** [comment] 2019-11-26 04:17
I doubt this is something in extension

**Comment by felangel** [comment] 2019-11-27 20:38
Tried reproducing the issue and still nothing 😞 

Closing for now since you've figured out how to resolve it on your side and it doesn't appear to be related to the bloc extension as you pointed out 👍

**Closed by felangel** 2019-11-27 20:38 UTC
Labels: extension, investigating

**Comment by andreacimino** [comment] 2019-12-28 15:37
I had the same problem and I fixed manually by editing the package.json file of the extension to

main": "./dist/extension.js"   from ("./out/extension.js") . Hope it helps.

**Comment by andreacimino** [comment] 2019-12-28 15:38
Until yesterday everything was working, most probably un upgrade broke something.

**Comment by felangel** [comment] 2019-12-28 23:08
@andreacimino thanks for reporting this! Just fixed and published v3.0.1

**Comment by JeasonL** [comment] 2019-12-31 08:12
![image](https://user-images.githubusercontent.com/8176138/71614625-c3c30880-2be7-11ea-90bc-6fd0fe5d662b.png)
Same problem on v3.0.1.

**Comment by felangel** [comment] 2019-12-31 16:10
@JeasonL thanks for reporting this. @andreacimino are you also experiencing the same issue on v3.0.1?

**Comment by andreacimino** [comment] 2019-12-31 16:13
I will try to install from scratch and will let you know (I am using still my modified version).

**Comment by andreacimino** [comment] 2019-12-31 16:15
Here works fine.

**Comment by felangel** [comment] 2019-12-31 16:16
@JeasonL are you able to provide more information or reproduction steps? Are you using Windows or MacOS? I am also unable to reproduce this but it sounds like you're running into the same issue as @agordeev.

**Comment by marcos930807** [comment] 2019-12-31 18:46
The error happens to me because i am running on flutter 1.9.1 and bloc 2.1.0 because can't upgrade flutter yet(an amalyzer wear error under investigating). When the extention get automatic updated to version 3.0 the errors appears. I fixes by just downgrade extenxion. Hope that help somebody. Sorry for my bad English.
