### ISSUE TITLE
chore: Bloc does not force us to add generic parameters.

### ISSUE THREAD

**Issue by vasilich6107** [felangel/bloc#3431] opened 2022-07-12 16:07 UTC
**Description**

Hi. Previously there was a need to add `generic` parmas when specifying `BlocBuilder<CubitType, StateType>`.
But now analyzer is not highlighting the error.
I suppose it is caused by having `B extends StateStreamable<S>` on generic type?
In this case if we use 
```dart
BlocBuilder(
   builder: (_, state) {}
);
```
we'll get an error `Error: Could not find the correct Provider<StateStreamable<Object?>>`

Do we have any option to return back to basics with forcing generics specification?

**Comment by felangel** [comment] 2023-04-15 19:33
Hi @vasilich6107 👋 
Thanks for opening an issue!

In which version of bloc did you observer this change? This is because the generic type is inferred to be `Object?` when you don't specify it. I don't think there's much we can do without introducing a breaking change and I feel the error is hopefully obvious enough to be spotted quickly.

See <https://stackoverflow.com/questions/52286139/is-it-possible-to-require-generic-type-arguments-on-a-dart-class>

Closing for now since this is working as designed imo but feel free to provide additional thoughts/comments and I'm happy to continue the conversation 👍

**Closed by felangel** 2023-04-15 19:33 UTC
Labels: chore

**Comment by tenhobi** [comment] 2023-04-15 20:06
@felangel, that is not actually true, not specified generic type fails to be inferred, therefore, is `dynamic`. I tried to play with bloc and flutter_bloc, but even when I remove `extends Object?` from `Streamable` etc., it still, for some reason, infers the type as `Object?`.

Why playing with it around, I discovered that while this code fails to infer (T is dynamic):

```dart
class Alpha<T> {
  Alpha();
}

void main() {
  final x = Alpha(); // Alpha<dynamic>
}
```

this version of the reproduction of `BlocBuilder` infers it as `Object?` for some reason. 🤔 

```dart
class Alpha<T> {
  final String Function(int context, T state) builder;

  Alpha({
    required this.builder,
  });
}

void main() {
  final x = Alpha( // Alpha<Object?>
    builder: (context, state) => 'aaa',
  );
}
```

I would probably expect that it is still a `dynamic`, since I don't see any clue why the `state` parameter should not be kept as `dynamic` like that. 🤷

**Comment by felangel** [comment] 2023-04-15 22:16
The reason it infers the state as `Object? is because of https://github.com/felangel/bloc/blob/13597e2ba7780e3e0bf0581050944b1f9c7b1c08/packages/bloc/lib/src/bloc_base.dart#L4.

This is because `Object?` is slightly safer than dynamic (you can't just access any method/property on the object).

**Comment by tenhobi** [comment] 2023-04-16 13:04
Well, as you can see in my second example code above, I don't even have `extends Object?` and even when I removed it in the bloc, it also inferred the type as `Object?`.

But generally (not the case for this issue), I think it's best not to `extends Object?` and rather enable the language strict inference in the analyzer. :)
