### ISSUE TITLE
Concurrency Issue with Bloc Events Processing Sequentially when events are Async

### ISSUE THREAD

**Issue by faisalansari0367** [felangel/bloc#4015] opened 2023-11-29 07:09 UTC
**Description**
The bloc library currently does not process events sequentially as expected, especially when dealing with asynchronous events. The problem arises when multiple events are dispatched one after another. Instead of waiting for the completion of an asynchronous event before processing the subsequent event, the bloc processes events concurrently, leading to unexpected behavior in some scenarios.

**Steps To Reproduce**

void main() {
  final bloc = ExampleBloc();

  bloc.add(ExampleAsyncEvent(1)); // First event
  bloc.add(ExampleAsyncEvent(2)); // Second event
  bloc.add(ExampleAsyncEvent(3)); // Third event
}

**Expected Behavior**
The second should be called when the first event has done it's job especially when it's async.

**Comment by quoc-huynh-cosee** [comment] 2023-11-29 10:43
Since Bloc 8.0.0 events are handled concurrently (See https://verygood.ventures/blog/how-to-use-bloc-with-streams-and-concurrency). 

If you want to handle your events sequentially, please check out [bloc_concurrency](bloc_concurrency) and the transformer [sequential](https://pub.dev/documentation/bloc_concurrency/latest/bloc_concurrency/sequential.html).

**Comment by faisalansari0367** [comment] 2023-11-29 10:52
> Since Bloc 7.2.0 events are handled concurrently (See [Changelog](https://pub.dev/packages/bloc/changelog#720), [Migration Guide](https://bloclibrary.dev/#/migration?id=v720) and this [blog](https://verygood.ventures/blog/how-to-use-bloc-with-streams-and-concurrency)).
> 
> If you want to handle your events sequentially, please check out [bloc_concurrency](bloc_concurrency) and the transformer [sequential](https://pub.dev/documentation/bloc_concurrency/latest/bloc_concurrency/sequential.html).

Thank you for your response.
I attempted to utilize a sequential transformer, but it isn't progressing to the next event only after completion of the prior event. Rather, it's adding another event as soon as the first one is added.

**Comment by quoc-huynh-cosee** [comment] 2023-11-29 10:57
> Thank you for your response.
> I attempted to utilize a sequential transformer, but it isn't progressing to the next event only after completion of the prior event. Rather, it's adding another event as soon as the first one is added.

Can you give me a minimal example of your bloc with the sequential transformer?

**Comment by felangel** [comment] 2023-12-15 06:41
Closing for now since there are no actionable next steps without a minimal reproduction sample.

**Closed by felangel** 2023-12-15 06:41 UTC
Labels: question, waiting for response
