### ISSUE TITLE
fix: Bloc is being rebuilt from zero only in certain cases

### ISSUE THREAD

**Issue by limonadev** [felangel/bloc#3622] opened 2022-11-10 16:14 UTC
**Description**
If we have a `BlocProvider` to create a Bloc inside a widget part of a `Column`, depending on the siblings in that column the Bloc will be recreated in some cases, losing its state.

**Steps To Reproduce**

1. Clone https://github.com/limonadev/reproducible_issues and make `cd  bloc_rebuild`
2. Run the project (only tested on an Android mobile device) and press the button 'Change number'
3. Press the icon button and see how the number is reset to 0. 
4. Comment in the code any of the lines [53](https://github.com/limonadev/reproducible_issues/blob/main/bloc_rebuild/lib/main.dart#L53) or [55](https://github.com/limonadev/reproducible_issues/blob/main/bloc_rebuild/lib/main.dart#L55) and re run the app. Repeat the steps from 1 to 3 and see how the number state is not lost.

**Behavior with a single text:**

https://user-images.githubusercontent.com/16759478/201148455-15bf8b47-24c2-4eff-8711-f3a6a60b8b16.mp4

**Behavior with two texts:**

https://user-images.githubusercontent.com/16759478/201148105-46b187ab-f72f-48c2-b4a2-68bd908ade91.mp4

**Expected Behavior**
To maintain a consistent behavior in bloc recreation.

**Additional Context**
To be honest, I'm not sure if this is the expected behavior. I understand that putting the BlocProvider as a parent of the column instead of as its child can fix this behavior, but if we have a use case of a very simple functionality very deep in the tree, we would have to put the BlocProvider the most top of the tree as we need to make sure it's not going to lose the state.

**Comment by Coaspe** [comment] 2022-11-22 18:09
Hello! @limonadev 
I think this problem is not about `Bloc` but `updateChildren` method.
I wrote issue on Flutter repository about this.

**Comment by tenhobi** [comment] 2023-03-11 20:11
Hey @limonadev, as stated above, the issue is a matter of rebuilding the whole `BlocProvider` subtree. If you want to eliminate such behaviours, no matter if the algorithm is potentially inconsistent, as stated above, provide blocs, etc., above the subtree that is being rebuilt, or use Keys at the right places.

Since there hasn't been any response, I am closing the issue. Feel free to reopen it if you have something to add.

**Closed by tenhobi** 2023-03-11 20:11 UTC
Labels: question
