### ISSUE TITLE
Why is state not change in cubit?

### ISSUE THREAD

**Issue by PrzemyslawPluszowy** [felangel/bloc#3850] opened 2023-05-23 17:21 UTC
Hello why the state not emitting to builder, state always is initial

```


class package: flutterextends StatefulWidget {
  const RegisterScreen({super.key});

  @override
  State<RegisterScreen> createState() => _RegisterScreenState();
}

class _RegisterScreenState extends State<RegisterScreen> {
  final List _ageList = List.generate(80, (index) => index + 13);
  final List _weightList = List.generate(100, (index) => index + 40);
  final List _heightList = List.generate(150, (index) => index + 120);
  final List _hrRestList = List.generate(210, (index) => index + 30);
  final List _hrRMaxList = List.generate(120, (index) => index + 100);

  final TextEditingController _emailController = TextEditingController();
  final TextEditingController _nameController = TextEditingController();
  final TextEditingController _passwordController = TextEditingController();

  final TextEditingController _ageController = TextEditingController();
  final TextEditingController _heightController = TextEditingController();
  final TextEditingController _weightController = TextEditingController();
  final TextEditingController _hrRestController = TextEditingController();
  final TextEditingController _hrMaxController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    final colorScheme = Theme.of(context).colorScheme;
    return Scaffold(
      backgroundColor: Theme.of(context).colorScheme.primaryContainer,
      body: SingleChildScrollView(
        child: SizedBox(
          width: double.infinity,
          height: MediaQuery.of(context).size.height,
          child: Column(
            children: [
              Container(
                  color: Theme.of(context).colorScheme.primaryContainer,
                  height: MediaQuery.of(context).size.height * 0.3,
                  width: double.infinity,
                  child: AvatarImage(colorScheme: colorScheme)),
              Container(
                  decoration: BoxDecoration(
                    borderRadius: const BorderRadius.only(
                        topLeft: Radius.circular(25),
                        topRight: Radius.circular(25)),
                    color: Theme.of(context).primaryColor,
                  ),
                  height: MediaQuery.of(context).size.height * 0.7,
                  width: double.infinity,
                  child: Column(
                    children: [
                      Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: CustomTextField(
                            colorScheme: colorScheme,
                            controller: _nameController,
                            hintText: 'Enter your name',
                            label: 'Name',
                            iconData: Icons.person),
                      ),
                      Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: CustomTextField(
                            colorScheme: colorScheme,
                            controller: _emailController,
                            hintText: 'Enter your email',
                            label: 'Email',
                            iconData: Icons.email),
                      ),
                      Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: CustomTextField(
                          colorScheme: colorScheme,
                          controller: _passwordController,
                          hintText: 'Enter yor password',
                          label: 'Password',
                          iconData: Icons.lock,
                          isPassword: true,
                        ),
                      ),
                      const SizedBox(
                        height: 3,
                      ),
                      Container(
                        padding: const EdgeInsets.symmetric(horizontal: 3),
                        width: double.infinity,
                        height: 60,
                        child: Row(
                          children: [
                            Flexible(
                              child: Padding(
                                padding:
                                    const EdgeInsets.symmetric(horizontal: 5),
                                child: CustomTextField(
                                    press: () {
                                      dialogBulider(
                                          context: context,
                                          list: _ageList,
                                          title: 'Pick your age',
                                          controller: _ageController,
                                          startValue: 13,
                                          unit: '');
                                    },
                                    readOnly: true,
                                    colorScheme: colorScheme,
                                    controller: _ageController,
                                    label: 'Age',
                                    iconData: Icons.date_range),
                              ),
                            ),
                            Flexible(
                              child: Padding(
                                padding:
                                    const EdgeInsets.symmetric(horizontal: 5),
                                child: CustomTextField(
                                    press: () {
                                      dialogBulider(
                                          context: context,
                                          list: _heightList,
                                          title: 'Pick your height',
                                          controller: _heightController,
                                          startValue: 120,
                                          unit: 'cm');
                                    },
                                    readOnly: true,
                                    colorScheme: colorScheme,
                                    controller: _heightController,
                                    hintText: '',
                                    label: 'Height',
                                    iconData: Icons.height),
                              ),
                            ),
                            Flexible(
                              child: Padding(
                                padding:
                                    const EdgeInsets.symmetric(horizontal: 5),
                                child: CustomTextField(
                                    press: () {
                                      dialogBulider(
                                          context: context,
                                          list: _weightList,
                                          title: 'Pick your weight',
                                          controller: _weightController,
                                          startValue: 40,
                                          unit: 'kg');
                                    },
                                    readOnly: true,
                                    colorScheme: colorScheme,
                                    controller: _weightController,
                                    hintText: '',
                                    label: 'Weight',
                                    iconData: Icons.scale),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(
                        height: 8,
                      ),
                      SizedBox(
                        width: MediaQuery.of(context).size.width,
                        child: Padding(
                          padding: const EdgeInsets.all(9),
                          child: Row(
                            children: [
                              const Flexible(child: Divider()),
                              Flexible(
                                  child: Text(
                                ' Optional ',
                                style: TextStyle(color: colorScheme.onPrimary),
                              )),
                              const Flexible(child: Divider()),
                              const Flexible(child: SizedBox())
                            ],
                          ),
                        ),
                      ),
                      Container(
                        padding: const EdgeInsets.symmetric(
                          horizontal: 3,
                        ),
                        width: double.infinity,
                        height: 60,
                        child: Row(
                          children: [
                            Flexible(
                              child: Padding(
                                padding:
                                    const EdgeInsets.symmetric(horizontal: 5),
                                child: CustomTextField(
                                    press: () {
                                      dialogBulider(
                                          context: context,
                                          list: _hrRestList,
                                          title: 'set HR Rest',
                                          controller: _hrRestController,
                                          startValue: 30,
                                          unit: 'bpm');
                                    },
                                    readOnly: true,
                                    colorScheme: colorScheme,
                                    controller: _hrRestController,
                                    hintText: '',
                                    label: 'HR Rest',
                                    iconData: Icons.monitor_heart_outlined),
                              ),
                            ),
                            Flexible(
                              child: Padding(
                                padding:
                                    const EdgeInsets.symmetric(horizontal: 5),
                                child: CustomTextField(
                                    press: () {
                                      dialogBulider(
                                          context: context,
                                          list: _hrRMaxList,
                                          title: 'set HR Max',
                                          controller: _hrMaxController,
                                          startValue: 100,
                                          unit: 'bpm');
                                    },
                                    readOnly: true,
                                    colorScheme: colorScheme,
                                    controller: _hrMaxController,
                                    hintText: '',
                                    label: 'HR Max',
                                    iconData: Icons.monitor_heart),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const Spacer(),
                      SizedBox(
                        height: 50,
                        child: OutlinedButton.icon(
                            style: ButtonStyle(
                              shape: MaterialStateProperty.all(
                                  RoundedRectangleBorder(
                                      borderRadius:
                                          BorderRadius.circular(15.0))),
                              side: MaterialStateProperty.all(BorderSide(
                                color: colorScheme.onPrimary,
                              )),
                              foregroundColor: MaterialStatePropertyAll(
                                  colorScheme.onPrimary),
                            ),
                            onPressed: submitFieldButton,
                            icon: BlocBuilder<AuthCubit, AuthCubitState>(
                              builder: (context, state) {
                                if (state is AuthCubitLoading) {
                                  return CircularProgressIndicator();
                                }
                                return Icon(Icons.send_sharp);
                              },
                            ),
                            label: const Text('Create new profile')),
                      ),
                      const Spacer(),
                      GestureDetector(
                        onTap: () => context.go('/'),
                        child: RichText(
                          text: const TextSpan(
                            text: 'You have an account?',
                            children: [
                              TextSpan(
                                  text: ' Log in ',
                                  style: TextStyle(fontWeight: FontWeight.bold))
                            ],
                          ),
                        ),
                      ),
                      const Spacer()
                    ],
                  )),
            ],
          ),
        ),
      ),
    );
  }

  void submitFieldButton() async {
    UserEntity newUser = UserEntity(
      age: int.tryParse(_ageController.text),
      weight: int.parse(_weightController.text),
      height: int.parse(_heightController.text),
      hrMax: int.tryParse(_hrMaxController.text),
      hrRest: int.tryParse(_hrRestController.text),
      userName: _nameController.text,
      email: _emailController.text,
      password: _passwordController.text,
    );
    await di.getIt<AuthCubit>().registerUser(user: newUser);
  }

  Future<void> dialogBulider(
      {required BuildContext context,
      required List list,
      required String title,
      required TextEditingController controller,
      required int startValue,
      required String unit}) async {
    return showDialog(
      context: context,
      builder: (context) => AlertDialog(
          actions: [
            TextButton(
                onPressed: () {
                  context.pop();
                },
                child: const Text('Ok'))
          ],
          title: Text(title),
          content: SizedBox(
            height: 300,
            width: 300,
            child: Center(
              child: CupertinoPicker(
                  // magnification: 1.22,
                  squeeze: 1.2,
                  // useMagnifier: true,
                  itemExtent: 50,
                  onSelectedItemChanged: (value) {
                    setState(() {
                      controller.text = '${value + startValue}';
                    });
                  },
                  children:
                      list.map((e) => Center(child: Text('$e'))).toList()),
            ),
          )),
    );
  }
}

//Cubit------------------

`
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:new_app/src/domain/entities/user_entity.dart';
import 'package:new_app/src/domain/usecases/register_user_usecase.dart';

import 'auth_cubit_state.dart';

class AuthCubit extends Cubit<AuthCubitState> {
  AuthCubit({required this.registerUserUsecase}) : super(AuthCubitInitial());

  final RegisterUserUsecase registerUserUsecase;

  Future<void> registerUser({required UserEntity user}) async {
    emit(AuthCubitLoading());
    await Future.delayed(Duration(seconds: 5), () {});

    try {
      await registerUserUsecase.call(user);
      emit(AuthCubiLoaded());
    } catch (e) {
      emit(AuthCubitError(error: e.toString()));
    }
  }
}


//AuthCubit---------------


abstract class AuthCubitState {
  const AuthCubitState();
}

class AuthCubitInitial extends AuthCubitState {}

class AuthCubitLoading extends AuthCubitState {}

class AuthCubiLoaded extends AuthCubitState {}

class AuthCubitError extends AuthCubitState {
  final String error;

  const AuthCubitError({required this.error});
}
`

//injection-------------


final getIt = GetIt.instance;

Future<void> init() async {
  // register cubit
  getIt.registerFactory(() => AuthCubit(registerUserUsecase: getIt.call()));

  //register usecases
  getIt.registerLazySingleton(
      () => RegisterUserUsecase(fireRepository: getIt.call()));
  //register impl
  getIt.registerLazySingleton<FirebaseRepository>(
      () => FirebaseRepoImpl(remoteDataSource: getIt.call()));
  getIt.registerLazySingleton<RemoteDataSource>(() => RemoteDataSourceImpl(
      firebaseAuth: getIt.call(), firebaseFirestore: getIt.call()));

  final firebaseFirestore = FirebaseFirestore.instance;
  final firebaseAuth = FirebaseAuth.instance;
  getIt.registerLazySingleton(() => firebaseAuth);
  getIt.registerLazySingleton(() => firebaseFirestore);
}

**Comment by PrzemyslawPluszowy** [comment] 2023-05-23 19:34
ok i find error in my code but can tell me why get.it is not work
i change       await di.getIt<AuthCubit>().registerUser(user: newUser); to     context.read<AuthCubit>().registerUser(user: newUser);
 and is working

**Comment by felangel** [comment] 2023-05-23 19:43
> ok i find error in my code but can tell me why get.it is not work i change await di.getIt().registerUser(user: newUser); to context.read().registerUser(user: newUser); and is working

Hi @PrzemyslawPluszowy 👋 
I'm guessing the issue is because you're using a factory in get_it which means every time you access the cubit you're getting a new instance instead of reusing the existing instance. In general, I don't recommend mixing get_it with BlocProvider for this exact reason. I personally don't use get_it since BlocProvider and RepositoryProvider are built-in and are generally all you need to injecting/resolving dependencies. Hope that helps 👍

**Closed by felangel** 2023-05-23 19:43 UTC
Labels: bug

**Comment by PrzemyslawPluszowy** [comment] 2023-05-23 19:46
thank you

**Comment by PrzemyslawPluszowy** [comment] 2023-05-23 19:53
can you explain me how to good practice to put dependency injection when i use clean architecture to BlockProvider
