### ISSUE TITLE
fix: BlocListener with same Bloc/Cubit but different listenWhen: The listener id not called.

### ISSUE THREAD

**Issue by erlangparasu** [felangel/bloc#3934] opened 2023-08-17 02:52 UTC
**Description**
`BlocListener` with same `Bloc`/`Cubit` (but with different listenWhen condition): The listener is not called.

**Steps To Reproduce**

BlocListener<MyCubit, MyState>(),
BlocListener<MyCubit, MyState>(),
BlocListener<MyCubit, MyState>(),

**Expected Behavior**
`listener` called on each BlocListener declaration

**Screenshots**
-

**Additional Context**
-

**Comment by felangel** [comment] 2023-08-17 02:59
Hi @erlangparasu 👋
Thanks for opening an issue!

Can you please provide a link to a minimal reproduction sample? Thanks!

**Comment by felangel** [comment] 2023-09-13 01:39
Closing for now since there is no minimal reproduction sample.

**Closed by felangel** 2023-09-13 01:39 UTC
Labels: question, waiting for response, needs repro info
