### ISSUE TITLE
[Best practice] Where to manage user translated messages (BLOC or Page) ?

### ISSUE THREAD

**Issue by fvisticot** [felangel/bloc#676] opened 2019-11-17 09:24 UTC
Repository layer fire an exception in the Bloc Layer.
This exception message is "API oriented" and not "User oriented" and not internationalized

Where is the best place to implement the "User message" with internationalization support ?

1. In the bloc:
The bloc is catching all the exceptions an change the state with a FailureState containing an user understandable message internationalizeed

2. In the page:
The bloc change the state with the error in parameter and it is to the view responsability to manage error and internationalization

For me, it seems better to choose solution 1 (in the BLOC) because if we need to manage different pages with same BLOC the code is already there.

**Comment by felangel** [comment] 2019-11-17 14:53
Hi @fvisticot 👋 
Thanks for opening an issue!

I believe this is a duplicate of https://github.com/felangel/bloc/issues/657. 

Hope that helps 👍

**Closed by felangel** 2019-11-17 14:53 UTC
