### ISSUE TITLE
Expecting states before acting on a cubit in unit test - Breaks AAA Unit testing methodology

### ISSUE THREAD

**Issue by rajivrajan** [felangel/bloc#2269] opened 2021-03-26 11:42 UTC
**Describe the bug**
I have a simple cubit where I emit a loading state before I make an API call that subsequently emits states. 
typically, test cases would be written in a style where the first section of the unit test would perform **arrangements**, then perform a set of **actions** and finally **assert** (following AAA here.) Extending bloc works perfectly fine, whereas extending a cubit causes test cases to fail randomly! the only solution we found is below. 

This is a huge problem for a code base that is extensive such as ours, trying to use Cubits in place of Blocs.  

An example would be

```
class LoginCubit extends Cubit<LoginState> {
  final AccountLoginUsecase _loginUsecase;
  final LoginValidationUsecase _validationUsecase;

  LoginCubit()
      : _loginUsecase = AccountLoginUsecase(),
        _validationUsecase = LoginValidationUsecase(),
        super(InitialState());

  void login(String userName, String password) {
    emit(LoginLoadingState());
    if (userName.isNotEmpty) {
      _validateAndLogin(userName, password);
    } else {
      emit(LoginErrorState());
    }
  }

  void _validateAndLogin(String userName, String password) {
    if (_validationUsecase.isUserNameValid(userName) &&
        _validationUsecase.isPasswordValid(password)) {
      _loginUsecase.login(userName, password).then((value) {
        emit(LoginSuccessState());
      }).catchError((error) {
        emit(LoginErrorState());
      });
    }
  }
}
```

**Unit Tests**
```
void main() {
  test('initial state', () {
    LoginCubit _cubit = LoginCubit();

    expect(_cubit.state, isA<InitialState>());
  });

  test('emits logged in success state on successful login - fails', () {
    LoginCubit _cubit = LoginCubit();

    _cubit.login('userName', 'P2ssasd');
    expectLater(
        _cubit,
        emitsInOrder([
          isA<LoginLoadingState>(),
          isA<LoginSuccessState>(),
        ]));
  });

  test('emits logged in success state on successful login - succeeds', () {
    LoginCubit _cubit = LoginCubit();

    expectLater(
        _cubit,
        emitsInOrder([
          isA<LoginLoadingState>(),
          isA<LoginSuccessState>(),
        ]));
    _cubit.login('userName', 'P2ssasd'); //This line should be before the assertion!
  });
}
```

**Expected behavior**
the assertion should happen post the acting

**Screenshots**
Here's a screenshot!
<img width="1587" alt="Screenshot 2021-03-26 at 5 04 05 PM" src="https://user-images.githubusercontent.com/60695921/112625737-571fd380-8e55-11eb-9678-5b70e50e6659.png">

Paste the output of running `flutter doctor -v` here.
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.2 19C57 darwin-x64, locale en-GB)
    • Flutter version 2.0.1 at /Users/rajivrajan/flutter/flutter
    • Framework revision c5a4b4029c (3 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rajivrajan/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/rajivrajan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    ! Xcode 11.3.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.9.1 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2019.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.

**Comment by felangel** [comment] 2021-03-29 04:58
Hi @rajivrajan 👋 
Thanks for opening an issue!

This is expected behavior and is how streams are generally tested because it's not safe to assume that the stream will emit after a certain period of time. With streams you should generally always setup the expectation first and then act. With that being said, I would highly recommend using [package:bloc_test](https://pub.dev/packages/bloc_test) which addresses this issue by standardizing bloc tests:

```dart
blocTest(
  'emits logged in success state on successful login - succeeds',
  build: () => LoginCubit(),
  act: (cubit) => cubit.login('userName', 'P2ssasd'),
  expect: () => [
    isA<LoginLoadingState>(),
    isA<LoginSuccessState>(),
  ],
);
```

Hope that helps 👍 

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 😄

**Closed by felangel** 2021-03-29 04:58 UTC
Labels: pkg:bloc_test, question

**Comment by gerryau** [comment] 2022-04-12 06:07
How would this work when using freezed for states? Because there is no LoginLoadedState.
