### ISSUE TITLE
[bloc_test] Test with multiple Matchers will not completing

### ISSUE THREAD

**Issue by nibo** [felangel/bloc#2059] opened 2021-01-06 08:05 UTC
**Description**
I got a complex cubit which emits a state after initialization. In the act-part of blocTest i call an additional method from the cubit which emits another state. So in the expect-part i got two states which should be emitted.
If i debug the blocTest everything works as expected and the `test.expect(states, expect);` method is called. At this point the emitted states are exactly what i expected. But after that nothing happens, no error is thrown and the test will not be completed.

     // WORKING
     blocTest<DetailsCubit,
        DetailsState<DetailData, EditData>>(
      'emits no data - unknown id',
      build: () => getIt<DetailsCubit>(
        param1: DetailInitializer(detailsId: -1),
      ),
      expect: [
        detailIsEmpty(),
      ],
    );

     // WORKING
    blocTest<DetailsCubit,
        DetailsState<DetailData, EditData>>(
      'emits details',
      build: () => getIt<DetailsCubit>(
        param1: DetailInitializer(detailsId: 5),
      ),
      expect: [
        detailsLoaded(5, "type", [0, 1]),
      ],
    );

    // NOT WORKING
    blocTest<DetailsCubit,
        DetailsState<DetailData, EditData>>(
      'emits no data and then details',
      build: () => getIt<DetailsCubit>(
        param1: DetailInitializer(detailsId: -1),
      ),
      act: (cubit) => cubit.changeDetailData(5),
      expect: [
        detailIsEmpty(),
        detailsLoaded(5, "type", [0, 1]),
      ],
    );

    Matcher detailIsEmpty() => allOf([
      isA<NoData<DetailData, EditData>>(),
      hasProperty<NoData<DetailData, EditData>>(
          (NoData<DetailData, EditData> state) =>
              state.detail.model == null &&
              state.detail.type == null &&
              state.detail.list == null,
          isTrue)
    ]);

    Matcher detailsLoaded(
      int id,
      String type,
      List<int> ids,
    ) =>
    allOf([
      isA<Show<DetailData, EditData>>(),
      hasProperty<Show<DetailData, EditData>>(
          (Show<DetailData, EditData> state) {
        return state.detail.model.id == id &&
            state.detail.type.type ==
                type &&
            const ListEquality().equals(
              state.detail.list.map((e) => e.id).toList(growable: false),
              ids,
            );
      }, isTrue)
    ]);

**Expected behavior**
I expect that an error is thrown if my matching is wrong or the test successfully completes

**Logs**
```
flutter analyze
Running "flutter pub get" in ********...          1.040ms
Analyzing ********...
No issues found! (ran in 7.5s)
```
```
flutter doctor -v
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H114 darwin-x64, locale de-DE)
    • Flutter version 1.24.0-10.2.pre at /Users/*****/Library/flutter
    • Framework revision 022b333a08 (7 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/*****/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.0 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2018.2.8)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.88

• No issues found!

```

**Comment by felangel** [comment] 2021-01-11 15:55
Hi @nibo 👋 
Thanks for opening an issue!

Are you able to provide a link to a complete reproduction sample? It would make it much easier for me to help if I can debug the issue locally, thanks! 🙏

**Comment by felangel** [comment] 2021-01-31 03:11
Closing for now since there is no reproduction sample. Feel free to comment with additional information and I'm happy to continue the conversation 👍

**Closed by felangel** 2021-01-31 03:11 UTC
Labels: pkg:bloc_test, question, waiting for response
