### ISSUE TITLE
override methods in bloc class

### ISSUE THREAD

**Issue by BrianMwas** [felangel/bloc#2385] opened 2021-04-14 19:51 UTC
I need some help. I have a bloc class that's basically meant for authentication but every time after I have called it and I navigate to an auth protected screen I'm no longer authenticated and I have to authenticated again. I thought using hydrated bloc would be the way to go but am currently falling short on how to use it from my code.

I have tried omitting the overrides as I want to save the state only and not the transforms toJson and fromJson because I have a class that already does that.
Here's my code

`class AuthBloc extends Bloc<AuthEvent, AuthState> {
  final IAuthFacade authFacade;
  AuthBloc(this.authFacade) : super(const AuthState.initial());

  @override
  Stream<AuthState> mapEventToState(
    AuthEvent event,
  ) async* {
    yield* event.map(authCheckRequested: (e) async* {
      final userOption = await authFacade.getSignedInUser();

      yield userOption.fold(() => const AuthState.unAuthenticated(),
          (user) => AuthState.authenticated(user));
    }, signedOut: (e) async* {
      await authFacade.signOut();
      yield const AuthState.unAuthenticated();
    });
  }
}
`

**Comment by narcodico** [comment] 2021-04-14 20:00
Hi @BrianMwas 👋

The info you posted is incomplete so please share a repo with a minimal reproduction of your issue.

**Comment by II11II** [comment] 2021-04-15 17:55
Hi @BrianMwas 🖐,

Do you want to omit some states for the hydrated bloc?

**Comment by felangel** [comment] 2021-04-19 02:28
Closing for now since there isn't a complete reproduction sample. Feel free to provide additional information and we can continue the discussion 👍

**Closed by felangel** 2021-04-19 02:28 UTC
Labels: question, waiting for response
