### ISSUE TITLE
bloc_test not capturing one state

### ISSUE THREAD

**Issue by oscarshaitan** [felangel/bloc#3304] opened 2022-03-30 11:02 UTC
**Description**
I have a cubit that on the constructiosn call the a method _int()
 inside this method I have 3 if statements the first 2 pass the tests but the last one the most simple case just emit an state with out any previous operation is not captured by the test.
 the only way to capture the state on the test is putting a future.delayed with any time
 
 
![image](https://user-images.githubusercontent.com/9093952/160814641-c1d5b9de-2e7f-4501-bece-dd54a630cdbc.png)

the test that is not passing 

![image](https://user-images.githubusercontent.com/9093952/160814711-194cdd23-2186-4655-bd48-183326144493.png)

I tried 
use the wait on the test
put a future.delayed on the act
I combine both cases 

is simply dont emiting that state. I debug the test and is passign there but the test is not capturing that state

**Comment by felangel** [comment] 2022-04-01 01:45
Hi @YazeedAlKhalaf 👋
Thanks for opening an issue!

Can you please provide a link to a minimal reproduction sample that I can run/debug locally? Thanks!

**Comment by felangel** [comment] 2022-04-04 21:58
Closing since there are no actionable next steps. Feel free to provide a link to a minimal reproduction sample and I'm happy to take a closer look 👍

**Closed by felangel** 2022-04-04 21:58 UTC
Labels: question, waiting for response

**Comment by oscarshaitan** [comment] 2022-04-05 11:23
I will upload the example later today!

**Comment by Abdulaziz4** [comment] 2022-04-08 00:36
I faced similar issue and solved it by adding wait duration to the test equal to the Future.delayed duration. I hope that may solve your problem.

**Comment by oscarshaitan** [comment] 2022-04-08 09:21
I test the same but didnt work

**Comment by felangel** [comment] 2022-04-08 13:59
@oscarshaitan I recommend restructuring your cubit like:

```dart
class BugTestCubit extends Cubit<BugTestState> {
  BugTestCubit() : super(const BugTestState.init());

  Future<void> init() async {
    emit(const BugTestState.later());
  }
}
```

Then your test would look like:

```dart
blocTest<BugTestCubit, BugTestState>(
    'ReportCubit with draft completed report should emit the continue status',
    build: () => BugTestCubit(),
    act: (cubit) => cubit.init(),
    expect: () => [
      equals(const BugTestState.later()),
    ],
);
```

The reason your current test is failing is because the bloc immediately initializes and emits the new state before the subscription is created. Hope that helps 👍

**Comment by oscarshaitan** [comment] 2022-04-08 19:39
so in the real app has to force the cubit to bi initiated like Cubit()..init() ??

**Comment by oscarshaitan** [comment] 2022-04-22 12:29
@felangel  sorry still got the question

**Comment by YazeedAlKhalaf** [comment] 2022-04-22 20:37
i am not sure but is "init" a method that is auto-run once you provide the cubit?
