### ISSUE TITLE
Issue with getting current state in init state when init state is first called when page build

### ISSUE THREAD

**Issue by momoDragon** [felangel/bloc#1776] opened 2020-09-28 03:04 UTC
Upgrade from 4.0.0 to version 6.0 >, caused me not to be able to listen to state in init state when a page is first built, causing my old code to break. 

For example, 
When i navigate to a new page, i use to be able to print the current state in init state
Now, i am not able to print the current state when init state is called, only when the state updates that it prints. 

```
  @override
  void initState() {
     BlocProvider.of<TestBloc>(context).listen((state) {
      print(state);
    });
    super.initState();
  }
```

**Comment by felangel** [comment] 2020-09-28 03:08
Hi @momoDragon 👋
Thanks for opening an issue!

This is a duplicate of #1766 and was intentional and documented in the [migration guide](https://bloclibrary.dev/#/migration) 👍

**Closed by felangel** 2020-09-28 03:08 UTC
Labels: duplicate
