### ISSUE TITLE
Can closing the Bloc become optional?

### ISSUE THREAD

**Issue by RaviKavaiya** [felangel/bloc#740] opened 2019-12-24 14:46 UTC
First of all, this is not an issue. Need some help.

Hello, I am using this package after a long, updated from v0.15.0 (flutter_bloc).
I have an older application that was using 0.15.0, I updated dependency to 2.0.0 (bloc) and 2.1.1 (flutter_bloc).

Now, I get warnings of closing the sinks (the bloc objects) (instances of dart.core.Sink). I know, this is USEFUL.

BUT, imagine below situation : 

```dart
void main() {
  BlocSupervisor.delegate = AppBlocDelegate();

  MyBloc bloc1 = MyBloc();

  bloc1.listen((state) {
    if (state is ProcessDone) {
      // do some processing, and then...
      // runApp(MyApp());
    }
  });
  bloc1.add(StartProcess());
}
```

Now, I get warning here, too. I can't close this bloc in void main() !!!

Moreover, I don't want to move this initialization logic into a widget. (To be honest, I have the code to initialize SharedPreferences in 'MyBloc1', so that preferences load before I show anything to user.)

Any suggestions?

**Comment by felangel** [comment] 2019-12-24 16:56
Hi @RaviKavaiya 👋 
Thanks for opening an issue!

This is a duplicate of https://github.com/felangel/bloc/issues/587 and there is an issue open on the Dart Linter to resolve false positives at https://github.com/dart-lang/linter/issues/1381.

Regarding your specific question, I would either avoid creating streams and subscriptions directly in main because they will never be closed or you can simply [disable the lint rule](https://github.com/flutter/flutter/blob/e58dc16d7bec7199190f1408667e24e38328cc3b/analysis_options.yaml#L88) as is done within Flutter itself.

Hope that helps!

**Closed by felangel** 2019-12-24 16:56 UTC
