### ISSUE TITLE
bloc_test >=8.0.0-nullsafety.0 is incompatible with flutter_test

### ISSUE THREAD

**Issue by haashem** [felangel/bloc#2145] opened 2021-02-13 18:55 UTC
I have added `bloc_test: ^8.0.0-nullsafety.0 ` to `dev_dependencies`.
but when I run `flutter test` I encounter this issue:

```
Because bloc_test >=8.0.0-nullsafety.0 depends on meta ^1.3.0 and every version of flutter_test from sdk depends on meta 1.3.0-nullsafety.6, bloc_test >=8.0.0-nullsafety.0 is incompatible with flutter_test from sdk.
So, because my_app depends on both flutter_test any from sdk and bloc_test ^8.0.0-nullsafety.0, version solving failed.
```

Here is SDK constraints:
`sdk: '>=2.12.0-133.7.beta <3.0.0'`

and using Flutter: 1.26.0-17.3.pre

any idea?

**Comment by felangel** [comment] 2021-02-13 21:11
Hi @haashem 👋 
Thanks for opening an issue!

I believe you just need to switch to the latest beta (`flutter channel beta && flutter upgrade`).

Hope that helps! 👍

**Comment by haashem** [comment] 2021-02-14 07:48
Hi, Your packages are awesome and most of flutter community are using it!👏
I already did that:
`Flutter is already up to date on channel beta
Flutter 1.26.0-17.3.pre • channel beta • https://github.com/haashem/flutter.git
Framework • revision 4b50ca7f7f (9 days ago) • 2021-02-04 19:44:27 -0800
Engine • revision 2c527d6c7e
Tools • Dart 2.12.0 (build 2.12.0-259.8.beta)`

The issue relates to this line in `bloc_test` configuration file:

https://github.com/felangel/bloc/blob/23a3da23b7fd83ce87ee48191308f425302e62a4/packages/bloc_test/pubspec.yaml#L15

the meta package version should updated to `1.3.0-nullsafety.0`

**Comment by Supercaly** [comment] 2021-02-14 10:07
Hi, I've got the same problem with `flutter_bloc`

```
Because every version of flutter from sdk depends on meta 1.3.0-nullsafety.6 and bloc >=7.0.0-nullsafety.2 depends on meta ^1.3.0, flutter from sdk is incompatible with bloc >=7.0.0-nullsafety.2.
And because flutter_bloc >=7.0.0-nullsafety.2 depends on bloc >=7.0.0-nullsafety.2 <7.0.0, flutter from sdk is incompatible with flutter_bloc >=7.0.0-nullsafety.2.
So, because tasky depends on both flutter any from sdk and flutter_bloc ^7.0.0-nullsafety.2, version solving failed.
pub get failed (1; So, because tasky depends on both flutter any from sdk and flutter_bloc ^7.0.0-nullsafety.2, version solving failed.)
```

I'm using `beta channel` on the latest version

**Comment by haashem** [comment] 2021-02-14 13:26
I found the issue, the flutter remote repository was pointing to the fork version on my GitHub.
I changed flutter git remote path to flutter origin git repository and then upgraded the flutter. now is working well.

**Comment by Supercaly** [comment] 2021-02-14 13:38
@haashem In my case the flutter repository it's already like that, but the problem remains

**Comment by haashem** [comment] 2021-02-14 13:40
@Supercaly run this common and submit the output here: `flutter channel beta && flutter upgrade`

**Comment by felangel** [comment] 2021-02-14 21:51
Closing for now since it looks like this was resolved by upgrading to the latest beta channel. @Supercaly please provide detailed reproduction steps if you're still having trouble after upgrading, thanks! 👍

**Closed by felangel** 2021-02-14 21:51 UTC
Labels: pkg:bloc_test, question, waiting for response

**Comment by Supercaly** [comment] 2021-02-15 09:14
Sorry for the delay. @haashem This is the output of the command

```
C:\Users\Lorenzo\Desktop\taskyapp>flutter channel beta && flutter upgrade
Switching to flutter channel 'beta'...
git: From https://github.com/flutter/flutter
git:    696e4f70d1..b2e05062b6  master     -> origin/master
git: Your branch is up to date with 'origin/beta'.
git: Already on 'beta'
Successfully switched to flutter channel 'beta'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
Flutter is already up to date on channel beta
Flutter 1.26.0-17.5.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 1fe38dcb5f (4 days ago) • 2021-02-10 16:25:47 -0800
Engine • revision d4453f6018
Tools • Dart 2.12.0 (build 2.12.0-259.9.beta)
```

**Comment by dcenis165** [comment] 2021-05-24 08:35
I am facing the same issue now. @Supercaly did you manage to solve it?

**Comment by AnnaBersh** [comment] 2021-05-24 09:08
I have faced the similar issue and for me the real problem was another dependency. Updating `dio` to `dio: ^4.0.0` solved this for me
