### ISSUE TITLE
Listening to state stream

### ISSUE THREAD

**Issue by simonhull** [felangel/bloc#272] opened 2019-05-05 13:16 UTC
The solution to this might be dead simple.  I'm working on an AngularDart application using the Bloc library.  I have an App Component currently and a Login Component which contains a form and whose sole purpose right now is to dispatch a login event to an Auth Bloc.  I'm trying to listen to the changing values from my App Component in order to handle things like routing, but also to display information about a currently logged in user.  However I'm struggling with trying to listen to the state directly.  I know you can use the Bloc Pipe to do this on child components, but since this is the root component I need to listen to it in other ways.

Currently my App component looks like this:
```
class AppComponent implements OnInit, OnDestroy {
  AuthBloc _authBloc;
  AuthState _authState;
  bool authenticated = false;
  @override
  void ngOnInit() {
    _authBloc = AuthBloc();
    _authBloc.state.listen((currentState) {
      print(currentState);
      if (currentState is Authenticated) {
        this.authenticated = true;
      }
    });
  }
@override
  void ngOnDestroy() {
    this._authBloc.dispose();
  }
}
```

And here's the very basic AuthBloc:

```
class AuthBloc extends Bloc<AuthEvents, AuthState> {
  @override
  AuthState get initialState => NotAuthenticated();

  @override
  Stream<AuthState> mapEventToState(AuthEvents event) async* {
    if (event is Login) {
      try {
        yield LoginSucceeded();

        yield Authenticated();
      } catch (error) {
        yield LoginFailed(error: error);
      }
    } else if (event is Register) {
      yield Registering();
      try {
        yield RegistrationSucceeded();
        yield Authenticated();
      } catch (error) {
        yield RegistrationFailed(error: error);
      }
    }
  }
}
```

Printing the value of current state only logs the initial state value, and none of the following states after a dispatch.  I do have a test written that logs the states in the expected order and it passes, however I can't seem to get the same effect listening to the state stream directly. 

I do have the code split, so the AuthBloc is in a common library, and the AppComponent is in an Angular specific library.

Thanks for your help!

**Comment by felangel** [comment] 2019-05-05 14:44
Hi @simonhull 👋 
Thanks for opening an issue!

Can you please share the code in which you are dispatching events to the authBloc?
My guess is the instance you’re listening to is not the same instance that you are dispatching too. Thanks!

**Comment by simonhull** [comment] 2019-05-05 14:57
For sure, here's the value of the Login Component

```
class LoginPageComponent implements OnInit {
  String email;
  String password;
  bool remember;
  AuthBloc _authBloc;
  void ngOnInit() {
    _authBloc = AuthBloc();
  }

  login() {
    this._authBloc.dispatch(Login(email: this.email, password: this.password));
  }
}
```

I think I see what you mean about it being two different instances of the AuthBloc, in that case would I share a single copy globally using something like a service?

**Comment by felangel** [comment] 2019-05-05 15:00
Yeah the issue is you have a different instance. I think registering the bloc as a ClassProvider and using AngularDart’s dependency injection to provide the same instance is what I would do. Hope that helps 👍

**Comment by felangel** [comment] 2019-05-05 15:09
Closing this for now but feel free to comment with additional questions and I'm happy to continue the conversation 😄

**Comment by mranhtu** [comment] 2019-12-20 03:45
I have the same problem, hope you support. How to listen to the state after performing an action, from which i can use the router. 
I tried to follow your [example](https://github.com/felangel/Bloc/tree/master/examples/github_search), but it failed.

My repo: [https://github.com/mranhtu/bloc_example](https://github.com/mranhtu/bloc_example)

**Comment by felangel** [comment] 2019-12-20 03:49
@mranhtu thanks for sharing a link to your sample app. I'll take a look as soon as I can.

**Comment by felangel** [comment] 2019-12-20 15:59
@mranhtu I took a look and opened a [pull request](https://github.com/mranhtu/bloc_example/pull/1) with some suggestions and I added the code to listen to the bloc. Hope that helps!

**Closed by felangel** 2019-12-20 15:59 UTC
Labels: question
