### ISSUE TITLE
bloc Android plugin disabled

### ISSUE THREAD

**Issue by vendramini** [felangel/bloc#158] opened 2019-03-22 20:41 UTC
**Describe the bug**
Right click on any folder, New -> Bloc Generator -> New Bloc is always disabled.
```
Android Studio 3.3.2
Build #AI-182.5107.16.33.5314842, built on February 15, 2019
JRE: 1.8.0_152-release-1248-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-46-generic
```
Awesome work, guys =)

**Comment by felangel** [comment] 2019-03-22 22:35
@vendramini thanks for reporting this! 💯 

@jorgecoca have you been able to test the published plugin? I need to update my Android Studio still but I'll try to do that later this evening and see if I can reproduce this.

**Comment by jorgecoca** [comment] 2019-03-23 02:04
Nope, it is not disabled, see this:

<img width="1024" alt="Screen Shot 2019-03-22 at 8 59 27 PM" src="https://user-images.githubusercontent.com/3237451/54860254-85f29480-4ce5-11e9-9a7f-5b46d5a9d773.png">
<img width="647" alt="Screen Shot 2019-03-22 at 8 59 37 PM" src="https://user-images.githubusercontent.com/3237451/54860255-85f29480-4ce5-11e9-89b7-888cf41e31c4.png">
![bloc](https://user-images.githubusercontent.com/3237451/54860282-eaadef00-4ce5-11e9-9401-830c8195e703.gif)

**Comment by felangel** [comment] 2019-03-23 02:52
@vendramini can you give more details about how to reproduce the problem you're having?

**Comment by vendramini** [comment] 2019-03-23 03:26
I just downloaded the plugin directly from Android Studio.
Every folder with context menu shows me the "New Bloc" disabled.

How could I get more information for you?

**Comment by felangel** [comment] 2019-03-23 16:59
@vendramini I confirmed that it works for me as well
```
Android Studio 3.3.2
Build #AI-182.5107.16.33.5314842, built on February 15, 2019
JRE: 1.8.0_152-release-1248-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6
```

are you able to try on a different machine? The only difference I see is @jorgecoca and I are on macOS and you're on Linux 🤔

**Comment by yy1300326388** [comment] 2019-03-25 06:23
@felangel  I have the same problem on mac

![image](https://user-images.githubusercontent.com/8764899/54899059-8c615600-4f09-11e9-8cab-67946db0a775.png)


![image](https://user-images.githubusercontent.com/8764899/54899042-7489d200-4f09-11e9-9e44-9bedb87d1e7a.png)

**Comment by jorgecoca** [comment] 2019-03-25 12:07
Make sure that you are "right-clicking" on a folder of your project.

This is what happens when you do not click on a folder:

<img width="911" alt="Screen Shot 2019-03-25 at 7 03 25 AM" src="https://user-images.githubusercontent.com/3237451/54918477-5c479200-4ecc-11e9-83ab-7bc5a2f21f15.png">

This is what happens when you click on a folder:

<img width="868" alt="Screen Shot 2019-03-25 at 7 03 37 AM" src="https://user-images.githubusercontent.com/3237451/54918542-95800200-4ecc-11e9-9d77-474d632106b5.png">

**Comment by jorgecoca** [comment] 2019-03-25 12:08
If it does not work still, please check the Event Log of Android Studio, and see if there is something wrong. If so, could you send us a copy of the logs? Thanks!

**Comment by vendramini** [comment] 2019-03-25 15:31
Yes, I do clicked in the folder =)

`~/.AndroidStudio3.3/system/log` is the only folder I found with logs.
`2019-03-25 12:18:11,736 [entQueue-0]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: Bloc Code Generator (1.0), Dart (182.5215), Flutter (33.4.1) `
Is the only line about Bloc Plugin.

https://developer.android.com/reference/android/util/EventLog this page says another log location, but I can't find it - and I don't know if it really has something about.

**Comment by yy1300326388** [comment] 2019-03-26 02:54
@jorgecoca  I also clicked on the folder first.

**Comment by felangel** [comment] 2019-03-27 03:38
Update: I was able to reproduce the issue so I'll try to figure out the root cause and hopefully we'll have a fix out in the next few days. 👍

**Comment by vendramini** [comment] 2019-04-03 19:31
@felangel sorry the delay, I traveled.

I tried both folders: with and without .dat files. Same problem.

I opened my Android IDE now and the plugin has updated. But the problem here still.

**Comment by felangel** [comment] 2019-04-04 02:43
@vendramini no problem! Thanks for following up 👍 

We're continuing to investigate the issue but if you discover any new information which can help us please let us know!

**Comment by felangel** [comment] 2019-04-19 01:38
@vendramini the issue should be resolved by #228 I am just waiting for it to be reviewed published 👍

**Comment by felangel** [comment] 2019-04-21 00:21
Just pushed the update (v1.3) so it should be available in the next few days 👍 
Closing this for now but feel free to open another issue if the problem persists in v1.3

**Closed by felangel** 2019-04-21 00:21 UTC
Labels: bug, extension, in progress

**Comment by vendramini** [comment] 2019-04-23 20:11
Awesome =)
