### ISSUE TITLE
flutter_bloc - Notification 0nResume redirect to new page

### ISSUE THREAD

**Issue by karthikeyanp307** [felangel/bloc#1488] opened 2020-07-19 18:35 UTC
Hi,

I am using flutter_bloc in my application and for notifications, I am using https://pub.dev/packages/firebase_messaging. I am in need of redirecting the user to a specific screen in the application when a notification is received via onResume() or onLauch() method in the main.dart. How to do this?

When tried with Navigator, page redirection is not happening. I am following https://github.com/felangel/bloc/tree/master/examples/flutter_login for this. 

Please help me to resolve this issue.

Thanks.

**Comment by warriorCoder** [comment] 2020-07-19 19:34
@karthikeyanp307 Can you share your project or some code with where the issue is happening.

It would seem like your bloc isn't high enough in the tree to catch when a notification comes in to yield a new state OR that your state isn't changing correctly and so the Navigation code isn't being called.

Of course, it could be neither of these things.

**Comment by felangel** [comment] 2020-07-20 02:48
HI @karthikeyanp307 👋 
Thanks for opening an issue!

As @warriorCoder mentioned, it would be much easier to help if you could share a sample app which illustrates the problem you're facing 👍

**Comment by karthikeyanp307** [comment] 2020-07-20 10:53
Hi @felangel ,

Thanks for your reply and comments. I have shared a sample code via https://github.com/karthikeyanp307/flutter_login. This is not an executable one but for your view. Please help me to redirect to the inbox page from main.dart.

Thanks in advance.

**Comment by mintymac** [comment] 2020-07-22 21:45
@karthikeyanp307 To do this, you need to do something like the following in `initState()`:

`_firebaseMessaging.configure(onResume: 
      (Map<String, dynamic> message) async {
        print("onResume: $message");
         print(notificationBloc.state.toString());
        notificationBloc.add(
          NotificationReceived(
            my.Notification(
                id: uuid.v5(Uuid.NAMESPACE_URL, 'www.example.com'),
                title: message['notification']['title'],
                body: message['notification']['body']),
          ),
        );
      },
);`

**Comment by felangel** [comment] 2020-07-25 04:20
@mintymac thanks so much for taking the time to answer, I really appreciate it!

@karthikeyanp307 closing this for now but feel free to comment with any additional questions and I’m happy to continue the conversation 👍

**Closed by felangel** 2020-07-25 04:20 UTC
Labels: question, waiting for response
