### ISSUE TITLE
BlocEventListener Widget

### ISSUE THREAD

**Issue by fabryx92** [felangel/bloc#320] opened 2019-05-27 01:39 UTC
**Is your feature request related to a problem? Please describe.**
Very often my widgets react more to event changes then state changes, especially when it comes to reacting with Navigation, Snackbars and things like that.
This happens every time I choose to structure the state classes as separate classes (like the AuthenticationState class in the FirebaseLogin example). In this situation, if I had my data loaded in one of the states and something happen, a state change will trigger a UI change and my data are not in the next state unless I have in all the states the field to carry my data on.
In the situation of the single state class (like the LoginState class in the FirebaseLogin example again) the problem does not arise obviously.
When I choose the first state's structure I always listen to the event stream of my bloc manually and react to the events inside the listener.

**Describe the solution you'd like**
It would be interesting a widget (called like BlocEventListener for example) that worked like the current BlocListener but that reacted to event changes instead of state changes.

```dart
BlocEventListener(
  bloc: _bloc,
  listener: (context, event) {
    if (event is ButtonPressed) {
      Navigator.of(context).pushNamed('/details');
    }
  },
  child: Widget()
)
```

**Comment by felangel** [comment] 2019-05-27 01:56
Hi @fabryx92 👋 
Thanks for opening an issue!

Regarding your feature request, I'm still not sure I understand the use-case for `BlocEventListener`. If you want to navigate in response to an event can't you just navigate where you dispatch? In this case, I'm assuming you'd have a `Button` widget and in the `onPressed` callback you'd be dispatching `ButtonPressed`. Instead of doing that, couldn't you just push the `/details` named route?

The goal of `BlocListener` is if you wanted to navigate or do other one-time things in response to state changes that required business logic (determining if you're logged in or not etc...).

Let me know what you think and if I misunderstood the use-case. Thanks! 👍

**Comment by fabryx92** [comment] 2019-05-27 02:21
I have a `NewRequestBloc` that handles the logic of creating a new request, and I also have one Bloc for each page fo the request creation process. 
Some pages have certain dependencies and because of that, the `NewRequestBloc` acts as an orchestrator of all the blocs of the request creation process. Inside the NewRequestBloc, based on some events on a screen I have to dispatch events on other blocs. The problem is that the event to which I must react is determined inside the `NewRequestBloc` and not in the bloc of the page where iI currently is. 
To use your example of the `Button`: suppose I have `Screen1`, and `Screen2` with `Bloc1` and `Bloc2`, and the NewRequestBloc orchestrate both the blocs. 
In the `Screen1` I set some values and in the `Screen2` I have a button. 
In the `onPressed` of this button I dispatch `ButtonPressed`, in the `NewRequestBloc` I listen for the events of the `Bloc2` and only there, based on things depending on `Screen1,` I can decide what event to dispatch to the `Bloc2`. 
Now imagine that the screens are 4 or 5, I decided to have an orchestrator bloc to avoid a web of dependencies between blocs, but because of this choice I have to dispatch events from the  `NewRequestBloc` to the others bloc.

It seems reasonable to you?
Obviously, even without this "BlocEventListener" I can continue to do things the way I'm doing them, but in these last days I had the idea of this possible widget and so I proposed it here.

**Comment by felangel** [comment] 2019-05-27 02:28
@fabryx92 are you able to provide a sample application that illustrates the problem you're facing? I think it would help me better understand and have more context if you are able to provide me with a basic example app.

Also, not sure if this helps or not but recently we've added an `onEvent` callback to the `BlocDelegate` which you can override in order to globally handle all events that are dispatched to blocs in your application. In the callback you'll have access to the Bloc as well as the Event which was dispatched.

Let me know if that helps and if you could provide a link to an example application that would be awesome!

**Comment by anticafe** [comment] 2019-05-27 10:41
@felangel What I understand from his situation is, sometimes dispatch state from Bloc to UI, but because that state is one-time action, he doesn't want to trigger rebuild UI but just catch it in a `BlocEventListener` and handle it (for example after login successfully, `BlocEventListener` will receive and handle `LoginStateSuccess` but I don't need to rebuild UI here)

**Comment by fabryx92** [comment] 2019-05-27 13:00
@felangel I wanted to avoid to use the `onEvent` `BlocDelegate` callback for this kind of things because it means that I will have a mix of logic coming from different pieces of the app all in the same place.
My case is exactly what I described in the previous comment. I was just thinking that for the same reason the BlocListener was added, could be added this "BlocEventListener" in order to have an equally simple solution to react only one time to events. As I said the events are dispatched from external sources, not from the widget in which I have to react itself.

The reason why I can't rely on state changes is that if I have this state's structure:

```dart
class StateInitial extends State {
}

class StateFetched extends State {
  final Data data;
}

class StateNextButtonPressed extends State {
}
```

After pressing the next button my UI will rebuild if I change my state to `StateNextButtonPressed`, What I want, instead, is to keep my state to `StateFetched` and after this "external source" will dispatch the event I will react to the coming event.
But again, I already doing it by listening to the event stream, and it's ok for me.

**Comment by felangel** [comment] 2019-05-27 16:26
@fabryx92 I understand the use-case now but the problem is blocs convert events to states. In this case, the change you're proposing would break that paradigm because it would encourage dispatching events without having any states as a result. It would really help me if you could share a sample app that illustrates the problem so that I can try to suggest alternative ways to handle this.

Let me know if that makes sense and thanks to you and @anticafe for the additional info. 👍

**Comment by fabryx92** [comment] 2019-05-27 16:37
@felangel I agree with you. In fact, I think that when I face this kind of problem is a clear hint that I have to restructure the states classes going from the `AuthenticationState` type of state classes to the `LoginState` type.
I'm doing this refactoring right now by adding boolean flags to determine in which state I am instead of relying on the class of the state I have. 
And in this way, I can update these flags as an effect to an event and use the current BlocListener to react to the state changes.

Probably I was "fighting the library" instead of using it to help me.

**Comment by felangel** [comment] 2019-05-27 17:10
@fabryx92 yeah I agree and I am more than happy to help with any questions you have while refactoring. Closing this for now 👍

**Closed by felangel** 2019-05-27 17:10 UTC
Labels: question, waiting for response
