### ISSUE TITLE
Disposal of Bloc not work

### ISSUE THREAD

**Issue by AndreGroeschel** [felangel/bloc#2040] opened 2020-12-23 17:21 UTC
**Describe the bug**
The way how automatic disposal of a bloc is described in the docs does not work.

**To Reproduce**
1. Go to https://bloclibrary.dev/#/recipesflutterblocaccess?id=app-2
2. Create a minimal app with the example code and run it
3. Dispose() never gets called and accordingly close also never gets called

**Expected behavior**
A minimal example that shows how to create a bloc and how to close it

**Comment by felangel** [comment] 2020-12-30 04:00
Hi @AndreGroeschel 👋 
Thanks for opening an issue and sorry for the delayed response!

I don't think I understand the reproduction steps/issue. The example you provided manually disposes the bloc from the `dispose` of the `State` class. In the example you linked, `dispose` will only get called when the `AppState` is disposed which only will happen if the `App` widget is unmounted from the widget tree.

```dart
import 'package:flutter/material.dart';
import 'package:bloc/bloc.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

void main() => runApp(App());

class App extends StatefulWidget {
  @override
  _AppState createState() => _AppState();
}

class _AppState extends State<App> {
  final _counterBloc = CounterBloc();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      routes: {
        '/': (context) => BlocProvider.value(
              value: _counterBloc,
              child: HomePage(),
            ),
        '/counter': (context) => BlocProvider.value(
              value: _counterBloc,
              child: CounterPage(),
            ),
      },
    );
  }

  @override
  void dispose() {
    _counterBloc.close();
    super.dispose();
  }
}
```

A bloc will only be "automatically dispose" if it is created using `BlocProvider` and it will be disposed when the `BlocProvider`  is unmounted from the widget tree.

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-12-30 04:00 UTC
Labels: question

**Comment by AndreGroeschel** [comment] 2020-12-30 21:30
Hi @felangel,

thank you very much for the detailed explanation! Now it makes sense to me why `Dispose `never got called or automatic disposal is not working.

Regarding the example, I think now that it's more of a general Flutter problem. If I run the code above on Android and close the app, `Dispose` never gets called. Apparently, for the same reason that you explained...the top-level widget never gets unmounted from the widget tree.

After some research, it seems to make the above code work, and really closing the Bloc a mixin of `WidgetsBindingObserver` is required, along with overriding `didChangeAppLifecycleState`.

**Comment by KoustuvGanguly** [comment] 2022-02-24 13:31
Hi @AndreGroeschel ,
  About overriding `didChangeAppLifecycleState.` do I need to do/write anything inside the overridden method or I can keep it blank only with `super.didChangeAppLifecycleState(state);`? 
Facing same issue. Page closed still BlocListener is active and getting callback!

**Comment by TheLastGimbus** [comment] 2023-09-19 21:12
Hi there!

I think i have this issue too... 

I thought that if i nicely use `BlocProviders` in my widget tree, without any tricks, all my `close()` methods should be called by those providers... but it turns out that when my app closes, they do not run 😬😬😬 because... idk, the top level widget's dipose doesn't get called??

It would be nice if bloc would handle this...
