### ISSUE TITLE
'PreferencesBloc' doesn't conform to the bound 'BlocBase<PreferencesState>' of the type parameter 'B'.

### ISSUE THREAD

**Issue by EDnny12** [felangel/bloc#2317] opened 2021-04-10 05:55 UTC
This issue started to occur after updating project to null safety

**Comment by narcodico** [comment] 2021-04-10 09:12
Hi @EDnny12 👋

This looks like a duplicate of https://github.com/felangel/bloc/issues/479.

**Closed** 2021-04-19 02:31 UTC
Labels: duplicate, waiting for response
