### ISSUE TITLE
Why Hydrate Storage is always null?

### ISSUE THREAD

**Issue by beingsalmanshaikh** [felangel/bloc#1532] opened 2020-07-26 09:54 UTC
I tried implementing hydrated_bloc but I am stuck on Hydrated Storage initialization.
I might be doing something wrong but not able to figure out what. 
I already tried adding following lines but it isn't working. 
 ```
  WidgetsFlutterBinding.ensureInitialized();
  HydratedBloc.storage =  await HydratedStorage.build();
  runApp(MyApp());
```
```

BlocProvider(
        create: (context) =>
            ThemeBloc(ThemeState(themeData: appThemeData[AppTheme.Default])),
        child: BlocBuilder<ThemeBloc, ThemeState>(
          builder: (context, state) => _buildWithTheme(context,state),
        ),
      )
```

```
  bloc: ^6.0.1
  flutter_bloc: ^6.0.1
  hydrated_bloc: ^6.0.0
  equatable: ^1.2.3
```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 6.3.9600], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 4.0)
[√] Connected device (1 available)

• No issues found!
```
This is the error I am getting.
```

I/flutter (26276): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (26276): The following StorageNotFound was thrown building _InheritedProviderScope<ThemeBloc>(value: null):
I/flutter (26276): Storage was accessed before it was initialized.
I/flutter (26276): Please ensure that storage has been initialized.
I/flutter (26276): 
I/flutter (26276): For example:
I/flutter (26276): 
I/flutter (26276): HydratedCubit.storage = await HydratedStorage.build();
I/flutter (26276): 
I/flutter (26276): The relevant error-causing widget was:
I/flutter (26276):   _InheritedProviderScope<ThemeBloc>
I/flutter (26276):   file:///C:/Users/salman-shaikh/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/provider-4.3.1/lib/src/inherited_provider.dart:130:12
I/flutter (26276): 
I/flutter (26276): When the exception was thrown, this was the stack:
I/flutter (26276): #0      HydratedMixin.hydrate (package:hydrated_bloc/src/hydrated_cubit.dart:103:26)
I/flutter (26276): #1      new HydratedBloc (package:hydrated_bloc/src/hydrated_bloc.dart:15:5)
I/flutter (26276): #2      new ThemeBloc (package:frontapp/screens/global/theme/bloc/theme_bloc.dart:8:33)
I/flutter (26276): #3      _MyAppState.build.<anonymous closure> (package:frontapp/main.dart:64:13)
I/flutter (26276): #4      _CreateInheritedProviderState.value (package:provider/src/inherited_provider.dart:612:35)
I/flutter (26276): #5      _InheritedProviderScopeElement.value (package:provider/src/inherited_provider.dart:475:33)
I/flutter (26276): #6      Provider.of (package:provider/src/provider.dart:227:29)
I/flutter (26276): #7      BlocProvider.of (package:flutter_bloc/src/bloc_provider.dart:110:23)
I/flutter (26276): #8      BlocProviderExtension.bloc (package:flutter_bloc/src/bloc_provider.dart:148:53)
I/flutter (26276): #9      _BlocBuilderBaseState.initState (package:flutter_bloc/src/bloc_builder.dart:131:38)
I/flutter (26276): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
I/flutter (26276): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
I/flutter (26276): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (26276): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
I/flutter (26276): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (26276): #15     _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:397:11)
I/flutter (26276): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (26276): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
I/flutter (26276): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
I/flutter (26276): ...     Normal element mounting (7 frames)
I/flutter (26276): #25     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
I/flutter (26276): ...     Normal element mounting (7 frames)
I/flutter (26276): #32     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
I/flutter (26276): ...     Normal element mounting (17 frames)
I/flutter (26276): #49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (26276): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
I/flutter (26276): #51     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1148:16)
I/flutter (26276): #52     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1119:5)
I/flutter (26276): #53     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1061:17)
I/flutter (26276): #54     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)
I/flutter (26276): #55     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1060:13)
I/flutter (26276): #56     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:941:7)
I/flutter (26276): #57     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:922:7)
I/flutter (26276): (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter (26276): 
I/flutter (26276): ════════════════════════════════════════════════════════════════════════════════════════════════════
D/PhoneWindow(26276): setNavigationBarColor: ffffffff

```

Sorry if the question is too silly, I am just a beginner. Please help.

**Comment by felangel** [comment] 2020-07-26 14:23
Hi @beingsalmanshaikh 👋
Thanks for opening an issue!

Can you share a link to the repository? Thanks!

**Comment by beingsalmanshaikh** [comment] 2020-07-26 16:38
Sorry man, I would have but I can't share it because I don't have rights to share it. It's my company's project. I can share all the required code snippets though.

**Comment by felangel** [comment] 2020-07-27 14:31
@beingsalmanshaikh can you create a new simple app to illustrate the issue you're facing?

**Comment by beingsalmanshaikh** [comment] 2020-07-28 13:12
@felangel OK. I will do that.

**Comment by felangel** [comment] 2020-08-02 02:17
Closing for now since there isn't enough information to reproduce the issue but feel free to provide a link to a sample app which reproduces the issue and I'm happy to reopen the issue and look into it 👍

**Closed by felangel** 2020-08-02 02:17 UTC
Labels: question, waiting for response

**Comment by pwaliapk** [comment] 2021-08-30 17:03
Instead of  HydratedBloc.storage =  await HydratedStorage.build();
do 
 HydratedBloc.storage =  await HydratedStorage.build(HydratedStorage.webStorageDirectory);
