### ISSUE TITLE
docs: Best practice for awaiting finished event processing when state does not change

### ISSUE THREAD

**Issue by Lootwig** [felangel/bloc#3054] opened 2021-12-08 09:26 UTC
When adding an event that might or _might **not**_ cause a state change, is there a recommended way of ensuring it has been processed before executing the next statement?

If I _know_ there will be a state change, I'm usually doing this:

```dart
final stateUpdate = bloc.stream.first as Future<void>;
bloc.add(EventWithGuaranteedStateChange());
await stateUpdate;
doAfterProcessingIsDone();
```

However, if the processing does not necessarily change the state, the only way I can think of for making this work is to force a "dummy" update, which seems hacky.

From what I could tell, https://bloclibrary.dev/#/coreconcepts?id=observing-a-bloc would be a) overkill with registering the observer at the top level and b) only fire on actual state changes as well.

**Comment by felangel** [comment] 2021-12-08 15:10
Hi @Lootwig 👋 
Thanks for opening an issue!

Can you please provide a bit more context regarding what you're trying to achieve? Thanks!

**Comment by Lootwig** [comment] 2021-12-08 15:27
hey @felangel 👋 The bloc in question is supposed to prepare the state for a `FlowBuilder` before navigating to it.

This "preparation" consists of assembling a list asynchronously, updating the state with it and then emitting.

The `==` operator of the state returns true if the List is empty before and after assembly, which means: if the items have not changed,  no new state is emitted - hence with code as written above, there would be no navigation.

What I've done for now is to modify the equality check, so that consecutive states with empty lists are considered distinct (if the list is a new object).

**Comment by felangel** [comment] 2021-12-08 15:53
@Lootwig can you provide a link to a minimal reproduction sample? I'd love to take a closer look, thanks!

**Comment by Lootwig** [comment] 2021-12-08 17:12
here you go. man, building even small examples like these still takes quite a while :(

https://dartpad.dev/?id=c31f3a2a6e1f8b8c54be802fb47ae669

**Comment by felangel** [comment] 2021-12-08 17:40
@Lootwig thanks!

I refactored it so please check it out and let me know if that helps 👍 
https://dartpad.dev/?id=1c981719123a11dcd16df35fb7fea7bb

**Comment by Lootwig** [comment] 2021-12-12 01:37
It does, thank you!

In fact, the example led me down a rabbit hole of intense refactoring of multiple components I felt could be improved on, and in the process two things came up:

1. I had stumbled across context.watch / select on occasion, but their documentation never made it clear that (mostly by leaving out the _how_) they can actually turn a "dumb" stateless widget into an auto-updating one, which is mainly why I never really saw their potential and kept using context.read and BlocBuilders. Would you be open to a modification of the doc?
2. I spent a **ridiculous** amount debugging a scenario where a context.select never updated its widget, only to find out that the Bloc it was accessing was registered through a _RepositoryProvider_ rather than a BlocProvider. The main issue why I didn't figure it out sooner was that the context.select in this case still _works_... only like a context.read 😅 do you think making this at least a runtime error, if not possible as compile-time, would be an option?

**Comment by felangel** [comment] 2021-12-15 22:31
> It does, thank you!
> 
> In fact, the example led me down a rabbit hole of intense refactoring of multiple components I felt could be improved on, and in the process two things came up:
> 
> 1. I had stumbled across context.watch / select on occasion before your reply, but their documentation never made it clear that (mostly by leaving out the _how_) they can actually turn a "dumb" stateless widget into an auto-updating one, which is mainly why I never really saw their potential and kept using context.read and BlocBuilders. Would you be open to a modification of the doc?
> 2. I spent a **ridiculous** amount debugging a scenario where a context.select never updated its widget, only to find out that the Bloc it was accessing was registered through a _RepositoryProvider_ rather than a BlocProvider. The main issue why I didn't figure it out sooner was that the context.select in this case still _works_... only like a context.read 😅 do you think making this at least a runtime error, if not possible as compile-time, would be an option?

That's great to hear!

Regarding 1, I'm happy to adjust the documentation. Can you please provide the section of the docs which was unclear for you?

Regarding 2, definitely! We can throw a runtime exception if you try to provide a bloc using `RepositoryProvider` 👍

**Comment by Lootwig** [comment] 2021-12-16 11:59
It's actually an extension of the Provider package. [I've created a PR](https://github.com/Lootwig/provider/pull/1) for it.

**Comment by felangel** [comment] 2021-12-18 16:14
> It's actually an extension of the Provider package. [I've created a PR](https://github.com/rrousselGit/provider/pull/707) for it.
> 
> Edit: wrong base repo

Great! Closing this for now since #3067 should cover the bloc-specific change 👍

Let me know if I missed anything else and thanks again! 🙏

**Closed by felangel** 2021-12-18 16:14 UTC
Labels: question, waiting for response, documentation
