### ISSUE TITLE
build: flutter_bloc: ^8.1.0

### ISSUE THREAD

**Issue by ProFive** [felangel/bloc#3589] opened 2022-10-23 13:18 UTC
**Description**
  @overrides
   ^^^^^^^^^
: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
../…/src/bloc.dart:84
  @overrides
   ^
3

FAILURE: Build failed with an exception.

Describe what changes need to be done to the build system and why

**Comment by felangel** [comment] 2022-10-23 14:37
Hi @ProFive 👋
Thanks for opening an issue!

Can you please provide a link to a minimal reproduction sample? Based on the error I’m guessing you just need to clear you pub cache and make sure you’re using an unmodified version of the library. Hope that helps

**Comment by Luci3b** [comment] 2022-10-23 15:38
I think the correct spelling would be `@override`

**Comment by ProFive** [comment] 2022-10-24 00:29
@felangel 

Flutter SDK 3.3.5 on Mac M1

DEBUG CONSOLE 
: Error: Undefined name 'overrides'.
../…/src/bloc.dart:84
  @overrides
   ^^^^^^^^^
: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
../…/src/bloc.dart:84
  @overrides
   ^
3
FAILURE: Build failed with an exception.

* Where:
Script '/Users/Shared/Flutter/flutter_3.3.5/packages/flutter_tools/gradle/flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/Shared/Flutter/flutter_3.3.5/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Exception: Gradle task assembleDebug failed with exit code 1
Exited

DEMO:
I copied the same example from flutter_bloc 8.1.1 
[main.dart.TXT](https://github.com/felangel/bloc/files/9847940/main.dart.TXT)

**Comment by acampuzanoo** [comment] 2022-10-26 15:47
Hi @ProFive I think that what @Luci3b mentioned is correct. The annotation has an extra "S" at the end based on the error message. It should be:

`@override`

Now, looking at the file that you shared, it should be fine that way. 

Do you have more details as of which example is the one you are copying from to try to reproduce?

**Comment by felangel** [comment] 2022-10-26 16:53
@ProFive I'm guessing you accidentally modified the bloc source code on your local machine. You probably command/ctrl clicked on the Bloc class, jumped to the source code, and accidentally added an `s` to your local version.

Closing for now since there are no actionable next steps but feel free to comment with any follow-ups and I'm happy to continue the conversation 👍

**Closed by felangel** 2022-10-26 16:53 UTC
Labels: question, waiting for response
