### ISSUE TITLE
BlocBuilder does not rerender UI

### ISSUE THREAD

**Issue by vfiruz97** [felangel/bloc#2662] opened 2021-08-12 17:46 UTC
**BlocBuilder does not rerender UI**
In my ChatMessageBloc, I have multiple events, but in my only “sendMessage” event, BlocBuilder does not change the UI.

**Here is a piece of code**
```
      ....
     sendMessage: (e) async* {
          yield state.copyWith(
            isSubmitting: true,
            failureOrUnitOption: none(),
          );
        final isMessage = state.message.isNotEmpty;
        if (isMessage) {
          final _res = await _repository.sendChatMessage(
            requestId: e.requestId,
            message: state.message,
            lastMessageId: state.lastMessageId,
            file: state.file,
          );

          yield _res.fold(
            (failure) => state.copyWith(
              isSubmitting: false,
              failureOrUnitOption: some(left(failure)),
            ),
            (newMessageList) => state.copyWith(
              isSubmitting: true,
              messages: List<Message>.from(state.messages + newMessageList),
              lastMessageId:
                  newMessageList.isNotEmpty ? newMessageList.first.id : state.lastMessageId,
              message: '',
              file: null,
              failureOrUnitOption: none(),
            ),
          );
        }

        yield state.copyWith(
          isSubmitting: false,
          failureOrUnitOption: none(),
        );
      },
      ...
```
But when I change this piece of code to another piece of code. It works.

```
      ....
          yield _res.fold(
            (failure) => state.copyWith(
              isSubmitting: false,
              failureOrUnitOption: some(left(failure)),
            ),
            (newMessageList) => state.copyWith(
              isSubmitting: true,
              messages: List<Message>.from(state.messages + newMessageList),
              lastMessageId:
                  newMessageList.isNotEmpty ? newMessageList.first.id : state.lastMessageId,
              message: '',
              file: null,
              failureOrUnitOption: none(),
            ),
          );
        }
      ...
```
👇👇👇

```
       if (_res.isRight()) {
            final newMessage = _res.getOrElse(() => []);
            yield state.copyWith(
              isSubmitting: true,
              messages: List<Message>.from(state.messages + newMessage),
              lastMessageId: newMessage.isNotEmpty
                  ? newMessage.first.id
                  : state.lastMessageId,
              message: '',
              file: null,
              failureOrUnitOption: none(),
            );
          }

          yield _res.fold(
            (failure) => state.copyWith(
              isSubmitting: false,
              failureOrUnitOption: some(left(failure)),
            ),
            (_) => state,
          );
```

I want to know what is wrong with the above code?

**Comment by felangel** [comment] 2021-08-12 17:52
Hi @vfiruz97 👋 
Thanks for opening an issue!

It would be much easier to help if you could provide a link to a minimal reproduction sample that illustrates the issue. That way I can run/debug locally and provide a PR with suggestions. Thanks! 🙏

**Comment by felangel** [comment] 2021-08-17 04:35
Closing for now since there is no reproduction sample. Feel free to provide one and I'm happy to take a closer look, thanks!

**Closed by felangel** 2021-08-17 04:35 UTC
Labels: question, waiting for response

**Comment by jorgesarabia** [comment] 2021-08-18 11:32
Hi @vfiruz97 I believe the problem you mention is related to [this](https://github.com/dart-lang/sdk/issues/44616)
