### ISSUE TITLE
Cubit provided to other screen through constructor params, the second time visiting the screen it's state doesn't change

### ISSUE THREAD

**Issue by aliftaufik** [felangel/bloc#1971] opened 2020-11-27 12:21 UTC
**Describe the bug**
So, I have these two screens. The MainScreen has a BlocProvider of ListMessageCubit. And when a button clicked, it will navigate to SecondScreen with the cubit as a constructor parameter.

On the SecondScreen, I provide the cubit using BlocProvider.value. And in the WidgetOnSecondScreen I have initState and dispose, in which both invokes cubit method that emits new state (one to populate messages, other to clear it). So when we enter the SecondScreen, getListMessage will trigger. And when we leave the screen, clearListMessage will trigger.

The bug happens when we go into the SecondScreen for the second time. I have observed it and I see that the method is invoked, the repo method (that fetch message data) is invoked (I print it out and it actually has the messages), but the cubit observer doesn't log any changes. And in the WidgetOnSeconScreen, the list is empty.

Here's the simplified version of my widgets:

```

class MainScreen extends StatelessWidget {
  const MainScreen({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => ListMessageCubit(),
      child: Scaffold(
        body: Builder(
          builder: (context) => Center(
            child: FlatButton(
              child: Text('Show Messages'),
              onPressed: () {
                final listMessageCubit = context.read<ListMessageCubit>();

                Navigator.of(context).push(MaterialPageRoute(
                  builder: (context) =>
                      SecondScreen(listMessageCubit: listMessageCubit),
                ));
              },
            ),
          ),
        ),
      ),
    );
  }
}

class SecondScreen extends StatelessWidget {
  const SecondScreen({
    Key key,
    this.listMessageCubit,
  }) : super(key: key);

  final ListMessageCubit listMessageCubit;

  @override
  Widget build(BuildContext context) {
    return BlocProvider.value(
      value: listMessageCubit,
      child: WidgetOnSecondScreen(),
    );
  }
}

class WidgetOnSecondScreen extends StatefulWidget {
  WidgetOnSecondScreen({Key key}) : super(key: key);

  @override
  _WidgetOnSecondScreenState createState() => _WidgetOnSecondScreenState();
}

class _WidgetOnSecondScreenState extends State<WidgetOnSecondScreen> {
  ListMessageCubit _listMessageCubit;

  @override
  void initState() {
    super.initState();
    _listMessageCubit = context.read<ListMessageCubit>()..getListMessage();
  }

  @override
  void dispose() {
    _listMessageCubit?.clearListMessage();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<ListMessageCubit, ListMessageState>(
      builder: (context, state) {
        final messageList = state.messageList;

        return ListView.builder(
          itemBuilder: (context, index) {
            final message = messageList.elementAt(index);
            return ListTile(
              title: message.sender.name,
              subtitle: message.text,
            );
          },
        );
      },
    );
  }
}

```

**To Reproduce**
1. Tap The 'Show Messages' button to navigate to the second screen
2. Expect to see a list of messages.
3. Go back to the main screen.
4. Tap the button again
5. Alas! The message list is empty!!

**Expected behavior**
It should show the messages, as it does the first time we visit SecondPage.

**Screenshots**

**Logs **
Run `flutter analyze` and attach any output of that command below.
`No issues found! (ran in 7.7s)`
If there are any analysis errors, try resolving them before filing this issue.

Paste the output of running `flutter doctor -v` here.

```
[✓] Flutter (Channel stable, 1.20.3, on macOS 11.0.1 20B29, locale en-ID)
    • Flutter version 1.20.3 at /Users/alif/development/flutter
    • Framework revision 216dee60c0 (3 months ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/alif/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/alif/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 12.0, Build version 12A8179i
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Redmi Note 7 (mobile) • 192.168.18.3:5555 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

**Additional context**

**Comment by felangel** [comment] 2020-11-27 19:25
Hi @aliftaufik 👋 
Thanks for opening an issue!

This is because your state is likely extending Equatable and you are emitting the same state multiple times which will result in no state change. You can read more about this in the [FAQs](https://bloclibrary.dev/#/faqs?id=state-not-updating).

Let me know if that helps 👍

**Comment by aliftaufik** [comment] 2020-11-27 23:59
I do use Equatable for all my models. And I also use List.from and Map.from to change reference. In my clearListMessage what I do is emit a new initial state. And in getListMessage, right after fetching the data, I print out the message length, and it's not zero, it's there. But when I emit it doesn't trigger a state change. And when I change the SecondScreen this way:

```

class SecondScreen extends StatefulWidget {
  const SecondScreen({
    Key key,
    this.listMessageCubit,
  }) : super(key: key);

  final ListMessageCubit listMessageCubit;

  @override
  _SecondScreenState createState() => _SecondScreenState();
}

class _SecondScreenState extends State<SecondScreen> {
  ListMessageCubit get _listMessageCubit => widget.listMessageCubit;

  @override
  void initState() {
    super.initState();
    _listMessageCubit.getListMessage();
  }

  @override
  void dispose() {
    _listMessageCubit.clearListMessage();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return BlocProvider.value(
      value: _listMessageCubit,
      child: WidgetToShowListOfMessages(), // No call to getListMessage or clearListMessage down here.
    );
  }
}

```

Which is, now the SecondScreen itself handle when to get the data and clear the data. And it works just fine! The state gets updated and the list is not empty.

So the difference is, the first one I invoke the method inside the child widget of the screen and get the cubit through the provider context. The second one I invoke the methods directly in the screen widget (I changed it to stateful), and get the cubit through the widget constructor parameters.

Can this difference make any unexpected behavior on the state?

**Comment by aliftaufik** [comment] 2020-11-28 00:35
As you see, my problem is actually solved that way. But, for the sake of curiosity, I hereby ask this solved question, just in case someone else finds the same problem as me but can't manage to solve it that way

**Comment by felangel** [comment] 2020-12-04 17:23
Are you able to share a link to a reproduction sample? It would be much easier for me to help if I can reproduce the issue locally, thanks 🙏

**Comment by felangel** [comment] 2021-01-06 06:23
Closing for now since there is not reproduction sample. Feel free to provide one and I'm happy to take a closer look 👍

**Closed by felangel** 2021-01-06 06:23 UTC
Labels: question, waiting for response
