### ISSUE TITLE
multiple screen listener with same state

### ISSUE THREAD

**Issue by alexaung** [felangel/bloc#3329] opened 2022-04-18 18:15 UTC
**Description**

I am facing on issue with success state. I have two pages, in bottom navigation bar. One page show the list with download button and one page is showing some info with download button. But both download button is same behaviour.  So I use same bloc and same widget. User click the download button, showModalBottomSheet show up and choose the download folder and download and then close the modal. If download success, show snack bar with action to go to download screen. What happening now is that it is showing snack bar two time.

Why and how can I show the snack bar with one active screen.

**Comment by Add00w** [comment] 2022-04-19 10:45
> **Description**
> 
> I am facing on issue with success state. I have two pages, in bottom navigation bar. One page show the list with download button and one page is showing some info with download button. But both download button is same behaviour. So I use same bloc and same widget. User click the download button, showModalBottomSheet show up and choose the download folder and download and then close the modal. If download success, show snack bar with action to go to download screen. What happening now is that it is showing snack bar two time.
> 
> Why and how can I show the snack bar with one active screen.

where did you put the code that shows the snackbar and how do you call the download function all these are important to answer this plz provide code reproducing the issue.

**Comment by felangel** [comment] 2022-05-05 17:29
Closing for now since there are no actionable next steps. Feel free to provide a link to a reproduction sample and I'm happy to take a closer look 👍

**Closed by felangel** 2022-05-05 17:29 UTC
Labels: question, waiting for response
