### ISSUE TITLE
Timing problem between State and BlocListener

### ISSUE THREAD

**Issue by vinnytwice** [felangel/bloc#1039] opened 2020-04-13 06:53 UTC
@felangel Hi, I'm facing a behaviour that I didn't expect, so there is something I must have misunderstood . Latest state is not available when loading the screen.  I have a button in my `MapScreen` drawer that navigates to `AlarmsScreen` providing `SchedulerBloc` to it, and dispatches an event to the `SchedulerBloc` so that `AlarmsScreen`  in its `BlocListener` receives a state with data needed to build the UI . I have noticed that not always `AlarmsScreen` builds accordingly to data passed with the state in the listener( same data of course ), and after a few tries I noticed that if I press the button a tad longer (a loading bar appears on the button??) than `AlarmsScreen` always draws correctly. This means, as the prints both  in the `BlocListener` an `SchedulerBloc` confirmed, that sometimes the screen loads after the state has been streamed and the `BlocListener` didn't catch it as it wasn't initialised yet. To make sure I added a timer with a 200 millisecond delay to dispatch the event and now it never fails. The timer is just a workaround, but is there a way to read the latest state streamed by the bloc when the screen loads? I actually though that the latest state was always available to listeners, that is my understanding of rxdart, so BlocListener would get it even after it's been streamed, well..I've been proven wrong ... If instead the latest state should indeed be available to the the BlocListener even if it loads after the state has been streamed, can you spot what I'm doing wrong?
As always thank you very much for your time and help, I see a new commit from yesterday! Any good fix? Here is the button:

```
FlatButton.icon(
                          icon: Image.asset(
                            'assets/schedulerButton.png',
                            height: 55,
                            width: 55,
                          ),
                          label: Text(
                            'Check scheduler',
                            style: TextStyle(
                                color: Colors.white,
                                fontSize: 18,
                                fontWeight: FontWeight.w400),
                          ),
                          color: Colors.transparent,
                          onPressed: () {
                            // TODO call LoadAlarms and navigate to SchedulerScreen
                            print('pressed');
                            cache.play('tableViewOpen.mp3');
                            BlocProvider.of<SchedulerBloc>(context)
                                .add(LoadAlarms());
                            Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (_) => BlocProvider.value(
                                        value: BlocProvider.of<SchedulerBloc>(
                                            context),
                                        child: SchedulerScreen(
                                            widget.key, widget.user),
                                      )),
                            );
                            Timer(Duration(milliseconds: 200), () {
                              BlocProvider.of<SchedulerBloc>(context)
                                  .add(LoadAlarms());
                            });
                          },
                        ),
```

and this is the screen:

```
class _SchedulerScreenState extends State<SchedulerScreen> {
  AudioCache cache = new AudioCache();

  List<Alarm> alarms = [];
  List<SchedulerCell> cells = [];

  @override
  Widget build(BuildContext context) {
    cache.loadAll(['click.mp3', 'tableViewOpen.mp3', 'tableViewClose.mp3']);
    dynamic backButton =
        Platform.isIOS ? CupertinoIcons.back : Icons.arrow_back;
    dynamic addButton = Platform.isIOS ? CupertinoIcons.add : Icons.add;
    return BlocListener<SchedulerBloc, SchedulerState>(
      listener: (BuildContext context, SchedulerState state) {
        if (state is AlarmsLoaded) {
          setState(() {
            alarms = state.alarms;
            print('ShedulerListener : alarms are $alarms');
            cells = state.cells;
            print('ShedulerListener : cells are $cells');
          });
        }
      },
      child: Scaffold(
        appBar: AppBar(
          elevation: 0,
          backgroundColor: Colors.transparent,
          leading: IconButton(
              icon: Icon(backButton),
              color: Colors.redAccent,
              onPressed: () {
                cache.play('tableViewClose.mp3');
                Navigator.pop(context);
              }),
          title: Text(
            'Controlli tragitti',
            textAlign: TextAlign.center,
            style: TextStyle(
                color: Colors.orange,
                fontSize: 22,
                fontWeight: FontWeight.w500,
                letterSpacing: 1),
          ),
          centerTitle: true,
          actions: <Widget>[
            IconButton(
              icon: Icon(addButton),
              color: Colors.redAccent,
              onPressed: () {
                // TODO navigate to AddEditCheckScreen
                cache.play('tableViewOpen.mp3');
                Navigator.push(
                  context,
                  MaterialPageRoute<AddEditCheckScreen>(
                      builder: (_) => BlocProvider.value(
                            value: BlocProvider.of<SchedulerBloc>(context),
                            child: AddEditCheckScreen(
                                key: widget.key,
                                isEditing: false,
                                user: widget.user),
                          )),
                );
              },
            ),
            IconButton(
              icon: Icon(Icons.clear),
              color: Colors.redAccent,
              onPressed: () {
                BlocProvider.of<SchedulerBloc>(context).add(ClearAlarms());
                // TODO navigate to AddEditCheckScreen
                cache.play('tableViewOpen.mp3');
              },
            )
          ],
        ),
        body: ListView.builder(
          padding: EdgeInsets.all(20),
          itemCount: alarms.length,
          itemBuilder: (BuildContext context, int index) => Container(
            color: Colors.redAccent,
            child: cells[index],
          ),
        ),
      ),
    );
  }
}
```

**Comment by felangel** [comment] 2020-04-13 13:58
Hi @vinnytwice 👋 
Thanks for opening an issue!

Can you please create a sample app which reproduces the issue and share the link so that I can run/debug it locally? Thanks 👍

**Comment by felangel** [comment] 2020-04-17 15:17
Closing for now since there aren't easy steps to reproduce the issue.
Feel free to add additional details or preferably a link to a sample app which illustrates the issue and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-04-17 15:17 UTC
Labels: question, waiting for response
