### ISSUE TITLE
[question]how to update a single property of an object

### ISSUE THREAD

**Issue by lihaotian0607** [felangel/bloc#1431] opened 2020-07-09 05:04 UTC
> mentioned in the previous question, but did not get your reply

```dart
@immutable
class UserState extends Equatable {
  final String nickname;
  final String address;

  const UserState({@required this.nickname,@required this.address});

  @override
  List<Object> get props => [nickname,address];

  @override
  String toString() => 'UserState { nickname: $nickname ,address: $address }';
}
```
### bloc
> only updating the address does not affect nickname
```dart
_updateAddress(UpdateAddress event) {
    return UserState(address: event.address); 
  }
```
whether it can only be used
```dart
return UserState(address: event.address, nickname: this.state.nickname);
```

**Comment by YeungKC** [comment] 2020-07-10 00:07
Hi, @lihaotian0607 

maybe you can use some extensions/snippets generate copyWith function

**Comment by lihaotian0607** [comment] 2020-07-10 02:54
> Hi, @lihaotian0607
> 
> maybe you can use some extensions/snippets generate copyWith function

thanks!! Do you have good suggestions?

**Comment by YeungKC** [comment] 2020-07-10 03:04
Hi, @lihaotian0607 

if you use Android studio, it have generate function, default hot key is command + N?

**Comment by lihaotian0607** [comment] 2020-07-10 03:05
ok, thank you very much for your answer!

**Comment by lihaotian0607** [comment] 2020-07-10 03:05
> Hi, @lihaotian0607
> 
> if you use Android studio, it have generate function, default hot key is command + N?

ok, thank you very much for your answer!

**Comment by YeungKC** [comment] 2020-07-10 03:08
its ok, if the problem is solved, then @felangel 
 will close this issue.

**Closed** 2020-07-10 03:08 UTC
Labels: question
