### ISSUE TITLE
I am confused with navigatorkey in material app, what if I use simple navigator instead of it.

### ISSUE THREAD

**Issue by rravithejareddy** [felangel/bloc#1660] opened 2020-08-23 13:46 UTC
In firebaselogin example you used <_navigatorkey.pushNamedAndRemoveUntil('/login', (Route<dynamic> route) => false);>
Suppose if I want to use navigationkey in homewidget tree do I need to use bloc. Or can I pass key over in constructors.

Instead if I use like this
<Navigator.of(context) .pushNamedAndRemoveUntil('/login', (Route<dynamic> route) => false);>

I don't understand why do we need Globalkey and navigationkey use over there.

What if I use navigationbloc example below
[https://dev.to/pedromassango/flutter-bloc-a-better-way-to-handle-navigation-4fig ]

**Comment by felangel** [comment] 2020-08-24 03:54
This is a duplicate of #1661

**Closed by felangel** 2020-08-24 03:54 UTC
Labels: duplicate
