### ISSUE TITLE
fix: BlocProvider.of() called with a context that does not contain a ScreenBloc [showDialog] method

### ISSUE THREAD

**Issue by Omar-Qalei** [felangel/bloc#3437] opened 2022-07-19 04:40 UTC
How does a Bloc context fit inside the showDialog when I used a screen-wide BlocProvider?

Error: BlocProvider.of() called with a context that does not contain a ScreenBloc [showDialog] method

```
//Screen This is simple example
BlocProvider(
        create: (context) => ScreenBloc()
        child:
            BlocListener<ScreenBloc, ScreenState>(
          listener: (context, state) {
            if (state is YesState) {
              Navigator.of(context).pop();
            }
          },
          child: const Body(),
        ),
      ),

// Dialog
showDialog(
   context: context,
      builder: (context) => AlertDialog(
          title: Text("Alert Message"),
            content: Text("Are you sure?"),
               actions: [
                 TextButton(
                      child: Text("YES"),
                       onPressed: () => BlocProvider.of<
                                                  ProfileAdvertisementsBloc>(
                                              context)
                                            ..add(
                                              ScreenYESEvent(),
                                            ),
                                        ),
                  TextButton(
                       child: Text("No"),
                        onPressed: () => Navigator.of(context).pop(),
                                        ),
                                      ],
                                    ),
                                  ),
```

**Comment by felangel** [comment] 2022-07-19 04:58
HI @Omar-Qalei 👋 
Thanks for opening an issue!

This is a duplicate of https://github.com/felangel/bloc/issues/2215. You need to provide the bloc to the dialog via `BlocProvider.value`. Hope that helps 👍

**Closed by felangel** 2022-07-19 04:58 UTC
Labels: bug

**Comment by Omar-Qalei** [comment] 2022-07-20 05:03
> HI @Omar-Qalei 👋 Thanks for opening an issue!
> 
> This is a duplicate of #2215. You need to provide the bloc to the dialog via `BlocProvider.value`. Hope that helps 👍

Why must be using more than one Bloc Provider in the same context?

**Comment by Gene-Dana** [comment] 2022-07-22 14:38
Hi there 👋🏼 Is this a scenario where you are using bloc to control UI? How come you cannot use simply use `SetState` if you want to pop one the value of 'Yes'?

**Comment by alirezat66** [comment] 2022-08-30 23:46
@felangel 
I use the below code because I didn't want to use a new cubit in my dialogue I needed exactly the same that I used on my page. 
```
Utility.showBottomNavigationMessage(
                      context,
                      MultiBlocProvider(
                        providers: [
                          BlocProvider<SubCategoryCubit>(
                            create: (context) => _subCategoryCubit,
                          ),
                          BlocProvider(
                            create: (context) => _insertFinanceCubit,
                          ),
                        ],
                        child: const SubCategorySelector(),
                      ),
                      Languages.of(context).subCategoryTitle,);
```
Although the dialogue works in a true way, It has a very bad bug. when I close the dialogue, these cubits closed too. but I don't want it and I try to find a way to prevent cubits from closing but I couldn't. could you please help me?
