### ISSUE TITLE
issue: bloc_test is incompatible with freezed(Package) without overriding dependencies

### ISSUE THREAD

**Issue by mosabalrsaheed** [felangel/bloc#3680] opened 2023-01-02 19:38 UTC
**Description**
It's impossible to have bloc_test in a project that have freezed, flutter_test

**Steps To Reproduce**

1. Add both bloc_test (latest) and freezed (latest) in a project
2. run pub get 

**Expected Behavior**
both bloc test and freezed should be added

**Additional Context**
Current error 

Because test >=1.16.0-nullsafety.19 <1.16.6 depends on test_api 0.2.19 and test >=1.16.6 <1.17.10 depends on analyzer ^1.0.0, test >=1.16.0-nullsafety.19 <1.17.10 requires test_api 0.2.19 or analyzer ^1.0.0.
And because test >=1.17.10 <1.20.0 depends on analyzer >=1.0.0 <3.0.0 and test >=1.20.0 <1.21.2 depends on test_api 0.4.9, test >=1.16.0-nullsafety.19 <1.21.2 requires test_api 0.2.19 or 0.4.9 or analyzer >=1.0.0 <3.0.0.
And because test >=1.21.0 <1.21.6 depends on analyzer >=2.0.0 <5.0.0 and test >=1.21.6 <1.21.7 depends on test_api 0.4.14, test >=1.16.0-nullsafety.19 <1.21.7 requires test_api 0.2.19 or 0.4.9 or 0.4.14 or analyzer >=1.0.0 <5.0.0.
And because test >=1.21.7 <1.22.0 depends on test_api 0.4.15 and test >=1.22.0 <1.22.1 depends on test_api 0.4.16, test >=1.16.0-nullsafety.19 <1.22.1 requires test_api 0.2.19 or 0.4.9 or 0.4.14 or 0.4.15 or 0.4.16 or analyzer >=1.0.0 <5.0.0.
And because test >=1.22.1 depends on test_api 0.4.17 and every version of flutter_test from sdk depends on test_api 0.4.12, if flutter_test from sdk and test >=1.16.0-nullsafety.19 then analyzer >=1.0.0 <5.0.0.
And because bloc_test >=8.0.0-nullsafety.5 depends on test ^1.16.0 and freezed 2.3.2 depends on analyzer ^5.2.0, one of flutter_test from sdk or bloc_test >=8.0.0-nullsafety.5 or freezed 2.3.2 must be false.
Because every version of core from path depends on freezed ^2.3.2 and no versions of freezed match >2.3.2 <3.0.0, every version of core from path requires freezed 2.3.2.
Thus, one of flutter_test from sdk or bloc_test >=8.0.0-nullsafety.5 or core from path must be false.
And because app depends on core from path, flutter_test from sdk is incompatible with bloc_test >=8.0.0-nullsafety.5.
So, because app depends on both flutter_test from sdk and bloc_test ^9.1.0, version solving failed.

**Comment by felangel** [comment] 2023-01-02 22:12
Hi @mosabalrsaheed 👋 
Thanks for opening an issue!

This is a duplicate of https://github.com/felangel/bloc/issues/3110. Closing for now but feel free to comment with any follow up questions and I'm happy to continue the conversation 👍

**Closed by felangel** 2023-01-02 22:12 UTC
Labels: bug
