### ISSUE TITLE
accessing initialState after upgrade to 6.0.1

### ISSUE THREAD

**Issue by farrokhpey** [felangel/bloc#1895] opened 2020-11-07 17:06 UTC
After upgrading flutter_bloc to latest version I can't access the initialState in my Tests, what should I do about this?

**Comment by felangel** [comment] 2020-11-07 17:11
Hi @farrokhpey 👋
Thanks for opening an issue!

You can just reference the state directly.

```dart
test(‘initial state is correct’, () {
  expect(MyBloc().state, MyState.initial());
});
```

Hope that helps 👍

**Comment by farrokhpey** [comment] 2020-11-07 17:16
Thank you, it worked now but another error occurred 

it says:  `This test failed after it had already completed. Make sure to use [expectAsync] or the [completes] matcher when testing async code`

**Comment by felangel** [comment] 2020-11-07 17:19
Can you share the complete test that failed?

**Comment by farrokhpey** [comment] 2020-11-07 17:19
I think it solved using `expectAsync` as below
`
test('initialState should be Empty', () {  
    // assert  
    expectAsync1((value) {  
      equals(Empty());  
    });  
  });  
`

**Comment by felangel** [comment] 2020-11-07 17:20
You shouldn’t need to do that? Can you share the full test?

**Comment by farrokhpey** [comment] 2020-11-07 17:21
```
import 'dart:async';

import 'package:bloc/bloc.dart';
import 'package:dartz/dartz.dart';
import 'package:meta/meta.dart';
import 'package:tamashagar/core/error/failure.dart';
import 'package:tamashagar/core/usecases/usecase.dart';
import 'package:tamashagar/features/domain/entities/number_trivia.dart';
import 'package:tamashagar/features/presentation/bloc/number_trivia_event.dart';
import 'package:tamashagar/features/presentation/bloc/number_trivia_state.dart';

import '../../../core/util/input_converter.dart';
import '../../domain/usecases/get_concrete_number_trivia.dart';
import '../../domain/usecases/get_random_number_trivia.dart';

const String SERVER_FAILURE_MESSAGE = 'Server Failure';
const String CACHE_FAILURE_MESSAGE = 'Cache Failure';
const String INVALID_INPUT_FAILURE_MESSAGE =
    'Invalid Input - The number must be a positive integer or zero.';

class NumberTriviaBloc extends Bloc<NumberTriviaEvent, NumberTriviaState> {
  final GetConcreteNumberTrivia getConcreteNumberTrivia;
  final GetRandomNumberTrivia getRandomNumberTrivia;
  final InputConverter inputConverter;


  NumberTriviaBloc({
    @required GetConcreteNumberTrivia concrete,
    @required GetRandomNumberTrivia random,
    @required this.inputConverter,
  })  : assert(concrete != null),
        assert(random != null),
        assert(inputConverter != null),
        getConcreteNumberTrivia = concrete,
        getRandomNumberTrivia = random, super(Empty());


  @override
  Stream<NumberTriviaState> mapEventToState(
      NumberTriviaEvent event,
      ) async* {
    if (event is GetTriviaForConcreteNumber) {
      final inputEither =
      inputConverter.stringToUnsignedInteger(event.numberString);

      yield* inputEither.fold(
            (failure) async* {
          yield Error(message: INVALID_INPUT_FAILURE_MESSAGE);
        },
            (integer) async* {
          yield Loading();
          final failureOrTrivia =
          await getConcreteNumberTrivia(Params(number: integer));
          yield* _eitherLoadedOrErrorState(failureOrTrivia);
        },
      );
    } else if (event is GetTriviaForRandomNumber) {
      yield Loading();
      final failureOrTrivia = await getRandomNumberTrivia(NoParams());
      yield* _eitherLoadedOrErrorState(failureOrTrivia);
    }
  }

  Stream<NumberTriviaState> _eitherLoadedOrErrorState(
      Either<Failure, NumberTrivia> failureOrTrivia,
      ) async* {
    yield failureOrTrivia.fold(
          (failure) => Error(message: _mapFailureToMessage(failure)),
          (trivia) => Loaded(trivia: trivia),
    );
  }

  String _mapFailureToMessage(Failure failure) {
    switch (failure.runtimeType) {
      case ServerFailure:
        return SERVER_FAILURE_MESSAGE;
      case CacheFailure:
        return CACHE_FAILURE_MESSAGE;
      default:
        return 'Unexpected error';
    }
  }
}

```

**Comment by farrokhpey** [comment] 2020-11-07 17:22
and the error

Testing started at 6:20 PM ...
/home/mahdi/flutter/bin/flutter --no-color test --machine test
dart:async  _startMicrotaskLoop

TimeoutException after 0:00:30.000000: Test timed out after 30 seconds. See https://pub.dev/packages/test#timeouts

package:bloc/src/cubit.dart 144:7                                            Cubit.onError.<fn>
package:bloc/src/cubit.dart 145:6                                            Cubit.onError
package:bloc/src/bloc.dart 201:11                                            Bloc.onError
===== asynchronous gap ===========================
dart:async                                                                   _StreamImpl.listen
package:bloc/src/bloc.dart 239:7                                             Bloc._bindEventsToStates
package:bloc/src/bloc.dart 22:5                                              new Bloc
package:tamashagar/features/presentation/bloc/number_trivia_bloc.dart 35:41  new NumberTriviaBloc
test/features/presentation/bloc/number_trivia_bloc_test.dart 31:12           main.<fn>
This test failed after it had already completed. Make sure to use [expectAsync]
or the [completes] matcher when testing async code.
package:bloc/src/cubit.dart 144:7                                            Cubit.onError.<fn>
package:bloc/src/cubit.dart 145:6                                            Cubit.onError
package:bloc/src/bloc.dart 201:11                                            Bloc.onError
===== asynchronous gap ===========================
dart:async                                                                   _StreamImpl.listen
package:bloc/src/bloc.dart 239:7                                             Bloc._bindEventsToStates
package:bloc/src/bloc.dart 22:5                                              new Bloc
package:tamashagar/features/presentation/bloc/number_trivia_bloc.dart 35:41  new NumberTriviaBloc
test/features/presentation/bloc/number_trivia_bloc_test.dart 31:12           main.<fn>

Unhandled error NoSuchMethodError: The method 'fold' was called on null.
Receiver: null
Tried calling: fold<NumberTriviaState>(Closure: (Failure) => Error, Closure: (NumberTrivia) => Loaded) occurred in Instance of 'NumberTriviaBloc'.
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      NumberTriviaBloc._eitherLoadedOrErrorState (package:tamashagar/features/presentation/bloc/number_trivia_bloc.dart:67:27)
<asynchronous suspension>
#2      NumberTriviaBloc.mapEventToState.<anonymous closure> (package:tamashagar/features/presentation/bloc/number_trivia_bloc.dart:54:18)
<asynchronous suspension>
#3      NumberTriviaBloc.mapEventToState.<anonymous closure> (package:tamashagar/features/presentation/bloc/number_trivia_bloc.dart)
#4      Right.fold (package:dartz/src/either.dart:92:64)
#5      NumberTriviaBloc.mapEventToState (package:tamashagar/features/presentation/bloc/number_trivia_bloc.dart:46:26)
<asynchronous suspension>
#6      Bloc._bindEventsToStates.<anonymous closure> (package:bloc/src/bloc.dart:231:20)
#7      Stream.asyncExpand.<anonymous closure>.<anonymous closure> (dart:async/stream.dart:644:30)
#8      StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
#9      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
#10     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
#11     _rootRunUnary (dart:async/zone.dart:1198:47)
#12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#15     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
#16     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
#17     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
#18     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
#19     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:116:48)
#20     _rootRun (dart:async/zone.dart:1182:47)
#21     _CustomZone.run (dart:async/zone.dart:1093:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#24     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
#25     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:116:48)
#26     _rootRun (dart:async/zone.dart:1190:13)
#27     _CustomZone.run (dart:async/zone.dart:1093:19)
#28     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#30     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

package:test_api                                                   expectLater
package:flutter_test/src/widget_tester.dart 406:10                 expectLater
test/features/presentation/bloc/number_trivia_bloc_test.dart 77:9  main.<fn>.<fn>
test/features/presentation/bloc/number_trivia_bloc_test.dart 68:7  main.<fn>.<fn>

Expected: should do the following in order:
          • emit an event that Empty:<Empty>
          • emit an event that Error:<Error>
  Actual: <Instance of 'NumberTriviaBloc'>
   Which: emitted • Error
            which didn't emit an event that Empty:<Empty>

package:test_api                                                    expectLater
package:flutter_test/src/widget_tester.dart 406:10                  expectLater
test/features/presentation/bloc/number_trivia_bloc_test.dart 109:9  main.<fn>.<fn>
test/features/presentation/bloc/number_trivia_bloc_test.dart 99:7   main.<fn>.<fn>

Expected: should do the following in order:
          • emit an event that Empty:<Empty>
          • emit an event that Loading:<Loading>
          • emit an event that Loaded:<Loaded>
  Actual: <Instance of 'NumberTriviaBloc'>
   Which: emitted • Loading
                  • Loaded
            which didn't emit an event that Empty:<Empty>

package:test_api                                                    expectLater
package:flutter_test/src/widget_tester.dart 406:10                  expectLater
test/features/presentation/bloc/number_trivia_bloc_test.dart 127:9  main.<fn>.<fn>
test/features/presentation/bloc/number_trivia_bloc_test.dart 117:7  main.<fn>.<fn>

Expected: should do the following in order:
          • emit an event that Empty:<Empty>
          • emit an event that Loading:<Loading>
          • emit an event that Error:<Error>
  Actual: <Instance of 'NumberTriviaBloc'>
   Which: emitted • Loading
                  • Error
            which didn't emit an event that Empty:<Empty>

package:test_api                                                    expectLater
package:flutter_test/src/widget_tester.dart 406:10                  expectLater
test/features/presentation/bloc/number_trivia_bloc_test.dart 145:9  main.<fn>.<fn>
test/features/presentation/bloc/number_trivia_bloc_test.dart 135:7  main.<fn>.<fn>

Expected: should do the following in order:
          • emit an event that Empty:<Empty>
          • emit an event that Loading:<Loading>
          • emit an event that Error:<Error>
  Actual: <Instance of 'NumberTriviaBloc'>
   Which: emitted • Loading
                  • Error
            which didn't emit an event that Empty:<Empty>

package:test_api                                                    expectLater
package:flutter_test/src/widget_tester.dart 406:10                  expectLater
test/features/presentation/bloc/number_trivia_bloc_test.dart 179:9  main.<fn>.<fn>
test/features/presentation/bloc/number_trivia_bloc_test.dart 170:7  main.<fn>.<fn>

Expected: should do the following in order:
          • emit an event that Empty:<Empty>
          • emit an event that Loading:<Loading>
          • emit an event that Loaded:<Loaded>
  Actual: <Instance of 'NumberTriviaBloc'>
   Which: emitted • Loading
                  • Loaded
            which didn't emit an event that Empty:<Empty>

package:test_api                                                    expectLater
package:flutter_test/src/widget_tester.dart 406:10                  expectLater
test/features/presentation/bloc/number_trivia_bloc_test.dart 196:9  main.<fn>.<fn>
test/features/presentation/bloc/number_trivia_bloc_test.dart 187:7  main.<fn>.<fn>

Expected: should do the following in order:
          • emit an event that Empty:<Empty>
          • emit an event that Loading:<Loading>
          • emit an event that Error:<Error>
  Actual: <Instance of 'NumberTriviaBloc'>
   Which: emitted • Loading
                  • Error
            which didn't emit an event that Empty:<Empty>

package:test_api                                                    expectLater
package:flutter_test/src/widget_tester.dart 406:10                  expectLater
test/features/presentation/bloc/number_trivia_bloc_test.dart 213:9  main.<fn>.<fn>
test/features/presentation/bloc/number_trivia_bloc_test.dart 204:7  main.<fn>.<fn>

Expected: should do the following in order:
          • emit an event that Empty:<Empty>
          • emit an event that Loading:<Loading>
          • emit an event that Error:<Error>
  Actual: <Instance of 'NumberTriviaBloc'>
   Which: emitted • Loading
                  • Error
            which didn't emit an event that Empty:<Empty>

**Comment by felangel** [comment] 2020-11-08 01:36
@farrokhpey can you please provide a link to a complete reproduction sample? It looks like you're not stubbing the state of one or more of the injected mock blocs. Also, I would highly recommend using the [bloc_test package](https://pub.dev/packages/bloc_test) because it will greatly simplify and standardize your bloc unit tests. Thanks 👍

**Comment by felangel** [comment] 2020-11-12 03:36
Closing for now since I cannot easily help without a reproduction sample. Feel free to provide one and I’m happy to take a closer look 👍

**Closed** 2020-11-12 03:37 UTC
Labels: question

**Comment by farrokhpey** [comment] 2020-11-12 15:32
Thank you @felangel 
I solver the problem by removing initialState(I mean `empty` state) from my tests.
