### ISSUE TITLE
Bloc to imlpement real time internet connection.

### ISSUE THREAD

**Issue by prajwal27** [felangel/bloc#1486] opened 2020-07-19 09:32 UTC
**Is your feature request related to a problem? Please describe.**
I wanted a bloc that can be used globally to display the availability of real-time internet connection, with the help of other external packages (connectivity and DataConnectionChecker). I want a state to be yielded whenever the connection is changed.

**Describe the solution you'd like**
I have here a screenshot of what I want the bloc to be.

**Bloc Code**
![Screenshot from 2020-07-19 15-01-01](https://user-images.githubusercontent.com/31249460/87871739-b5480d00-c9d0-11ea-9b3c-770415512da8.png)

**Bloc Event Code**
![Screenshot from 2020-07-19 14-38-53](https://user-images.githubusercontent.com/31249460/87871551-bb3cee80-c9ce-11ea-8208-ce99ef4a7214.png)

**Bloc State Code**
![Screenshot from 2020-07-19 14-39-08](https://user-images.githubusercontent.com/31249460/87871554-c132cf80-c9ce-11ea-891f-ecb0fe013674.png)

**Network Info Class**
![Screenshot from 2020-07-19 14-38-11](https://user-images.githubusercontent.com/31249460/87871558-c6901a00-c9ce-11ea-982c-0794994dd4c7.png)

**Dependency Injection using GetIt package**
![Screenshot from 2020-07-19 14-42-24](https://user-images.githubusercontent.com/31249460/87871596-09ea8880-c9cf-11ea-98b4-4bad0f41ee3e.png)

**Additional context**
The [DataConnectionChecker](https://pub.dev/packages/data_connection_checker) package is used to check current instance's internet connection.
The [Connectivity](https://pub.dev/packages/connectivity) package is used to see if there's any change in network connectivity.
 The error is in the Bloc Code. I'm not sure how to resolve it

**Comment by warriorCoder** [comment] 2020-07-19 19:29
Hi @prajwal27 ... The problem is that your bloc needs to yield a state, not a listener. Have you looked at www.resocoder.com tutorials? I know he has some that use the freezer package with bloc.

**Comment by prajwal27** [comment] 2020-07-19 20:28
@warriorCoder I have actually arrived at a solution. Will upload in some time.

**Comment by prajwal27** [comment] 2020-07-19 21:13
The solution which I found useful.

**Repository Code**
![Screenshot from 2020-07-20 02-34-52](https://user-images.githubusercontent.com/31249460/87885253-32f03500-ca32-11ea-99ba-0c2ae9b63fe0.png)

**Bloc Code**
![Screenshot from 2020-07-20 02-35-34](https://user-images.githubusercontent.com/31249460/87885281-6f239580-ca32-11ea-9427-1c71fd1ffc5b.png)

**Bloc State Code**
![Screenshot from 2020-07-20 02-36-07](https://user-images.githubusercontent.com/31249460/87885289-7c408480-ca32-11ea-9345-72fd6d0e22ab.png)

**Bloc Event Code**
![Screenshot from 2020-07-20 02-35-56](https://user-images.githubusercontent.com/31249460/87885286-79459400-ca32-11ea-926f-7cb20b404af8.png)

**Dependency Injection using get_it package**
![Screenshot from 2020-07-20 02-37-38](https://user-images.githubusercontent.com/31249460/87885292-81053880-ca32-11ea-9981-5cb3a8c4507c.png)

**Initialising in the app widget  (so that it's accessible globally)**
![Screenshot from 2020-07-20 02-38-42](https://user-images.githubusercontent.com/31249460/87885294-85315600-ca32-11ea-9b85-c4b7caf10c53.png)

I'm looking for more alternate solutions. If anyone has any, plz do tell!

**Comment by felangel** [comment] 2020-07-19 22:50
Hi @prajwal27 👋
Thanks for opening an issue!

The current solution you shared is what I would recommend because it allows your bloc to handle other incoming events while also listening for connectivity changes from the repo.

Closing for now but feel free to comment with any additional questions/concerns and I’m happy to continue the conversation 👍

**Closed by felangel** 2020-07-19 22:50 UTC
Labels: question

**Comment by prajwal27** [comment] 2020-07-29 18:06
@felangel   I  wanted to ask how to use these blocs in a bottom navigation bar of 3 tabs which uses AutomaticKeepAliveClientMixin. So there would be 3 blocbuilder at same time if I listen to it and build in each of the tabs
