### ISSUE TITLE
Unit Test BLoC

### ISSUE THREAD

**Issue by fwidjaya20** [felangel/bloc#1666] opened 2020-08-25 08:37 UTC
Hi Felix,

I'm trying to write some unit tests for my pretty simple Bloc. 
I want to test, that an added Event should emits some states.

Here is the Bloc:
```
class HeroBloc extends Bloc<HeroEvent, HeroState> {
  GetHeroesUseCase _getHeroes;

  HeroBloc({
    @required GetHeroesUseCase getHeroesUseCase
  }) : super(HeroUninitialized()) {
    this._getHeroes = getHeroesUseCase;
  }

  @override
  Stream<HeroState> mapEventToState(HeroEvent event) async* {
    if (event is FetchHeroes) {
      yield* this.mapFetchHeroes();
    }
  }

  Stream<HeroState> mapFetchHeroes() async* {
    yield HeroLoading();
    
    Either<Failure, List<HeroEntity>> result = await this._getHeroes(NoParams());

    yield* result.fold(
      (l) async* {
        yield HeroError(failure: l);
      },
      (r) async* {
        yield HeroLoaded(
          heroes: r
        );
      }
    );
  }
}
```

This is my Test:
```
test("Should emit [HeroLoading, HeroLoaded] when fire FetchHero", () {
    List<HeroEntity> mockData = [
      HeroEntity(
        id: 1,
        name: "npc_dota_hero_antimage",
        localizedName: "Anti-Mage",
        attackType: "melee",
        primaryAttr: "agi",
        roles: ["Carry", "Escape", "Nuker"],
        legs: 2
      )
    ];

    when(getHeroesUseCaseMock(any))
      .thenAnswer((_) async => Right(mockData));

    final bloc = HeroBloc(
      getHeroesUseCase: getHeroesUseCaseMock
    );
    final expected = [
      HeroLoading(),
      HeroLoaded(
        heroes: mockData
      )
    ];

    expectLater(bloc, emitsInOrder(expected));

    bloc.add(FetchHeroes());
  });
```

and the result is 
```
Should emit [HeroLoading, HeroLoaded] when fire FetchHero:

ERROR: Expected: should do the following in order:
          • emit an event that <Instance of 'HeroLoading'>
          • emit an event that <Instance of 'HeroLoaded'>
  Actual: <Instance of 'HeroBloc'>
   Which: emitted • Instance of 'HeroLoading'
                  • Instance of 'HeroLoaded'
            which didn't emit an event that <Instance of 'HeroLoading'>
```

Do you have any idea why this test keep failing ?

**Comment by felangel** [comment] 2020-08-26 03:09
Hi @fwidjaya20 👋 
Thanks for opening an issue!

Are you able to share a link to the complete code so I can run the test locally? If not, could you provide the `HeroState` implementation? Thanks 👍

**Comment by fwidjaya20** [comment] 2020-08-26 03:25
Thanks for the response, you can clone it on `https://github.com/fwidjaya20/flutter-test`

**Comment by felangel** [comment] 2020-08-26 04:11
@fwidjaya20 thanks for sharing the repo! I took a look and the issue is you can't compare different instances of your state unless you override the equality comparison operator and hashCode. In my opinion, the simplest way to do this is using the [equatable](https://pub.dev/packages/equatable) package.

Just add `equatable` to your `pubspec.yaml`:

```yaml
name: fluttertesting
description: Flutter Application with Testing
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dio: ^3.0.10
  equatable: ^1.2.4
  flutter_bloc: ^6.0.1
  bloc: ^6.0.2
  dartz: ^0.9.1
  get_it: ^4.0.4
  mockito: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

Then make your `HeroState` extend `Equatable`:

```dart
import 'package:equatable/equatable.dart';
import 'package:fluttertesting/cores/failure/failure.dart';
import 'package:fluttertesting/features/heroes/domains/entities/hero.dart';
import 'package:meta/meta.dart';

abstract class HeroState extends Equatable {
  @override
  List<Object> get props => [];
}

class HeroUninitialized extends HeroState {}

class HeroLoading extends HeroState {}

class HeroLoaded extends HeroState {
  final List<HeroEntity> heroes;

  HeroLoaded({this.heroes});

  HeroLoaded copyWith({List<HeroEntity> heroes}) {
    return HeroLoaded(heroes: heroes ?? this.heroes);
  }

  @override
  List<Object> get props => [heroes];
}

class HeroError extends HeroState {
  final Failure failure;

  HeroError({@required this.failure});

  @override
  List<Object> get props => [failure];
}
```

And lastly, since the `HeroState` contains a `List<HeroEntity>` make sure `HeroEntity` also extends `Equatable`:

```dart
import 'package:equatable/equatable.dart';
import 'package:meta/meta.dart';

class HeroEntity extends Equatable {
  final int id;
  final String name;
  final String localizedName;
  final String primaryAttr;
  final String attackType;
  final List<String> roles;
  final int legs;

  const HeroEntity({
    @required this.id,
    @required this.name,
    @required this.localizedName,
    @required this.primaryAttr,
    @required this.attackType,
    @required this.roles,
    @required this.legs,
  });

  @override
  List<Object> get props {
    return [
      id,
      name,
      localizedName,
      primaryAttr,
      attackType,
      roles,
      legs,
    ];
  }
}
```

Then the tests will pass 👍 

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 😄

**Closed by felangel** 2020-08-26 04:11 UTC
Labels: question, waiting for response
