### ISSUE TITLE
perf: MediaQuery.of.(context) conflict with BlocBuilder BuildContext

### ISSUE THREAD

**Issue by akshaynjarangal** [felangel/bloc#3456] opened 2022-07-27 05:08 UTC
**Description**

Hello @felangel  , We flutter developers want to fix the conflit issue of `flutter_bloc` in use of `MediaQuery.of.(context)` in the widget tree , when using the `MediaQuery.of.(context)` inside of Widget Tree , The Total Scaffold widget rebuild multiple times, instead of use with Transform.scale, we can't get errors.

**Comment by Gene-Dana** [comment] 2022-07-28 14:24
Hi there 👋🏼 Widgets rebuild constantly, that's the idea behind a declarative UI, and we use bloc as a means to simplify our understanding of all this. Why are you using `MediaQuery?` To get the size of the screen for your widgets?

**Comment by akshaynjarangal** [comment] 2022-07-29 05:06
> Hi there 👋🏼 Widgets rebuild constantly, that's the idea behind a declarative UI, and we use bloc as a means to simplify our understanding of all this. Why are you using `MediaQuery?` To get the size of the screen for your widgets?

MediaQuery for other Widget, like logo responsive  sizing , container responsive design

**Comment by felangel** [comment] 2022-07-29 14:17
Hi @akshaynjarangal 👋 
Thanks for opening an issue!

Are you able to share a link to a DartPad that reproduces the issue? This doesn't sound like a flutter_bloc issue. When you use `MediaQuery.of(context)` you are marking that widget as dependent on the MediaQuery which will trigger rebuilds for a variety of reasons. I'm guessing if you remove flutter_bloc from the equation you will still experience the multiple rebuilds. Let me know if that helps and please provide a DartPad if you're still having trouble, thanks!

**Comment by felangel** [comment] 2022-07-31 03:09
Closing for now since there aren't any actionable next steps. Feel free to provide a link to a minimal reproduction sample and I'm happy to take a closer look 👍

**Closed by felangel** 2022-07-31 03:09 UTC
Labels: question, waiting for response
