### ISSUE TITLE
how to update the progress bar by bloc?

### ISSUE THREAD

**Issue by lsk569937453** [felangel/bloc#1913] opened 2020-11-11 07:06 UTC
I want upload the file to the backend and update the progressbar by bloc.But the code could not work.I send 30 request and want every one add a new event so I can update the state,the code is flowing

```
import 'dart:async';
import 'dart:io';

import 'package:bloc/bloc.dart';
import 'package:flutter/cupertino.dart';
import 'package:meta/meta.dart';
import 'package:rxdart/rxdart.dart';
part 'pic_detail_event.dart';
part 'pic_detail_state.dart';

class PicDetailBloc extends Bloc<PicDetailEvent, PicDetailState> {
  PicDetailBloc() : super(PicDetailInitial());


  Stream<PicDetailState>_download()async*{
    for(int i=0;i<30;i++){
      downloadChunk().then((value){
        sleep(Duration(milliseconds: i*20));
        print(i);
        this.add(new PicDetailDownLoadProgressEvent());
      });
    }
    print("download start");
    yield PicDetaiDownloadProgessState(0,0,30);

  }

  Stream<PicDetailState>_updateProgress()async*{

    print(state.currentProgress.toString()+"-"+state.downloadState.toString());
    yield state.copyWith(downloadState: state.downloadState,currentProgress: state.currentProgress+1,maxProgress: state.maxProgress);

  }
  Future<int> downloadChunk()async{
   return  Future.delayed(Duration(seconds: 1), () {

      print('delay 1 s');
      return 1;

    });
  }

  @override
  Stream<PicDetailState> mapEventToState(
    PicDetailEvent event,
  ) async* {
    // TODO: implement mapEventToState

    print(event);
    if(event is PicDetailStartDownLoadEvent){
       yield* _download();
    }
    if(event is PicDetailDownLoadProgressEvent){
      yield* _updateProgress();
    }
  }
}

```

The result is that

```
I/flutter (10360): delay 1 s
I/flutter (10360): 0
I/flutter (10360): delay 1 s
I/flutter (10360): 1
I/flutter (10360): delay 1 s
I/flutter (10360): 2
I/flutter (10360): delay 1 s
I/flutter (10360): 3
I/flutter (10360): delay 1 s
I/flutter (10360): 4
I/flutter (10360): delay 1 s
I/flutter (10360): 5
I/flutter (10360): delay 1 s
I/flutter (10360): 6
I/flutter (10360): delay 1 s
I/flutter (10360): 7
I/flutter (10360): delay 1 s
I/flutter (10360): 8
I/flutter (10360): delay 1 s
I/flutter (10360): 9
I/flutter (10360): delay 1 s
I/flutter (10360): 10
I/flutter (10360): delay 1 s
I/flutter (10360): 11
I/flutter (10360): delay 1 s
I/flutter (10360): 12
I/flutter (10360): delay 1 s
I/flutter (10360): 13
I/flutter (10360): delay 1 s
I/flutter (10360): 14
I/flutter (10360): delay 1 s
I/flutter (10360): 15
I/flutter (10360): delay 1 s
I/flutter (10360): 16
I/flutter (10360): delay 1 s
I/flutter (10360): 17
I/flutter (10360): delay 1 s
I/flutter (10360): 18
I/flutter (10360): delay 1 s
I/flutter (10360): 19
I/flutter (10360): delay 1 s
I/flutter (10360): 20
I/flutter (10360): delay 1 s
I/flutter (10360): 21
I/flutter (10360): delay 1 s
I/flutter (10360): 22
I/flutter (10360): delay 1 s
I/flutter (10360): 23
I/flutter (10360): delay 1 s
I/flutter (10360): 24
I/flutter (10360): delay 1 s
I/flutter (10360): 25
I/flutter (10360): delay 1 s
I/flutter (10360): 26
I/flutter (10360): delay 1 s
I/flutter (10360): 27
I/flutter (10360): delay 1 s
I/flutter (10360): 28
I/flutter (10360): delay 1 s
I/flutter (10360): 29
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 0-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 1-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 2-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 3-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 4-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 5-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 6-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 7-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 8-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 9-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 10-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 11-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 12-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 13-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 14-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 15-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 16-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 17-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 18-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 19-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 20-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 21-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 22-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 23-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 24-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 25-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 26-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 27-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 28-0
I/flutter (10360): Instance of 'PicDetailDownLoadProgressEvent'
I/flutter (10360): 29-0
I/flutter (10360): 30
I/flutter (10360): 30
I/flutter (10360): 1.0
```

**Comment by felangel** [comment] 2020-11-11 16:38
Hi @lsk569937453 👋 
Thanks for opening an issue!

Can you please provide a link to a sample app which reproduces the issue? It's hard for me to help without a reproduction sample 👍

**Comment by felangel** [comment] 2020-11-24 21:38
Closing for now since there isn't a reproduction sample.

**Closed by felangel** 2020-11-24 21:38 UTC
Labels: question, waiting for response

**Comment by sgsm74** [comment] 2021-12-01 11:37
is it possible to implement download progress bar using bloc?only using event and state
