### ISSUE TITLE
fix: Recreate cubit user pop screen using the back button

### ISSUE THREAD

**Issue by kusayp** [felangel/bloc#3062] opened 2021-12-14 11:28 UTC
**Description**
I have 2 screens, user details summary (screen 1) and update user details (screen 2). 

On screen 1, user get the summary of the user details from the api.
On screen 2, user able to update for instance email of the user.

When the user on screen 2 and is done updating the email. and clicks the back button to go back to screen 1. I want screen to rebuild and load the new updated data from the api. It seems unless the user manually refresh the page. The issue is back button close the cubit for screen 2 and therefore if you go back to screen 2 the screen rebuilds and shows the updated data. But for screen 1 the cubit is not destroyed again after you navigate forward and therefore if the come back the screen stays the same.

here is a simplified version of my widgets

Screen 1

`class PersonalInfoCubit extends Cubit<PersonalInfoState> {
  PersonalInfoCubit() : super(Initial());

  final CheckConnectivity network = getIt<CheckConnectivity>();
  final GetUserDataUsecase usecase = getIt<GetUserDataUsecase>();

Future<void> getUser() async {
    emit(Loading());
    final connectivity = await network.isConnected();
    Either<Failure, UpdateProfileEntity> getUserOrfailure;
    if (connectivity) {
      getUserOrfailure = await usecase.call(NoParams());
      emit(getUserOrfailure.fold((l) => Error(), (r) => Success(r)));
    } else {
      emit(Error());
    }
  }

class PersonalInfoScreen extends StatelessWidget {

@override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => PersonalInfoCubit()..getUser(),
      child: Scaffold(
        appBar: customAppBar(context, title: PERSONAL_INFO_APPBAR_TITLE),
        body: SafeArea(
          child: Container(
              padding: EdgeInsets.all(DEFAULT_PAGE_PADDING),
              child: BlocConsumer<PersonalInfoCubit, PersonalInfoState>(
                listener: (context, state) {
                },
                builder: (context, state) {
                  if (state is Loading) {
                    return Container();
                  }
                  if (state is Success) {
                    return RefreshIndicator(
                      onRefresh: () =>
                          context.read<PersonalInfoCubit>().getUser(),
                      child: ListView(
                        children: buildPersonalInfoList(context, state.user),
                      ),
                    );
                  }
                  return Container();
                },
              )),
        ),
      ),
    );
  }
}`

screen 2
`class UpdateSurnameCubit extends Cubit<UpdateSurnameState> {
  UpdateSurnameCubit() : super(UpdateSurnameState());

  final CheckConnectivity network = getIt<CheckConnectivity>();
  final UpdateSurnameUsecase usecase = getIt<UpdateSurnameUsecase>();

  Future<void> inputChanged(String value) async {
    final _input = SurnameInput.dirty(value);
    emit(UpdateSurnameState(input: _input, status: Formz.validate([_input])));
  }

  Future<void> updateButtonClicked() async {
    if (!state.status.isValidated) return;
    emit(UpdateSurnameState(
        status: FormzStatus.submissionInProgress, input: state.input));
    final connectivity = await network.isConnected();
    Either<Failure, UpdateProfileEntity> updateOrfailure;
    if (connectivity) {
      final user = UpdateProfileModel(
        surname: state.input.value,
      );
      updateOrfailure = await usecase.call(user);
      emit(updateOrfailure.fold(
          (l) => UpdateSurnameState(
              status: FormzStatus.submissionFailure,
              input: state.input,
              error: l.message),
          (r) => UpdateSurnameState(
              status: FormzStatus.submissionSuccess, input: state.input)));
    } else {
      emit(UpdateSurnameState(
          status: FormzStatus.submissionFailure,
          input: state.input,
          error: "$INTERNET_FAILURE_MESSAGE"));
    }
  }
}

class UpdateSurnameScreen extends StatelessWidget {
  const UpdateSurnameScreen({Key? key})
      : super(key: key);

@override
  Widget build(BuildContext context) {
return BlocProvider(
      create: (context) => UpdateSurnameCubit(),
      child: Scaffold(
        appBar: customAppBar(context, title: UPDATE_SURNAME_APPBAR_TITLE),
);
}`

Thank you

**Comment by felangel** [comment] 2021-12-15 22:53
Hi @kusayp 👋 
Thanks for opening an issue!

Can you please provide a link to a GitHub repo or DartPad that contains a minimal reproduction sample? Thanks!

**Comment by felangel** [comment] 2021-12-18 16:12
Closing for now since there’s no minimal reproduction sample. Feel free to comment with a link to a reproduction sample and I’m happy to take a closer look 👍

**Closed by felangel** 2021-12-18 16:12 UTC
Labels: question, waiting for response
