### ISSUE TITLE
feat: Cancel running events after closing the bloc

### ISSUE THREAD

**Issue by karvulf** [felangel/bloc#4214] opened 2024-07-24 13:01 UTC
**Description**
At first, thanks for this awesome package, this is really useful for our project.

My feature request is about handling asynchronous events. In my case I have an event which calls a usecase very often and it takes some time before this event was handled. 
If I close this bloc, the asynchronous calls are still running which leads to issues.

**Desired Solution**

So I wanted to ask if it's possible to call something to close all current running events, e.g. `cancelRunningEvents();`. 
Or the default behavior could be that it just cancels automatically all running events after closing the bloc.
Another idea would be to add some configuration to the bloc or to a specific event which tells it to stop the event after closing the bloc.

**Additional Context**

This is an example code which illustrates my issue:

```dart
class TestBloc extends Bloc<TestEvent, TestState> {
  TestBloc() : super(TestInitial()) {
    on<TestRunEvent>(this._onTestRunEvent);
  }

  @override
  Future<void> close() async {
    cancelAllRunningEvents(); // I would wish to something like this
    await super.close();
  }

  Future<void> _onTestRunEvent(
    TestRunEvent event,
    Emitter<TestState> emit,
  ) async {
    for (int i = 0; i < 10; i++) {
      if(isClosed) return; // I would like to prevent doing these checks

      print('Running with counter = $i');
      // currently this call is still running even though my bloc was closed
      await Future.delayed(const Duration(seconds: 2));
    }
  }
}
```

**Comment by felangel** [comment] 2024-07-26 05:21
This is a duplicate of https://github.com/felangel/bloc/issues/4165. Happy to continue the discussion there 👍

**Closed by felangel** 2024-07-26 05:21 UTC
