### ISSUE TITLE
Feature: Ability to handle a "beforeSaveState" or similar just for hydrate_bloc

### ISSUE THREAD

**Issue by JohnGalt1717** [felangel/bloc#2068] opened 2021-01-10 22:37 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be very nice to have some sort of method that we could override that gets called right before hydrate is going to do it's state change. 
The reason for this is that I have values that don't update the state until a specific event, but I would like to have it so that those values are persisted on recovery from hydration.  So basically it would either emit a new state in that function or replace the state that was going to be passed to toJson only for hydrate_bloc.

And if I just use the toJson then it interferes with replayJson where I don't want to have this done.

**Describe alternatives you've considered**
I tried intercepting toJson and comparing the 2 states there but because of the nature of streams this seems dangerous and also adds a lot of overhead.

**Comment by felangel** [comment] 2021-01-12 05:03
Hi @JohnGalt1717 👋 
Thanks for opening an issue!

I'm not sure I understand the usecase. Can you please provide a link to a reproduction sample that illustrates the problem you're facing?

I would recommend doing whatever you need to do in `toJson` because that is the code that executes just before persisting the state.

> And if I just use the toJson then it interferes with replayJson where I don't want to have this done.

I'm not sure I understand what you mean by this. As I mentioned above, I would really appreciate it if you could provide a reproduction sample that would better help me understand the issue, thanks! 🙏

**Comment by felangel** [comment] 2021-01-13 18:27
Closing for now because there isn't enough information for me to proceed. Feel free to comment with additional information and I'm happy to continue the conversation 👍

**Closed by felangel** 2021-01-13 18:27 UTC
Labels: question, waiting for response
