### ISSUE TITLE
First state is not being listened

### ISSUE THREAD

**Issue by II11II** [felangel/bloc#2002] opened 2020-12-08 16:06 UTC
### **First state is not being listened by BlocListener**

Navigating to second page by calling method in cubit which get data from network

![image](https://user-images.githubusercontent.com/45257709/101508225-36f90100-3999-11eb-99de-b270c496fe65.png)

--------------------------------------------------------------------------------------------------
Cubit class
![image](https://user-images.githubusercontent.com/45257709/101508127-1df05000-3999-11eb-9db2-d97372f7e92b.png)

--------------------------------------------------------------------------------------------------
UI Page where BlocListener not listening FIRST state
![image](https://user-images.githubusercontent.com/45257709/101508010-00bb8180-3999-11eb-94a3-f35684c5cd59.png)

**Comment by felangel** [comment] 2020-12-08 16:16
Hi @II11II 👋 
Thanks for opening an issue!

This is expected behavior because `BlocListener` is only triggered by state changes. The initial state is not considered a state change. In this case the cubit has likely already emitted loading before the BlocListener was mounted. I would recommend refactoring to add the event after `BlocListener` is mounted to ensure that no state changes are missed.

Hope that helps 👍

**Comment by II11II** [comment] 2020-12-08 16:22
Hi @felangel 
Thank you for your reply!
Now I understood the bug.

Can you provide any little example how to solve this kind problem, please?
Or could you give link where this kind of problem solved?

**Comment by felangel** [comment] 2020-12-08 16:31
One solution is to lift the `BlocListener` up one level and call `getFavorites` in `initState` of the child widget.

**Comment by II11II** [comment] 2020-12-08 16:32
So, I need to convert stateless widget to stateful widget in order to implement this solution?

**Comment by felangel** [comment] 2020-12-08 16:35
That's one way but I'm happy to suggest other solutions if you can provide a reproduction sample.

**Comment by II11II** [comment] 2020-12-08 16:41
Firstly, thank you. It is great that i can get the advice of expert)

I can provide the code.

Will it be easy for you if i give link to this project or should i put codes here ?

**Comment by felangel** [comment] 2020-12-08 16:42
No problem! Link to the project is best 👍

**Comment by II11II** [comment] 2020-12-08 16:45
https://github.com/II11II/online-shop

**Comment by II11II** [comment] 2020-12-08 16:48
![image](https://user-images.githubusercontent.com/45257709/101514363-fef4bc80-399e-11eb-88f5-fad4fec69000.png)

**Comment by II11II** [comment] 2020-12-08 17:13
Direction in project.

All pages and cubit/state are located in lib/ui/page/ folder.
Repository class provides data from network and cache.

The problem is in lib/ui/page/favourite/favorite_page.dart where blocListener is not listening first state, because i called function, that get data from network , in lib/ui/page/my_orders_page/my_orders_page.dart in the Widget fab(context) method.

**Comment by II11II** [comment] 2020-12-08 17:18
Mr @felangel, if i miss something or something is not clear, please mention about it.
I will refactor it and give needful information about unclear code if it is needed from your side.

**Comment by II11II** [comment] 2020-12-09 17:46
@felangel 
Is it good way to solve this problem?
BlocBuilder<MyCubit, MyState>(
      cubit: BlocProvider.of<MyCubit>(context)..myFunction(),
      builder: (BuildContext context, state) {

}

**Comment by II11II** [comment] 2020-12-11 15:05
The first state is being listened in builder field, but it is not being listened by listener field. I think it is a bug.

**Comment by II11II** [comment] 2020-12-11 17:06
The loading state is now being listened in listener, when i added Future before emit Loading state 
![image](https://user-images.githubusercontent.com/45257709/101932653-e84ba100-3bfc-11eb-8c26-fbc0e7691e18.png)

**Comment by II11II** [comment] 2020-12-16 10:32
> One solution is to lift the `BlocListener` up one level and call `getFavorites` in `initState` of the child widget.

Hi @felangel,
It does not work, the first is missing.

**Comment by II11II** [comment] 2020-12-16 10:32
i think it is BUG

**Comment by felangel** [comment] 2020-12-18 07:31
@II11II this is working as expected. BlocListener only starts listening for state changes once it is mounted in the widget tree. In this case, the state change happens before the BlocListener widget is mounted (which is why adding the future resolves the issue). You should lift up the BlocListener higher in the widget tree to ensure that no state changes are missed.

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-12-18 07:31 UTC
Labels: question, waiting for response

**Comment by II11II** [comment] 2020-12-18 10:58
> That's one way but I'm happy to suggest other solutions if you can provide a reproduction sample.

You said that you would suggest other solutions

**Comment by II11II** [comment] 2020-12-18 11:00
> @II11II this is working as expected. BlocListener only starts listening for state changes once it is mounted in the widget tree. In this case, the state change happens before the BlocListener widget is mounted (which is why adding the future resolves the issue). You should lift up the BlocListener higher in the widget tree to ensure that no state changes are missed.
> 
> Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

But it is being listened in builder method without any issue.
By the way, could you wash little example ,please ?
P.s. it will answer to all my questions

**Comment by felangel** [comment] 2021-01-06 06:07
@II11II the reason builder works is because the UI is because BlocBuilder builds whenever the framework decides to build and is not guaranteed to be called once for each state change (since there must always be a widget rendered each frame). I highly recommend applying the suggestion above to lift the `BlocListener` higher in the widget tree to ensure states are missed.
