### ISSUE TITLE
BlocBuilder is not calling

### ISSUE THREAD

**Issue by narenbishtve** [felangel/bloc#1041] opened 2020-04-13 12:59 UTC
I'm trying to filter an existing list in an event but facing issue on blocbuilder.
Event Class :  

class SearchProfessionEvent extends ProfessionEvents {
  String searchItem;
  List<Category> categoriesList;

  SearchProfessionEvent(this.searchItem, this.categoriesList);

  @override
  Stream<ProfessionsState> applyAsync(
      ProfessionsState state, ProfessionBloc bloc) async* {
    var newFilteredList = categoriesList
        .where((value) => value.categoryName.contains(searchItem));

    yield ProfessionSuccessState(newFilteredList);
  }
}

**Comment by felangel** [comment] 2020-04-13 13:55
Hi @narenbishtve 👋 
Thanks for opening an issue!

Please make sure to avoid mutating state and yielding the mutated state. Instead, create a copy of the state, modify it, and then yield it.

```dart
final updatedList = List.from(categoryList)..where((value) => value.categoryName.contains(searchItem));
yield ProfessionSuccessState(updatedList);
```

Hope that helps 👍

**Comment by narenbishtve** [comment] 2020-04-13 14:18
Hi @felangel ,
I can share you my bloc,event and state code here : 

///////////////// STATES ///////////////////////
abstract class ProfessionsState {
  const ProfessionsState();
}
class ProfessionDefaultState extends ProfessionsState {
}
class ProfessionLoaderState extends ProfessionsState {
}
class ProfessionSuccessState extends ProfessionsState {
  final List<Category> categories;
  ProfessionSuccessState(this.categories);
}
class ProfessionFailureState extends ProfessionsState {
}

////////////////////// EVENTS 

abstract class ProfessionEvents {
  Stream<ProfessionsState> applyAsync(
      ProfessionsState state, ProfessionBloc bloc);
}

class GetProfessionsEvent extends ProfessionEvents {
  @override
  Stream<ProfessionsState> applyAsync(
      ProfessionsState state, ProfessionBloc bloc) async* {
    yield ProfessionLoaderState();

    try {
      Map<String, String> params = Map();

      params["profile_cat"] = "1";

      var result = await NetworkClient()
          .createPostRequest(NetworkApis.getCategories, params);

      // var categories=result['response']['data']['category'];
      yield ProfessionSuccessState(
          DashboardResponseModel.fromJson(result).response.data.category);
    } catch (e) {
      yield ProfessionFailureState();
    }
  }
}

class SearchProfessionEvent extends ProfessionEvents {
  String searchItem;
  List<Category> categoriesList;

  SearchProfessionEvent(this.searchItem, this.categoriesList);

  @override
  Stream<ProfessionsState> applyAsync(ProfessionsState state, ProfessionBloc bloc) async* {
    var newFilteredList = categoriesList
        .where((value) => value.categoryName.contains(searchItem));

    yield ProfessionSuccessState(newFilteredList);
  }
}

////////////////// MAIN SCREEN

BlocBuilder<ProfessionBloc, ProfessionsState>(
                          builder: (context, state) {
                        if (state is ProfessionSuccessState) {
                          if (categoriesList == null)
                            categoriesList = state.categories;

                          tempCategoriesList = state.categories;

                          return ListView.builder(
                            itemBuilder: (context, position) {
                              return AppText(
                                  text: tempCategoriesList[position]
                                      .categoryName);
                            },
                            itemCount: tempCategoriesList.length,
                          );
                        } else {
                          return Container();
                        }
                      }),


//////////////////

 searchController.addListener(() {
      if (categoriesList != null && categoriesList.length > 0) {
        _professionBloc.add(SearchProfessionEvent(
            searchController.value.text, categoriesList));
      }
    });

**Comment by felangel** [comment] 2020-04-13 15:12
@narenbishtve can you please share a single `main.dart` which I can run locally that reproduces the issue? It's a lot easier to help if you can share a runnable piece of code than a bunch of individual snippets.

**Comment by narenbishtve** [comment] 2020-04-14 04:02
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      initialRoute: AppStringConstants.CALL_RATE,
      onGenerateRoute: AppRouteHandler.generateRoute,
      theme: ThemeData(
        scaffoldBackgroundColor: AppColors.white,
        primarySwatch: Colors.blue,
      ),
      home: ProfessionScreen(),
    );
  }
}

**Comment by felangel** [comment] 2020-04-16 00:39
@narenbishtve I meant can you share the link to a standalone flutter application that I can run locally? It's not very easy to help if you provide lots of scattered code snippets.

**Comment by felangel** [comment] 2020-04-17 15:27
Closing for now since there is no way to easily reproduce the issue.
Feel free to comment with a link to a sample app which reproduces the issue and I'm happy to take a look 👍

**Closed by felangel** 2020-04-17 15:27 UTC
Labels: question, waiting for response
