### ISSUE TITLE
Get rid of provider and InheritedWidgets in flutter_bloc

### ISSUE THREAD

**Issue by manyopensource** [felangel/bloc#1483] opened 2020-07-18 03:31 UTC
Is that ever going to happen? Maybe you're working on it right now? TIA!

**Comment by felangel** [comment] 2020-07-18 15:58
Hi @manyopensource 👋
Thanks for opening an issue!

This is a duplicate of #712 so please check it out and comment with your thoughts 👍

**Closed** 2020-07-18 15:59 UTC
Labels: duplicate
