### ISSUE TITLE
[Question] dynamic controller initialization

### ISSUE THREAD

**Issue by gvory** [felangel/bloc#3279] opened 2022-03-10 17:52 UTC
I cannot initialize the tabController accordingly by pulling the tabbar list from the bloc.
I can't init an operation that I normally do in initState because the block logics do not work async.

**Comment by felangel** [comment] 2022-03-15 17:53
Hi @gvory 👋 
Thanks for opening an issue!

Can you please provide a minimal reproduction sample that illustrates the issue you're facing? Are you able to provide equivalent code that doesn't use bloc to illustrate what you're trying to achieve? Thanks!

**Comment by gvory** [comment] 2022-03-15 20:30
`import 'package:flutter/material.dart';

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with SingleTickerProviderStateMixin {
  late final TabController _tabController;

  @override
  void initState() {
    super.initState();
    initTabController();
  }

  Future<void> initTabController() async {
    List<String> futureTabList = [
      'Tab1',
      'Tab2'
    ]; // List Comes from bloc logic and init controller(Future)
    await Future.delayed(Duration(milliseconds: 10));
    _tabController = TabController(length: futureTabList.length, vsync: this);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Column(
          children: [
            TabBar(controller: _tabController, tabs: []),
            TabBarView(controller: _tabController, children: [])
          ],
        ),
      ),
    );
  }
}
`


We can think through such a fiction.

**Comment by felangel** [comment] 2022-03-29 02:23
Hi @gvory 👋 

You should be able to add the event to the bloc when it is instantiated, perform the async logic in the bloc and react to various states in the UI via a `BlocBuilder`/`BlocListener`:

```dart
BlocProvider(
  create: (context) => MyBloc()..add(MyEventA()),
  child: ChildWidget(),
);
```

```dart
class MyBloc extends Bloc<MyEvent, MyState> {
  MyBloc() : super(MyState.initial()) {
    on<MyEventA>((event, emit) async {...});
  }
}
```

```dart
BlocBuilder<MyBloc, MyState>(
  builder: (context, state) {
    if (state is Loading) {...}
    if (state is Success) {...}
    if (state is Failure) {...}
  },
)
```

Hope that helps 👍

**Comment by felangel** [comment] 2022-04-04 21:59
Closing for now since but feel free to comment with any follow-up and I'm happy to continue the conversation 👍

**Closed by felangel** 2022-04-04 21:59 UTC
Labels: question, waiting for response
