### ISSUE TITLE
build: Can't use bloC with Socket IO

### ISSUE THREAD

**Issue by ThangStar** [felangel/bloc#3966] opened 2023-10-02 13:51 UTC
emit was called after an event handler completed normally.
This is usually due to an unawaited future in an event handler.
Please make sure to await all asynchronous operations with event handlers
and use emit.isDone after asynchronous operations before calling emit() to
ensure the event handler has not completed.

![image](https://github.com/felangel/bloc/assets/52882277/c147e560-5df1-4b14-8201-7c06c92c39e6)
![image](https://github.com/felangel/bloc/assets/52882277/39d2a1f0-ec8d-480a-a206-100a0581103d)

**Comment by felangel** [comment] 2023-10-14 21:38
Hi @ThangStar 👋 
Thanks for opening an issue!

In this case you need to register the socket listener outside of the event handler and you can manually manage the subscription like:

```dart
MyBloc() : super(MyState()) {
  _socketSubscription = io.on('response', (data) => emit(...));
  // ...
}
```

This logic shouldn't be inside an event handler since event handlers are called each time an event is added and you likely don't want to have multiple socket connections. Closing for now but if you're still having trouble feel free to provide a link to a minimal reproduction sample and I'm happy to take a closer look, thanks!

**Closed by felangel** 2023-10-14 21:38 UTC

**Comment by ThangStar** [comment] 2023-10-15 17:47
Thank you, that's a great answer <3
