### ISSUE TITLE
FlutterBloc: BlocSelector rebuilds with old value

### ISSUE THREAD

**Issue by merelj** [felangel/bloc#2644] opened 2021-08-02 10:25 UTC
**Describe the bug**
Even though selector result is changing (`id` in my example, which is a wrapping widget prop), widget is still rebuilt with old data

**To Reproduce**
```
class WrappingWidget extends StatelessWidget {
  final String id;
  const WrappingWidget(
    this.id
  );

  @override
  Widget build(BuildContext context) {
    return BlocSelector<UsersBloc, UsersState, UserModel?>(
        selector: (state) => state.usersHashmap[id], // User or null; User is immutable
        builder: (ctx, user) { // here user never changes even if id is changed and widget is rebuilt
            // final user = GetIt.I<UsersBloc>().state.usersHashmap[id]; // here user is correct
          return UserName(user, key: ValueKey(id));
        },
    );
  }
}

```

**Expected behavior**
Widget is rebuilt with new data.

**Logs **
> Run `flutter analyze` and attach any output of that command below.

Analyzing my_awesome_app...
No issues found! (ran in 4.1s)

> Paste the output of running `flutter doctor -v` here.

[✓] Flutter (Channel unknown, 2.2.2, on Mac OS X 10.15.7 19H15 darwin-x64,
    locale en-RU)
    • Flutter version 2.2.2 at /Users/merelj/development/flutter
    • Framework revision d79295af24 (7 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/merelj/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • EC5D5C9D-6A51-4A3A-B114-417DF89407EF • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)

P.S.: BlocSelector is awesome -- and such a step forwards from BlocBuilder! ❤️ 
I refactored our whole app to use it, but ran into this issue.

**Comment by merelj** [comment] 2021-08-02 10:30
Same code with BlocBuilder works:

```
class WrappingWidget extends StatelessWidget {
  final String id;
  const WrappingWidget(
    this.id
  );

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<UsersBloc, UsersState>(
        buildWhen: (prev, cur) => prev.usersHashmap[id] != cur.usersHashmap[id],
        builder: (ctx, state) {
            final user = state.usersHashmap[id]
            return UserName(user, key: ValueKey(id));
        },
    );
  }
}
```

**Comment by felangel** [comment] 2021-08-02 13:40
Hi @merelj 👋
Thanks for opening an issue and for the positive feedback!

Can you please provide a link to a minimal reproduction sample? I’m happy to take a closer look, thanks!

**Comment by merelj** [comment] 2021-08-03 09:02
```
name: bug
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

```

```
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(textTheme: TextTheme(bodyText2: TextStyle(fontSize: 20))),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

final initState = {
  '0': UserModel('Alice'),
  '1': UserModel('Bob'),
  '2': UserModel('Carol'),
  '3': UserModel('Dave'),
};

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('ID: $_counter'),
            BlocProvider(create: (ctx) =>
              UsersBloc(initState),
              child: UserInfo('$_counter'),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => setState(() => _counter > 3 ? _counter = 0 : _counter++),
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

class UserInfo extends StatelessWidget {
  final String id;
  const UserInfo(this.id);

  @override
  Widget build(BuildContext context) {
    return BlocSelector<UsersBloc, Map<String, UserModel>, UserModel?>(
        // it all works if you add "bloc: UsersBloc(initState) " here instead of getting it from context
        selector: (state) => state[id],
        builder: (ctx, user) {
          final correctUser = BlocProvider.of<UsersBloc>(context).state[id];
          return Column(children: [
            Text("SELECTOR: ${user?.name ?? 'No User'}"),
            Text("PROVIDER: ${correctUser?.name ?? 'No User'}"),
          ]);
        }
    );
  }
}

class UserModel {
  final String name;
  const UserModel(this.name);
}

class UsersBloc extends Bloc<Object, Map<String, UserModel>> {
  UsersBloc(Map<String, UserModel> initialState) : super(initialState);
  @override
  Stream<Map<String, UserModel>> mapEventToState(Object event) async* { yield state; }
}
```

**Comment by merelj** [comment] 2021-08-03 09:06
https://user-images.githubusercontent.com/3993495/127989386-c823468a-6001-43c8-92b9-bff2e6dce822.mp4

**Comment by elianmortega** [comment] 2021-08-03 13:49
Hello @merelj,

the issue here is not with the bloc selector, in fact bloc selector is working great as  the selected should not be changing.

You are changing an `id` not the state of the `Bloc` for that reason the selector is not being updated. And it works when adding `bloc: UsersBloc(initState)` because what you are doing in there is creating a new `Bloc` instance for every build of the widget.

**Comment by merelj** [comment] 2021-08-03 13:57
oh, I see now, thank you 🙇 

could you give any suggestions on what would be a good alternative approach in this case?

my first idea was to add `key: ValueKey(id)` to `BlocSelector` for it to be rebuild on changes to id, but it didn't help.

**Comment by elianmortega** [comment] 2021-08-03 14:46
I see, but int that case you want your `Bloc` state to change without adding a new event. You're only modifying a variable in the UI, if you want to make changes to the state of the bloc you should add a new event and holding logic to change the state.

I could recreate your example but I think is better for you to checkout some of the [bloc library dev examples](https://bloclibrary.dev/#/flutterfirestoretodostutorial).

**Comment by merelj** [comment] 2021-08-04 08:30
There are no examples of `BlocSelector` in examples.

I already have included 2 viable workarounds in my code above. It's not a question of "how could I implement that logic using flutter_bloc?".

What I did want to know was "is there a recommended way to implement it using `BlocSelector` without unnecessary boilerplate code of `BlocProvider` inside `BlocSelector`, `BlocBuilder` and its `.buildWhen` method that often introduces bugs during refactors or new events that don't really do anything?"

I guess not.

I also don't think that current behaviour is obvious (especially since it is dissimilar to BlocBuilder) -- especially with no documentation and no examples.

Thank you.

**Comment by elianmortega** [comment] 2021-08-04 13:40
Hello @merelj I recommended looking at the bloc library examples because on the reproduction code you provided the logic was wrong and to learn the general good practices when using flutter_bloc.

I took the time and created an example for you of how to use BlocSelector:

Its a small counter app with two variables, the bloc selector is used so that only if the selected variable changes the widget will be rebuild, to check that I added a `DateTime` object so you can see that only the widget of the property being changed is rebuilt. 

### Demo:

https://user-images.githubusercontent.com/54898038/128191017-3112b22e-4412-43ec-8961-2799ba01be40.mov


### Code:

```dart
```

**Comment by felangel** [comment] 2021-08-04 13:42
> There are no examples of `BlocSelector` in examples.
> 
> I already have included 2 viable workarounds in my code above. It's not a question of "how could I implement that logic using flutter_bloc?".
> 
> What I did want to know was "is there a recommended way to implement it using `BlocSelector` without unnecessary boilerplate code of `BlocProvider` inside `BlocSelector`, `BlocBuilder` and its `.buildWhen` method that often introduces bugs during refactors or new events that don't really do anything?"
> 
> I guess not.
> 
> I also don't think that current behaviour is obvious (especially since it is dissimilar to BlocBuilder) -- especially with no documentation and no examples.
> 
> Thank you.

The example you provided will not work because your blocs always yields state. This means that no state changes will occur because the yielded state will always be identical to the current state. I highly recommend reading the [core concepts](https://bloclibrary.dev/#/coreconcepts) and updating your bloc implementation to emit a new state instance.

In addition, the bloc should manage the state and include any business logic needed when new events are added. Currently the bloc you have isn’t really doing anything and you’re managing the state in your UI.

**Comment by merelj** [comment] 2021-08-04 16:43
Thank you for your time.
I guess I am at fault here for not explaining my problem clearly, since unfortunately your example does not answer my question at all.. 😞 

I honestly **DO** understand that in my example the bloc wasn't doing anything.
**That is due to the fact that I was required to provide a "minimal reproduction sample" and my problem has nothing to do with state changes in response to events.** I promise you, in the app I am developing the Map inside the state is changed by events 😄 . But the selector function still depends on bloc state **AND** the widget building BlocSelector.

So what I am looking for is a way for my data to update **NOT ONLY** due to bloc changes (this part already works perfect, so I didn't think to illustrate it; I can if it would help to get my point across 👀 ), but also **as a result of widget state or argument changes**. 🤓 

I hope this makes my question more clear:
- does bloc package require that absolutely ALL of the state management (including the most minuscule UI changes in deeply nested widget) should **only** be handled by blocs and no other state management solutions (like StatefulWidget's setState) can ever be used in the app? 🐷 
- if the first answer is "no", is there a way to use BlocSelector so that it would rebuild its child if **EITHER** data in the bloc's state OR outside data changes? 🤝

**Comment by felangel** [comment] 2021-08-07 21:45
> Thank you for your time. 🙇
> I guess I am at fault here for not explaining my problem clearly, since unfortunately your example does not answer my question at all.. 😞
> 
> I honestly **DO** understand that in my example the bloc wasn't doing anything.
> **That is due to the fact that I was required to provide a "minimal reproduction sample" and my problem has nothing to do with state changes in response to events.** I promise you, in the app I am developing the `Map<String, UserModel>` inside the state is changed by events 😄 . But the result of selector function call still depends on bloc state **AND** the widget building BlocSelector.
> 
> So what I am looking for is a way for my data to update **NOT ONLY** due to bloc changes (this part already works perfect, so I didn't think to illustrate it; I can if it would help to get my point across 👀 ), but also **as a result of widget's state or argument changes**. 🤓
> 
> I hope this makes my question more clear:
> 
> * does bloc package require that absolutely ALL of the state management (including the most minuscule UI changes in deeply nested widget) should **only** be handled by blocs and no other state management solutions (like StatefulWidget's setState) can ever be used in the app? 🐷
> * if the first answer is "no", is there a way to use BlocSelector so that it would rebuild its child if **EITHER** data in the bloc's state OR outside data changes? 🤝

Hi @merelj `BlocSelector` works with bloc state only. If you decide to maintain state within your widget tree then you are responsible for managing when/how often you call `setState` to rebuild your UI.

In general I don't recommend mixing responsibilities and having some state managed by a widget and other managed by a cubit/bloc when they are closely related.

Unfortunately, there's not really a good way for a `BlocSelector` to know about data outside of the bloc (nor should it care imo).

Let me know if that helps and if you still have questions could you provide a reproduction sample that more closely illustrates what you're trying to achieve? Thanks! 🙏

**Comment by felangel** [comment] 2021-08-11 17:52
Closing for now but feel free to comment with additional comments/questions and I'm happy to continue the conversation 👍

**Closed by felangel** 2021-08-11 17:52 UTC
Labels: question, waiting for response, pkg:flutter_bloc
