### ISSUE TITLE
[User Problem] Issue with state not updating after initial state 

### ISSUE THREAD

**Issue by SungHyun-Patrick-Lee** [felangel/bloc#3026] opened 2021-12-02 14:15 UTC
**Description**

the first TimerUpdateState worked fine. But it doesn't work since the first TimerUpdateState.
I checked that the State is being received correctly.
There is no screen change through 'return _TimerWidget(timerTime: state.time)'.

**code**

- TimerWidget

```
class TimerWidget extends StatelessWidget {
  TimerWidget({Key? key}) : super(key: key);

  TimerCubit? _timerCubit;

  @override
  Widget build(BuildContext context) {
    _timerCubit = BlocProvider.of<TimerCubit>(context);
    _timerCubit!.getTimerTime();

    return BlocBuilder<TimerCubit, TimerCubitState>(
      bloc: _timerCubit,
      builder: (context, state) {
        if (state is TimerUpdateState) {
          return _TimerWidget(
            timerTime: state.time,
          );
        }

        return Container();
      },
    );
  }
}

class _TimerWidget extends StatefulWidget {
  TimerTime timerTime;

  _TimerWidget({
    required this.timerTime,
  });

  @override
  __TimerWidgetState createState() => __TimerWidgetState();
}

class __TimerWidgetState extends State<_TimerWidget>
    with SingleTickerProviderStateMixin {
  late TimerController _timerController;
  late AudioPlayer _player;
  TimerCubit? _timerCubit;

  @override
  void initState() {
    super.initState();
    _timerController = TimerController(this);
    _player = AudioPlayer();
  }

  @override
  void dispose() {
    super.dispose();
    _timerController.dispose();
    _player.dispose();
  }

  @override
  Widget build(BuildContext context) {
    _timerCubit = BlocProvider.of<TimerCubit>(context);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.center,
      mainAxisAlignment: MainAxisAlignment.start,
      children: [
        SizedBox(
          height: 80,
        ),
        Text(
          "잡고 싶은 기회를\n떠올려 보세요",
          textAlign: TextAlign.center,
          style: TextStyle(
            fontSize: 20,
            fontWeight: FontWeight.bold,
            height: 1.4,
          ),
        ),
        SizedBox(
          height: 48,
        ),
        SizedBox(
          height: 250,
          width: 250,
          child: InkWell(
            child: SimpleTimer(
              controller: _timerController,
              duration: Duration(seconds: widget.timerTime.time),
              progressTextStyle: TextStyle(fontSize: 50),
              onStart: () async {
                await _player.setAsset(AUDIO_SUCCESS_KEY);
                _player.play();
              },
              onEnd: () async {
                await _player.setAsset(AUDIO_SUCCESS_KEY);
                _player.play();
                _showAdDialog();
              },
            ),
            onTap: () {
              _showChangeTimerDialog();
            },
          ),
        ),
        SizedBox(
          height: 24,
        ),
        Row(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            IconButton(
              onPressed: () {
                _timerController.start();
              },
              icon: Container(
                child: Icon(
                  Icons.play_arrow,
                  size: 40,
                ),
              ),
            ),
            SizedBox(
              width: 30,
            ),
            IconButton(
              onPressed: () {
                _timerController.stop();
              },
              icon: Container(
                child: Center(
                  child: Icon(
                    Icons.stop,
                    size: 38,
                  ),
                ),
              ),
            ),
            SizedBox(
              width: 30,
            ),
            IconButton(
              onPressed: () {
                _timerController.reset();
              },
              icon: Container(
                child: Center(
                  child: Icon(
                    Icons.replay,
                    size: 34,
                  ),
                ),
              ),
            )
          ],
        )
      ],
    );
  }

  void _showAdDialog() {
    showDialog(
      context: context,
      useSafeArea: true,
      builder: (context) {
        return TimerAdWidget();
      },
    );
  }

  void _showChangeTimerDialog() {
    Picker(
      adapter: NumberPickerAdapter(data: <NumberPickerColumn>[
        const NumberPickerColumn(begin: 0, end: 5),
        const NumberPickerColumn(begin: 0, end: 59),
      ]),
      delimiter: <PickerDelimiter>[
        PickerDelimiter(
          child: Container(
            width: 30.0,
            alignment: Alignment.center,
            child: Icon(Icons.more_vert),
          ),
        )
      ],
      hideHeader: true,
      title: const Text('Select duration'),
      selectedTextStyle: TextStyle(color: Colors.blue),
      cancelText: "취소",
      confirmText: "확인",
      onConfirm: (picker, selected) {
        final minute = selected[0];
        final second = selected[1];

        final int time = 60 * minute + second;

        if (time == 0) {
          showToast("0 분 0 초는 입력하실 수 없습니다.");
          return;
        }

        _timerCubit!.changeTimerTime(TimerTime(time: time));
      },
    ).showDialog(context);
  }
}
```

- TimerCubit

```
class TimerCubit extends Cubit<TimerCubitState> {
  final GetTimerTime getTimerTimeUsecase;
  final ChangeTimerTime changeTimerTimeUsecase;

  TimerCubit({
    required this.getTimerTimeUsecase,
    required this.changeTimerTimeUsecase,
  }) : super(TimerInitState());

  void getTimerTime() async {
    final result = await getTimerTimeUsecase.getTimerTime();

    emit(TimerLoadingState());

    result.fold(
      (failure) {
        // TODO 개발 필요
      },
      (success) {
        emit(TimerUpdateState(time: success));
      },
    );
  }

  void changeTimerTime(TimerTime time) async {
    emit(TimerLoadingState());

    final result = await changeTimerTimeUsecase.changeTimerTime(time);

    result.fold(
      (failure) {
        // TODO 개발 필요
      },
      (success) {
        emit(TimerUpdateState(time: success));
      },
    );
  }
}
```

- TimerState

```
class TimerCubitState extends Equatable {
  @override
  List<Object?> get props => [];
}

class TimerInitState extends TimerCubitState {}

class TimerLoadingState extends TimerCubitState {}

class TimerUpdateState extends TimerCubitState {
  final TimerTime time;

  TimerUpdateState({required this.time});

  @override
  List<Object?> get props => [this.time];
}
```

**Comment by felangel** [comment] 2021-12-03 02:40
Hi @SungHyun-Patrick-Lee 👋 
Thanks for opening an issue!

I'm guessing you are either re-emitting the exact same state or your `TimerTime` class doesn't override `==` or extend `Equatable` properly. Please refer to the [FAQs](https://bloclibrary.dev/#/faqs?id=state-not-updating) for more details/examples.

Closing for now but if you're still having trouble please feel free to provide a link to a minimal reproduction sample and I'm happy to take a closer look 👍

**Closed by felangel** 2021-12-03 02:40 UTC
Labels: question

**Comment by SungHyun-Patrick-Lee** [comment] 2021-12-03 02:43
Thank you for response felangel

I already extends Equatable in TimerTime Class

```
class TimerTime extends Equatable {
  final int time;

  TimerTime({required this.time});

  @override
  List<Object?> get props => [time];
}
```

**Comment by felangel** [comment] 2021-12-03 02:46
> Thank you for response felangel
> 
> I already extends Equatable in TimerTime Class
> 
> ```
> class TimerTime extends Equatable {
>   final int time;
> 
>   TimerTime({required this.time});
> 
>   @override
>   List<Object?> get props => [time];
> }
> ```

Are you able to provide a link to a complete reproduction sample?

**Comment by SungHyun-Patrick-Lee** [comment] 2021-12-03 02:50
I'll remove link after you check

https://github.com/SungHyun-Patrick-Lee/imagine_30s

**Comment by felangel** [comment] 2021-12-03 02:57
> I'll remove link after you check
> 
> https://github.com/SungHyun-Patrick-Lee/imagine_30s

I'm not able to access that link.

**Comment by SungHyun-Patrick-Lee** [comment] 2021-12-03 03:03
Now I'm change

**Comment by felangel** [comment] 2021-12-03 03:07
> Now I changed

Thanks! What's the exact issue? The timer looks like it's working to me. I can start, stop and restart it and it appears to be working.

**Comment by SungHyun-Patrick-Lee** [comment] 2021-12-03 03:09
change time is not working

```
void _showChangeTimerDialog() {
    Picker(
      adapter: NumberPickerAdapter(data: <NumberPickerColumn>[
        const NumberPickerColumn(begin: 0, end: 5),
        const NumberPickerColumn(begin: 0, end: 59),
      ]),
      delimiter: <PickerDelimiter>[
        PickerDelimiter(
          child: Container(
            width: 30.0,
            alignment: Alignment.center,
            child: Icon(Icons.more_vert),
          ),
        )
      ],
      hideHeader: true,
      title: const Text('Select duration'),
      selectedTextStyle: TextStyle(color: Colors.blue),
      cancelText: "취소",
      confirmText: "확인",
      onConfirm: (picker, selected) {
        final minute = selected[0];
        final second = selected[1];

        final int time = 60 * minute + second;

        if (time == 0) {
          showToast("0 분 0 초는 입력하실 수 없습니다.");
          return;
        }

        _timerCubit!.changeTimerTime(TimerTime(time: time));
      },
    ).showDialog(context);
  }
```

this part

**Comment by felangel** [comment] 2021-12-03 03:16
> void _showChangeTimerDialog() {
>     Picker(
>       adapter: NumberPickerAdapter(data: <NumberPickerColumn>[
>         const NumberPickerColumn(begin: 0, end: 5),
>         const NumberPickerColumn(begin: 0, end: 59),
>       ]),
>       delimiter: <PickerDelimiter>[
>         PickerDelimiter(
>           child: Container(
>             width: 30.0,
>             alignment: Alignment.center,
>             child: Icon(Icons.more_vert),
>           ),
>         )
>       ],
>       hideHeader: true,
>       title: const Text('Select duration'),
>       selectedTextStyle: TextStyle(color: Colors.blue),
>       cancelText: "취소",
>       confirmText: "확인",
>       onConfirm: (picker, selected) {
>         final minute = selected[0];
>         final second = selected[1];
> 
>         final int time = 60 * minute + second;
> 
>         if (time == 0) {
>           showToast("0 분 0 초는 입력하실 수 없습니다.");
>           return;
>         }
> 
>         _timerCubit!.changeTimerTime(TimerTime(time: time));
>       },
>     ).showDialog(context);
>   }

I don't see that code in the repository. Are you sure you pushed your changes?

**Comment by SungHyun-Patrick-Lee** [comment] 2021-12-03 03:18
i'm sorry i didn't commit cause this issue :(

**Comment by felangel** [comment] 2021-12-03 03:31
@SungHyun-Patrick-Lee I opened a [pull request](https://github.com/SungHyun-Patrick-Lee/imagine_30s/pull/1) with the fixes.

**Comment by SungHyun-Patrick-Lee** [comment] 2021-12-03 03:33
Thank you sooo much!!!!!

**Comment by felangel** [comment] 2021-12-03 03:35
> Thank you sooo much!!!!!

No problem!
