### ISSUE TITLE
UI Freeze with complex State

### ISSUE THREAD

**Issue by andrea689** [felangel/bloc#1576] opened 2020-08-05 09:39 UTC
**Describe the bug**
I have a state with this prop: `Map<int, Map<int, MyObject>>`

Where `MyObject` have this props:

```
 Map<int, SplayTreeSet<MyObject2>>
 Map<int, SplayTreeSet<MyObject2>>
 SplayTreeSet<MyObject2>
 SplayTreeSet<MyObject2>
 int
 int
```

And `MyObject2` have `Date` and `double` props.

Every `SplayTreeSet` have 30 items.

When I yield a new state, in the web I have a freeze of ~3 sec, and in iOS a freeze of ~200ms.

I found that the freezes are due to the equality of the state in this lines:

https://github.com/felangel/bloc/blob/master/packages/bloc/lib/src/bloc.dart#L242

https://github.com/felangel/bloc/blob/master/packages/bloc/lib/src/cubit.dart#L80

How come the UI freeze? in your opinion how can I solve?

Thank you!

**Comment by andrea689** [comment] 2020-08-05 09:50
If I bypass the equals with a random number (`random.nextDouble()`) instead of the field of the state in `props` the equals is more fast (~10ms) and the UI not freeze, but the state is always changed even if is equal to previous state..

**Comment by felangel** [comment] 2020-08-05 13:28
Hi @andrea689 👋
Thanks for opening an issue!

Are you able to share a link to a sample app which reproduces the issue? Thanks!

**Comment by andrea689** [comment] 2020-08-05 14:42
Hi @felangel,
this is a simple example: https://github.com/andrea689/bloc_freeze

The timing is lower for the simplicity of the project, try to run on web to see better the freeze.

If you use the commented `props` the problem disappear: https://github.com/andrea689/bloc_freeze/blob/master/lib/bloc/custom_state.dart#L14

**Comment by felangel** [comment] 2020-09-03 04:44
Hi @andrea689 I took a look and the issue is the bloc state is nested map with a large amount of elements (100) and in order for `equatable` to compute whether the values are equal using `DeepCollectionEquality` it must compare each element in the map. You could avoid extending equatable in this case if you don't care about having value equality or alternatively you can manually override `==` and `hashCode` to reduce the computation. In any case, I'm going to close this issue since the question is related to `equatable`.

Feel free to [open an issue in equatable](https://github.com/felangel/equatable/issues) if you would like to further discuss alternatives 👍

**Closed by felangel** 2020-09-03 04:44 UTC
Labels: question
