### ISSUE TITLE
docs: implementation 1 bloc with 2 screen asyncronously conflict state.

### ISSUE THREAD

**Issue by davidwidjaya** [felangel/bloc#3895] opened 2023-07-01 11:47 UTC
Im asking for bloc state implementation, and the usecase below:

**I have 1 bloc named UsersBloc which is have event on<GetProfileRequested> that fetching an API...**
UsersBloc has 3 state : Success(), Loading(), and Failed().

I add event "GetProfileRequested" to the bloc on **HomeScreen & ProfileScreen which these two page RENDERED AT THE SAME TIME.**

Asyncronously the bloc return state at the same time, then make conflict state.

Im just have my solution : i adding Future.delayed for 1 seconds to ProfileScreen that prevent conflict state.

Anybody have a good solution?
Thankyou

**Comment by codesculpture** [comment] 2023-07-01 12:29
Can u just provide a code snippet that how u are doing. And by ur question HomeScreen and ProfileScreen is being has depend on the UserBloc right. So why its making conflict state. Please add any repo or more information

**Comment by felangel** [comment] 2023-10-14 21:40
Closing for now since there aren't any actionable next steps without a minimal reproduction sample. Feel free to file a new issue with a minimal reproduction sample if this is still an issue, thanks!

**Closed by felangel** 2023-10-14 21:40 UTC
Labels: documentation
