### ISSUE TITLE
question: BlocObserver and Injectable Singletons

### ISSUE THREAD

**Issue by psyfreak** [felangel/bloc#4141] opened 2024-04-04 15:52 UTC
**Question**
What is the best way to use BlocObserver for logging purpose with the [injectable](https://pub.dev/packages/injectable) singletons?

**Setup**
I have a BlocObserver logging most of the standard functions such as onCreate, onChange etc.
It is working well if my Blocs are annotated as "injectable" or "lazySingleton" but the BlocObserver is not logging for "singleton".
When I add for example an onChange(Change<State> change) directly  into the bloc it properly logs.
My assumption is that singleton blocs are created before the BlocObserver is "alive".

Thank you in advance.

**Comment by felangel** [comment] 2024-04-04 18:19
Hi @psyfreak 👋 
Thanks for opening an issue!

Can you please share a link to a minimal reproduction sample that illustrates the issue? Thanks!

**Comment by psyfreak** [comment] 2024-04-04 21:40
you are welcome. I will, but it may take a while. 
I also corrected the above. It works with lazySingleton annotation but not with singleton.

**Comment by felangel** [comment] 2024-04-20 04:09
Since there's no actionable next steps, I'm going to close this issue but once you have time to create a minimal reproduction sample, let me know and I'm happy to revisit this, thanks!

**Closed by felangel** 2024-04-20 04:09 UTC
Labels: question, waiting for response, needs repro info
