### ISSUE TITLE
feat:  Ability to expose/flatten nested blocs/cubits

### ISSUE THREAD

**Issue by iulian0512** [felangel/bloc#3660] opened 2022-12-08 15:28 UTC
**Description**

I would like to be able to expose (flatten) nested child blocs/cubits.

**Desired Solution**

```
//cubits
class ChildCubit extends Cubit{}

class ParentCubit extends Cubit 
{
  ChildCubit childcub;
}
//end cubits 

//widget
@override
Widget build(BuildContext _) {
  return MultiBlocProvider(
      providers: [
        BlocProvider(create: (_) => ParentCubit()),
        //provide the nested child cubit but not as a standalone instance
        //something like BlocProvider.value(value: parentCubitInstance.childcub)
      ],
      //if ChildCubit is not provided above this will fail
      child: BlocBuilder<ChildCubit, ChildCubitState>(
        //i don't want to do this !!
        bloc: BlocProvider.of<ParentCubit>(someContext).childcub
        builder: (context, state) {
          return Container();
        },
      ));
}
```

I know i can nest some BlocProviders but this is not optimal and when there are multiple nestings some performance degradation will occur.

**Comment by felangel** [comment] 2022-12-27 00:58
Hi @iulian0512 👋 
Thanks for opening an issue!

I'm not sure I fully understand the issue you're describing. Can you please elaborate and provide a minimal reproduction sample to illustrate the problem? Thanks!

**Comment by felangel** [comment] 2023-01-02 22:32
Closing for now since there is not enough information to help but I'm happy to continue the conversation if you're able to provide a link to a minimal reproduction sample with additional context, thanks!

**Closed by felangel** 2023-01-02 22:32 UTC
Labels: question, waiting for response

**Comment by iulian0512** [comment] 2023-01-03 08:40
@felangel  i have created a minimal example below, this can be reopened
```
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

void main() {
  runApp(const MyApp());
}

class ChildCubit extends Cubit<String> {
  ChildCubit() : super("this is child nested cubit");
}

class ParentCubit extends Cubit<String> {
  final ChildCubit child;
  ParentCubit()
      : child = ChildCubit(),
        super("this is parent cubit with a nested child");
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      //I need a way to expose ChildCubit, a nicer way other than nesting 2 BlocProviders which when the nesting has more than one level
      //there are performance issues
      providers: [BlocProvider(create: (_) => ParentCubit())],
      //this will fail because ChildCubit is not exposed
      child: BlocBuilder<ChildCubit, String>(
        builder: (context, state) => _buildAnotherWidget(),
      ),
    );
  }

  Widget _buildAnotherWidget() => BlocBuilder<ParentCubit, String>(
        builder: (context, state) => Container(),
      );
}

```
