### ISSUE TITLE
[Question] Current Location for Google Maps on App Start

### ISSUE THREAD

**Issue by danielyoon** [felangel/bloc#924] opened 2020-02-28 06:44 UTC
Hello @felangel !!

So I've been fiddling with BLoC for a few days and seem to have gotten the hang of it.
Been trying to use BLoC with Google Maps but having trouble implementing it.

So I have a userRepository that gets the current location in the constructor, and it's built right under the main app screen, but by the time I get to the Map Screen, it keeps giving me an error saying the current position is null. I'm sure using the RepositoryBloc is the correct solution, but am confused how to approach the situation. 

Any help?

**Comment by felangel** [comment] 2020-02-28 15:36
Hi @danielyoon 👋 
Thanks for opening an issue!

Are you able to share a link to a sample app which illustrates the issue you're facing? Thanks!

**Comment by felangel** [comment] 2020-03-02 00:23
Closing for now since there aren't reproduction steps. Feel free to add a link to a sample app and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-03-02 00:23 UTC
Labels: question, waiting for response

**Comment by danielyoon** [comment] 2020-03-06 05:17
```
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(
    RepositoryProvider(
      create: (context) => UserRepository(),
      child: MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final userRepository = RepositoryProvider.of<UserRepository>(context);
    return MaterialApp(
      home: userRepository.initialPosition == null
          ? SafeArea(
              child: Scaffold(
                body: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: <Widget>[
                    CircularProgressIndicator(),
                  ],
                ),
              ),
            )
          : Stack(
              children: <Widget>[
                GoogleMap(
                  initialCameraPosition: CameraPosition(
                      target: userRepository.initialPosition, zoom: 10.0),
                  onMapCreated: userRepository.onCreated,
                  myLocationButtonEnabled: true,
                )
              ],
            ),
    );
  }
}
```

```
class UserRepository {
  static LatLng _initialPosition;
  LatLng _lastPosition = _initialPosition;
  LatLng get initialPosition => _initialPosition;
  LatLng get lastPosition => _lastPosition;
  GoogleMapController _mapController;
  GoogleMapController get mapController => _mapController;

  UserRepository() {
    _getUserLocation();
    _loadingInitialPosition();
  }

  void _getUserLocation() async {
    print("Getting user location...");
    LocationData location = await Location().getLocation();
    _initialPosition = LatLng(location.latitude, location.longitude);
    print("Current latitude: ${location.latitude}");
    print("Current longitutde: ${location.longitude}");
  }
```
Something like this without getting too in-depth into. Don't know if I'm using RepositoryProvider correctly, or if it's not being provided to the Map's parameter? I see the print statements being printed in console, but the map never loads.

**Comment by felangel** [comment] 2020-03-15 00:43
@danielyoon would it be possible for you to share a link to a sample app which I can run locally to reproduce the issue you're having? Thanks!
