### ISSUE TITLE
Not updating UI on Deleting an Item from List

### ISSUE THREAD

**Issue by jaydangar** [felangel/bloc#1847] opened 2020-10-21 06:43 UTC
Hello I am working on an app where I need to use List<String> as data. I am able to add new String into the list, and clear it. But  There's one feature in which I need to clear Items one by one from the last index. using bloc I am able to clear last Item once, but then nothing happens in terms of UI, in Bloc the data are being updated. Kindly look into the code and suggest some ideas. Thanks & Regards.

My Bloc Consumer to update UI : 

```
BlocConsumer<QuizBloc, QuizState>(
            listener: (context, state) {
              if (state is QuizClearState) {
                activateAllButtons();
              }
            },
            builder: (context, state) {
              return BlocBuilder<QuizBloc, QuizState>(
                cubit: BlocProvider.of<QuizBloc>(context),
                builder: (context, state) {
                  if (state is QuizOutputState) {
                    _userAnswer = state.outputString.join(" ");
                  } else if (state is QuizClearState) {
                    _userAnswer = state.outputString.join(" ");
                  } else if (state is QuizRemoveState) {
                    _userAnswer = state.outputString.join(" ");
                  }
                  return UserInputWidget(userAnswer: _userAnswer);
                },
              );
            },
          ),
```

UI (Buttons for UI updation):

```
Expanded(
                      flex: 1,
                      child: Row(
                        children: [
                          IconButton(
                              icon: Icon(Icons.clear),
                              onPressed: () =>
                                  BlocProvider.of<QuizBloc>(context)
                                      .add(ResetInputEvent())),
                          IconButton(
                              icon: Icon(Icons.backspace),
                              onPressed: () =>
                                  BlocProvider.of<QuizBloc>(context)
                                      .add(RemoveLastStringEvent())),
                        ],
                        mainAxisAlignment: MainAxisAlignment.start,
                      ),
                    )
``` 

Bloc : 

```
class QuizBloc extends Bloc<QuizEvent, QuizState> {
  final userInput = List<String>();

  QuizBloc() : super(QuizInitialState());

  @override
  Stream<QuizState> mapEventToState(
    QuizEvent event,
  ) async* {
    if (event is AddStringEvent) {
      yield* _mapAddStringEventToState(event);
    } else if (event is RemoveLastStringEvent) {
      yield* _mapRemoveLastElementEventToState(event);
    } else if (event is ResetInputEvent) {
      yield* _mapResetEventEventToState(event);
    }
  }

  Stream<QuizState> _mapAddStringEventToState(AddStringEvent event) async* {
    userInput.add(event.latestString);
    yield QuizOutputState(userInput);
  }

  Stream<QuizState> _mapRemoveLastElementEventToState(
      RemoveLastStringEvent event) async* {
    if (userInput.isNotEmpty) {
      userInput.removeLast();
      yield QuizRemoveState(userInput);
    }
  }

  Stream<QuizState> _mapResetEventEventToState(ResetInputEvent event) async* {
    userInput.clear();
    yield QuizClearState(userInput);
  }
}

```

States : 
```

@immutable
abstract class QuizState extends Equatable {
  
}

class QuizInitialState extends QuizState {
  
  QuizInitialState();

  @override
  List<Object> get props => [];
}

class QuizOutputState extends QuizState {
  final List<String> outputString;

  QuizOutputState(this.outputString);

  @override
  List<Object> get props => [this.outputString];
}

class QuizRemoveState extends QuizState {
  final List<String> outputString;

  QuizRemoveState(this.outputString);

  @override
  List<Object> get props => [this.outputString];
}

class QuizClearState extends QuizState {
  final List<String> outputString;

  QuizClearState(this.outputString);

  @override
  List<Object> get props => [this.outputString];
}

```

Events: 

```
@immutable
abstract class QuizEvent extends Equatable {}

class AddStringEvent extends QuizEvent {
  final String latestString;
  
  AddStringEvent(this.latestString);

  @override
  List<Object> get props => [this.latestString];
}

class RemoveLastStringEvent extends QuizEvent {
  RemoveLastStringEvent();

  @override
  List<Object> get props => [];
}

class ResetInputEvent extends QuizEvent {
  ResetInputEvent();

  @override
  List<Object> get props => [];
}

```

**Comment by QAQyzk** [comment] 2020-10-21 23:13
The problem is reuse the variable `userInput ` for new state. Because list does not change its reference when the element changed.

One solution will be to replace 
>       yield QuizRemoveState(userInput);
 
to `yield QuizRemoveState(List.of(userInput));` which make copy of the original list and pass it to `QuizRemoveState `

**Comment by felangel** [comment] 2020-10-23 16:40
Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-10-23 16:40 UTC
Labels: question, waiting for response
