### ISSUE TITLE
Usage with Nested Routes

### ISSUE THREAD

**Issue by whysetiawan** [felangel/bloc#2194] opened 2021-03-05 17:13 UTC
Hi @felangel i have another problem with Navigator. I have a home page which has bottom tab and another navigator. In order to call a Bloc from the screen, it always give me an error that the context doesn't provide Bloc. How to solve this problem?

```
@override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider<TrxCubit>(
          // lazy: false,
          create: (_) => TrxCubit(),
        ),
        BlocProvider<TrxFormBloc>(
          lazy: false,
          create: (_) => TrxFormBloc(
            _.read<TrxCubit>(),
            _.read<AuthBloc>(),
            _.read<PopupCubit>(),
          ),
        ),
      ],
      child: WillPopScope(
        onWillPop: () async {
          if (navigatorKey.currentState.canPop()) {
            // 'maybePop' method handles the decision of 'pop' to another WillPopScope if they exist.
            //If no other WillPopScope exists, it returns true
            navigatorKey.currentState.maybePop();
            return Future<bool>.value(false);
          }
          //if nothing remains in the stack, it simply pops
          return Future<bool>.value(true);
        },
        child: Scaffold(
          body: AnnotatedRegion<SystemUiOverlayStyle>(
            value: SystemUiOverlayStyle(
              statusBarIconBrightness: Brightness.light,
            ),
            child: Navigator(
              initialRoute: '/home',
              key: navigatorKey,
              onPopPage: (route, result) {
                ScaffoldMessenger.of(context).hideCurrentSnackBar();
                return true;
              },
              onGenerateRoute: (RouteSettings settings) {
                print('hey this is setting $settings');
                switch (settings.name) {
                  case "/home":
                    return MaterialPageRoute(
                      builder: (_) => tabBar(),
                    );
                  case "/history":
                    return MaterialPageRoute(builder: (_) => HistoryScreen());
                  case "/transfer":
                    return MaterialPageRoute(builder: (_) => TransferScreen());
                  case "/payments/pulsa":
                    return MaterialPageRoute(builder: (_) => PulsaScreen());
                  case "/payments/listrik":
                    return MaterialPageRoute(builder: (_) => ListrikScreen());
                  case "/payments/inquiry":
                    return MaterialPageRoute(
                        builder: (_) => PaymentInquiryScreen());
                  case "/payments/pin":
                    return MaterialPageRoute(builder: (_) => PinInput());
                  case "/payments/receipt":
                    return MaterialPageRoute(
                        builder: (_) => PaymentInquiryScreen());
                  default:
                    print('default is ${settings.name}');
                    return null;
                }
              },
            ),
          ),
        ),
      ),
    );
```

I read `TrxCubit` or `TrxFormBloc` for all the defined route.

**Comment by Gene-Dana** [comment] 2021-03-12 01:51
From what I understand, I believe you can pass in the actual into your widgets, although I'm not certain this is the best practice. 

Another option would be to pass in the cubit/bloc directly in the pages.

Recently, I moved to navigating with Flowbuilder because it implements Navigator 2.0 under the hood like this

https://github.com/Team-Crushing-It/l2t_alpha/blob/a7396c8cf2ddfb475b6119378585777466cf2852/lib/app/app.dart#L59-L73

https://github.com/Team-Crushing-It/l2t_alpha

**Comment by felangel** [comment] 2021-03-25 02:37
Hi @whysetiawan 👋 
Thanks for opening an issue and sorry for the delayed response! Are you able to share a link to a complete reproduction sample? It would be much easier to help if I can run/debug the issue locally, thanks! 🙏

**Comment by felangel** [comment] 2021-03-29 04:41
Closing for now since there is no reproduction sample.

**Closed by felangel** 2021-03-29 04:41 UTC
Labels: question, waiting for response
