### ISSUE TITLE
Flutter Bloc/State delayed activities when moving between pages

### ISSUE THREAD

**Issue by michelhabib** [felangel/bloc#2403] opened 2021-04-18 22:09 UTC
This might be more of a question, I looked everywhere, and now I think it is better to ask a direct question. Not sure if this is the right place. I am using Flutter Bloc package.

I am expecting that as soon as I navigate from page A to page B, and remove all other pages in stack if any (PushAndRemoveUntil false), then:
- All defined blocs inside Page A shall be closed immediately (unless defined above MaterialApp), 
- And BlocBuilders/BlocListeners of Page A should stop accepting any new states, Especially if I cancel stream subscriptions defined in the bloc.

**However**, 
- The bloc close function is delayed, which also delays stream subscription cancellation defined in the close function, 
- the bloc close function may not run until the build function of Page B runs (sometimes Built twice)
- And BlocBuilder/BlocListener may still run on the Page A (not sure how!) and may disturb my app's behavior.

**Questions**:
- Should I add more logic to the BlocListener of Page A to stop accepting new states when it calls Navigator? 
- Should I add more logic to the BlocBuilder, to stop rebuilding Page A widgets in the background, while it is waiting to be destroyed (I mean both the widget and the BlocBuilder)
- Should I call the Bloc Close function earlier manually?

I have been trying to look for solutions, but they all go to a direction where I add management to state management, which is what takes me back to the source, here. 
I know I haven't submitted any source code, because the issue appears with larger and complex behavior, too difficult to extract in an example. I could try to put something together, if you feel this is not the expected behavior.

**Comment by felangel** [comment] 2021-04-19 02:10
Hi @michelhabib 👋 
Thanks for opening an issue!

Can you provide a reproduction sample? As long as the bloc was created by a BlocProvider you shouldn't need to manually call `close`. The bloc instance should be closed as soon as the associated `BlocProvider` instance is unmounted from the widget tree.

**Comment by felangel** [comment] 2021-05-03 02:44
Closing for now since there isn't a reproduction sample.

**Closed by felangel** 2021-05-03 02:44 UTC
Labels: question, waiting for response

**Comment by doitduri** [comment] 2021-09-14 11:30
Hi, @felangel 

This issue occurs to me, too. 
I provide the sample code below. I want to know the reason for `BlocBase.close`.


**code:**

1. PageA.dart
```
Navigator.of(context).pushAndRemoveUntil(
  MaterialPageRoute(
      builder: (_) => BlocProvider<TestCubit>.value(
            value: BlocProvider.of<TestCubit>(context),
            child: PageB(),
          )),
  (route) => false,
);
```

2. PageB.dart
```
class PageB extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _PageBState();
}

class _PageBState extends State<PageB> {
  late TestCubit _testCubit;

  @override
  void initState() {
    super.initState();
    _testCubit = context.read<TestCubit>();
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(),
      body: BlocBuilder<TestCubit, TestState>(
            builder: (context, state) {
              return Wrap(
                runSpacing: 15,
                children: [
                  Text(
                    "새 비밀번호를 입력해주세요.",
                  ),
                ],
              );
            }),
    );
  }
}
```
![image](https://user-images.githubusercontent.com/26545623/133249322-745c963d-496b-49d5-beb7-168a8e9e7e87.png)

**Comment by felangel** [comment] 2021-09-14 13:11
> Hi, @felangel
> 
> This issue occurs to me, too.
> I provide the sample code below. I want to know the reason for `BlocBase.close`.
> 
> **code:**
> 
> 1. PageA.dart
> 
> ```
> Navigator.of(context).pushAndRemoveUntil(
>   MaterialPageRoute(
>       builder: (_) => BlocProvider<TestCubit>.value(
>             value: BlocProvider.of<TestCubit>(context),
>             child: PageB(),
>           )),
>   (route) => false,
> );
> ```
> 
>  1. PageB.dart
> 
> ```
> class PageB extends StatefulWidget {
>   @override
>   State<StatefulWidget> createState() => _PageBState();
> }
> 
> class _PageBState extends State<PageB> {
>   late TestCubit _testCubit;
> 
>   @override
>   void initState() {
>     super.initState();
>     _testCubit = context.read<TestCubit>();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
> 
>     return Scaffold(
>       appBar: AppBar(),
>       body: BlocBuilder<TestCubit, TestState>(
>             builder: (context, state) {
>               return Wrap(
>                 runSpacing: 15,
>                 children: [
>                   Text(
>                     "새 비밀번호를 입력해주세요.",
>                   ),
>                 ],
>               );
>             }),
>     );
>   }
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/26545623/133249322-745c963d-496b-49d5-beb7-168a8e9e7e87.png)

Can you provide a link to a complete minimal reproduction sample?

**Comment by doitduri** [comment] 2021-09-14 15:02
> > Hi, @felangel
> > This issue occurs to me, too.
> > I provide the sample code below. I want to know the reason for `BlocBase.close`.
> > **code:**
> > 
> > 1. PageA.dart
> > 
> > ```
> > Navigator.of(context).pushAndRemoveUntil(
> >   MaterialPageRoute(
> >       builder: (_) => BlocProvider<TestCubit>.value(
> >             value: BlocProvider.of<TestCubit>(context),
> >             child: PageB(),
> >           )),
> >   (route) => false,
> > );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. PageB.dart
> > 
> > ```
> > class PageB extends StatefulWidget {
> >   @override
> >   State<StatefulWidget> createState() => _PageBState();
> > }
> > 
> > class _PageBState extends State<PageB> {
> >   late TestCubit _testCubit;
> > 
> >   @override
> >   void initState() {
> >     super.initState();
> >     _testCubit = context.read<TestCubit>();
> >   }
> > 
> >   @override
> >   Widget build(BuildContext context) {
> > 
> >     return Scaffold(
> >       appBar: AppBar(),
> >       body: BlocBuilder<TestCubit, TestState>(
> >             builder: (context, state) {
> >               return Wrap(
> >                 runSpacing: 15,
> >                 children: [
> >                   Text(
> >                     "새 비밀번호를 입력해주세요.",
> >                   ),
> >                 ],
> >               );
> >             }),
> >     );
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/26545623/133249322-745c963d-496b-49d5-beb7-168a8e9e7e87.png)
> 
> Can you provide a link to a complete minimal reproduction sample?


Please check the code.

[project infomation]
1. main -> PageA  (provide TestCubit)
2. PageA -> PageB (BlocProvide.value)
- **change TestState using TextField**

**sample project demo :** 
![bloc](https://user-images.githubusercontent.com/26545623/133282030-5664f53a-5b7d-4be7-9f2d-951d9f223aa4.gif)

**sample code :**
https://github.com/doitduri/bloc_sample
