### ISSUE TITLE
CurrentState still uninitialized even if State changed

### ISSUE THREAD

**Issue by victorshn** [felangel/bloc#861] opened 2020-02-10 14:46 UTC
I'am working to a login app with firebase and bloc, The login work well but the transition in the console show that **currentState** is **Uninitialized**, i would like to see the **currentState** to be **Authenticated**. this is my code:`import 'dart:async';
```
import 'package:bloc/bloc.dart';
import 'package:damajex/repository/auth_repository.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_sign_in/google_sign_in.dart';
import './bloc.dart';

class AuthBloc extends Bloc<AuthEvent, AuthState> {
  final AuthRepository _authRepository =
      AuthRepository(auth: FirebaseAuth.instance, googleSignin: GoogleSignIn());
  StreamSubscription _todosSubscription;

  @override
  AuthState get initialState => Uninitialized();

  @override
  Stream<AuthState> mapEventToState(
    AuthEvent event,
  ) async* {
    if (event is AppStarted) {
      yield* _mapAuthCurrentState();


    }
    if (event is AuthChanged) {
      if(event.user!=null){
        //yield Unauthenticated();
      //}else{
        yield*  _mapAuthChangedState(event);
      }


    }

    if (event is LoggedOut) {
      yield Unauthenticated();
      _authRepository.logout();
    }
  }

  Stream<AuthState> _mapAuthChangedState(AuthChanged event) async* {
    yield Authenticated(event.user);
  }

  Stream<AuthState> _mapAuthCurrentState() async* {
    _todosSubscription?.cancel();
    _todosSubscription = _authRepository.onAuthStateChanged().listen(
          (auth) => add(
            AuthChanged(auth),
          ),
        );
  }

  @override
  Future<void> close() {
    _todosSubscription?.cancel();
    return super.close();
  }
}`

and the event is :`import 'package:equatable/equatable.dart';
import 'package:firebase_auth/firebase_auth.dart';

abstract class AuthEvent extends Equatable {
  const AuthEvent();
  @override
  List<Object> get props => [];
}

class AppStarted extends AuthEvent {

}

class AuthChanged extends AuthEvent {
  final FirebaseUser user;

  AuthChanged(this.user);

  @override
  List<Object> get props {
    return [user];
  }

  @override
  String toString() {
    return 'AuthChanged{user: $user';
  }


}
class LoggedOut extends AuthEvent {}

`

and `import 'package:equatable/equatable.dart';
import 'package:firebase_auth/firebase_auth.dart';

abstract class AuthState extends Equatable {
  const AuthState();

  @override
  List<Object> get props {
    return [];
  }


}

class Uninitialized extends AuthState {}

class Authenticated extends AuthState {
  final FirebaseUser user;

  const Authenticated(this.user);

  @override
  List<Object> get props => [user];

  @override
  String toString() => 'Authenticated { user: $user }';
}

class Unauthenticated extends AuthState {}`


```
in main function:
```
  home: BlocBuilder<AuthBloc, AuthState>(
                        builder: (context, state) {
                          if (state is Unauthenticated) {
                            return NewAccountScreen();
                          }
                          if (state is Authenticated) {
                            return MainPage();
                          } else {
                            return SplashScreen();
                          }
                        },
                      ),
```

please help me

**Comment by felangel** [comment] 2020-02-10 15:12
Hi @victorshn 👋 
Thanks for opening an issue!

Are you able to share a link to a sample app which illustrates the issue you're facing? Thanks!

**Comment by victorshn** [comment] 2020-02-11 05:59
Hello this is the project https://github.com/victorshn/damajex

**Comment by felangel** [comment] 2020-02-11 15:39
@victorshn seems like the invitation isn't valid anymore so I can't access the repo.

**Comment by felangel** [comment] 2020-02-12 23:54
Closing since I am unable to access a reproduction sample. Feel free to provide a sample and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-02-12 23:54 UTC
Labels: question, waiting for response
