### ISSUE TITLE
Check the state listener but not check the state twice at builder

### ISSUE THREAD

**Issue by duomoteng** [felangel/bloc#1071] opened 2020-04-20 11:39 UTC
Hi, really thanks for the awesome library.
I am working on a page that needs to `Navigator.push` to another page. 

For example,
I am currently on page A. When I pressed a button on page A, it needs to `Navigator.push` to a new page B, without changing the Page A. When I returned from Page B, Page A keeps what look like as before.

If I remove the ` if (state is GoToEditor) ` in `BlocBuilder`, it will show me a cannot be null error.

I want the Page A to stay unchanged when I go to the Page B, and still unchanged  when I go back from Page B.

```dart
 @override
  Widget build(BuildContext context) {
    return BlocListener(
      bloc: _noteBloc,
      listener: (BuildContext context, NotesListState state){
        if (state is GoToPageB) {
          Navigator.push(
            context,
            MaterialPageRoute(builder: (context) => PageB()),
          );
        }
      },
      child: BlocBuilder<NotesListBloc, NotesListState>(
        bloc: _noteBloc,
        builder: (context, state) {

          if (state is NoteUninitialized) {
            return Center(
              child: CircularProgressIndicator(),
            );
          }
          if (state is GoToPageB) {
            return Container(); // I retuned a container, so it will be empty after leaving Page A
            );
          }

        },
      ),
    );
  }


```

**Comment by krevedkokun** [comment] 2020-04-20 13:08
https://pub.dev/documentation/flutter_bloc/latest/flutter_bloc/BlocBuilder/condition.html

**Comment by duomoteng** [comment] 2020-04-20 19:48
> https://pub.dev/documentation/flutter_bloc/latest/flutter_bloc/BlocBuilder/condition.html

Really thanks for your reply, I have changed it to use BlocConsumer and it works

**Comment by duomoteng** [comment] 2020-04-20 19:55
Really thanks for your reply. Based on your hint, I have changed it to use `BlocConsumer.` But another issue happened. When it `navigation.push` to another page, and then return to the origin page, the bloc is not working again.

I tried to remove the dispose method, but still not working.
My logger  shows that the bloc working well for the first time, but second I tap the button, it stops working after `yield GoToEditor`

```dart
  @override
  Widget build(BuildContext context) {
    return BlocConsumer<NotesListBloc, NotesListState>(
      bloc: _noteBloc,

      listenWhen: (previous, current) {
        return true;
      },
      
      listener: (BuildContext context, NotesListState state) {
        logger.v('listener: $state');
        
        if (state is GoToPageB) {
          logger.v('Now should navigate to page B');
          Navigator.push(
            context,
            MaterialPageRoute(builder: (context) => PageB()),
          );
        }
      },

      buildWhen: (previous, current) {
        logger.v('buildWhen: $current');
        if (current is GoToPageB) {
          return false;
        }
        return true;
      },

      builder: (context, state) {
   if (state is NoteUninitialized) {
            return Center(
              child: CircularProgressIndicator(),
            );
          }
      
  }



```

**Comment by duomoteng** [comment] 2020-04-20 20:16
I solved the problem by `yield` a `DoNothingState` before `GoToPageB` state. The issue is caused because of 2 same states is called. But I still want to know is there any better solution to solve this?

**Comment by felangel** [comment] 2020-04-21 06:51
Hi @duomoteng 👋 
Thanks for opening an issue!

Can you please share a link to a sample app which illustrates the issue you're facing? Thanks 👍

**Comment by felangel** [comment] 2020-04-27 06:10
Closing since there was no sample application provided to reproduce the issue. Feel free to comment with a link to a sample app and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-04-27 06:10 UTC
Labels: question, waiting for response
