### ISSUE TITLE
[Flutter Web dev branch] As anyone tried to build something using the bloc?

### ISSUE THREAD

**Issue by AlexandreRoba** [felangel/bloc#957] opened 2020-03-14 09:38 UTC
**Describe the bug**
I'm facing inconsistent behaviour when using the bloc on a flutter web app. It kind of put the bloc in a 'Broken state'. No more events which are added to the bloc are triggering the mapEventToState.

I managed to narrow the issue to this:
Here is my bloc:
```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:hophop_admin/blocs/blocs.dart';
import 'package:hophop_admin/repositories/auth/auth_repository.dart';

import 'login_event.dart';
import 'login_state.dart';

class LoginBloc extends Bloc<LoginEvent, LoginState> {
  final AuthRepository _authRepository;
  final AppBloc _appBloc;

  LoginBloc(
      {@required AuthRepository authRepository, @required AppBloc appBloc})
      : assert(authRepository != null),
        assert(appBloc != null),
        this._appBloc = appBloc,
        this._authRepository = authRepository;

  @override
  LoginState get initialState => LoginStateInitial();

  @override
  Stream<LoginState> mapEventToState(LoginEvent event) async* {
    print('Receive the notification');
    if (event is SignInLoginEvent) {
      yield* _mapSignInLoginEvent(event);
    } else if (event is CleanErrorLoginEvent) {
      yield* _mapCleanErrorLoginEvent(event);
    }
  }

  Stream<LoginState> _mapSignInLoginEvent(SignInLoginEvent event) async* {
    yield IsLoadingLoginState();
    try {
//Code that works
        //throw Exception("Error from the bloc");
//Code that fails
      var result = await _authRepository.breakEverything();
    } catch (error) {
      print('An Error');
      yield LoginErrorLoginState('$error');
    }
  }

  Stream<LoginState> _mapCleanErrorLoginEvent(
      CleanErrorLoginEvent event) async* {
    yield LoginStateInitial();
  }
}
```
The problem happens on the mapper `_mapSignInLoginEvent`
If a throw an exception from withing the bloc everyting works as expected. Everytime I add the SignInLoginEvent, the mapper yield a LoginErrorLoginState('$error').

If a replace the throw from the bloc to the call to the repository method which throws, the Error state is yeild the first time, but then every call to the bloc add method have no effect. The base method 'mapEventToState' is not triggered. The event is added as I have a log line that say so.

The code for the repository is:
```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:hophop_admin/models/models.dart';

class AuthRepository {
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final Firestore _db = Firestore.instance;

  Future<User> get getUser async {
    //TODO: this is related to bug [firebase_auth_web] authentication status not persistent #1918
    //var fbUser = await _auth.currentUser();
    var fbUser = await _auth.onAuthStateChanged.first;
    if (fbUser != null) return User(uid: fbUser.uid, email: fbUser.email);
    return null;
  }

  Future<User> signIn(String email, String password) async {
    try {
      var authResult = await _auth.signInWithEmailAndPassword(
          email: email, password: password);
      if (authResult.user != null) {
        return User(uid: authResult.user.uid, email: authResult.user.email);
      }
      throw Exception("This should never happen");
    } catch (error) {
      throw Exception('$error');
    }
  }

  Future<String> breakEverything() async {
    throw Exception('Error');
  }

  Future<void> signOut() async {
    await _auth.signOut();
  }
}
````
 From the repository I simply raise an error but the bloc is "brokken" and no more event are handled.

Any idea?

**Comment by felangel** [comment] 2020-03-14 14:42
Hi @AlexandreRoba 👋
Thanks for opening an issue!

I believe this is an issue with the Dev Dart compiler and I have opened https://github.com/flutter/flutter/issues/47858 to track this. You shouldn’t have any issues running in release mode and please give the above issue a 👍 to help raise the priority. Thanks! 🙏

**Comment by phamnhuvu-dev** [comment] 2020-04-09 03:01
I have the same problem but when using the stream on the web platform. But when I run web with the release option, the problem is gone. Very lucky

**Comment by felangel** [comment] 2020-05-20 06:20
closing this since it is being tracked via https://github.com/dart-lang/sdk/issues/39994.

**Closed by felangel** 2020-05-20 06:20 UTC
Labels: bug, dependency

**Comment by hynra** [comment] 2020-09-12 16:52
The issue ( https://github.com/dart-lang/sdk/issues/39994 ) is closed, which means the problem is fixed. However, I still have this problem. Is there any other solution besides using `--release`?
