### ISSUE TITLE
bloc.listen method does not return initial values once called

### ISSUE THREAD

**Issue by eimantas1998** [felangel/bloc#1542] opened 2020-07-28 15:14 UTC
Hello, im having an issue, i have upgraded my application from flutter 4.0.0 to 6.0.1 and i have noticed that bloc.listen method has changed, it does not return anything from the start (current state of the bloc, it is listening to), it only returns state once the bloc state has changed, is this intended, if so is there any other method that i could use that works as a listener but returns the current state of the bloc once called.

[√] Flutter (Channel beta, 1.20.0-7.2.pre, on Microsoft Windows [Version 10.0.18362.959], locale en-US)
    • Flutter version 1.20.0-7.2.pre at C:\flutter
    • Framework revision a2bde82fbd (10 days ago), 2020-07-18 15:16:35 -0700
    • Engine revision 60b269d898
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\Eimantas\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\Eimantas\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (4 available)
    • FRD L09 (mobile) • 73QDU16731005444 • android-arm64  • Android 7.0 (API 24)
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 84.0.4147.89
    • Edge (web)       • edge             • web-javascript • Microsoft Edge 84.0.522.44

• No issues found!

**Comment by felangel** [comment] 2020-07-28 15:15
Hi @eimantas1998 👋 
Thanks for opening an issue!

This is a duplicate of https://github.com/felangel/bloc/issues/1541, https://github.com/felangel/bloc/issues/1512, and https://github.com/felangel/bloc/issues/1518.

**Closed by felangel** 2020-07-28 15:15 UTC
Labels: duplicate
