### ISSUE TITLE
calling close() does not close _stateSubject

### ISSUE THREAD

**Issue by DaVaMa1** [felangel/bloc#809] opened 2020-01-27 07:34 UTC
We're having an issue with regards to unit testing our implementations of Bloc. 
When we call close() and expect a done event it never arrives. When debugging and awaiting the close we notice that the close never completes. 
It seems to hang on await _stateSubject.close(); in bloc itself.

The Dart documentation is not so clear about it but streams should close once they deliver the Done event, which only happens as long as there are listeners. I expect that when I use expect(_bloc, emits) in my unit test that the correct streams are listened to and the close will complete...

**To Reproduce**
I'll see if I can get an example working, I can't share my current code.

**Expected behavior**
I expect the stream to close when I call close.

**Comment by felangel** [comment] 2020-01-28 05:16
Hi @DaVaMa1 👋 
Thanks for opening an issue!

Can you please share a link to a sample app which reproduces the issue you're having? Thanks! 👍

**Comment by felangel** [comment] 2020-01-29 05:03
Closing for now since there is not enough information to reproduce the issue. Feel free to comment with additional info or a sample app and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-01-29 05:03 UTC
Labels: question, waiting for response
