### ISSUE TITLE
docs: Please use Jetbrains Mono as code font

### ISSUE THREAD

**Issue by erlangparasu** [felangel/bloc#3388] opened 2022-06-06 12:30 UTC
**Description**
Please use `'JetBrains Mono'` font-family for code

**Comment by erlangparasu** [comment] 2022-06-06 12:41
![image](https://user-images.githubusercontent.com/20636828/172162475-f99cd043-a4fa-4b5b-bf92-9c4dc2402737.png)

looks better isn't? :)

**Comment by flexagoon** [comment] 2022-06-06 19:13
no it doesnt

**Comment by erlangparasu** [comment] 2022-06-06 21:35
![image](https://user-images.githubusercontent.com/20636828/172253130-5b48d7b3-5e44-4f2f-a5f7-93d920886e1e.png)

this how it look like without JetBrains Mono font, in my browser

**Comment by felangel** [comment] 2022-06-15 18:52
@erlangparasu is this specific to your browser? Are you also experiencing this effect in other browsers?

**Comment by erlangparasu** [comment] 2022-06-15 19:40
yes it's only in Firefox. here is a screenshot of it. I think it looks like it's not a monospaced font. how about the display on your computer (with Firefox)?

ss:
![image](https://user-images.githubusercontent.com/20636828/173909959-38496113-0948-45d2-925e-f564ec6d4e94.png)

**Comment by erlangparasu** [comment] 2022-06-15 19:46
sorry in advance, basically I just want it to look monospaced in all browsers 😅🙏

**Comment by flexagoon** [comment] 2022-07-03 23:25
![image](https://user-images.githubusercontent.com/66178592/177060703-bd270d7c-8e5a-43bb-936b-b116faa75ea3.png)
@erlangparasu here's what it looks like for me. I am also using Firefox. Can you share more details about your system?

**Comment by felangel** [comment] 2022-07-11 04:20
Closing for now since it doesn’t appear to be a reproducible issue. Feel free to provide additional info/steps to reproduce and I’m happy to continue the conversation 👍

**Closed by felangel** 2022-07-11 04:20 UTC
Labels: question, waiting for response, documentation
