### ISSUE TITLE
TabBarView bug with Scrollable.ensureVisible and bloc

### ISSUE THREAD

**Issue by MariosKoni** [felangel/bloc#4046] opened 2024-01-16 14:58 UTC
**Description**
I'm using a `TabBarView`. I have 3 tabs (`wantKeepAlive => true`). Each tab provides and builds the same bloc. In each tab I run an API call. If an error occurs during the call, I emit an error state. Back in the builder, when in error state, I display a simple widget that informs the user that something went wrong with `Scrollable.ensureVisible(context)` in its `initState`. This forces the tab to change and try to make the widget visible in all tabs, resulting in the user being in a different tab from the one he/she tapped.

main.dart
```
import 'package:bloc_test_m/bloc/tabs_bloc.dart';
import 'package:equatable/equatable.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const _Tabs(),
    );
  }
}

class _Tabs extends StatelessWidget {
  const _Tabs();

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 3,
      initialIndex: 0,
      child: Scaffold(
        appBar: AppBar(
          title: const Text('Minimal test'),
          bottom: const TabBar(
            tabs: [
              Tab(
                icon: Icon(Icons.first_page),
                child: Text('First'),
              ),
              Tab(icon: Icon(Icons.face_2), child: Text('Second')),
              Tab(
                icon: Icon(Icons.last_page),
                child: Text('Third'),
              ),
            ],
          ),
        ),
        body: const TabBarView(
          children: [
            _FirstPage(),
            _SecondPage(),
            _ThirdPage(),
          ],
        ),
      ),
    );
  }
}

class _FirstPage extends StatefulWidget {
  const _FirstPage();

  @override
  State<_FirstPage> createState() => _FirstPageState();
}

class _FirstPageState extends State<_FirstPage>
    with AutomaticKeepAliveClientMixin {
  @override
  Widget build(BuildContext context) {
    super.build(context);

    return const ViewWidget();
  }

  @override
  bool get wantKeepAlive => true;
}

class _SecondPage extends StatefulWidget {
  const _SecondPage();

  @override
  State<_SecondPage> createState() => _SecondPageState();
}

class _SecondPageState extends State<_SecondPage>
    with AutomaticKeepAliveClientMixin {
  @override
  Widget build(BuildContext context) {
    super.build(context);

    return const ViewWidget();
  }

  @override
  bool get wantKeepAlive => true;
}

class _ThirdPage extends StatefulWidget {
  const _ThirdPage();

  @override
  State<_ThirdPage> createState() => _ThirdPageState();
}

class _ThirdPageState extends State<_ThirdPage>
    with AutomaticKeepAliveClientMixin {
  @override
  Widget build(BuildContext context) {
    super.build(context);

    return const ViewWidget();
  }

  @override
  bool get wantKeepAlive => true;
}

class ViewWidget extends StatelessWidget {
  const ViewWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocProvider<TabsBloc>(
      create: (context) => TabsBloc(),
      child: const _ViewWidget(),
    );
  }
}

class _ViewWidget extends StatelessWidget {
  const _ViewWidget();

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<TabsBloc, TabsState>(builder: (context, state) {
      if (state is TabsStateError) {
        return const Center(child: _ErrorWidget());
      }

      return Center(
          child: ElevatedButton(
        onPressed: () => context.read<TabsBloc>().add(Fetch()),
        child: const Text('Spank me'),
      ));
    });
  }
}

class _ErrorWidget extends StatefulWidget {
  const _ErrorWidget();

  @override
  State<_ErrorWidget> createState() => __ErrorWidgetState();
}

class __ErrorWidgetState extends State<_ErrorWidget> {
  @override
  void initState() {
    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
      if (mounted) {
        Scrollable.ensureVisible(context);
      }
    });

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        const SizedBox(height: 50),
        const Text('Oh no'),
        OutlinedButton(
          onPressed: () => context.read<TabsBloc>().add(Fetch()),
          child: const Text('Yes daddy'),
        ),
      ],
    );
  }
}

class User extends Equatable {
  const User(
      {required this.id,
      required this.userId,
      required this.title,
      required this.completed});

  factory User.fromJson(Map<String, dynamic> json) => User(
      id: json['id'],
      userId: json['userId'],
      title: json['title'],
      completed: json['completed']);

  final int id;
  final int userId;
  final String title;
  final bool completed;

  @override
  List<Object?> get props => [id, userId, title, completed];
}
```

**Expected Behavior**
User should remain in the same tab when the error occurred.

**Additional Context**

_Flutter version:_
```
Flutter 3.16.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2e9cb0aa71 (5 weeks ago) • 2023-12-11 14:35:13 -0700
Engine • revision 54a7145303
Tools • Dart 3.2.3 • DevTools 2.28.4
```

_bloc version:_
```
flutter_bloc: ^8.1.3
bloc: ^8.1.2
```

https://github.com/felangel/bloc/assets/26388649/713d943e-84c2-4433-9da3-41aa467157aa

**Comment by felangel** [comment] 2024-01-18 06:21
Hi @MariosKoni 👋 
Thanks for opening an issue!

Can you please share a link to a minimal reproduction sample on GitHub or DartPad? It would be much easier to help if we can reproduce the issue locally, thanks!

**Comment by MariosKoni** [comment] 2024-01-18 08:40
Hi @felangel, here's the [link](https://github.com/MariosKoni/bloc-test-m) to the code in Github.

**Comment by Hyla96** [comment] 2024-01-24 08:52
I think your app behaves as you coded it:
- You initialize all tabs at once;
- On initialization you add the `Fetch()` event;
- If something  goes wrong (F.I. the website is not available) the bloc emits your ErrorState;
- Since this happens during the initialization, most likely it happens for all 3 instances of your bloc;
- Your 3 blocs react in sequence;
- The last 3rd (and last) bloc will be the last one calling `Scrollable.ensureVisible(context)`, so that's the page your app will display;

If you don't want your tabs to switch on error state you might wanna remove `Scrollable.ensureVisible(context)` in the initState of your error widget.

**Comment by felangel** [comment] 2024-02-01 03:19
Closing for now since there doesn't appear to be any actionable next steps.

**Closed by felangel** 2024-02-01 03:19 UTC
Labels: question, waiting for response, needs repro info
