### ISSUE TITLE
fix: Bloc Extension not creating the Bloc folder when used Bloc : New Bloc in VS Code.

### ISSUE THREAD

**Issue by PrabeshPP** [felangel/bloc#3165] opened 2022-01-24 09:47 UTC
**Description**
Bloc Extension is not creating the bloc folder ,rather it is creating the file in another folder. Plus, the extension is not implementing the equatable template in User setting rather the bloc template can only be modified in Workspace.

**Steps To Reproduce**

1. Go to Bloc Extension Setting in VS Code.
2. Click on the New Bloc Template: Type;
3. Scroll down to Equatable.
4. It will change to auto as soon as you close the extension setting of bloc.

https://user-images.githubusercontent.com/83439329/150759476-e5c916fe-abf1-4561-b53f-15fb4fadbd4e.mp4

https://user-images.githubusercontent.com/83439329/150759538-516a901e-c353-4526-a0f9-512f8deacc22.mp4

**Comment by PrabeshPP** [comment] 2022-01-24 09:49
Help me with this problem!
If you need any other information, I would be happy to provide.

**Comment by felangel** [comment] 2022-01-24 16:53
Hi @PrabeshPP 👋 
Thanks for opening an issue!

Can you share your bloc extension version and VSCode version?

I'm not able to reproduce on VSCode Insiders.
<img width="256" alt="Screen Shot 2022-01-24 at 10 52 53 AM" src="https://user-images.githubusercontent.com/8855632/150827751-43114e9f-2cc0-4183-8948-8bf398e8a7be.png">

**Comment by PrabeshPP** [comment] 2022-01-25 03:43
Hi @felangel 
Bloc Extension Version is v6.4.0.
And the VSCode version is 
![VSCode_Version](https://user-images.githubusercontent.com/83439329/150906927-beea2fa1-f5b1-465f-9d36-48538d79e1f9.jpg)
Waiting for your reply!

**Comment by felangel** [comment] 2022-01-26 15:25
@PrabeshPP I'm not able to reproduce the issue unfortunately! Can you try uninstalling/reinstalling the bloc extension and/or uninstalling/reinstalling VSCode?

**Comment by felangel** [comment] 2022-02-01 01:35
Closing for now since there aren't any actionable next steps. Let me know if you're still facing the issue after a reinstall and I'm happy to continue the conversation 👍

**Closed by felangel** 2022-02-01 01:35 UTC
Labels: waiting for response, extension
