### ISSUE TITLE
BLOC STATE ISSUE 

### ISSUE THREAD

**Issue by yanisG** [felangel/bloc#2113] opened 2021-01-25 17:58 UTC
**Describe the bug**
when a user disconnect and reconnect with another account he will get the previous state 

**To Reproduce**
1.  create an account 
2. click the button add some todos (add for exemple 4 todos)
3. disconnect and reconnect with another account 
4. here is a screenshot of what we get 
![Capture d’écran 2021-01-25 185542](https://user-images.githubusercontent.com/39929140/105746055-40d1c600-5f3f-11eb-8dee-ba45edc08e40.png)

**Expected behavior**
we should get 0 todos but am getting the previous 3 todos of the previous account.
after we disconnect we should have a way to clear all the todos_bloc state  so that when a new user connect he will get his proper  data 

**here is the link to the application that illustrates the problem** : https://github.com/yanisG/bloc_issue
**it's the combination of your LOGIN APP and FIRESTORE TODOS APP** 

thank you.

**Comment by felangel** [comment] 2021-01-26 00:52
Hi @yanisG 👋 
Thanks for opening an issue!

I took a look and the issue is the TodosBloc is globally scoped. When you have state that is user-specific, I highly recommend scoping the bloc to just the authenticated branch of the widget tree. In this case, I would recommend moving the BlocProvider which creates/provides the `TodosBloc` to the `HomePage` since that is the root of the authenticated subtree. With this approach, whenever the authentication state changes, this subtree will be rebuilt and a fresh new `TodosBloc` will be created without retaining the previous state.

Hope that helps! Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Closed by felangel** 2021-01-26 00:52 UTC
Labels: question

**Comment by yanisG** [comment] 2021-01-26 17:22
hello ,
thank you for your reply ,actually in my app i'm using the  onGenerateRoute 
so i have some thing like that :
```

final TodosBloc _todosBloc = TodosBloc(TodosRepository());

Route onGenerateRoute(
    RouteSettings settings,
  ) {
    switch (settings.name) {
      case '/':
        return MaterialPageRoute(
          builder: (_) => LandingPage(),
        );
      case '/Home':
        return MaterialPageRoute(
          builder: (context) => MultiBlocProvider(providers: [
              BlocProvider.value(value: _todosBloc ..add(InitialEvent())),
             //other bloc..
          ], child: Home()),
        );
   case '/OTHER_SCREEN':
        return MaterialPageRoute(
          builder: (context) => MultiBlocProvider(providers: [
              BlocProvider.value(value: _todosBloc ),
             //other bloc..
          ], child: Home()),
        );
      case '/Login':
            return MaterialPageRoute(
              builder: (context) => Lgin(),
            );
 default:
        return null;
    }
  }
```
**i didn't found a solution here ! if you can suggest something it would be nice thank you** 
**i tried to do it as follow but it did not work !**  hope you can help me ! 

```
Route onGenerateRoute(
    RouteSettings settings,
  ) {
    switch (settings.name) {
      case '/':
        return MaterialPageRoute(
          builder: (_) => LandingPage(),
        );
      case '/Home':
        return MaterialPageRoute(
          builder: (context) => MultiBlocProvider(providers: [
              BlocProvider.value(value: TodosBloc(TodosRepository())..add(InitialEvent())),
             //other bloc..
          ], child: Home()),
        );
   case '/OTHER_SCREEN':
        return MaterialPageRoute(
          builder: (context) => MultiBlocProvider(providers: [
              BlocProvider.value(value: TodosBloc(TodosRepository()) ),
             //other bloc..
          ], child: Home()),
        );
      case '/Login':
            return MaterialPageRoute(
              builder: (context) => Lgin(),
            );
 default:
        return null;
    }
  }
```

**Comment by TheWCKD** [comment] 2021-01-26 21:49
Hello, man, I'm WCKD, you contacted me on YouTube over this issue. I am checking out your code and I don't seem to understand why you have 2 routes (the /home and /other Screen) navigating you to the same HomePage().

**Comment by TheWCKD** [comment] 2021-01-26 21:53
The other problem I can see is that you manually created the TodoBloc, but I can't see where, or more importantly if, you properly closed it. Since you manually provided it via BlocProvider.value() you'll have to manually close it into the dispose method from the widgets you provided it, so that whenever the authentication state changes, and those widgets will get disposed, the TodoBloc will be closed too.

**Comment by yanisG** [comment] 2021-01-26 22:07
@TheWCKD  my bad i did not type all of my code here , so no i edit my comment and as you can see  i tried to use two method  
the first one where i used `final TodosBloc _todosBloc = TodosBloc(TodosRepository());`  with the disposed method and the other without using it , and for both it did not work i still getting the previous state

**Comment by TheWCKD** [comment] 2021-01-26 22:50
I don't think you understood. You will need to have both of your pages (home and other Screen) converted to stateful widgets. Then for both of them, you should override the onDispose methods and call the TodoBloc.close() into those 2 overridden methods. You can access the to-do bloc by using context.read<TodoBloc>(), therefore you can call context.read<TodoBloc>().close() in both of the 2 pages dispose overridden methods.

**Comment by yanisG** [comment] 2021-01-27 16:25
@TheWCKD I tried what you said and i'm afraid that doesn't want to work either.
you can check the code here : https://github.com/yanisG/bloc_issue
it's the combination of bloc LOGIN APP and FIRESTORE TODOS APP 
i'm trying to do best practice for bloc and navigation routes but it's keep showing the previous state when i use onGeneratedRoute methode.

**Comment by TheWCKD** [comment] 2021-01-27 16:32
Let me check and see if I have any solution to this.

**Comment by TheWCKD** [comment] 2021-01-27 17:04
Man, I'm sorry but your code is too difficult to read, the entire structure of your project is messed up. I can't even run the project since it's linked to your firebase. 

Maybe @felangel can interpret it more easily.

**Comment by TheWCKD** [comment] 2021-01-27 17:38
Have you tried providing the instance of the `TodoBloc` to the `HomePage`, with BlocProvider? Like this:

```dart
class AppRouter {
  Route onGenerateRoute(
    RouteSettings settings,
  ) {
    switch (settings.name) {
      case '/':
        return SplashPage.route();
      case '/Home':
        return MaterialPageRoute(
          builder: (_) => BlocProvider(
            create: (context) =>
                TodosBloc(todosRepository: FirebaseTodosRepository()),
            child: HomePage(),
          ),
        );
      case '/Login':
        return MaterialPageRoute(
          builder: (_) => LoginPage(),
        );
      default:
        return null;
    }
  }
}
```

Then have the HomePage set up like this: 

```dart
class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final textTheme = Theme.of(context).textTheme;
    final user = context.select((AuthenticationBloc bloc) => bloc.state.user);
    return Scaffold(
        appBar: AppBar(
          title: const Text('Home'),
          actions: <Widget>[
            IconButton(
                key: const Key('homePage_logout_iconButton'),
                icon: const Icon(Icons.exit_to_app),
                onPressed: () {
                  context
                      .read<AuthenticationBloc>()
                      .add(AuthenticationLogoutRequested());
                })
          ],
        ),
        body: BlocBuilder<TodosBloc, TodosState>(builder: (context, state) {
          if (state is TodosLoading) {
            return Center(
              child: CircularProgressIndicator(),
            );
          } else if (state is TodosLoaded)
            return Align(
              alignment: const Alignment(0, -1 / 3),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: <Widget>[
                  Avatar(photo: user.photo),
                  const SizedBox(height: 4.0),
                  Text(user.email, style: textTheme.headline6),
                  const SizedBox(height: 4.0),
                  Text(user.name ?? '', style: textTheme.headline5),
                  Text("number of todos =  ${state.todos.length.toString()}"),
                  FlatButton(
                    color: Colors.red,
                    onPressed: () {
                      context.read<TodosBloc>().add(AddTodo(
                          Todo(complete: false, note: "aaa", task: "kkk")));
                    },
                    child: Text("add todo"),
                  )
                ],
              ),
            );

          return Center(
            child: CircularProgressIndicator(),
          );
        }));
  }
}
```

In this case, the TodoBloc should be created right after the /home route has been requested, in your case when the user is authenticated, or re authenticated after it's been logged out. So every time you're in one of these scenarios, the TodoBloc should be recreated and also automatically closed, thus loosing its state. Can you check if it works for you?

**Comment by yanisG** [comment] 2021-01-27 18:37
@TheWCKD sorry for the code structure because as i said it's the combination of the two bloc app examples ,i did the app quickly just for you and to link it to firebase it's easy just drop your google-services.json ,
and  in my case i have another project that i'm working on and i'm trying to do best practice included onGeneratedRoute.


and for the solution it's working but let's imagine that we have like 3 screens that needs to be provided with todosBloc  so we will create every time a new instance for Todosbloc ??
for example like that ? 
```
case '/Home':
        return MaterialPageRoute(
          builder: (_) => BlocProvider(
            create: (context) =>
                TodosBloc(todosRepository: FirebaseTodosRepository()),
            child: HomePage(),
          ),
        );
case '/screen2':
        return MaterialPageRoute(
          builder: (_) => BlocProvider(
            create: (context) =>
                 TodosBloc(todosRepository: FirebaseTodosRepository()),
            child: screen2(),
          ),
        );
case '/screen3':
        return MaterialPageRoute(
          builder: (_) => BlocProvider(
            create: (context) =>
                TodosBloc(todosRepository: FirebaseTodosRepository()),
            child: screen3(),
          ),
        );

```

**Comment by TheWCKD** [comment] 2021-01-27 19:45
No, because that way it would create 3 different instances of the TodoBloc for each of the 3 pages. 

I suppose your widget tree will look like this 

**MaterialApp>HomeScreen>Screen1/Screen2/Screen3** (if user is authenticated)

**MaterialApp>LoginScreen (if user is logged out)**

(screen1, screen2 or screen3 would be children of the home page). 

In this case, you can provide the **only instance of the TodoBloc** only to the `HomeScreen`, just as @felangel said, by using **BlocProvider**. Then, whenever you want to **push new pages** over the homescreen, like screen1, 2 or 3 they will automatically have the instance of the previously provided todobloc, available right there, by calling `context.read<TodoBloc>()`, since screen1, 2 and 3 would be children of the already injected HomeScreen. Your AppRouter should look like.

```dart
class AppRouter {
  Route onGenerateRoute(
    RouteSettings settings,
  ) {
    switch (settings.name) {

      // your default home route (this is the default screen being pushed inside your app after the MaterialApp) (if the user is logged in)

      // widget tree will look like this MaterialApp>HomeScreen

      case '/authenticatedHome':
        return MaterialPageRoute(
          builder: (_) => BlocProvider(
              create: (homeScreenContext) => TodosBloc(
                    todosRepository:
                        homeScreenContext.read<FirebaseTodosRepository>(),
                  ),
              child: HomePage()),
        );

      // widget tree will look like this  MaterialApp>HomeScreen>Screen1
      // you have access to the TodosBloc instance here since Screen1 is below the HomeScreen in the widget tree

      case '/screen1':
        return MaterialPageRoute(
          builder: (screen1Context) => BlocProvider<TodosBloc>.value(
            value: screen1Context.read()<TodosBloc>(),
            child: Screen1(),
          ),
        );

      // widget tree will look like this  MaterialApp>HomeScreen>Screen2
      // you have access to the TodosBloc instance here since Screen2 is below the HomeScreen in the widget tree

      case '/screen2':
        return MaterialPageRoute(
          builder: (screen2Context) => BlocProvider<TodosBloc>.value(
            value: screen2Context.read()<TodosBloc>(),
            child: Screen2(),
          ),
        );

      // widget tree will look like this  MaterialApp>HomeScreen>Screen3
      case '/screen3':
        return MaterialPageRoute(
          builder: (screen3Context) => BlocProvider<TodosBloc>.value(
            value: screen3Context.read()<TodosBloc>(),
            child: Screen3(),
          ),
        );

      // widget tree will look like this  MaterialApp>Login (if there's nobody authenticated)

      //therefore, the homescreen won't exist anymore and the TodoBloc will be reset

      case '/login':
        return MaterialPageRoute(
          builder: (loginContext) => LoginScreen(),
        );

      default:
        return null;
    }
  }
}
```

Your app.dart should look like this 

```dart
class _AppViewState extends State<AppView> {
  final _navigatorKey = GlobalKey<NavigatorState>();

  NavigatorState get _navigator => _navigatorKey.currentState;
  final AppRouter _appRouter = AppRouter();
  @override
  Widget build(BuildContext context) {
    return MultiRepositoryProvider(
      providers: [
        RepositoryProvider(create: (_) => AuthenticationRepository()),
      ],
      child: MultiBlocProvider(
        providers: [
          BlocProvider<AuthenticationBloc>(
            create: (context) {
              return AuthenticationBloc(
                authenticationRepository:
                    context.read<AuthenticationRepository>(),
              );
            },
          ),
        ],
        child: BlocListener<AuthenticationBloc, AuthenticationState>(
          listener: (context, state) {
            switch (state.status) {
              case AuthenticationStatus.authenticated:
                _navigator.pushNamedAndRemoveUntil(
                  '/authenticatedHome',
                  (route) => false,
                );
                break;
              case AuthenticationStatus.unauthenticated:
                _navigator.pushNamedAndRemoveUntil(
                  '/Login',
                  (route) => false,
                );
                break;
              default:
                break;
            }
          },
          child: MaterialApp(
            theme: theme,
            navigatorKey: _navigatorKey,
            onGenerateRoute: _appRouter.onGenerateRoute,
          ),
        ),
      ),
    );
  }
}
```

And now, whenever you want to push another screen from your homescreen, you'll have your desired scenario, I hope you understood. If not, let me know.

**Comment by yanisG** [comment] 2021-01-27 21:53
@TheWCKD man to go from homeScreen to screen2 for example i do the `Navigator.pushNamed(context,'/screen2');` and when i use your solution that you proposed im getting the could not find the` Error: Could not find the correct Provider<TodosBloc> above this Builder Widget` **and it makes sense** as you said here :

![homescreen](https://user-images.githubusercontent.com/39929140/106058731-f0e73080-60f1-11eb-84e7-b7d28403e87b.PNG)

```
case '/screen2':
        return MaterialPageRoute(
          builder: (screen2Context) => BlocProvider<TodosBloc>.value(
            value: screen2Context.read()<TodosBloc>(),
            child: Screen2(),
          ),
        );
```
i think screen2Context does not contain  the TodosBloc  maybe we should pass the context with RouteSettings arguments no ?

**Comment by yanisG** [comment] 2021-01-27 22:07
@TheWCKD  i'm getting `Error: Could not find the correct Provider<ToddsBloc> above this Builder Widget`  and i think it makes sense 
```
case '/screen2':
        return MaterialPageRoute(
          builder: (screen2Context) => BlocProvider<TodosBloc>.value(
            value: screen2Context.read()<TodosBloc>(),
            child: Screen2(),
          ),
        );
```
because here screen2Context does not contain the TodosProvider no ? as you said here in your video : 
![Carrrrpture](https://user-images.githubusercontent.com/39929140/106060262-12e1b280-60f4-11eb-83e7-49736ea1abbe.PNG)

maybe we should pass it with RouteSettings arguments to obtain the pushed context!?

**Comment by TheWCKD** [comment] 2021-01-27 23:20
Oh, sorry, I think you're correct. I'm sorry, I've been lately programming a lot of C# and really got out of my hands with flutter and dart haha. 

What if you write them like this:

```dart
case '/screen1':
        return MaterialPageRoute(
          builder: (_) => Builder(
            builder: (BuildContext screen1) {
              return BlocProvider<TodosBloc>.value(
                value: screen1.read()<TodosBloc>(),
                child: Screen3(),
              );
            },
          ),
        );
```

**Comment by TheWCKD** [comment] 2021-01-27 23:55
Yep, you can do something like this when you're pushing a new screen. You can pass the current homescreen `context` as an argument to the `onGeneratedRoute` function.

```dart
MaterialButton(
  color: Colors.redAccent,
  child: Text(
    'Go to Second Screen',
    style: TextStyle(color: Colors.white),
  ),
  onPressed: () {
    Navigator.of(context).pushNamed(
      '/second',
      arguments: context,
    );
  },
),
```

Then, inside the onGenerateRoute function you'll have something like this:

```dart
class AppRouter {
  Route onGenerateRoute(RouteSettings settings) {
    BuildContext context = settings.arguments;
    switch (settings.name) {
      case '/':
        return MaterialPageRoute(
          builder: (_) => BlocProvider<TodosBloc>(
            create: (context) => TodosBloc(),
            child: HomeScreen(),
          ),
        );

      case '/second':
        return MaterialPageRoute(
          builder: (_) => BlocProvider.value(
            value: context.read<TodosBloc>(),
            child: SecondScreen(),
          ),
        );
...
```

And, voila, that's how you can provide the existing TodoBloc to all of your screens.

**Comment by yanisG** [comment] 2021-01-28 18:17
yep , and this is how we do it !! 💯 !
@TheWCKD  thanks for your replies and i hope you too learned something from this issue, at first it  was a little confusing to me because i didn't find any docs for that case.(you should talk about it in your future videos 👍 ).

**see you in the next Issue HAHA :D .**
