### ISSUE TITLE
Stop The Process For Loop In BLoC

### ISSUE THREAD

**Issue by rrifafauzikomara** [felangel/bloc#2125] opened 2021-02-02 12:59 UTC
First of all, I have two `for`, `for` (`first for`) inside `for` (`second for`), and when inside `second for` failed to execute some process, I will `stop the process looping` using `break` and update variable boolean too `error = true`. And in `first for` will check if variable boolean `error == true` it will stop the process looping to using `break`. And I try it on the `DartPad` website and this is the logic that I made.
```
void main() {
  
  var a = [1,2,3,4,5];
  var b = [1,2,3,4,4,6];
  
  // first defined as false
  var error = false;
  
  for (var test1 in a) {
    var index = a.indexOf(test1);
    if (error) {
      // if the variable changed to true (error), stop looping too
      break;
    } else {
      print('Outside --> $index');
      for (var test2 in b) {
        var index = b.indexOf(test2);
        if (index == 2) {
          // update to true and stop the loopong
          // it's mean like when failed execute some function and stop the process
          error = true;
          break;
        } else {
          print('Inside --> $index');
        }
      }
    }
  }
}
```

And this is the result when error:
```
Outside --> 0
Inside --> 0
Inside --> 1
```

And this is the result when no error:
```
Outside --> 0
Inside --> 0
Inside --> 1
Inside --> 2
Inside --> 3
Inside --> 3
Inside --> 5

Outside --> 1
Inside --> 0
Inside --> 1
Inside --> 2
Inside --> 3
Inside --> 3
Inside --> 5

Outside --> 2
Inside --> 0
Inside --> 1
Inside --> 2
Inside --> 3
Inside --> 3
Inside --> 5

Outside --> 3
Inside --> 0
Inside --> 1
Inside --> 2
Inside --> 3
Inside --> 3
Inside --> 5

Outside --> 4
Inside --> 0
Inside --> 1
Inside --> 2
Inside --> 3
Inside --> 3
Inside --> 5
```

Using the above code, my logic was successful. And I want to try that logic to my code in BLoC because have the same case.

Splash Screen:
```
class _SplashScreenState extends State<SplashScreen> {
  var _errorQuery = false;    // first defined as false (1)
  var _errorMessage = '';

  void _getDatabaseVersion(BuildContext context) {
    context.read<DatabaseVersionBloc>().add(GetDatabaseVersion());
  }

  @override
  void initState() {
    super.initState();
    _getDatabaseVersion(context); // execute first when init this class (2)
  }

  @override
  Widget build(BuildContext context) {
    var width = MediaQuery.of(context).size.width;
    return Scaffold(
      body: MultiBlocListener(
        listeners: [
          BlocListener<DatabaseVersionBloc, DatabaseVersionState>( // first BLoC
            listener: (context, state) {
              if (state is DatabaseVersionNoInternetConnection) {
                ...
              } else if (state is DatabaseVersionRequestTimeout) {
                ...
              } else if (state is DatabaseVersionError) {
                ...
              } else if (state is DatabaseVersionSuccess) {
                if (state.last) {
                  _navigateToDashboard();
                } else {
                  var maxValueOfLavDataId = state.lavDataId.reduce(max);
                  for (var i in state.data) { // this is `first for` like in the example code
                    if (_errorQuery) { // first, this variable still `false` because first time hit (10)
                      CustomDialog(
                        descriptions: _errorMessage,
                        onPressed: () => _getDatabaseVersion(context),
                      ).show(context); // this show the alert dialog (11)
                      break; // stop the looping because of `_errorQuery` is `true` from `second for` that error execute some function in the `catch` (12)
                    } else {
                      context.read<DatabaseQueryBloc>().add(GetDatabaseQuery( // hit this bloc, and inside this bloc has `second for` that will be return boolean `true` and will be update `_errorQuery` from `false` to `true`
                          databaseVersion: i.dataVersion,
                          lavDataId: i.lavDataId,
                          maxValueOfLavDataId: maxValueOfLavDataId)); // hit this bloc (3)
                    }
                  }
                }
              }
            },
          ),
          BlocListener<DatabaseQueryBloc, DatabaseQueryState>( // second BLoC
            listener: (context, state) { // on this state, will update `_errorQuery` from `false` to `true` except in the `DatabaseQuerySuccess`
              if (state is DatabaseQueryNoInternetConnection) {
                setState(() {
                  _errorMessage = state.message;
                  _errorQuery = state.error;
                });
              } else if (state is DatabaseQueryRequestTimeout) {
                setState(() {
                  _errorMessage = state.message;
                  _errorQuery = state.error;
                });
              } else if (state is DatabaseQueryError) {
                setState(() {
                  _errorMessage = state.message;
                  _errorQuery = state.error; // get update `_errorQuery` from `false` to `true` based on error `catch` (9)
                });
              } else if (state is DatabaseQuerySuccess) {
                if (state.last) {
                  _navigateToDashboard();
                }
              }
            },
          )
        ],
        child: ...,
      ),
    );
  }
}
```

BLoC
```
class DatabaseQueryBloc extends Bloc<DatabaseQueryEvent, DatabaseQueryState> {
   ...

  Stream<DatabaseQueryState> _getDatabaseQuery(
      String databaseVersion, int lavDataId, int maxValueOfLavDataId) async* {
    try {
      var error = false; // first of all, I defined this as `false` (4)
      yield DatabaseQueryLoading(status: 'Downloading ..');
      
      ...

      yield DatabaseQueryLoading(status: 'Inserting ..');
      for (var i in jsonQueryData) {
        try {
          await useCase.runInsertQueryFromServer(i.queryValue);
          error = false;
        } catch (e) {
          print('Error Inserting Query --> $e');
          error = true; // and when I failed execute the function, it will update to `true` (5)
          break; // stop looping process when failed inserting data (6)
        }
      }

      if (error) { // because of error, this variable updated to `true` like in the `catch` above (7)
        yield DatabaseQueryError(
            message: Modular.get<LanguageKeys>().unknownError.tr(),
            error: error); // and return `true` error to `DatabaseQueryError` state (8)
      } else {
        
        ...

        if (lavDataId == maxValueOfLavDataId) {
          yield DatabaseQuerySuccess(last: true);
        } else {
          yield DatabaseQuerySuccess(last: false);
        }
      }
    } on DioError catch (e) {
      ...
    }
  }
}
```

But when I try that code, the `_errorQuery` is not running again, it's mean when I already update the value from `false` to `true` based on ` Second For` in the BLoC. And when I check the log, this is the result:
```
// this loop expected if success is 5
First For ---> false
First For ---> false
First For ---> false
First For ---> false 
First For ---> false

// Result 1st looping from `First For`
Second For ---> false
Second For ---> false
Second For ---> false
Second For ---> false
Second For ---> false

// Result 2nd looping from `First For`
Second For ---> false
Second For ---> false
Second For ---> false
Second For ---> false
Second For ---> false

// Result 3rd looping from `First For`
// This loop expected is 5 if success no error
Second For ---> false
Second For ---> false
Second For ---> true // in this get the error and update the data

// Result 4th looping from `First For`
Second For ---> false
Second For ---> false
Second For ---> false
Second For ---> false
Second For ---> false

// Result 5th looping from `First For`
Second For ---> false
Second For ---> false
Second For ---> false
Second For ---> false
Second For ---> false
```

Based on that result, why `First For` it's looping all data first? Because I expected to like this:
```
First For ---> false
Second For ---> false
Second For ---> false
Second For ---> false
Second For ---> false
Second For ---> false

First For ---> false
Second For ---> false
Second For ---> false
Second For ---> false
Second For ---> false
Second For ---> false

First For ---> false
Second For ---> false
Second For ---> false
Second For ---> true // will stop because of error
```

And on my code already set the note with the number `(1), (2), until (12)`

**Comment by felangel** [comment] 2021-02-03 20:13
Hi @rrifafauzikomara 👋 
Thanks for opening an issue!

Can you please provide a link to a complete reproduction sample which illustrates the problem you're facing? It would be much easier for me to help if I can clone and reproduce the issue locally, thanks! 🙏

**Comment by rrifafauzikomara** [comment] 2021-02-04 04:34
Thanks for the response @felangel 

This is the repo for the below case: [https://github.com/rrifafauzikomara/flutter_app](https://github.com/rrifafauzikomara/flutter_app)


This is the result when no error:
```
flutter: First For Index --> 0
flutter: First For --> false
flutter: First For Index --> 1
flutter: First For --> false
flutter: First For Index --> 2
flutter: First For --> false
flutter: First For Index --> 3
flutter: First For --> false
flutter: First For Index --> 4
flutter: First For --> false


flutter: Second For Index --> 0
flutter: Second For --> false
flutter: Second For Index --> 1
flutter: Second For --> false
flutter: Second For Index --> 2
flutter: Second For --> false
flutter: Second For Index --> 3
flutter: Second For --> false
flutter: Second For Index --> 4
flutter: Second For --> false
flutter: Second For Index --> 0
flutter: Second For --> false
flutter: Second For Index --> 1
flutter: Second For --> false
flutter: Second For Index --> 2
flutter: Second For --> false
flutter: Second For Index --> 3
flutter: Second For --> false
flutter: Second For Index --> 4
flutter: Second For --> false
flutter: Second For Index --> 0
flutter: Second For --> false
flutter: Second For Index --> 1
flutter: Second For --> false
flutter: Second For Index --> 2
flutter: Second For --> false
flutter: Second For Index --> 3
flutter: Second For --> false
flutter: Second For Index --> 4
flutter: Second For --> false
flutter: Second For Index --> 0
flutter: Second For --> false
flutter: Second For Index --> 1
flutter: Second For --> false
flutter: Second For Index --> 2
flutter: Second For --> false
flutter: Second For Index --> 3
flutter: Second For --> false
flutter: Second For Index --> 4
flutter: Second For --> false
flutter: Second For Index --> 0
flutter: Second For --> false
flutter: Second For Index --> 1
flutter: Second For --> false
flutter: Second For Index --> 2
flutter: Second For --> false
flutter: Second For Index --> 3
flutter: Second For --> false
flutter: Second For Index --> 4
flutter: Second For --> false
```

And this is the result when error:
```
flutter: First For Index --> 0
flutter: First For --> false
flutter: First For Index --> 1
flutter: First For --> false
flutter: First For Index --> 2
flutter: First For --> false
flutter: First For Index --> 3
flutter: First For --> false
flutter: First For Index --> 4
flutter: First For --> false


flutter: Second For Index --> 0
flutter: Second For --> false
flutter: Second For Index --> 1
flutter: Second For --> false
flutter: Second For Index --> 2
flutter: Second For --> false
flutter: Second For Index --> 3
flutter: Second For --> false
flutter: Break Looping Insert Query ---> true
flutter: Second For Index --> 0
flutter: Second For --> false
flutter: Second For Index --> 1
flutter: Second For --> false
flutter: Second For Index --> 2
flutter: Second For --> false
flutter: Second For Index --> 3
flutter: Second For --> false
flutter: Break Looping Insert Query ---> true
flutter: Second For Index --> 0
flutter: Second For --> false
flutter: Second For Index --> 1
flutter: Second For --> false
flutter: Second For Index --> 2
flutter: Second For --> false
flutter: Second For Index --> 3
flutter: Second For --> false
flutter: Break Looping Insert Query ---> true
flutter: Second For Index --> 0
flutter: Second For --> false
flutter: Second For Index --> 1
flutter: Second For --> false
flutter: Second For Index --> 2
flutter: Second For --> false
flutter: Second For Index --> 3
flutter: Second For --> false
flutter: Break Looping Insert Query ---> true
flutter: Second For Index --> 0
flutter: Second For --> false
flutter: Second For Index --> 1
flutter: Second For --> false
flutter: Second For Index --> 2
flutter: Second For --> false
flutter: Second For Index --> 3
flutter: Second For --> false
flutter: Break Looping Insert Query ---> true
```

As you can see above, why `First For` it's looping all data first? Because I expected to like this:
```
flutter: First For Index --> 0
flutter: First For --> false
flutter: Second For Index --> 0
flutter: Second For --> false
flutter: Second For Index --> 1
flutter: Second For --> false
flutter: Second For Index --> 2
flutter: Second For --> false
flutter: Second For Index --> 3
flutter: Second For --> false
flutter: Second For Index --> 4
flutter: Second For --> false

flutter: First For Index --> 1
flutter: First For --> false
flutter: Second For Index --> 0
flutter: Second For --> false
flutter: Second For Index --> 1
flutter: Second For --> false
flutter: Second For Index --> 2
flutter: Second For --> false
flutter: Second For Index --> 3
flutter: Second For --> false
flutter: Second For Index --> 4
flutter: Second For --> false

flutter: First For Index --> 2
flutter: First For --> false
flutter: Second For Index --> 0
flutter: Second For --> false
flutter: Second For Index --> 1
flutter: Second For --> false
flutter: Second For Index --> 2
flutter: Second For --> false
flutter: Second For Index --> 3
flutter: Second For --> false
flutter: Second For Index --> 4
flutter: Second For --> false

flutter: First For Index --> 3
flutter: First For --> false
flutter: Second For Index --> 0
flutter: Second For --> false
flutter: Second For Index --> 1
flutter: Second For --> false
flutter: Second For Index --> 2
flutter: Second For --> false
flutter: Second For Index --> 3
flutter: Second For --> false
flutter: Second For Index --> 4
flutter: Second For --> false

flutter: First For Index --> 4
flutter: First For --> false
flutter: Second For Index --> 0
flutter: Second For --> false
flutter: Second For Index --> 1
flutter: Second For --> false
flutter: Second For Index --> 2
flutter: Second For --> false
flutter: Second For Index --> 3
flutter: Second For --> false
flutter: Second For Index --> 4
flutter: Second For --> false
```

**Comment by felangel** [comment] 2021-02-10 03:00
Hi @rrifafauzikomara sorry for the delayed response! The reason why the example is executing in this order is because you are looping through each item in state.data synchronously and adding an event to the DatabaseQueryBloc and these events are processed asynchronously. As a result, all of the event are added immediately and then they are processes in the order in which they are received by the DatabaseQueryBloc. If you want each event to be processed before adding the next one you will need to adjust your logic. Something like this should work:

```dart
             ...
              } else if (state is DatabaseVersionSuccess) {
                // ignore: close_sinks
                final bloc = context.read<DatabaseQueryBloc>();
                if (_errorQuery) {
                  CustomDialog(
                    descriptions: _errorMessage,
                    onPressed: () => _getDatabaseVersion(context),
                  ).show(context);
                  return;
                }

                bloc.add(GetDatabaseQuery());
                print('First For Index --> 0');
                await bloc.first;
                for (int i = 1; i < state.data.length; i++) {
                  var index = state.data.indexOf(i);
                  print('First For Index --> $index');
                  print('First For --> $_errorQuery');
                  bloc.add(GetDatabaseQuery());
                  await bloc.first;
                }
              }
```

This code adds the first event and then waits until a new state was emitted before adding another event. In general there are better ways to achieve this but it's hard for me to provide suggestions without better understanding what you're trying to achieve.

Hope that helps and closing for now but feel free to comment with any questions or [join the discord server](https://discord.gg/Hc5KD3g) 👍

**Closed by felangel** 2021-02-10 03:00 UTC
Labels: question, waiting for response
