### ISSUE TITLE
Exception thrown on unit testing bloc: The following NoSuchMethodError was thrown building BlocBuilder<SignInBloc, SignInState>(dirty, state: _BlocBuilderBaseState<SignInBloc, SignInState>#2717f): The getter 'isFormValid' was called on null. 

### ISSUE THREAD

**Issue by geovin89** [felangel/bloc#1324] opened 2020-06-21 03:02 UTC
**Describe the bug**
I was following the [Firebase login tutorial](https://bloclibrary.dev/#/flutterfirebaselogintutoria)  and I ended with this issue while adding unit tests to my code (actual code works fine)

**To Reproduce**
1. My SignOn Screen code (I am using getIt for dependency injection)
```dart
class SignInScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: Text('Sign In'),
        backgroundColor: Colors.redAccent,
      ),
      body: BlocProvider<SignInBloc>(
        create: (context) => getIt<SignInBloc>(),
        child: SignInForm(),
      ),
    );
  }
}
```
2. The SignInForm is exactly like the LoginForm code  provided in the tutorial

3. I created Mock classes for unit testing the SignInScreen like this
```dart
@test
@Injectable(as: SignInBloc)
class MockSignInBloc extends MockBloc<SignInEvent, SignInState>
    implements SignInBloc {}
```
(The injection works fine I believe)

4. I get this error on unit testing the SignInScreen 
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building BlocBuilder<SignInBloc, SignInState>(dirty,
state: _BlocBuilderBaseState<SignInBloc, SignInState>#8d82e):
The getter 'isFormValid' was called on null.
Receiver: null
Tried calling: isFormValid

**Expected behavior**
The unit tests should work fine with the initial SignInState state emitted from the bloc

Any reason why the initial state is not emitted by the mocked bloc resulting in the state being null?

**Comment by felangel** [comment] 2020-06-21 03:24
Hi @geovin89 👋 
Thanks for opening an issue! 

Since you're mocking the bloc you need to stub the state otherwise the bloc's state will be null.

```dart
when(signInBloc.state).thenReturn(SomeState());
// The rest of the test...
```

Hope that helps 👍

**Comment by geovin89** [comment] 2020-06-21 03:55
Thanks a lot for the quick response felngel

One more question, so how does the
```dart
blocTest(
      'emits [] when nothing is added',
      build: () async => CounterBloc(),
      skip: 0,
      expect: [InitialState],
    );
```
work without mocking returning states?

**Comment by geovin89** [comment] 2020-06-21 04:08
Additonally is there anyway blocTests can be for adding multiple events? like this
```dart
blocTest('emits states from initial when email is valid',
          build: () async {
            return SignInBloc(signInWithCredentials);
          },
          act: (signInBloc) => signInBloc.add(
                SignInEmailChanged(email: invalidEmail),
                SignInEmailChanged(email: validEmail),
              ),
          wait: const Duration(milliseconds: 300),
          expect: [emailInvalidState, emailValidState]);
```

Thanks in advance

**Comment by felangel** [comment] 2020-06-21 13:20
blocTest should be used to test your bloc (the real implementation) so you shouldn’t be using a MockBloc in your blocTest. Blocs should be mocked in widget tests to ensure that you can fully test how the widget behaves in each scenario. With any tests, the thing that your testing should be the actual implementation and all of the dependencies should ideally be mocked.

Regarding your second question, you can just call add multiple times or chain them together like:

```dart
blocTest('emits states from initial when email is valid',
          build: () async {
            return SignInBloc(signInWithCredentials);
          },
          act: (signInBloc) => 
              signInBloc
                ..add(SignInEmailChanged(email: invalidEmail))
                ..add(SignInEmailChanged(email: validEmail),)
              ),
          wait: const Duration(milliseconds: 300),
          expect: [emailInvalidState, emailValidState]);
```

Closing for now but feel free to comment with additional questions and I’m happy to continue the conversation 👍

**Closed by felangel** 2020-06-21 13:20 UTC
Labels: pkg:bloc_test, question, waiting for response

**Comment by geovin89** [comment] 2020-06-21 19:15
Gotcha!

Thanks a lot Felix. Hopefully the last question :). This for my understanding of how whenListen works.
I was trying to widget test snack bar display in the LoginForm screen
```dart
testWidgets('should show snack bar loading when bloc returns loading state',
        (WidgetTester tester) async {
      whenListen(signInBloc,
          Stream.fromIterable([SignInState.initial(), SignInState.loading()]));

      await tester.pumpWidget(
        BlocProvider.value(
          value: signInBloc,
          child: MaterialApp(
            home: Scaffold(body: SignInForm()),
          ),
        ),
      );

      await tester.pump();

      final snackBarFinder = find.byKey(snackBarKey);
      final widget = snackBarFinder.evaluate().first.widget as SnackBar;
       expect(snackBarFinder, findsOneWidget);

    });
````
if I pass only SignInState.loading(), the test fails; I just want to know why. 
P.S. Is there a better way for testing how the UI would behave when bloc receives each of the events? Like first you added emailChanged and then passwordChanged, Submit etc

**Comment by geovin89** [comment] 2020-06-21 19:28
I did try your suggestion 
```dart
final emailValidState = SignInState.initial();
final emailInvalidState = emailValidState.copyWith(isEmailValid: false);

blocTest(
        'should emit correct states when email is changed from invalid to valid',
        build: () async {
          return SignInBloc(signInWithCredentials);
        },
        act: (signInBloc) => signInBloc
          ..add(SignInEmailChanged(email: invalidEmail))
          ..add(SignInEmailChanged(email: validEmail)),
        wait: const Duration(milliseconds: 300),
        verify: (_) async {
          verifyNever(signInWithCredentials(any));
        },
        expect: [emailInvalidState, emailValidState],
      );
```

but I am receiving this error
```log
.<fn>.<fn>
package:bloc_test/src/bloc_test.dart 140:20                                 blocTest.<fn>.<fn>
===== asynchronous gap ===========================
dart:async                                                                  _asyncThenWrapperHelper
package:bloc_test/src/bloc_test.dart                                        blocTest.<fn>.<fn>
dart:async                                                                  runZoned
package:bloc_test/src/bloc_test.dart 135:11                                 blocTest.<fn>

type 'SignInBloc' is not a subtype of type 'Future<void>'
```

**Comment by felangel** [comment] 2020-06-23 23:10
@geovin89 can you please share a link to a sample app which reproduces the issue and I'll take a look and try to open a pull request 👍

**Comment by geovin89** [comment] 2020-06-24 04:43
I have created a sample app here https://github.com/geovin89/bloc_test. I have posted my questions in there as 3 Todos so that you dont get lost in there

**Comment by felangel** [comment] 2020-06-29 15:55
@geovin89 sorry for the delay! I opened a [pull request](https://github.com/geovin89/flutterbloctestapp/pull/1) with my suggestions 👍

**Comment by geovin89** [comment] 2020-07-05 16:30
@felangel  You have gone above and beyond for this refactor! Thanks for putting in the time to answer my question and also making the existing code better. I feel indebted :).

Once again thank you!!

**Comment by ostup17** [comment] 2022-09-11 12:41
> 

I'm getting a similar error and can't figure out how to fix it -
_Error - The following RangeError was thrown building BlocBuilder<DetailsCubit, DetailsState>(dirty, dependencies: [_InheritedProviderScope<DetailsCubit?>], state: _BlocBuilderBaseState<DetailsCubit, DetailsState>#5a690):
RangeError (index): Invalid value: Only valid value is 0: 5_

MultiBlocProvider - ```
return MultiBlocProvider(
       providers: [
         BlocProvider<DetailsCubit>(create: (context) => sl<DetailsCubit>()..loadDetails()),
       ],
       child: Scaffold(
         body: DetailsBody(),
       ),
     );
```

BlockBuilder - ```
return BlocBuilder<DetailsCubit, DetailsState>(
         builder: (context, state) {
           List<DetailsEntity> details = [];
           if(state is DetailsLoading) {
             return _loadingIndicator();
           } else if(state is DetailsLoaded) {
             details = state.detailList;
           }
```
