### ISSUE TITLE
fix: Bloc with freezed package not listening to changes

### ISSUE THREAD

**Issue by mjd-dalloul** [felangel/bloc#3512] opened 2022-08-19 16:59 UTC
I am having this issue, it appears sometimes `BlocBuilder` and `BlocListener` dosen't work.
here is an example:
my state
```
class UploadFilesState with _$UploadFilesState {
  const factory UploadFilesState({
    required double uploadProgress,
    required bool isUploading,
    required Option<Either<Failure, bool>> uploadSuccessOrFailed,
    required Option<Either<Failure, bool>> uploadFileToQueueSuccessOrFailure,
    required Option<Either<Failure, bool>> uploadFileToPrintSuccessOrFailure,
    required Option<Either<Failure, GCodeAnalysisEntity>> fileAnalyzingSuccessOrFailure,
    required bool analyzing,
    required List<UploadTaskEntity> tasks,
    required Option<UploadTaskEntity> doneTask,
  }) = _DownloadUploadFilesState;

  factory UploadFilesState.initial() => UploadFilesState(
    uploadProgress: 0.0,
    isUploading: false,
    analyzing: false,
    tasks: [],
    doneTask: none(),
    uploadSuccessOrFailed: none(),
    uploadFileToQueueSuccessOrFailure: none(),
    uploadFileToPrintSuccessOrFailure: none(),
    fileAnalyzingSuccessOrFailure: none(),
  );
}
```
and this is my event handlers in bloc
```
  Future<void> _onFileUploadedToQueue(FileUploadedToQueue event,
      Emitter<UploadFilesState> emit) async {
    emit(state.copyWith(analyzing: true, fileAnalyzingSuccessOrFailure: none()));
    final gCodeResult =
    await analyzeGCodeFile(event.file);
    emit(state.copyWith(analyzing: false, fileAnalyzingSuccessOrFailure: optionOf(gCodeResult)));
    if(gCodeResult.isLeft()) {
      return;
    }
    final tasks = List.of(state.tasks);
    final task = createTask(
        'Adding file ${event.file.path
            .split('/')
            .last} to print queue',
        UploadType.QUEUE);
    tasks.add(task);
    emit(state.copyWith(
      tasks: tasks,
    ));
    final res = await addToQueue(
      AddQueueItemEntity(
        gCodeAnalysisModel: GCodeAnalysisModel.fromDomain(
          gCodeResult.getOrElse(() => GCodeAnalysisEntity.initial()),
        ),
        file: event.file,
        taskId: task.id,
      ),
    );
    add(UploadFilesEvent.removeTask(task.id, optionOf(res)));
  }
  Future<void> _onTaskUpdated(TaskUpdated event,
      Emitter<UploadFilesState> emit) async {
    final tasks = List.of(state.tasks);
    for (int i = 0; i < tasks.length; i++) {
      if (tasks[i].id == event.taskId) {
        tasks[i] = tasks[i].copyWith(taskProgress: event.progress);
        break;
      }
    }
    emit(state.copyWith(
      tasks: tasks,
    ));
  }

  Future<void> _onRemoveTask(RemoveTask event,
      Emitter<UploadFilesState> emit) async {
    emit(state.copyWith(
      doneTask: none(),
      uploadFileToQueueSuccessOrFailure: none(),
      uploadFileToPrintSuccessOrFailure: none(),
    ));
    final tasks = List.of(state.tasks);
    late UploadTaskEntity doneTask;
    late final UploadType uploadType;
    for (int i = 0; i < tasks.length; i++) {
      if (tasks[i].id == event.id) {
        doneTask = tasks[i];
        uploadType = tasks[i].uploadType;
      }
    }
    tasks.removeWhere((element) => element.id == event.id);
    emit(state.copyWith(
      tasks: tasks,
      doneTask: optionOf(doneTask),
      uploadFileToQueueSuccessOrFailure: uploadType == UploadType.QUEUE ? event
          .successOrFailure : none(),
      uploadFileToPrintSuccessOrFailure: uploadType == UploadType.PRINT ? event
          .successOrFailure : none(),
    ));
  }
```
and I am providing this bloc above the material app snice it will like singleton bloc (bloc name is UploadFilesBloc)

```
class AppProvider extends StatelessWidget {
  const AppProvider({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: <BlocProvider<dynamic>>[
        BlocProvider<UploadFilesBloc>.value(
            value: sl<UploadFilesBloc>()
              ..add(const UploadFilesEvent.initialEvent())),
        BlocProvider<AppBloc>.value(
            value: sl<AppBloc>()..add(const AppEvent.initialEvent())),
        BlocProvider<AuthBloc>.value(value: sl<AuthBloc>()),
        // BlocProvider<WebSocketBloc>.value(value: sl<WebSocketBloc>()),
        BlocProvider<FilamentBloc>.value(value: sl<FilamentBloc>()),
      ],
      child: const App(),
    );
  }
}
```
now I just wanna show the user some toast or flushbar when anything change inside this bloc
so I have a listener above the material app.

```
class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MultiBlocListener(
        listeners: [
          BlocListener<UploadFilesBloc, UploadFilesState>(
            listenWhen: (p, c) =>
                p.fileAnalyzingSuccessOrFailure !=
                c.fileAnalyzingSuccessOrFailure,
            listener: (context, state) {
              state.fileAnalyzingSuccessOrFailure.fold(
                () {
                  //ignore
                },
                (failureOrSuccess) {
                  failureOrSuccess.fold(
                    (failure) => FailureParser.parseFailure(
                        RouteManager.navigatorGlobalKey.currentContext!,
                        failure),
                    (_) {
                     log('good file');
                    },
                  );
                },
              );
            },
          ),
          BlocListener<UploadFilesBloc, UploadFilesState>(
            listenWhen: (_, c) => c.analyzing,
            listener: (context, state) {
                FlushbarHelper.createLoading(
                  message: UIHelperFunctions.formatStringWithCapFirstLatter(
                      'Analyzing file'),
                  linearProgressIndicator: const LinearProgressIndicator(),
                ).show(RouteManager.navigatorGlobalKey.currentContext!);
            },
          ),
        ],
        child: BlocBuilder<AppBloc, AppState>(
          buildWhen: (p, c) =>
              p.theme != c.theme || p.connectionStatus != c.connectionStatus,
          builder: (BuildContext context, AppState state) {
            return MaterialApp(
              home: const SplashPage(),
              onGenerateRoute: RouteManager.onGenerateRoute,
              navigatorKey: RouteManager.navigatorGlobalKey,
              theme: AppTheme.getThemeData(state.theme),
            );
          },
        ));
  }
}
```
those 2 listener are not triggered when changing the state, of course I thought for some reason the state is not updating so that the listener is not triggered.
so I commented this condition (oldState != newState)
`if (this.state == state && _emitted) return;`
`if (state == _state && _emitted) return;`
also some `BlocBuilder` inside some pages are not triggered too.

**Comment by adryanev** [comment] 2022-08-27 06:15
Have you tried using `BlocProvider(create: (_) => sl<UploadFilesBloc>()` instead of `BlocProvider.value()` when providing the bloc? @mjd-dalloul

**Comment by mjd-dalloul** [comment] 2022-08-27 15:58
same result, because it technically the same since the bloc is above the `MaterialApp` and am only doing `.value` because I am following some pattern in my code.

**Comment by akshaynjarangal** [comment] 2022-09-21 04:20
@mjd-dalloul Hey bro , we facing the same issue with freezed bloc, and When initialise a bloc in Material App,and when try listening/building  change another screen , then bloc state will reset to to initial. @felangel Please find out the bug.

**Comment by adryanev** [comment] 2022-12-22 17:24
> same result, because it technically the same since the bloc is above the `MaterialApp` and am only doing `.value` because I am following some pattern in my code. @adryanev

Hmm, I'm also using bloc with freezed and have no issues with it. From my experience, if the builders / listeners are not triggered when an event is fired, it's happened because the bloc that firing the event and the listener were different instance.
So, make sure you are not calling the bloc with `sl<UploadFilesBloc>() ` or having another `BlocProvider<UploadFilesBloc>()` in other places.

**Comment by felangel** [comment] 2022-12-27 01:47
Hi @mjd-dalloul 👋 
Can you please provide a link to a minimal reproduction sample that illustrates the issue? Thanks!

**Comment by felangel** [comment] 2023-01-02 22:33
Closing for now since there isn't enough information to help. Please provide a link to a minimal reproduction sample and I'm happy to take a closer look, thanks!

**Closed by felangel** 2023-01-02 22:33 UTC
Labels: question, waiting for response
