### ISSUE TITLE
6.0+ BlocProvider that wraps MaterialApp fails to be added to home widget's context

### ISSUE THREAD

**Issue by JohnGalt1717** [felangel/bloc#1694] opened 2020-09-03 14:18 UTC
**Describe the bug**
Per above:

App/build
BlocProvider<ABloc> => return MaterialApp(home: SomePage) => SomePage.Build => BlockBuilder<ABloc> throws.

**To Reproduce**
1. in the root App Stateless Widget wrap the MaterialApp() in a blocprovider.
2. In the home: of MaterialApp use a BlocBuilder to get the blocProvider's bloc
3. BlocProvider.of() called with a context

**Expected behavior**
Should work like 5.0 worked and properly pass the provider through the material app.

**Comment by felangel** [comment] 2020-09-03 14:37
Hi @JohnGalt1717 👋 
Thanks for opening an issue!

Can you please provide a sample app which reproduces the issue? Thanks 👍

**Comment by felangel** [comment] 2020-09-07 22:18
Closing for now since there isn't enough information to reproduce the issue. Feel free to comment with additional information or a sample app and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-09-07 22:18 UTC
Labels: question, waiting for response

**Comment by JohnGalt1717** [comment] 2020-09-09 14:03
Sorry, was on vacation.

I believe I found my issue. It was odd that it cropped up with V6 and wasn't there with the same code in V5.  (had the bloc defined in multiple packages).

Thanks.
