### ISSUE TITLE
Condition state is not read if the page called before was opened by navigator

### ISSUE THREAD

**Issue by FredG13** [felangel/bloc#1008] opened 2020-04-07 01:49 UTC
Good morning,

I have a problem when I open the SplashPage with Navigator. The SplashFinished state launched at the end of the page loading is not read in the page calling main.asp : 

**The SplashPage is called from the main.dart page:**

```
if (state is AuthenticationInit) {
         //return SplashPage(); --> **** it works **** 

         SchedulerBinding.instance.addPostFrameCallback((_) {
           Navigator.of(context).pushReplacementNamed("/splash"); // Opening the SplashPage --> **** Does not work : state is AuthenticationAuthOk is not read ***
           return;
         });
 }
```

**SplashPage :**
`BlockProvider.of<AuthenticationBlock>(context).add(SplashFinished());`

**AuthenticationBlock Page:**
```
if (event is SplashFinished) {
        yield AuthenticationAuthOk();
}
```
**The condition state below is not read if the page SplashPage called before was opened by Navigator**.
**Whereas if I do a "return SplashPage();" in my main.asp page it works!**
```
if (state is AuthenticationAuthOk) {
          
}
```

Thanks in advance for your help.
My best regards,

Frédéric

**Comment by theDarkBoffin** [comment] 2020-04-07 16:15
Hi @FredG13,
Can you provide more details on `SplashPage` so that I could get a better understanding as to where you're calling `BlocProvider.of<AuthenticationBloc>(context).add(SplashFinished());`?

Regards.

**Comment by FredG13** [comment] 2020-04-07 17:32
Hi @theDarkBoffin,

Here is the code of the SplashPage :

```
class SplashPage extends StatefulWidget {
  /// Constructeur.
  const SplashPage();

  @override
  _SplashPageState createState() => _SplashPageState();
}

class _SplashPageState extends State<SplashPage> with SingleTickerProviderStateMixin {
  AnimationController _iconAnimationController;
  CurvedAnimation _iconAnimation;

  @override
  void initState() {
    super.initState();
    _iconAnimationController = AnimationController(vsync: this, duration: const Duration(milliseconds: 3000));
    _iconAnimation = CurvedAnimation(parent: _iconAnimationController, curve: Curves.easeOut);
    _iconAnimation.addListener(() => setState(() {}));
    _iconAnimation.addStatusListener((status) {
      if (status == AnimationStatus.completed) {

        // ************** Adding the event SplashFinished ************** 
        BlocProvider.of<AuthentificationBloc>(context).add(SplashFinished());

      }
    });
    _iconAnimationController.forward();
  }

  @override
  void dispose() {
    _iconAnimationController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return BackgroundStart(
      listWidgets: <Widget>[
        Center(
          child: Hero(tag: "logo", child: LogoContainer(image: logo, withImg: 300.0 * _iconAnimation.value, heightImg: 98.0 * _iconAnimation.value)),
        )
      ],
    );
  }
}

```
Thanks.

Regards.

**Comment by theDarkBoffin** [comment] 2020-04-07 18:08
Hey @FredG13,
Thanks for providing the code snippet. `SplashPage` looks fine. By this, what I can assume is, maybe the way you're providing `AuthenticationBloc` using `BlocProvider` might be the issue here. I'm sorry, I would need a code snippet on how you're providing/creating `AuthenticationBloc`, and how your main.dart looks like where you're checking `state is AuthenticationAuthOk`.
If I try to answer based on just `SplashPage` now, I must answer with a lot of assumptions.
Thanks.

**Comment by FredG13** [comment] 2020-04-07 19:46
@theDarkBoffin,

Here is the code of the AuthenticationBloc:

```
class AuthenticationBloc extends Bloc<AuthenticationEvent, AuthenticationState> {
  /// Dépôt Utilisateur.
  final UtilisateurRepository utilisateurRepository;

  /// Constructeur.
  AuthenticationBloc({@required this.utilisateurRepository}) : assert(utilisateurRepository != null);

  @override
  AuthenticationState get initialState => AuthenticationInit();

  @override
  Stream<AuthenticationState> mapEventToState(AuthenticationEvent event) async* {
    if (event is AppStarting) {
      yield AuthenticationInit();
    }

    // ************************************************** Event SplashFinished **************************************************

    if (event is SplashFinished) {
      yield* _verifieJeton();
      if (globals.jwt != null) {
        yield AuthenticationAuthOk(); // ----> See next page main.asp
      }
    }

    // **************************************************************************************************************************

    if (event is Connecte) {
      print("event is Connecte");
      yield AuthenticationLoading();

      // Sauvegarde sur le disque le jeton JWT
      await utilisateurRepository.sauvegarderJeton(event.utilisateurApi.jwt);

      // Récupère les données sur le jeton
      final mapJeton = await jwtEstValide(event.utilisateurApi.jwt);
      print("Renouvellement jeton : Date début = ${mapJeton["dateDeb"]}, Date fin = ${mapJeton["dateFin"]}");

      // Enregistre les données dans les variables globales de l'application
      _setGlobals(utilisateurApi: event.utilisateurApi, mapJeton: mapJeton);
    }

    if (event is Deconnecte) {
      print("event is Deconnecte");
      yield AuthenticationLoading();
      await utilisateurRepository.supprimerJeton();
      _razGlobals(); // RAZ des variables globales de l'application
      yield AuthenticationInit();
    }

    if (event is VerifieJeton) {
      yield* _verifieJeton();
    }
  }

  /// Vérifie le jeton JWT.
  Stream<AuthenticationState> _verifieJeton() async* {
    String jeton;

    try {
      if (globals.jwt.isNullOrEmpty()) {
        jeton = await prefs.getJwt();
      } else {
        jeton = globals.jwt;
      }

      if (!jeton.isNullOrEmpty()) {
        Map<String, int> mapJeton;

        // On récupère le jeton et on vérifie s'il est toujours valide
        mapJeton = await jwtEstValide(jeton);

        if (!mapJeton.isNullOrEmpty()) {
          // ******* Le jeton est valide

          print("******* Le jeton est valide *******");
          print("mapJeton idUtilisateur = ${mapJeton["idUtilisateur"]}");
          print("globals.jwt = ${globals.jwt}");
          print("***********************************");

          var renouvelleJeton = false;

          if (globals.jwt.isNullOrEmpty()) {
            renouvelleJeton = true;
          } else {
            // On renouvelle le jeton tous les jours
            final dateDuJour = DateFormat("yyyy-MM-dd").format(DateTime.now());
            final dateDeb = DateFormat("yyyy-MM-dd").format(DateTime.fromMillisecondsSinceEpoch(globals.jwtDateDeb * 1000));

            print("Aujourd'hui = $dateDuJour, dateDeb Jeton = $dateDeb");

            if (dateDuJour.compareTo(dateDeb) == 1) {
              // La date de début du jeton n'est plus à la date d'aujourd'hui -> On renouvelle le jeton
              renouvelleJeton = true;
            }
          }

          if (renouvelleJeton) {
            // On renouvelle le jeton

            if (globals.jwt.isNullOrEmpty()) {
              globals.jwt = jeton;
            }

            final utilisateurApi = await utilisateurRepository.getUtilisateur(idUtilisateur: mapJeton["idUtilisateur"]);

            // Sauvegarde sur le disque le jeton JWT
            utilisateurRepository.sauvegarderJeton(utilisateurApi.jwt);

            // Récupère les données sur le jeton
            final mapNewJeton = await jwtEstValide(utilisateurApi.jwt);
            print("Renouvellement jeton : idUtilisateur = ${mapNewJeton["idUtilisateur"]}, Date début = ${mapNewJeton["dateDeb"]}, Date fin = ${mapNewJeton["dateFin"]}");

            // Enregistre les données dans les variables globales de l'application
            _setGlobals(utilisateurApi: utilisateurApi, mapJeton: mapNewJeton);
          } else {
            print("On ne renouvelle pas le jeton");
          }
        } else {
          // Le jeton n'est plus valide -> On le supprime
          utilisateurRepository.supprimerJeton();
          jeton = null;

          // RAZ des variables globales de l'application
          _razGlobals();
        }
      }
    } on ExceptionApi catch (e, s) {
      print("********************************************************************");
      print("Erreur authentification_bloc ExceptionApi : Message = ${e.message},\n\nDétail = ${e.detail?.message},\nFichier = ${e.detail?.fichier},\nCode = ${e.detail?.code},\nN° ligne = ${e.detail?.ligne},\n${e.detail?.trace}, Trace : $s\n");
      print("********************************************************************");
      jeton = null;
    } catch (e, s) {
      print("********************************************************************");
      print("Erreur authentification_bloc : ${e.toString()},\nTrace : $s");
      print("********************************************************************");
      jeton = null;
    }

    if (jeton.isNullOrEmpty()) {
      // RAZ des variables globales de l'application
      _razGlobals();

      // ********************************************* 
      yield AuthenticationNonAuth();
    }
  }

  /// Enregistre les données sur le jeton et l'utilisateur connecté dans les variables globales de l'application
  void _setGlobals({@required UtilisateurApi utilisateurApi, @required Map<String, int> mapJeton}) {
    globals.jwt = utilisateurApi.jwt;
    globals.jwtDateDeb = mapJeton["dateDeb"];
    globals.jwtDateFin = mapJeton["dateFin"];
    globals.utilisateurEnCours = utilisateurApi.utilisateur;
  }

  /// RAZ des données sur le jeton et de l'utilisateur connecté dans les variables globales de l'application
  void _razGlobals() {
    globals.jwt = null;
    globals.jwtDateDeb = null;
    globals.jwtDateFin = null;
    globals.utilisateurEnCours = null;
  }
}

```

Here is the code of the main.asp:

```

/// Transitions et erreurs dans l'application.
class SimpleBlocDelegate extends BlocDelegate {
  @override
  void onEvent(Bloc bloc, Object event) {
    super.onEvent(bloc, event);
    print(event);
  }

  @override
  void onTransition(Bloc bloc, Transition transition) {
    super.onTransition(bloc, transition);
    print("Transition : $transition");
  }

  @override
  void onError(Bloc bloc, Object error, StackTrace stacktrace) {
    super.onError(bloc, error, stacktrace);
    print("Erreur : $error\n${stacktrace.toString()}");
  }
}

void main() {
  BlocSupervisor.delegate = SimpleBlocDelegate();
  final utilisateurRepository = UtilisateurRepository();
  runApp(
    BlocProvider<AuthenticationBloc>(
      create: (context) {
        return AuthenticationBloc(utilisateurRepository: utilisateurRepository)..add(AppStarting());
      },
      child: App(utilisateurRepository: utilisateurRepository),
    ),
  );
}

/// Application.
class App extends StatelessWidget {
  /// Dépôt Utilisateur.
  final UtilisateurRepository utilisateurRepository;

  /// Constructeur.
  App({Key key, @required this.utilisateurRepository}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "SportAdic",
      debugShowCheckedModeBanner: false,
      theme: themeParDefaut,
      home: _getPageDemarrage(),
      onGenerateRoute: (settings) {
        switch (settings.name) {
          case "/decision":
            return MyCustomRoute<void>(builder: (context) => DecisionPage(), settings: settings);
          case "/login":
            return MyCustomRoute<void>(builder: (context) => settings.arguments as Widget, settings: settings, transitionMilliseconds: 4000);
          case "/login_inscription":
            return SlideEcranGauche(widget: LoginPage(utilisateurRepository: utilisateurRepository, formMode: FormMode.inscription));
          case "/home":
            return MyCustomRoute<void>(builder: (context) => ActiviteFamillePage(), settings: settings);
          case "/splash":
            return MyCustomRoute<void>(builder: (context) => SplashPage(), settings: settings);

          default:
            return null;
        }
      }
    );
  }

  /// Obtenir la page de démarrage de l'application.
  Widget _getPageDemarrage() {
    return BlocBuilder<AuthenticationBloc, AuthenticationState>(
      builder: (context, state) {


        if (state is AuthenticationInit) {
          //return SplashPage(); --> **** it works ****
          SchedulerBinding.instance.addPostFrameCallback((_) {
            Navigator.of(context).pushReplacementNamed("/splash"); // Opening the SplashPage --> **** Does not work : state is AuthenticationAuthOk is not read ***
            return;
          });
        }


        if (state is AuthenticationLoading) {
          return Loading();
        }
        if (state is AuthenticationNonAuth) {
          print("*** state is AuthenticationNonAuth *** ");
          SchedulerBinding.instance.addPostFrameCallback((_) {
            Navigator.pushReplacementNamed(context, "/login", arguments: LoginPage(utilisateurRepository: utilisateurRepository));
            return;
          });
        }
       
        *************** Does not work : state is AuthenticationAuthOk is not read *************** 
        if (state is AuthenticationAuthOk) {
          return ActiviteFamillePage();
        }

        return SplashPage();
      },
    );
  }
}

/// Gestion des transitions entre les pages.
class MyCustomRoute<T> extends MaterialPageRoute<T> {
  /// Temps de transition en milli-seconde.
  final int transitionMilliseconds;

  /// Constructeur.
  MyCustomRoute({WidgetBuilder builder, RouteSettings settings, this.transitionMilliseconds = 500}) : super(builder: builder, settings: settings);

  @override
  Duration get transitionDuration => Duration(milliseconds: transitionMilliseconds);

}

```
Thanks for your help.

Frédéric

**Comment by theDarkBoffin** [comment] 2020-04-07 21:10
@FredG13 thanks for the code.
`return SplashPage()` will trigger state change because `SplashPage` is the child of `BlocBuilder`, and `BlocBuilder` isn't disposed of by the engine when `SplashPage` adds the event `AuthenticationAuthOk`.
But, if you use `Navigator.of(context).pushReplacementNamed`, by the time `SplashPage` is pushed, the engine will dispose `BlocBuilder`, and hence your builder isn't called anymore on state change.

In the Login Recipe section of the documentation, BlocBuilder is used for navigation instead of `Navigator`. This is actually a chicken-and-egg situation. If we use `BlocListener` as a parent of `MaterialApp` and try to push the new route, it won't work because `BlocListener`'s context isn't valid to modify the child `MaterialApp`'s `Navigator`. If we use `BlocListener` as the home of `MaterialApp`, and push routes based on state change, `BlocListener` is disposed of when you push the first route.
Initially, I stumbled upon this problem too and just ended up using `Direct Navigation` using `BlocBuilder` as suggested in the **Navigation Recipe** of the documentation. It has been sufficient for my use cases. I suggest you go with the same approach if it doesn't hurt your use case.

@felangel even I'm interested to know the best pattern to follow in such a circumstance where one needs **Navigator for routing and BlocListener for deciding which route to load**.

**Comment by FredG13** [comment] 2020-04-07 21:58
@theDarkBoffin,

Thank you very much for your response. I'm looking forward to @felangel's answer :)

I need to make a 4 second transition to open the Login page. That's why I use Navigator.pushReplacementNamed :

`return MyCustomRoute<void>(builder: (context) => settings.arguments as Widget, settings: settings, transitionMilliseconds: 4000);) `

How can I make this transition with a direct navigation (return LoginPage())?

Thanks.

**Comment by felangel** [comment] 2020-04-10 05:54
Hey @FredG13 and @theDarkBoffin  👋 
Sorry for the delay! I'll put together a sample app to demonstrate how I'd handle this situation tomorrow 👍

**Comment by FredG13** [comment] 2020-04-10 10:10
No problem, thanks a lot :)

**Comment by felangel** [comment] 2020-04-16 01:01
@FredG13 @theDarkBoffin check out https://gist.github.com/felangel/12e0dcf8acf37e1a4b75dae052c36656 and let me know if that helps and sorry for the delay!

**Comment by FredG13** [comment] 2020-04-17 00:19
Hi @felangel,
Thank you so much for your help.
Unfortunately, it's not working on my end.
If I do a "yield AuthenticationAuthOk();" from the LoginPage, the condition "if (state is AuthenticationAuthOk)" is not read in the main.dart page.

Here's the code to my main.asp page:

```
import 'package:flutter/material.dart';
import 'package:bloc/bloc.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import 'blocs/authentification/authentification.dart';
import 'repositories/utilisateur/utilisateur_repository.dart';
import 'themes.dart';
import 'ui/activite/activite_famille_page.dart';
import 'ui/login/login_page.dart';
import 'ui/login/splash.dart';
import 'widgets/loading.dart';
import 'widgets/slide_ecran_gauche.dart';

/// Transitions et erreurs dans l'application.
class SimpleBlocDelegate extends BlocDelegate {
  @override
  void onEvent(Bloc bloc, Object event) {
    super.onEvent(bloc, event);
    print(event);
  }

  @override
  void onTransition(Bloc bloc, Transition transition) {
    super.onTransition(bloc, transition);
    print("Transition : $transition");
  }

  @override
  void onError(Bloc bloc, Object error, StackTrace stacktrace) {
    super.onError(bloc, error, stacktrace);
    print("Erreur : $error\n${stacktrace.toString()}");
  }
}

void main() {
  BlocSupervisor.delegate = SimpleBlocDelegate();
  final utilisateurRepository = UtilisateurRepository();
  runApp(
    BlocProvider<AuthentificationBloc>(
      create: (context) {
        return AuthentificationBloc(utilisateurRepository: utilisateurRepository)..add(AppDemarree());
      },
      child: App(utilisateurRepository: utilisateurRepository),
    ),
  );
}

/// Application.
class App extends StatefulWidget {
  /// Dépôt Utilisateur.
  final UtilisateurRepository utilisateurRepository;

  /// Constructeur.
  App({Key key, @required this.utilisateurRepository}) : super(key: key);

  @override
  _AppState createState() => _AppState();
}

class _AppState extends State<App> {
  final _navigatorKey = GlobalKey<NavigatorState>();

  NavigatorState get _navigator => _navigatorKey.currentState;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: "SportAdic",
        navigatorKey: _navigatorKey,
        debugShowCheckedModeBanner: false,
        theme: themeParDefaut,
        home: _getPageDemarrage(),
        onGenerateRoute: (settings) {
          switch (settings.name) {
            case "/login":
              return MyCustomRoute<void>(builder: (context) => settings.arguments as Widget, settings: settings, transitionMilliseconds: 4000);
            case "/login_mot_passe_oublie":
              return SlideEcranGauche(widget: LoginPage(utilisateurRepository: widget.utilisateurRepository, formMode: FormMode.motDePasseOublie));
            case "/login_inscription":
              return SlideEcranGauche(widget: LoginPage(utilisateurRepository: widget.utilisateurRepository, formMode: FormMode.inscription));
            case "/login_change_mot_passe":
              return SlideEcranGauche(widget: settings.arguments as Widget);
            case "/home":
              return MyCustomRoute<void>(builder: (context) => ActiviteFamillePage(), settings: settings);
            case "/splash":
              return MyCustomRoute<void>(builder: (context) => SplashPage(), settings: settings);
            default:
              return null;
          }
        }
    );
  }

  /// Obtenir la page de démarrage de l'application.
  Widget _getPageDemarrage() {
    return BlocBuilder<AuthentificationBloc, AuthentificationState>(
      builder: (context, state) {
        if (state is AuthentificationInit) {
          return SplashPage();
        }
        if (state is AuthentificationLoading) {
          return Loading();
        }
        if (state is AuthentificationNonAuth) {
          SchedulerBinding.instance.addPostFrameCallback((_) {
            _navigator.pushNamedAndRemoveUntil("/login", (route) => false, arguments: LoginPage(utilisateurRepository: widget.utilisateurRepository));
            return;
          });
        }
        if (state is AuthentificationAuthOk) {
          widget.utilisateurRepository.creeLogConnexion(); // On logue la connexion
          return ActiviteFamillePage();
        }
        return SplashPage();
      },
    );
  }
}

/// Gestion des transitions entre les pages.
class MyCustomRoute<T> extends MaterialPageRoute<T> {
  /// Temps de transition en milli-seconde.
  final int transitionMilliseconds;

  /// Constructeur.
  MyCustomRoute({WidgetBuilder builder, RouteSettings settings, this.transitionMilliseconds = 500}) : super(builder: builder, settings: settings);

  @override
  Duration get transitionDuration => Duration(milliseconds: transitionMilliseconds);

//  @override
//  Widget buildTransitions(BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, Widget child) {
//    return FadeTransition(opacity: animation, child: child);
//  }

}

```

**Comment by felangel** [comment] 2020-04-17 15:19
@FredG13 can you please share a link to a sample app which reproduces the issue? I'm happy to take a look 👍

**Comment by FredG13** [comment] 2020-04-18 14:24
Hi @felangel,

I created a sample app : [https://github.com/FredG13/app_for_felix_angelov](https://github.com/FredG13/app_for_felix_angelov)
Thank you for your help.

**Comment by felangel** [comment] 2020-04-22 05:25
Hi @FredG13 sorry for the delay! I've created a [gist](https://gist.github.com/felangel/2b3af9c92491b962de3cf0bdcfac131d) in which I modified your sample app to function properly.

Hope that helps!

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-04-22 05:25 UTC
Labels: question, waiting for response

**Comment by FredG13** [comment] 2020-04-22 12:39
Hi @felangel ,

Thanks again for your help.
The button pushes are working now.
However, the transition to the first page when opening the application does not work.
Don't bother, I'll do without.

Thank you very much for your time.

My best regards,

Fred
