### ISSUE TITLE
HomePage does not display when I click the login Button

### ISSUE THREAD

**Issue by estem** [felangel/bloc#1848] opened 2020-10-21 16:19 UTC
Hello,

first of all, thank for these amazing articles, I have just one issue for the flutter_login exemple, when I enter a correct username and password, and then clicked on the login button thye home page does not displayed.

Thank you

**Comment by venkateshironman** [comment] 2020-10-21 17:35
Have you navigate the screen after successful login ?

**Comment by felangel** [comment] 2020-10-22 00:39
Hi @estem 👋 
Thanks for opening an issue!

Can you please provide a link to a sample app which illustrates the issue? There isn't enough information at the moment to help. Thanks!

**Comment by estem** [comment] 2020-10-22 08:06
Hello @felangel 

the issue was in the login_form :
`class _LoginButton extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocBuilder<LoginBloc, LoginState>(
      buildWhen: (previous, current) => previous.status != current.status,
      builder: (context, state) {
        return state.status.isSubmissionInProgress
            ? const CircularProgressIndicator()
            : RaisedButton(
                key: const Key('loginForm_continue_raisedButton'),
                child: const Text('Login'),
                onPressed: state.status.isValidated
                    ? () {
                        context.bloc<LoginBloc>().add(const LoginSubmitted());
                      }
                    : null,
              );
      },
    );
  }`

when I click the login button, the state.status.isValidated then the home_page doesn't displayed.

**Comment by venkateshironman** [comment] 2020-10-22 13:48
Please provide the bloc class also.
Think so you didn't added a navigate code after successful login

**Comment by estem** [comment] 2020-10-23 07:56
Yes, I agree with you thats why I opened this issue, the author must update the flutter_login repository to add the code to navigate to the home_page after successful login.

Thanks

**Comment by felangel** [comment] 2020-10-23 14:07
@estem I'm not sure I understand the issue. Can you please share a link to a complete sample app which illustrates the issue? Are you referring to [examples/flutter_login](https://github.com/felangel/bloc/tree/master/examples/flutter_login)? If so, the navigation is happening at https://github.com/felangel/bloc/blob/a801b2128de5ea4727c39e8ba83cfd1b2eb86430/examples/flutter_login/lib/app.dart#L56 in response to changes in the `AuthenticationState`.

**Comment by estem** [comment] 2020-10-23 15:39
@felangel  yes, I was talking about flutter_login, I followed you article :https://bloclibrary.dev/#/flutterlogintutorial, and when  I click the login button the Home_page doesn't displayed. I think therr's something wrong.

Thank you

**Comment by felangel** [comment] 2020-10-23 16:09
@estem can you push the complete code up to github and share a link?

**Comment by felangel** [comment] 2020-10-25 22:56
Closing for now since there isn't enough information to reproduce the issue so I can't help. Feel free to provide a link to a sample app which reproduces the issue and I'm happy to take a look 👍

**Closed by felangel** 2020-10-25 22:56 UTC
Labels: question, waiting for response
