### ISSUE TITLE
emit state from listening to stream in a bloc doesn't work

### ISSUE THREAD

**Issue by YaserH25** [felangel/bloc#3786] opened 2023-04-01 22:26 UTC
Im using **_StreamController_** to track the progress of uploading an image using **_Dio_**, so when i sink a value in my stream i trigger an event to emit new state to rebuild my widget, the problem is it does not emit new state.

This is the code from my _**ChatBloc**_

```
class Chat extends Bloc<ChatEvent, ChatState> {
  final StreamController<FileDetails> uploadStream =
      StreamController<FileDetails>();

  Chat(this.chatUseCases, this.chat)
      : super(const SingleChatState()) {
    on<ChatEmitUploadList>(_emitUploadList);

    /// listen to changes form upload stream
    uploadStream.stream.listen((event) {
      List<FileDetails> details = state.fileDetailsList;
      details
          .firstWhereOrNull((element) => element.id == event.id)!
          .percentage = event.percentage;
      add(SingleChatEvent.emitUploadList(fileDetails: event));
    });
  }
}

  FutureOr<void> _emitUploadList(
      ChatEmitUploadList event, Emitter<SingleChatState> emit) {
    print('emit once');
    List<FileDetails> details = List.from(state.fileDetailsList);
    details
        .firstWhereOrNull((element) => element.id == event.fileDetails.id)!
        .percentage = event.fileDetails.percentage;
    emit(state.copyWith(fileDetailsList: details));
  }
```

This is my BlocBuilder

```
class UploadingWidget extends StatelessWidget {
  const UploadingWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<ChatBloc, ChatState>(
      builder: (context, state) {
        if (state.status == SingleChatStatus.uploadingFiles) {
          return Container(
            decoration: BoxDecoration(
                color: Colors.white, borderRadius: BorderRadius.circular(20.r)),
            margin: const EdgeInsets.all(8),
            padding: const EdgeInsets.all(8),
            child: CustomScrollView(
              shrinkWrap: true,
              slivers: [
                SliverGrid.builder(
                  gridDelegate: const SliverGridDelegateWithMaxCrossAxisExtent(
                      maxCrossAxisExtent: 100),
                  itemBuilder: (context, index) => Material(
                    child: SizedBox(
                      height: 100,
                      width: 100,
                      child: Center(
                        child: Text(
                            state.fileDetailsList[index].percentage.toString()),
                      ),
                    ),
                  ),
                  itemCount: state.fileDetailsList.length,
                )
              ],
            ),
          );
        }
        return const SizedBox.shrink();
      },
    );
  }
}
```

This is my method in dio 

```
final response = await dio.post(BASE_TEST+sendMessageEndPoint,data: data,
onSendProgress: (count, total) {
  if(file!=null){
    String fileName = file.path.toString().split('/').last;
    double percentage = (count / total * 100).toDouble();
    uploadStream.sink.add(FileDetails(id: file.path!, percentage: percentage,file: file));
  }
},);
```

this is my debug console
```
[log] onEvent -- ChatBloc, ChatEvent.emitUploadList(fileDetails: Instance of 'FileDetails')
[log] onEvent -- ChatBloc, ChatEvent.emitUploadList(fileDetails: Instance of 'FileDetails')
[log] onEvent -- ChatBloc, ChatEvent.emitUploadList(fileDetails: Instance of 'FileDetails')
[log] onEvent -- ChatBloc, ChatEvent.emitUploadList(fileDetails: Instance of 'FileDetails')
[log] onEvent -- ChatBloc, ChatEvent.emitUploadList(fileDetails: Instance of 'FileDetails')

```

i also tried emit.forEach but still no use
```
  FutureOr<void> _subscribeToUploadStream(ChatSubscribeToUploadStreamEvent event, Emitter<SingleChatState> emit) {
    emit.forEach(uploadStream.stream, onData: (data) {
      print(data.percentage);
      List<FileDetails> details = List.from(state.fileDetailsList);
      details
          .firstWhereOrNull((element) => element.id == data.id)!
          .percentage = data.percentage;
      return state.copyWith(fileDetailsList: details,status: SingleChatStatus.uploadingFiles,);
    },);
  }
```

**Comment by tenhobi** [comment] 2023-04-03 05:06
As the example is incomplete, not sure, but does the listener in the Chat bloc `uploadStream.stream.listen((event) {` actually listen to any changes? Do a log there.

**Comment by YaserH25** [comment] 2023-04-03 08:35
> As the example is incomplete, not sure, but does the listener in the Chat bloc `uploadStream.stream.listen((event) {` actually listen to any changes? Do a log there. And ideally, post a repo with a minimal reproducible example here, please.

actually it does an unexpected behavior, it already adds the event, but doesn't print any log

**Comment by VikasJilla** [comment] 2023-04-05 13:04
can you try emitting new state every time, instead of copyWith? Probably bloc is seeing no difference in the new states being emitted.

**Comment by YaserH25** [comment] 2023-04-05 23:17
> can you try emitting new state every time, instead of copyWith? Probably bloc is seeing no difference in the new states being emitted.

does bloc prevent emitting the same state? or it emits it and prevent rebuild? 
can't when i used Stream builder to trigger rebuilding the widget when ever i add new value to the stream, i found out the the state already updated

**Comment by VikasJilla** [comment] 2023-04-06 03:44
> > can you try emitting new state every time, instead of copyWith? Probably bloc is seeing no difference in the new states being emitted.
> 
> does bloc prevent emitting the same state? or it emits it and prevent rebuild? can't when i used Stream builder to trigger rebuilding the widget when ever i add new value to the stream, i found out the the state already updated

I think it emits the state and prevents rebuild, if it finds the current state and new state are same.
Just to test this, Can you emit some random state, just before emitting `emit(state.copyWith(fileDetailsList: details));` and check if the UI is updating

**Comment by tenhobi** [comment] 2023-04-06 08:55
@YaserH25 Bloc doesn't emit the same state. Note that two instances with the same parameters are not the same. Only if you use Equatable or manually override `==` and `hashCode` it is considered as same, because comparison and hashCode match.

**Comment by felangel** [comment] 2023-04-15 19:08
Closing for now since there are no actionable next steps. If this is still an issue please provide a minimal reproduction sample and we're happy to take a closer look, thanks! 👍

**Closed by felangel** 2023-04-15 19:08 UTC
Labels: question
