### ISSUE TITLE
Add event from other event - problems to dispose when destroying bloc

### ISSUE THREAD

**Issue by giaur500** [felangel/bloc#4251] opened 2024-09-18 06:35 UTC
There's 2 events defined. Each event contains some network calls + emits status changes (loading/data loaded). When first event contains `add` method to execute other event, it works fine unless the bloc is about to be destroyed while event calls not finished yet. If there's any call in progress, bloc dispose causes endless loop somewhere (but no exception) and app hangs - stop responding.

Example code:
```

FutureOr<void> _onGetEventDetails(GetEventDetailsEvent event, Emitter<DetailsState> emit) async {

emit(state.copyWith(isLoading: true);
final data = await mcityRepository.loadSomeData();
emit(state.copyWith(isLoading: false, newData: data);

add(GetAdditionalInfoEvent());

}
```

`GetAdditionalInfoEvent()` has similar network calls end emits. The bloc is created when page is created it needs to be disposed when page is destroyed. But from some reason, it hangs my app when network calls are not finished yet (loading status) and user close the page - bloc should be destroyed, but instead app hangs.

Everything is fine if there's no any `add` method call to execute other event inside first event. 

Please clarify - is it not recommended to exeucte other event from event? What actually happens here? More detailed description on SO: https://stackoverflow.com/questions/78993079/flutterbloc-post-event-from-other-event-app-hangs-on-bloc-dispose-endless-l

In this case I can't be sure there will never be any oparation in progress. Window with loading status (network call in progress) may be closed - popped form the stack without waiting for result. I don't want corresponding bloc to be global, it should be disposed when loading window is closed.

**Comment by felangel** [comment] 2024-10-04 04:53
Hi @giaur500 👋 
Thanks for opening an issue!

Can you please share a link to a minimal reproduction sample that illustrates the issue you're facing along with detailed steps to reproduce the issue? I'm happy to take a closer look and provide suggestions, thanks! 🙏

**Comment by felangel** [comment] 2024-11-19 05:30
Closing for now since there is no reproduction sample. If this is still an issue feel free to provide a link to a repro and I'm happy to take a closer look, thanks!

**Closed by felangel** 2024-11-19 05:30 UTC
Labels: question, waiting for response, needs repro info
