### ISSUE TITLE
Dont work fromJson

### ISSUE THREAD

**Issue by Mirshodbek** [felangel/bloc#2546] opened 2021-06-19 04:44 UTC
Hello. I am using hydrated_bloc package in my project. But I can not receive saved state bloc. 
Here is my code.  If there are some mistakes aware me. Thank. 
![Screenshot from 2021-06-18 23-46-55](https://user-images.githubusercontent.com/36184953/122631133-d2a2c100-d0e2-11eb-9733-fe5bc820fea8.png)
![Screenshot from 2021-06-18 23-46-34](https://user-images.githubusercontent.com/36184953/122631136-d5051b00-d0e2-11eb-904d-754c6a2d02eb.png)

**Comment by felangel** [comment] 2021-06-19 04:47
Hi @Mirshodbek 👋
Thanks for opening an issue!

Can you please provide a link to a minimal reproduction sample so I can reproduce the issue locally? I don’t have enough information to help based on the screenshots. Thanks!

**Comment by Mirshodbek** [comment] 2021-06-19 04:50
```import 'dart:async';

import 'package:formz/formz.dart';
import 'package:hydrated_bloc/hydrated_bloc.dart';
import 'package:meta/meta.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:sap_work/bloc/internet/internet_cubit.dart';
import 'package:sap_work/data_provider/prof_provider.dart';
import 'package:sap_work/models/feedback/feedback.dart';
import 'package:sap_work/models/profile/profile.dart';
import 'package:sap_work/models/resume/resume.dart';
import 'package:sap_work/repository/hunter_repository.dart';
import 'package:sap_work/screens/authorization/authorization.dart';

part 'profile_bloc.freezed.dart';

class ProfileBloc extends HydratedBloc<ProfileEvent, ProfileState> {
  final HunterRepositoryBase _repository;
  final InternetCubit internetCubit;
  late final StreamSubscription internetStreamSubscription;

  final ProfProvider _provider = ProfProvider();
  var _profile;
  var _resume;
  List<FeedbackResume> _feedbacks = [];
  List<Resume> _resumes = [];
  bool _isAdd = false;
  int _id = 0;

  ProfileBloc(this._repository, this.internetCubit)
      : super(ProfileState.profileState(
          profile: ProfileHunter("Имя", "", "", "", "", 0),
          feedbacksCount: 2,
          resume: Resume(0, 0, "Введите название резюме", "", "", 0, "", ""),
          id: 0,
        )) {
    monitorInternetCubit();
  }

  StreamSubscription<InternetState> monitorInternetCubit() {
    return internetStreamSubscription =
        internetCubit.stream.listen((internetState) {
      if (internetState is ConnectedInternetState &&
          internetState.connectionType == ConnectionType.Wifi) {
        add(ProfileEvent.refresh());
      } else if (internetState is ConnectedInternetState &&
          internetState.connectionType == ConnectionType.Mobile) {
        add(ProfileEvent.refresh());
      }
    });
  }

  @override
  Stream<ProfileState> mapEventToState(
    ProfileEvent event,
  ) async* {
    yield* event.map(
      initial: _initialEvent,
      refresh: _refreshEvent,
      selectResumes: _selectResumesEvent,
      toggleResume: _toggleResumeEvent,
      addResumeButton: _addResumeButtonEvent,
      addResumeName: _addResumeNameEvent,
    );
  }

  Stream<ProfileState> _initialEvent(_IntialProfileEvent event) async* {}

  Stream<ProfileState> _refreshEvent(_RefreshProfileEvent event) async* {
    try {
      _profile = await _repository.getProfileHunter();
      _feedbacks = await _repository.getFeedbacks();
      _resume = await _provider.resumeHunter(_id);
      yield ProfileState.profileState(
        profile: _profile,
        feedbacksCount: _feedbacks.length,
        resume: _resume,
        id: _id,
      );
    } catch (_) {}
  }

  Stream<ProfileState> _selectResumesEvent(
      _SelectResumesProfileEvent event) async* {
    try {
      _profile = await _repository.getProfileHunter();
      _feedbacks = await _repository.getFeedbacks();
      yield* _repository.getResumes().map((_event) {
        return ProfileState.selectResumesState(
          profile: _profile,
          feedbacksCount: _feedbacks.length,
          resumes: _event,
          isAdd: _isAdd,
          status: FormzStatus.pure,
          id: 0,
        );
      });
    } catch (_) {}
  }

  Stream<ProfileState> _toggleResumeEvent(
      _ToggleResumeProfileEvent event) async* {
    _id = event.id;
    yield state.maybeMap(
      orElse: () => state,
      selectResumesState: (_state) => _state.copyWith(id: event.id),
    );
    _feedbacks = await _repository.getFeedbacks(id: event.id);
    _resume = await _provider.resumeHunter(_id);
    yield ProfileState.profileState(
      profile: _profile,
      feedbacksCount: _feedbacks.length,
      resume: _resume,
      id: event.id,
    );
  }

  Stream<ProfileState> _addResumeNameEvent(
      _AddResumeNameProfileEvent event) async* {
    final isValidated = Formz.validate([Texts.dirty(event.name)]);
    if (isValidated.isValidated) {
      try {
        yield state.maybeMap(
          orElse: () => state,
          selectResumesState: (_state) =>
              _state.copyWith(status: FormzStatus.submissionInProgress),
        );
        await _provider.createResume(event.name);
        yield* _repository.getResumes().map((_event) {
          return state.maybeMap(
            orElse: () => state,
            selectResumesState: (_state) => _state.copyWith(
              resumes: _event,
              isAdd: false,
            ),
          );
        });
      } catch (_) {}
    } else {
      yield state.maybeMap(
        orElse: () => state,
        selectResumesState: (_state) => _state.copyWith(status: isValidated),
      );
    }
  }

  Stream<ProfileState> _addResumeButtonEvent(
      _AddResumeButtonProfileEvent event) async* {
    _isAdd = !event.isAdd;
    yield state.maybeMap(
      orElse: () => state,
      selectResumesState: (_state) => _state.copyWith(isAdd: _isAdd),
    );
  }

  @override
  ProfileState? fromJson(Map<String, dynamic> json){
    return ProfileState.profileState(
      profile: ProfileHunter.fromJson(
          json['profile_hunter'] as Map<String, dynamic>),
      feedbacksCount: json['resume_feedbacks'] as int,
      resume: Resume.fromJson(json['resume'] as Map<String, dynamic>),
      id: json['id'] as int,
    );
  }

  @override
  Map<String, dynamic>? toJson(ProfileState state) {
    if (state is ProfileScreenState) {
      return {
        'profile_hunter': state.profile.toJson(),
        'resume': state.resume.toJson(),
        'resume_feedbacks': state.feedbacksCount,
        'id': state.id,
      };
    }
  }

  @override
  Future<void> close() {
    internetStreamSubscription.cancel();
    return super.close();
  }

 
}

@freezed
abstract class ProfileEvent with _$ProfileEvent {
  const factory ProfileEvent.initial() = _IntialProfileEvent;

  const factory ProfileEvent.refresh() = _RefreshProfileEvent;

  const factory ProfileEvent.selectResumes() = _SelectResumesProfileEvent;

  const factory ProfileEvent.toggleResume({
    required final int id,
  }) = _ToggleResumeProfileEvent;

  const factory ProfileEvent.addResumeButton({required final bool isAdd}) =
      _AddResumeButtonProfileEvent;

  const factory ProfileEvent.addResumeName({required final String name}) =
      _AddResumeNameProfileEvent;
}

@freezed
abstract class ProfileState with _$ProfileState {
  const factory ProfileState.initial() = InitialProfileState;

  const factory ProfileState.profileState({
    required final ProfileHunter profile,
    required final int feedbacksCount,
    required final Resume resume,
    required final int id,
  }) = ProfileScreenState;

  const factory ProfileState.selectResumesState({
    required final ProfileHunter profile,
    required final int feedbacksCount,
    required final List<Resume> resumes,
    required final bool isAdd,
    required final FormzStatus status,
    required final int id,
  }) = SelectResumesProfileState;
}
```

**Comment by felangel** [comment] 2021-06-19 04:54
Can you share a link to a minimal reproduction sample? It would be much easier to help if I can run/debug the code locally.

**Comment by Mirshodbek** [comment] 2021-06-19 05:02
https://github.com/Mirshodbek/sapwork 
Here you can see my project.

**Comment by Mirshodbek** [comment] 2021-06-19 05:12
You need first registration and after that you can enter code 1234.

**Comment by Mirshodbek** [comment] 2021-06-19 09:31
What is problem? Are there some mistakes?

**Comment by jonathankao97** [comment] 2021-07-15 17:33
Hey @Mirshodbek, the link to the GitHub repo is broken and the snippet isn't enough to reproduce the issue. Could you send an updated link? Thanks

**Comment by felangel** [comment] 2021-07-20 13:55
Closing for now since there isn’t a working reproduction sample. Feel free to provide one and I’m happy to reopen this and continue the conversation 👍

**Closed by felangel** 2021-07-20 13:55 UTC
Labels: investigating, question
