### ISSUE TITLE
The first state of a dependency Bloc doesn't listen 6.x

### ISSUE THREAD

**Issue by jcsena** [felangel/bloc#1573] opened 2020-08-04 18:29 UTC
**Describe the bug**
In version 6.x when I have the dependency of a "bloc" it doesn't listen the first state.

For example

``` dart
 NotificationBloc({
    @required UserRepository userRepository,
    @required AuthenticationBloc authenticationBloc,
  }) : super(NotificationsUninitialized()) {
    assert(userRepository != null);
    assert(authenticationBloc != null);
    _userRepository = userRepository;
    _authBloc = authenticationBloc;

    _authSubscription = _authBloc.listen((authState) {
      if (authState is Authenticated) {
        add(FetchNotifications());
      }
    });
  }
```
## Workaround 

```dart 
 NotificationBloc({
    @required UserRepository userRepository,
    @required AuthenticationBloc authenticationBloc,
  }) : super(NotificationsUninitialized()) {
    assert(userRepository != null);
    assert(authenticationBloc != null);
    _userRepository = userRepository;
    _authBloc = authenticationBloc;
    
    if(_authBloc.state is Authenticated){
       add(FetchNotifications());
    }
    _authSubscription = _authBloc.listen((authState) {
      if (authState is Authenticated) {
        add(FetchNotifications());
      }
    });
  }

```

**Comment by felangel** [comment] 2020-08-04 18:45
Hi @jcsena 👋 
Thanks for opening an issue!

This is a duplicate of #1542 #1541 #1518

**Closed by felangel** 2020-08-04 18:45 UTC
Labels: duplicate
