### ISSUE TITLE
issue: type 'Null' is not a subtype of type '<BLOC_NAME>' in type cast, relate to repository injection

### ISSUE THREAD

**Issue by phamducmanh1452001** [felangel/bloc#3508] opened 2022-08-16 08:02 UTC
Hi everyone at the great state management !
I did refactor my code from
#photo1 to #photo2, and I receive  Error: "type 'Null' is not a subtype of type 'LoginBloc' in type cast".

The named "create" function in BlocProvider did not call. For my part, I see they are similar but flutter_bloc said no.
How do they work or effect to Flutter tree then create this difference ?

Thank you so much and happy coding !

#photo1
![image](https://user-images.githubusercontent.com/72958990/184828739-f90f0367-fa07-4100-a48f-3a7ec59a334e.png)

#photo2
![image](https://user-images.githubusercontent.com/72958990/184828914-32880492-c8fb-416c-a404-40660388bd9e.png)

**Comment by renancaraujo** [comment] 2022-08-16 11:26
These two codes will not behave equally. The closure passed "create" is, by default, executed lazily, which makes, in the first code snippet, the repository instances to be instantiated only when referenced for the first time. But in the refactored code, these same instancies are created eagerly. 


But the interesting part is that "LoginBloc" (as described in the error message) is not part of the refactored code.

**Comment by phamducmanh1452001** [comment] 2022-08-17 02:14
> These two codes will not behave equally. The closure passed "create" is, by default, executed lazily, which makes, in the first code snippet, the repository instances to be instantiated only when referenced for the first time. But in the refactored code, these same instancies are created eagerly.
> 
> But the interesting part is that "LoginBloc" (as described in the error message) is not part of the refactored code.

I don't think the refactored code make them are created eagerly, buddy.
But maybe, I guess constructor of RepositoryProvider did change a global thing

**Comment by 3kdeveloper** [comment] 2022-11-22 15:30
Hi @phamducmanh1452001 

I face the same problem today.
So I solve them by wrapping Multi Bloc Provider in Multi Repository Provider.

**Comment by Allan-Nava** [comment] 2022-11-24 10:05
The flutter_login demo has this problem :
`
type 'Null' is not a subtype of type 'LoginBloc' in type cast
`

**Comment by felangel** [comment] 2022-12-27 01:44
@phamducmanh1452001 can you please provide a link to a minimal reproduction sample? This isn't enough information to help unfortunately.

**Comment by emperorKez** [comment] 2022-12-30 00:54
I am getting the same error with flutter_login demo

**Comment by felangel** [comment] 2023-01-02 22:38
> I am getting the same error with flutter_login demo

I'm not able to reproduce. Can you please provide clear reproduction steps along with the full error and stacktrace? Thanks!

**Comment by felangel** [comment] 2023-01-12 14:16
Closing for now since I can’t reproduce and there is no reproduction sample. Feel free to provide one and I’m happy to take another look 👍

**Closed by felangel** 2023-01-12 14:16 UTC
Labels: question, waiting for response

**Comment by dk-a-dev** [comment] 2024-05-31 14:39
@felangel Hi bud, I am facing the same error
i am sharing the traceback

![image](https://github.com/felangel/bloc/assets/84137299/0c03452b-6e26-43a9-8942-a195906f995d)

this is the logi_page.dart file snippet
I have imported login_form.dart since the LoginForm widget needed it
![image](https://github.com/felangel/bloc/assets/84137299/b8ad1ec4-6546-4211-9098-e19882ea2846)

**Comment by dk-a-dev** [comment] 2024-05-31 14:41
```dart
import 'dart:async';

import 'package:authentication_repository/authentication_repository.dart';
import 'package:bloc/bloc.dart';
import 'package:equatable/equatable.dart';
import 'package:flutter_login/login/models/models.dart';
import 'package:formz/formz.dart';

part 'login_event.dart';
part 'login_state.dart';

class LoginBloc extends Bloc<LoginEvent, LoginState> {
  LoginBloc({
    required AuthenticationRepository authenticationRepository,
  })  : _authenticationRepository = authenticationRepository,
        super(const LoginState()) {
    on<LoginUsernameChanged>(_onUsernameChanged);
    on<LoginPasswordChanged>(_onPasswordChanged);
    on<LoginSubmitted>(_onSubmitted);
  }

  final AuthenticationRepository _authenticationRepository;

  void _onUsernameChanged(
    LoginUsernameChanged event,
    Emitter<LoginState> emit,
  ) {
    final username = Username.dirty(event.username);
    emit(
      state.copyWith(
        username: username,
        isValid: Formz.validate([state.password, username]),
      ),
    );
  }

  void _onPasswordChanged(
    LoginPasswordChanged event,
    Emitter<LoginState> emit,
  ) {
    final password = Password.dirty(event.password);
    emit(
      state.copyWith(
        password: password,
        isValid: Formz.validate([password, state.username]),
      ),
    );
  }

  Future<void> _onSubmitted(
    LoginSubmitted event,
    Emitter<LoginState> emit,
  ) async {
    if (!state.isValid) {
      return;
    }
    emit(state.copyWith(status: FormzSubmissionStatus.inProgress));
    try {
      await _authenticationRepository.logIn(
        username: state.username.value,
        password: state.password.value,
      );
      emit(state.copyWith(status: FormzSubmissionStatus.success));
    } catch (_) {
      emit(state.copyWith(status: FormzSubmissionStatus.failure));
    }
  }
}
```

this is login_bloc.dart
