### ISSUE TITLE
feat: BlocSelector with "selectWhen"

### ISSUE THREAD

**Issue by dedonnodev** [felangel/bloc#3418] opened 2022-07-03 10:17 UTC
**Description**

There is no option to select which Bloc's event should trigger the "selector" of BlocSelector

**Desired Solution**

it would be awesome to have a "selectWhen" in BlocSelector, to avoid useless rebuild with empty values

**Additional Context**

Now i use check in "selector" if the event is the event i'm interested of, and if it isn't, i return a null/empty value that trigger a rebuild of child (that i wouldn't need)

**Comment by felangel** [comment] 2022-07-03 15:07
Hi @dedonnodev 👋
Thanks for opening an issue!

The UI should only depend on the state. The presentation layers adds events to the bloc and can listen for state changes. If you are rebuilding the UI depending on the event added then that’s no longer the bloc pattern.

 I recommend refactoring so that all the information needed is provided via the bloc state. Can you provide a concrete use-case for why your presentation layer rebuilds depending on the event? Thanks!

**Comment by felangel** [comment] 2022-10-16 14:26
> Hi @felangel I'm using Bloc for a "settings page", where every section rebuild when its setting value change. I'm using a BlocSelector. Example: `BlocSelector<SettingsBloc, SettingsState, String>( selector: (state) => state.maybeMap( ready: (value) => value.printerIp, orElse: () => '', ), builder:{...} )`
> 
> i use a SettingBloc for the whole "settings page" and then use blocSelector for "filter" settings for each section. But i don't think it's the right way... isn't it? 🥲

Can you provide a link to a minimal reproduction sample that illustrates the issue? It would be much easier to help if I can reproduce locally, thanks! 🙏

**Comment by felangel** [comment] 2022-12-27 01:50
Closing for now since there is no reproduction sample.

**Closed by felangel** 2022-12-27 01:50 UTC
Labels: question, waiting for response

**Comment by bekaIva** [comment] 2023-09-30 14:01
Can we reopen this please?

This is my issue with BlocSelector.

The Bloc:
`class LiveStreamBloc extends Bloc<LiveStreamEvent, LiveStreamState> {
  final GetLiveStream _getLiveStream;
  LiveStreamBloc(this._getLiveStream) : super(const LiveStreamState.initial()) {
    on<LiveStreamEvent>((event, emit) async {
      await switch (event) {
        StartFetchingLiveStream() => emit.forEach(
            _mapStartFetchingLiveStreamToState(emit),
            onData: (data) => data,
            onError: (error, stackTrace) {
              return LiveStreamState.error(error.toString());
            },
          ),
      };
    }, transformer: restartable());
  }

  Stream<LiveStreamState> _mapStartFetchingLiveStreamToState(Emitter<LiveStreamState> emit) async* {
    while (!isClosed || !emit.isDone) {
      yield const LiveStreamState.loading();
      final liveStream = await _getLiveStream(null);
      yield liveStream.fold(
        (l) => LiveStreamState.error(l.toString()),
        (r) => LiveStreamState.loaded(r),
      );
      await Future.delayed(const Duration(seconds: 30));
    }
  }
}`

The state:
`@freezed
sealed class LiveStreamState with _$LiveStreamState {
  const factory LiveStreamState.initial() = Initial;
  const factory LiveStreamState.loading() = Loading;
  const factory LiveStreamState.loaded(LiveModel liveModel) = Loaded;
  const factory LiveStreamState.error(String message) = Error;
}`

BlocSelector:
`class LiveIcon extends StatelessWidget {
  const LiveIcon({super.key});

  @override
  Widget build(BuildContext context) {
    //make outlined button rectangular with rounded corners
    return BlocSelector<LiveStreamBloc, LiveStreamState, LiveModel?>(
      selector: (state) => switch (state) {
        Loaded(:var liveModel) when (liveModel.liveUrl?.length ?? 0) > 0 => liveModel,
        _ => null
      },
      builder: (context, liveModel) {
        bool isLive = liveModel != null;
        return Text('Is live: $isLive');
      },
    );
  }
}`

The issue here is that when Loading state is emitted I get isLive false, I know if I keep LiveModel in loading state as well and assign it from current loaded state if it is and do same check for loading state in selector solve the issue but it is too many checks, I want Loading state to be skipped and don't trigger builder method.

**Comment by AngeloAvv** [comment] 2024-03-07 07:53
Hey @felangel , I came here with the purpose of creating a similar issue until I noticed there's already an existing one that has been discussed and closed. From my point of view, there are some more explanatory examples that might justify the need of a buildWhen/selectWhen (name it as you want :) ). I'll give you more context because as soon as I discovered BlocSelector (I've been using BlocBuilder most of the times from the beginning)

I know that code speaks thousands words, but I'll try giving a more high-level scenario I faced just yesterday.

Imagine you have a BLoC that primarily handles a specific resource like a VideoClip, in this BLoC you can add multiple events where you can ask for video details, comments, and perform operations like deleting it, and so on.

Now you have a single BLoC with multiple events that works in a single page where multiple widgets interact with. In my specific scenario, I was getting video details to reproduce the video in the upper part of the page, but at the same time I was asking for video comments in the lower bound. Since I needed to manipulate the comments by transforming a comment X into a small subset of comments Y, a BlocSelector was perfect for this scenario.

I know, this might be business logic related, but all I was doing was transforming a list of comments into a list of a scalar type with a condition. Instead of doing it when referencing the widget to be shown, I was doing it in the selector. I put a BlocSelector there that was transforming the data from X to Y, while returning an empty array for all the other states.

What happened next? I asked for the video details to reproduce the video, and since I was emitting different states for this particular scenario, I was able to show the video player on the top side of the page because I was reacting to these states with a buildWhen filter, but all of a sudden the comments section disappeared because the state of the bloc switched from FetchedCommentsVideoState to FetchedDetailsVideoState.

I was forced to switch back to a BlocBuilder decorated with a buildWhen condition for the comments section because I didn't had the chance to skip particular states I didn't want to listen to. In this case my code became more verbose as I had to remap the data available in the FetchedDetailsVideoState just before creating the CommentsListWidget.

I don't know if this scenario might help you better understand the purpose of selectWhen/buildWhen, but I think it might be easily be reproduced in a snipped example.
