### ISSUE TITLE
Write code in Bloc File makes my Computer Lag

### ISSUE THREAD

**Issue by febryardiansyah** [felangel/bloc#1575] opened 2020-08-05 07:17 UTC
Hi !!, i have a problem with bloc plugin. i've just updated my android studio and bloc plugin. When i create bloc using bloc plugin and write code inside of bloc file, that's really make my computer lag. But, when i code in others file (not bloc) its normal. 

Im currently using mac os Mojave with 8gb ram

sometimes this card show up when i code in bloc file
![image](https://user-images.githubusercontent.com/33514300/89382869-b34ab180-d725-11ea-92e0-cef21d1bd4d7.png)
thanks

**Comment by felangel** [comment] 2020-08-05 13:27
Hi @febryardiansyah 👋
Thanks for opening an issue!

The android studio plugin doesn’t do anything while you are typing so I’m not sure why this would happen. Are you sure it’s bloc-specific because the bloc extension only helps with creating new blocs and doesn’t do any processing while you are working on an existing bloc file? Is there anything else you can provide which clearly indicates the issue is related to the bloc library? Thanks 👍

**Comment by febryardiansyah** [comment] 2020-08-06 05:23
Thanks for the response
Yes, im really sure this lag only comes while i typing in bloc file. But, i don't know either this caused by bloc extension.
Since im using old bloc extension and bloc 5.0, this issue never come.

**Comment by felangel** [comment] 2020-08-06 06:08
@febryardiansyah can you please provide a link to a sample app which illustrates the issue as well as reproduction steps/a video?

**Comment by febryardiansyah** [comment] 2020-08-06 08:36
@felangel i've just uploaded sample video the difference between when i typing code in bloc file and not
https://www.youtube.com/watch?v=MNUpJKEM5yY

Maybe, i'll try to reinstall bloc extension later.

**Comment by felangel** [comment] 2020-08-10 13:04
@febryardiansyah any updates on this?

**Comment by felangel** [comment] 2020-08-11 13:26
Closing for now since there isn’t enough information to reproduce the issue.

**Closed by felangel** 2020-08-11 13:26 UTC
Labels: question

**Comment by febryardiansyah** [comment] 2020-08-15 00:35
@felangel hi, I'm sorry to reply so late. i just uninstalled bloc extension and it looks normal i think. but, there's still old bloc extension on my android stuido or it is just android studio's feature ?
![image](https://user-images.githubusercontent.com/33514300/90301359-95b9dc80-dec9-11ea-92f6-24a2072e1c33.png)

![image](https://user-images.githubusercontent.com/33514300/90301397-cac62f00-dec9-11ea-800f-cd5542a06895.png)
