### ISSUE TITLE
Many BlocListener Registered with Navigation.pushName()

### ISSUE THREAD

**Issue by loreberti89** [felangel/bloc#783] opened 2020-01-16 15:45 UTC
**Flutter_bloc: ^2.0.0**

I have a problem with register of BlocListener.

I have 3 Widget, let's say **Widget1**, **Widget2** and **Widget3**.
In **Widget1** that is a initialRoute  I have registered my BlocListener for SnackBar:

```
class Widget1 extends StatelessWidget{
   Widget build(BuildContext context) {
      return  BlocListener<SnackbarBloc, SnackbarState>(
        listener: (context, state) {
          if (state is SnackbarSuccess) {
            Scaffold.of(context).showSnackBar(SnackBar(
              content: Text('${state.message}'),
              backgroundColor: Colors.green,
            ));
          }
          if (state is SnackbarError) {
            Scaffold.of(context)..showSnackBar(SnackBar(
              content: Text('${state.message}'),
              backgroundColor: Colors.red,
            ));
          }
        },
       child: Container();
      )
   }
}
```

So when I create my Widget1 I register my SnackBarListener.
In my app I have a NavigationBloc and Listener for handle the navigation like:
```
BlocListener<NavigationBloc, NavigationState>(
      listener: (context, state) {
        if (state is Widget1) {
          Navigator.of(context).pushNamed('/widget1');
        }
        if (state is Widget2) {
          Navigator.of(context).pushNamed('/widget2');
        }
        if (state is Widget3) {
          Navigator.of(context).pushNamed('/widget3');
        }
    
      },
    )
```
Once time I change my page to Widget2, and then I return in Widget1 with NavigationBloc and so with Navigator.of(context).pushNamed('/widget1');
the listener for snackBar in Widget1 is re-registered so if I try to open my snackbar the function:

```
Scaffold.of(context).showSnackBar(SnackBar(
              content: Text('${state.message}'),
              backgroundColor: Colors.green,
            ));
```

Is called twice, and then 3 times and so on.
How Should I handle these cases?

**Comment by felangel** [comment] 2020-01-16 16:30
Hi @loreberti89 👋 
Thanks for opening an issue!

Are you able to share a link to a sample app which illustrates the problem you're having? Thanks!

**Comment by loreberti89** [comment] 2020-01-16 17:51
> Hi @loreberti89 👋
> Thanks for opening an issue!
> 
> Are you able to share a link to a sample app which illustrates the problem you're having? Thanks!

Sorry I haven't a direct link for sample App, But I've create a gist that is simil of my code, or maybe can help to understand my problem.

https://gist.github.com/loreberti89/a916d03ed20ea10484fae3cb001964cf

**Comment by felangel** [comment] 2020-01-25 12:05
Hi @loreberti89 I took a look and this is behaving as intended. Every time you push a new named route it will push a a new instance of the widget on the stack and because there is a BlocListener each listener will subscribe to the existing bloc so you will end up with multiple listeners. I would recommend not having a global "SnackBarBloc" because a snack bar should be scoped to the scaffold (page) that you are on and it is not intended behavior to reuse a single snackbar across multiple pages. 

In your case, you might want to look into using an overlay instead of a snack bar and also in this case, I would recommend having a single BlocListener below your BlocProvider which handles showing/hiding the overlay.

Hope that helps! Closing for now but feel free to comment with additional questions/comments and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-01-25 12:05 UTC
Labels: question, waiting for response
