### ISSUE TITLE
fix: Bloc Builder Not Rebuild

### ISSUE THREAD

**Issue by mstfkhazaal** [felangel/bloc#3601] opened 2022-11-03 11:44 UTC
When I use BlocBuilder inside alert dialog or bottomsheet BlocBuilder not rebuild

**Comment by Gene-Dana** [comment] 2022-11-03 14:32
Hi there 👋🏼 It's hard for us to help with out further context - it could be any number of issues - do you have a repo you can share?

**Comment by felangel** [comment] 2022-11-03 14:43
Also it might be helpful to check out the [FAQs section](https://bloclibrary.dev/#/faqs?id=state-not-updating) if you haven't already.

**Comment by Gene-Dana** [comment] 2022-11-03 19:27
Forgot we had this ! Good look @felangel

**Comment by felangel** [comment] 2022-11-08 15:59
Closing for now since there are no actionable next steps. Feel free to provide additional context and a minimal reproduction sample and I'm happy to take a closer look 👍

**Closed by felangel** 2022-11-08 15:59 UTC
Labels: question, waiting for response
