### ISSUE TITLE
When add Navigator.pushNamed get this: BlocProvider.of() called with a context that does not contain a Bloc of type ActivationBloc.

### ISSUE THREAD

**Issue by dominikchrastek** [felangel/bloc#374] opened 2019-06-24 14:44 UTC
Hello sir,

I have issue with `redirect` to another page and I have no idea what I'm doing wrong. I've already searched for solutions however nothing helped me, yet.

My solution works correctly, however when I've tried add 
redirect to `login` screen `Navigator.of(context).pushNamed('/login');` that is triggered in `BlocListener` when the state is `ActivationStateActivated ` then I've got this error:

```
flutter: The following assertion was thrown building ActivationScreen(dirty):
flutter:         BlocProvider.of() called with a context that does not contain a Bloc of type ActivationBloc.
flutter:         No ancestor could be found starting from the context that was passed to
flutter: BlocProvider.of<ActivationBloc>().
flutter:         This can happen if the context you use comes from a widget above the BlocProvider.
flutter:         This can also happen if you used BlocProviderTree and didn't explicity provide
flutter:         the BlocProvider types: BlocProvider(bloc: ActivationBloc()) instead of
flutter: BlocProvider<ActivationBloc>(bloc: ActivationBloc()).
flutter:         The context used was: ActivationScreen(dirty)
```
I have this Bloc class
```
class ActivationBloc extends Bloc<ActivationEvent, ActivationState> {
  final TerminalRepository terminalRepository;

  ActivationBloc({@required this.terminalRepository})
      : assert(terminalRepository != null);

  @override
  ActivationState get initialState => ActivationStateInit();

  @override
  Stream<ActivationState> mapEventToState(ActivationEvent event) async* {
    if (event is ActivationEventInit) {
      final token = await terminalRepository.getToken();

      print(token);

      if (token != null) {
        yield ActivationStateActivated();
      } else {
        yield ActivationStateInit();
      }
    }
    if (event is ActivationEventActivate) {
      yield ActivationStateLoading();

      try {
        final terminal = await terminalRepository.activate(event.pin);

        await terminalRepository.storeToken(terminal.token);
        yield ActivationStateActivated();
      } catch (err) {
        yield ActivationStateError(error: err.toString());
      }
    }
  }
}
```
Router class
```
class Router {
  final TerminalRepository terminalRepository = new TerminalRepository();

  Route screenActivation() {
    return MaterialPageRoute(
      builder: (BuildContext context) {
        return BlocProvider<ActivationBloc>(
            builder: (context) =>
                ActivationBloc(terminalRepository: terminalRepository),
            child: ActivationScreen());
      },
    );
  }

  Route screenLogin() {
    return MaterialPageRoute(
      builder: (BuildContext context) {
        return ActivationScreen();
      },
    );
  }

  Route routes(RouteSettings settings) {
    print(settings.name);
    switch (settings.name) {
      case "/":
        return screenActivation();
      case "/login":
        return screenLogin();

      default:
        return screenActivation();
    }
  }
}
```

and finally there is my component:
```
class ActivationScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final activationBloc = BlocProvider.of<ActivationBloc>(context); // here should be the error

    return BlocListener(
        bloc: activationBloc,
        listener: (BuildContext context, ActivationState state) {
          print(state);

          if (state is ActivationStateLoading) {
            return Loading();
          }
          if (state is ActivationStateActivated) {
            // Navigator.of(context).pushNamed('/login');
          }
        },
        child: Scaffold(
          appBar: AppBar(
            title: Text("Activation"),
          ),
          body: BlocBuilder(
              bloc: activationBloc,
              builder: (BuildContext context, ActivationState state) {
                if (state is ActivationStateInit) {
                  activationBloc.dispatch(ActivationEventInit());
                }
                if (state is ActivationStateLoading) {
                  return Loading();
                }
                return buildBody(context, activationBloc, state);
              }),
        ));
  }
}
```

Do you have any idea what's wrong there?
Thank you

**Comment by felangel** [comment] 2019-06-24 16:40
Hi @dominikchrastek 👋 
Thanks for opening an issue!

Are you able to share a link to the full source code? It would be much easier for me to help if I can run and debug the app locally? Thanks!

**Comment by dominikchrastek** [comment] 2019-06-24 17:55
Hello @felangel,
thank you for the quick response!

there is the dummy repo with the example, i've just stubbed some meaningless data.

https://github.com/dominikchrastek/fl_bloc_playground

If you will comment the `line 23` in `lib/src/activation/activation_screen.dart` with the Navigator stuff then there won't be any error ¯\_(ツ)_/¯ 

Thank you

**Comment by felangel** [comment] 2019-06-26 02:06
Hey @dominikchrastek no problem!

I took a quick look and it looks like the issue is you're not providing an `ActivationBloc` in the `/login` route.

I updated the route to look like:

```dart
  Route screenLogin() {
    return MaterialPageRoute(
      builder: (BuildContext context) {
        return BlocProvider(
          builder: (context) =>
              ActivationBloc(terminalRepository: terminalRepository),
          child: ActivationScreen(),
        );
      },
    );
  }
```

and `BlocProvider.of<ActivationBloc>(context)` resolves the `ActivationBloc` properly.

In the sample you sent, that leads to an infinite loop because `ActivationScreen` always dispatches the init event which triggers the `Navigation.pushNamed` but hopefully that answers your question. 👍 

Closing for now but feel free to comment with additional information/questions and I'm happy to continue the conversation 😄

**Closed by felangel** 2019-06-26 02:06 UTC
Labels: question, waiting for response

**Comment by dominikchrastek** [comment] 2019-06-27 10:26
Hi @felangel ,

thank you for the help, I've discovered that I was using wrong component on the `/login` screen 🤦‍♂  
I am new in flutter (frontend react/redux/graphql background) so I wanna ask if this is a legit way how to do programmatically redirect?

**Comment by felangel** [comment] 2019-06-28 01:05
Hi @dominikchrastek no worries! Yeah you can either programatically route using named routes or using anonymous routes using `Navigator.of(context).push(...)`. 👍
