### ISSUE TITLE
bloc file consume to much memory while editing

### ISSUE THREAD

**Issue by BoshiLee** [felangel/bloc#2110] opened 2021-01-23 06:36 UTC
**Describe the bug**
Did anyone has idea why bloc files consume too much memory while editing?
I am using android studio when I editing bloc file and it use lot of memory if I open bloc file. It really hard to edit file.

**To Reproduce**
1. Go to 'any bloc or cubit file'
2.  Edit any line of file
3. consume to much memrory
4. close bloc file will release some memory

**Expected behavior**
bloc file consume to much memory while editing

**Screenshots**

**Logs **
Run `flutter analyze` and attach any output of that command below.
If there are any analysis errors, try resolving them before filing this issue.

Paste the output of running `flutter doctor -v` here.

**Additional context**

**Comment by felangel** [comment] 2021-01-25 19:00
Hi @BoshiLee 👋 
Thanks for opening an issue!

Can you provide any more information? It's hard to identify the cause of the issue based on your description, thanks! 🙏

**Comment by bakeyevrus** [comment] 2021-01-26 22:39
If you are using Android Studio, there is an [open issue](https://github.com/flutter/flutter-intellij/issues/5108). It is not about the BLoC library, but 'part of' and 'part' constructions. I didn't manage to find any solution except increasing the max heap size for Android studio approx. to 4GBs. 

As for the VS Code, there is a workaround, which helped me. Have a look [here](https://github.com/flutter/flutter-intellij/issues/5034#issuecomment-742418977).

**Comment by felangel** [comment] 2021-01-29 05:47
Thanks for linking the relevant issue @bakeyevrus 🙏 
Closing for now since it doesn't appear to be bloc-specific and is already being tracked 👍

**Closed by felangel** 2021-01-29 05:47 UTC
Labels: extension, question, waiting for response
