### ISSUE TITLE
bloc_test causes dependency constraints and I can't figure out why

### ISSUE THREAD

**Issue by kleinesNugget** [felangel/bloc#3971] opened 2023-10-11 09:30 UTC
**Description**
Adding bloc_test to a project causes dependencies like "analyzer" to be constrained.
In my case, adding bloc_test to a project with "freezed" caused "analyzer" (6.2.0 -> 5.13.0), "_fe_analyzer_shared" (64.0.0 -> 61.0.0) and "dart_style" (2.3.3 -> 2.3.2) to be downgraded.
After looking through the pubspec of bloc_test, I couldn't really figure out what's causing those constraints, since all dependencies either don't seem to depend on those, or had no constraints that should be causing this.

**Steps To Reproduce**

1. Create a new flutter project
2. Add "freezed" to the dependencies
3. Add "bloc_test" to the dependencies
4. Watch "analyzer", "_fe_analyzer_shared" and "dart_style" being downgraded (< Symbol)

**Expected Behavior**
Adding bloc_test currently shouldn't cause dependencies like "analyzer", "_fe_analyzer_shared" and "dart_style" to be constraint.

**Screenshots**
![image](https://github.com/felangel/bloc/assets/44408413/98eb78e8-3839-4457-aa3b-6571362dd27e)

**Additional Context**
Adding freezed as a dependency isn't required to make the constraint happen. It just makes it easier to see, that those dependencies are being downgraded. Without freezed, pub would just say, that those dependencies have been installed, but a newer version is available.

**Comment by felangel** [comment] 2023-10-11 13:52
Can you share a minimal pubspec.yaml to reproduce this without freezed? Regarding freezed, it seems related to https://github.com/rrousselGit/freezed/issues/989

**Comment by kleinesNugget** [comment] 2023-10-11 14:47
Yeah sure.
I've attached 2 pubspecs, one before and after adding bloc_test, without freezed of course.
The base pubspec was created by `flutter create`

The analyzer dependency is stuck at 5.13.0 with 6.2.0 being available, similar thing for the others I've mentioned above.

The issue you've mentioned seems to have been fixed in the latest freezed release, which was the one I was using originally.

Thank you for having a look 😃 

[pubspecs.zip](https://github.com/felangel/bloc/files/12871277/pubspecs.zip)

**Comment by felangel** [comment] 2023-10-14 20:57
```yaml
name: sandbox
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

```
$ flutter packages outdated
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name  Current  Upgradable  Resolvable  Latest  
all dependencies are up-to-date.
```

```
$ flutter packages add dev:bloc_test
Resolving dependencies... 
+ _fe_analyzer_shared 61.0.0 (65.0.0 available)
+ analyzer 5.13.0 (6.3.0 available)
+ args 2.4.2
+ bloc 8.1.2
+ bloc_test 9.1.4
  collection 1.17.2 (1.18.0 available)
+ convert 3.1.1
+ coverage 1.6.4
+ crypto 3.0.3
+ diff_match_patch 0.4.1
+ file 7.0.0
+ frontend_server_client 3.2.0
+ glob 2.1.2
+ http_multi_server 3.2.1
+ http_parser 4.0.2
+ io 1.0.4
+ js 0.6.7
+ logging 1.2.0
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.9.1 (1.11.0 available)
+ mime 1.0.4
+ mocktail 1.0.1
+ node_preamble 2.0.2
+ package_config 2.1.0
+ pool 1.5.1
+ pub_semver 2.1.4
+ shelf 1.4.1
+ shelf_packages_handler 3.0.2
+ shelf_static 1.1.2
+ shelf_web_socket 1.0.4
+ source_map_stack_trace 2.1.1
+ source_maps 0.10.12
  stack_trace 1.11.0 (1.11.1 available)
  stream_channel 2.1.1 (2.1.2 available)
+ test 1.24.3 (1.24.8 available)
  test_api 0.6.0 (0.6.1 available)
+ test_core 0.5.3 (0.5.8 available)
+ typed_data 1.3.2
+ vm_service 11.10.0 (12.0.0 available)
+ watcher 1.1.0
  web 0.1.4-beta (0.3.0 available)
+ web_socket_channel 2.4.0
+ webkit_inspection_protocol 1.2.1
+ yaml 3.1.2
Changed 37 dependencies!
```

```
$ flutter packages outdated         
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name  Current  Upgradable  Resolvable  Latest  

dev_dependencies: all up-to-date.
all dependencies are up-to-date.
```

The analyzer dependency is at 5.13.0 because the latest stable version of Flutter requires it:
https://github.com/flutter/flutter/blob/2f708eb8396e362e280fac22cf171c2cb467343c/packages/flutter/pubspec.yaml#L29C3-L29C106

When I add `freezed`, the version of `package:analyzer` does not change:

```
$ flutter packages add freezed      
Resolving dependencies... 
  _fe_analyzer_shared 61.0.0 (65.0.0 available)
  analyzer 5.13.0 (6.3.0 available)
+ build 2.4.1
+ build_config 1.1.1
+ checked_yaml 2.0.3
  collection 1.17.2 (1.18.0 available)
+ dart_style 2.3.2 (2.3.3 available)
+ freezed 2.4.5
+ freezed_annotation 2.4.1
+ json_annotation 4.8.1
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.9.1 (1.11.0 available)
+ pubspec_parse 1.2.3
+ source_gen 1.4.0
  stack_trace 1.11.0 (1.11.1 available)
  stream_channel 2.1.1 (2.1.2 available)
  test 1.24.3 (1.24.8 available)
  test_api 0.6.0 (0.6.1 available)
  test_core 0.5.3 (0.5.8 available)
  vm_service 11.10.0 (12.0.0 available)
  web 0.1.4-beta (0.3.0 available)
Changed 9 dependencies!
```

Are you using the `stable` channel of `Flutter`? The output above is using:

```
Flutter 3.13.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2f708eb839 (5 days ago) • 2023-10-09 09:58:08 -0500
Engine • revision a794cf2681
Tools • Dart 3.1.3 • DevTools 2.25.0
```

**Comment by kleinesNugget** [comment] 2023-10-15 21:13
Hey yeah, I'm using the stable channel of flutter.
If this is the case it confuses me.
When installing freezed first, it installs the latest version of analyzer and the others. I don't really understand how that works if flutter is the weakest link in the chain.
I mean now the constraint makes sense, I just don't quite get how freezed manages to get the latest versions, if that's the way it works and why installing bloc_test then causes the version to drop again.

**Comment by felangel** [comment] 2023-10-27 04:44
I wasn't able to reproduce that behavior locally. Going to close this since I don't think there are any actionable steps in `bloc_test`.

**Closed by felangel** 2023-10-27 04:44 UTC
Labels: bug, question, waiting for response, pkg:bloc_test, needs repro info
