### ISSUE TITLE
Bloc listener does get called even after widget is disposed

### ISSUE THREAD

**Issue by abhishek199-dhn** [felangel/bloc#2160] opened 2021-02-17 06:49 UTC
**Describe the bug**

My use case is to have a global UserBloc Provider such that I don't need to wrap each route with it and any widget can access the logged-in user.

SplashView is my initial route and in case the user is not logged-in it goes to the login page and after successful authentication, it redirects the user to HomeView where I again fire a User event again.

The issue is that when I fire an event from HomeView the bloc listener in SplashView gets invoked and it pushes the HomeView Widget again in the route stack. And it gets stuck in a loop.

Not sure what's the issue since When I route to HomeView I remove all the prev routes from the route stack and it shouldn't invoke the prev bloc listener?

Also, I have observed sometimes the behavior is not consistent like sometimes it gets called for only 2 times or 20 times or 1 time. 

Please let me know how to fix this and if there is any other way to implement a global bloc provider.

```dart
final Map<String, WidgetBuilder> routes = <String, WidgetBuilder>{
  Routes.splash: (context) => SplashView(),
  Routes.profile: (context) => ProfileScreen(),
  Routes.home: (context) => HomeView(),
};

```

```dart

class MyApp extends StatelessWidget {
  static final navigatorKey = GlobalKey<NavigatorState>();

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider<UserBloc>( // global bloc provider
          create: (BuildContext context) => sl<UserBloc>()
            ..add(
              GetLoggedInUserEvent(),
            ),
        ),
        BlocProvider<AppBloc>(
          create: (BuildContext context) => sl<AppBloc>()..add(GetAppData()),
        ),
      ],
      child: MaterialApp(
        navigatorKey: navigatorKey,
        title: Constants.getAppName(),
        theme: ThemeData(
          primaryColor: HColors.primaryColor,
        ),
        home: SplashView(),
        routes: routes,
      ),
    );
  }
}

```

```dart


class SplashView extends StatefulWidget {
  const SplashView();

  @override
  _SplashViewState createState() => _SplashViewState();
}

class _SplashViewState extends State<SplashView> {
  User _user;

  @override
  void initState() {
    setState(() {
      _user = null;
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MultiBlocListener(
      listeners: [userBlocListener(), appBlocListener()],
      child: BasePage(
        child: Container(
          child: Stack(
            children: [
              _getSplashBackground(),
              _getAppNameAndDescription(),
              _getDecorationImage(),
            ],
          ),
        ),
      ),
    );
  }

 ...

  Widget userBlocListener() {
    return BlocListener<UserBloc, UserState>(
      listener: (blocContext, blocState) {

       // this bloc listener gets called even this route is not in the route stack when the event is fired from the homeView.
        if (blocState is UserLoaded) {
          setState(() {
            _user = blocState.user;
          });
          handleUserRouting(blocState.user, true);
        }
      },
    );
  }

  void handleUserRouting(User user, bool isUserBlocLoaded) {
    if (this.mounted) {
      if (user != null) {
        if (user.status == UserStatus.ACTIVE) {
          if (user.profileStatus == UserProfileStatus.COMPLETE) {
           // removing this route from the route stack
            Navigator.pushNamedAndRemoveUntil(
                context,
                Routes.home,
                (Route<dynamic> route) => false,
              );
          }
        }
      } else{  // route to login }
    }
  }
}

```

```dart

class HomeView extends StatefulWidget {
  @override
  _HomeViewState createState() => _HomeViewState();
}

class _HomeViewState extends State<HomeView> {
  @override
  void initState() {
    // need to fire this event again in case when user comes from this flow (get the user in home): splash -> user not found -> login -> home  
    BlocProvider.of<UserBloc>(context).add(GetLoggedInUserEvent());
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      child: BlocBuilder<UserBloc, UserState>(
        builder: (context, state) {
          String name = "";
          if (state is UserLoaded) {
            name = state.user.name;
          }
          return HumaneAppPage(
            bodyChild: Text("Some Random Body"),
            title: "Hello $name,\nLet's get untangled",
          );
        },
      ),
    );
  }
}
```

**Logs **
Run `flutter analyze` and attach any output of that command below.
If there are any analysis errors, try resolving them before filing this issue.

`flutter doctor -v` output

```
[✓] Flutter (Channel stable, 1.22.2, on macOS 11.0.1 20B50, locale en-IN)
    • Flutter version 1.22.2 at /Users/abhishek/data/humaneWorkspace/flutter
    • Framework revision 84f3d28555 (4 months ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/abhishek/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

! Doctor found issues in 1 category.
```
**dependencies** 
```  
dependencies:
  flutter:
    sdk: flutter
  flutter_signin_button: ^1.0.0
  intl: ^0.16.1
  graphql_flutter: ^3.0.1
  flutter_bloc: 5.0.0 // also tired using 6.1.2 
  equatable: ^1.1.1
  dartz: ^0.9.0
  data_connection_checker: 0.3.4
  get_it: 4.0.2
  url_launcher: ^5.5.2
  firebase_core: ^0.5.0
  firebase_messaging: ^7.0.0
  shared_preferences: ^0.5.10
  pdf_render: ^0.67.0
  firebase_auth: ^0.18.3
  firebase_dynamic_links: ^0.6.2
  firebase_remote_config: ^0.4.3
  overlay_support: ^1.0.5
```

**Comment by jurej1** [comment] 2021-02-17 08:20
Try this it may help

```
 void handleUserRouting(User user, bool isUserBlocLoaded) {
    if (this.mounted) {
      if (user != null) {
        if (user.status == UserStatus.ACTIVE) {
          if (user.profileStatus == UserProfileStatus.COMPLETE) {
           // removing this route from the route stack
BlocProvider.of<UserBloc>(context).add(GetLoggedInUserEvent());
            Navigator.of(context).pushReplacementNamed(//in here the homw view route);
          }
        }
      } else{  // route to login }
    }
  }
```

**Comment by abhishek199-dhn** [comment] 2021-02-17 09:58
@jurej1 thanks for your reply. Will it make any difference?
Anyways firing an event in the splash screen won't help in case the user goes through this flow: Splash -> Login -> Home View. So `GetLoggedInUserEvent()` must be fired again after login i.e in homeView screen. 

mainly I wanted to know why the listener is active even if the widget is disposed of. I can't even call `userBloc.dispose()` on widget dispose as any future events to global UserBloc will stop executing.

**Comment by jurej1** [comment] 2021-02-17 12:14
> Firing an event in the splash screen won't help in case the user goes through this flow: Splash -> Login -> Home View. So `GetLoggedInUserEvent()` must be fired again after login i.e in homeView screen.

Yes true so you only need to fire this event when the user is going to go from Splash to Home view

**Comment by jurej1** [comment] 2021-02-17 12:14
> mainly I wanted to know why the listener is active even if the widget is disposed of. I can't even call `userBloc.dispose()` on widget dispose as any future events to global UserBloc will stop executing.

For this i am not sure. Sorry

**Comment by felangel** [comment] 2021-02-17 17:22
Hi @abhishek199-dhn 👋 
Thanks for opening an issue!

`BlocListener` will unsubscribe when the widget is unmounted. If this is still an issue can you please create a simple sample app which reproduces the issue and share the link? Thanks! 🙏

**Comment by abhishek199-dhn** [comment] 2021-02-17 19:37
> Hi @abhishek199-dhn 👋
> Thanks for opening an issue!
> 
> `BlocListener` will unsubscribe when the widget is unmounted. If this is still an issue can you please create a simple sample app which reproduces the issue and share the link? Thanks! 🙏

Hey @felangel, I have created a simple sample app and have added it to this repo - https://github.com/abhishek199-dhn/bloc-listener-test. I'm able to reproduce the issue.

Please let me know if have any difficulties in running the app. Thanks!

**Comment by jurej1** [comment] 2021-02-18 18:34
@abhishek199-dhn  Hey! I have forked your example and did some changes to it. The problem has disappeare🎉. Let me know if you like the changes.💪
@felangel it would also mean a lot for me if you could also check it out and just give me your thoughts about the way I used Bloc.

**Comment by abhishek199-dhn** [comment] 2021-02-19 06:32
> @abhishek199-dhn Hey! I have forked your example and did some changes to it. The problem has disappeare🎉. Let me know if you like the changes.💪
> @felangel it would also mean a lot for me if you could also check it out and just give me your thoughts about the way I used Bloc.

Thanks, @jurej1 I went through your PR. I appreciate your help! This is one of the ways to solve the problem by moving the BlocListener at a global level along with the BlocProvider.  But the issue I'm trying to address here is that `BlockListener` should `unsubscribe` when the `widget is unmounted.`. So in my case, I have a BlocListener at a ChildWidget.

**Comment by felangel** [comment] 2021-02-19 22:57
Hi @abhishek199-dhn 👋 
Thanks for opening an issue!

The issue isn't that `BlocListener` isn't disposed, it's that the `SplashScreen` is disposed after the `HomePage` is initialized which triggers an infinite loop. I would highly recommend using a different approach:

- Use [FlowBuilder](https://pub.dev/packages/flow_builder) to control the navigation state based on the bloc state (recommended)
- Use a single `BlocListener` at the root to handle navigation rather than a `BlocListener` in the `SplashPage` itself as @jurej1 mentioned.

You can check out an [authentication flow example](https://github.com/felangel/flow_builder/blob/master/example/lib/authentication_flow/authentication_flow.dart) for how the implementation could look with `FlowBuilder`.

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Closed by felangel** 2021-02-19 22:57 UTC
Labels: question, waiting for response
