### ISSUE TITLE
Crash stream when initial state is null.

### ISSUE THREAD

**Issue by amadeu01** [felangel/bloc#1348] opened 2020-06-27 17:17 UTC
**Describe the bug**
If you have a BLOC with null on the initial state.

```dart
class AlarmBloc extends Bloc<EmergencyEvent, AlarmState> {
  //....

  @override
  AlarmState get initialState => null;
````
It will throw an error for the first time the event is mapped. But, then it will not let you know that the bloc is not working anymore due to invalid `current state`.

I know that is not desirable to start with `null` as a state. And maybe no one does this. But, if somehow the state ended up with null. It is kind of hard to find out why the event's haven't been treated.

**To Reproduce**

**Expected behavior**
Keep throwing errors for every new event added to the bloc with an invalid state.

**Logs **

```
E/flutter (10146): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: 'package:bloc/src/transition.dart': Failed assertion: line 23 pos 16: 'currentState != null': is not true.
E/flutter (10146): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
E/flutter (10146): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (10146): #2      new Transition (package:bloc/src/transition.dart:23:16)
E/flutter (10146): #3      Bloc._bindStateSubject.<anonymous closure> (package:bloc/src/bloc.dart:159:28)
E/flutter (10146): #4      Stream.forEach.<anonymous closure>.<anonymous closure> (dart:async/stream.dart:875:38)
E/flutter (10146): #5      _runUserCode (dart:async/stream_pipe.dart:11:23)
E/flutter (10146): #6      Stream.forEach.<anonymous closure> (dart:async/stream.dart:875:7)
E/flutter (10146): #7      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (10146): #8      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (10146): #9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (10146): #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (10146): #11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter (10146): #12     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:385:25)
E/flutter (10146): #13     _BroadcastStreamController._add (dart:async/broadcast_stream_controller.dart:293:5)
E/flutter (10146): #14     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (10146): #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (10146): #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (10146): #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (10146): #18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter (10146): #19     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:127:11)
E/flutter (10146): #20     _HandleErrorStream._handleData (dart:async/stream_pipe.dart:266:10)
E/flutter (10146): #21     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
E/flutter (10146): #22     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (10146): #23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (10146): #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (10146): #25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (10146): #26     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
E/flutter (10146): #27     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
E/flutter (10146): #28     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
E/flutter (10146): #29     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (10146): #30     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (10146): #31     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (10146): #32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (10146): #33     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (10146): #34     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (10146): #35     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (10146): #36     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (10146): #37     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (10146): #38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (10146): 
```

**Comment by felangel** [comment] 2020-06-28 00:53
Hi @amadeu01 👋 
Thanks for opening an issue!

This is a duplicate of #1312 and is fixed in bloc ^5.0.0-dev.7.
Hope that helps 👍

**Closed by felangel** 2020-06-28 00:53 UTC
Labels: duplicate
