### ISSUE TITLE
Bloc state subscription doesn't yield current state

### ISSUE THREAD

**Issue by millerovv** [felangel/bloc#1659] opened 2020-08-23 09:25 UTC
When subscribing to bloc state stream using `listen` method, current state is not yielded. 
This happens since `Bloc` became an extension of `Cubit` instead of `CubitStream` because of the difference in implementations of listen method:

#### CubitStream (bloc 5.0.1):

```
@override
  StreamSubscription<State> listen(
    void Function(State) onData, {
    Function onError,
    void Function() onDone,
    bool cancelOnError,
  }) {
    return _stream.listen(
      onData,
      onError: onError,
      onDone: onDone,
      cancelOnError: cancelOnError,
    );
  }
```

Where _stream constructed as the current state followed by _controller.stream:
```
Stream<State> get _stream async* {
    yield state;
    yield* _controller.stream;
  }
```

When we subscribed to our bloc, current state has been yielded simultaneously to our subscription.

#### Cubit (bloc 6.0.2)

Exposes subscription to state stream controller but doesn't yield current state

```
@override
  StreamSubscription<State> listen(
    void Function(State) onData, {
    Function onError,
    void Function() onDone,
    bool cancelOnError,
  }) {
    _controller ??= StreamController<State>.broadcast();
    return _controller.stream.listen(
      onData,
      onError: onError,
      onDone: onDone,
      cancelOnError: cancelOnError,
    );
  }
```

I consider this as a significant breaking change, that has lead to great amount of logical errors throughout my projects.
For now I will revert back to bloc 5.0.1.

**Comment by felangel** [comment] 2020-08-24 03:56
Hi @millerovv 👋 
Thanks for opening an issue!

This is a duplicate of #1573, #1542, #1541, and #1518 and was an intentional breaking change which is documented in the [migration guide](https://bloclibrary.dev/#/migration?id=%e2%9d%97bloc-does-not-emit-last-state-on-subscription).

Hope that helps 👍

**Closed by felangel** 2020-08-24 03:56 UTC
Labels: duplicate

**Comment by T-mans** [comment] 2020-12-04 07:32
@millerovv, I used extension function to deal with this problem: like this:
`extension BlocExt<Event, State> on Bloc<Event, State> {
  StreamSubscription<State> publishDelayListen(
    void onData(State value), {
    Function onError,
    void onDone(),
    bool cancelOnError,
  }) {
    onData(state);
    return listen(
      onData,
      onError: onError,
      onDone: onDone,
      cancelOnError: cancelOnError,
    );
  }
}`
