### ISSUE TITLE
BlocBuilder is not updating on state change

### ISSUE THREAD

**Issue by ezra126** [felangel/bloc#1767] opened 2020-09-23 20:42 UTC
I want to redirect to the home page after sign in at the login page .even the state changes  it remains on the login page. the logout button at the home page works and  but the login button does not trigger in the blocbuilder

 main.dart
```
 return MaterialApp(
          debugShowCheckedModeBanner: false,
          //initialRoute:  BlocProvider.of<AuthenticationBloc>(context) == Uninitialized ? splashscreenRoute : loginScreenRoute,
       //  initialRoute: homeRoute,
         onGenerateRoute: Router.generateRoute,
         home:  BlocBuilder<AuthenticationCubit,AuthenticationState>(
         builder: (context, state) {
           if (state is Authenticated) {
             return HomeScreen();
           }
           else if (state is Uninitialized) {
             return SplashScreen();
           }
           else if (state is Unauthenticated) {
           
            return WelcomeScreen();   // the page which consist sign in and register button
          }
           return Container();
         },
       ),
        );
```

login page 
```
BlocListener<LoginBloc, LoginState>(
      listener: (context, state) {
         if (state.isSuccess) {
          BlocProvider.of<AuthenticationCubit>(context).loggedIn();
        }
})


 GestureDetector(
                            onTap: () {
                              // signInGoogle();
                              // BlocProvider.of<AuthenticationCubit>(context).loggedIn();
                              BlocProvider.of<LoginBloc>(context).add(LoginWithGooglePressed());
                            },
```

full code --->[https://github.com/ezra126/bekloh_user/tree/authentication/](url)   thanks in advance

**Comment by RollyPeres** [comment] 2020-09-23 20:58
Hi @ezra126 👋

This is a duplicate of https://github.com/felangel/bloc/issues/1745.
Your issue was already addressed in a PR so what is the purpose of opening a new issue with the very same problem ?

**Closed** 2020-09-24 04:28 UTC
Labels: duplicate
