### ISSUE TITLE
close not called

### ISSUE THREAD

**Issue by eliudio** [felangel/bloc#2073] opened 2021-01-12 12:25 UTC
Hi,

I've got a bloc implementation, similar to https://github.com/felangel/bloc/blob/master/examples/flutter_firestore_todos/lib/blocs/todos/todos_bloc.dart

I've noticed that the close is never alled. Hence the todosSubscription?.cancel(); is never called. In flutter_web, firestore this is an issue as listening twiice not allowed, which I think is another issue. But even if it was ok to listen twice, listening without unsubscribing is not a good idea regardless, so I'm quite happy flutter_web is pointing me to this issue.

Any idea under what situation the close wouldn't be called? I assume going out of scope, i.e. switching to another page in my app would result in destroying the widget, destroying the bloc and hence the close being called. But it doesn't happen. Do I have to do something specific to make sure the close on bloc is called?

thanks,

Johan

**Comment by felangel** [comment] 2021-01-13 01:00
Hi @eliudio 👋 
Thanks for opening an issue!

I believe this is a duplicate of https://github.com/felangel/bloc/issues/2040. Hope that helps!

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Closed by felangel** 2021-01-13 01:00 UTC
Labels: duplicate, question
