### ISSUE TITLE
'B' doesn't conform to the bound 'StateStreamable<S>' of the type parameter 'B'

### ISSUE THREAD

**Issue by giacomomasseron** [felangel/bloc#3927] opened 2023-08-09 10:05 UTC
**Description**
Hi, I get the error in title with this code:  

	void showBottomSheet<B extends Bloc, S>(
	{required BuildContext context, required B bloc}) async {
		final result = await showModalBottomSheet(
		isDismissible: true,
		useSafeArea: true,
		useRootNavigator: true,
		isScrollControlled: true,
		context: context,
		builder: (context) {
			return BlocProvider<B>.value(
				value: bloc,
				child: BlocBuilder<B, S>( // <--- HERE I get the error
				    builder: (context, state) {
					return Text('test');
				    },
				),
			);
		});
		if (result == null) {
			if (context.mounted) {
				context.read<B>().add(MyEvent());
			}
		}
	}

**Expected Behavior**
`Bloc` class extends `BlocBase` class, that implements `StateStreamableSource<State>` interface.  
I shouldn't get this error.

**Comment by tenhobi** [comment] 2023-08-14 14:37
I suppose you need to fix your type parameters. `B extends Bloc` does not mention Bloc's event nor state, therefore B is unrelated to S? Something like that I suppose. https://github.com/felangel/bloc/blob/master/packages/bloc/lib/src/bloc.dart#L43

**Comment by felangel** [comment] 2023-09-13 01:41
Closing for now since there doesn't appear to be any actionable next steps. If this is still an issue feel free to provide a minimal reproduction sample, thanks!

**Closed by felangel** 2023-09-13 01:41 UTC
Labels: question, waiting for response
