### ISSUE TITLE
Scoped Provider throwing context error on second route build

### ISSUE THREAD

**Issue by CosmicPangolin** [felangel/bloc#1874] opened 2020-10-30 18:30 UTC
**Describe the bug**
This one is really idiosyncratic and has me stumped.  I have a LoginPage that contains a scoped LoginPageBloc provider (pic 1).  This page gets built independently for two different routes based on the presence of a user (pic 2).  Within LoginPage's BlocBuilder scope are components that call BlocProvider.of<LoginPageBloc>(context) to inform widget properties (pic 3).

First LoginPage build works as expected regardless of route.  Routing to another page (without login required) and then to the other login route works as expected.  However, navigating from one login route to the other, such that the first LoginPage is disposed and a second is immediately built, throws an error that reconciles itself - the relevant component with a BlocProvider.of call flashes red with a UI error and then builds correctly.

The really crazy thing is that I can print BlocProvider.of<LoginPageBloc>(context) within that component build method and it prints correctly at first before throwing an error on a framework rebuild and then printing correctly on a second framework rebuild (the framework seems to call build method 3x ONLY for the second LoginPage build).  In addition, I can print from the Bloc constructor to confirm that a second LoginPageBloc is built after the new route is called (routes are pushed with the pushNamedAndRemoveUntil method).  The log pic shows these outcomes.

I can try to reproduce in a simple app if there's not something obvious I'm missing...but it seems to me that, for one rebuild frame after initial build, the widget loses track of the appropriately scoped provider because....??  I'm also using the route name as a key for all of these components (provider, login page, and erroring component) with no effect.

**Expected behavior**
Since the provider is scoped, I expect to have access within that widget tree...and it seems like I do, except for just a little bit..........O_o

**Screenshots**

![image](https://user-images.githubusercontent.com/40650466/97741131-85180c00-1a9f-11eb-99c2-56d560942903.png)

![image](https://user-images.githubusercontent.com/40650466/97744880-35d4da00-1aa5-11eb-8dac-e88a323059f2.png)

![image](https://user-images.githubusercontent.com/40650466/97741617-3dde4b00-1aa0-11eb-9a5a-d2795b5b793b.png)

**Logs **
No associated analysis errors 

![image](https://user-images.githubusercontent.com/40650466/97742097-1176fe80-1aa1-11eb-8a37-15e90ae5a0ee.png)

![image](https://user-images.githubusercontent.com/40650466/97742162-25226500-1aa1-11eb-88d8-750d90c16340.png)

**Comment by felangel** [comment] 2020-10-31 15:51
Hi @CosmicPangolin 👋 
Thanks for opening an issue!

Are you able to share a link to a complete reproduction sample? Thanks! 👍

**Comment by CosmicPangolin** [comment] 2020-11-01 01:52
Heya Felix,

I wasn't able to reproduce initially, so I spent a lot of time digging through the InheritedWidget framework code before eventually noticing that it had something to do with a Hero widget in my tree between the provider and provider.of calls.

This sample should loosely reproduce:


```
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:bloc/bloc.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Bloc Failz',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      routes: routes,
    );
  }
}

Map<String, WidgetBuilder> routes = <String, WidgetBuilder>{
  '/': (_) => MyHomePage(),
  '/route_2': (_) => MyHomePage(),
};

class MyHomePage extends StatefulWidget {

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return BlocProvider<TestBloc>(
      create: (context) => TestBloc(),
      child: BlocBuilder<TestBloc, TestState>(
        builder: (context, testState) => Scaffold(
            appBar: AppBar(
              // Here we take the value from the MyHomePage object that was created by
              // the App.build method, and use it to set our appbar title.
              title: Text('Why u fail me'),
            ),
            drawer: Drawer(
              child: Padding(
                padding: const EdgeInsets.only(top: 60),
                child: Column(
                  children: [
                    ListTile(
                      title: Text('Route1'),
                      onTap: () => Navigator.of(context).pushNamedAndRemoveUntil('/', (route) => false),
                    ),
                    ListTile(
                      title: Text('Route2'),
                      onTap: () => Navigator.of(context).pushNamedAndRemoveUntil('/route_2', (route) => false),
                    ),
                  ],
                ),
              ),
            ),
            body: Hero(
              tag: 'center',
              child: Center(
              // Center is a layout widget. It takes a single child and positions it
              // in the middle of the parent.
              child: Column(
                // Column is also a layout widget. It takes a list of children and
                // arranges them vertically. By default, it sizes itself to fit its
                // children horizontally, and tries to be as tall as its parent.
                //
                // Invoke "debug painting" (press "p" in the console, choose the
                // "Toggle Debug Paint" action from the Flutter Inspector in Android
                // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
                // to see the wireframe for each widget.
                //
                // Column has various properties to control how it sizes itself and
                // how it positions its children. Here we use mainAxisAlignment to
                // center the children vertically; the main axis here is the vertical
                // axis because Columns are vertical (the cross axis would be
                // horizontal).
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  BlahBlah(),
                  Text(
                    '$_counter',
                    style: Theme.of(context).textTheme.headline4,
                  ),
                ],
              ),
            ),),
            floatingActionButton: FloatingActionButton(
              onPressed: _incrementCounter,
              tooltip: 'Increment',
              child: Icon(Icons.add),
            ), // This trailing comma makes auto-formatting nicer for build methods.
          ),
        ),
      );
  }
}

class BlahBlah extends StatefulWidget {
  @override
  _BlahBlahState createState() => _BlahBlahState();
}

class _BlahBlahState extends State<BlahBlah> {
  @override
  Widget build(BuildContext context) {
    return Container(child: Text(BlocProvider.of<TestBloc>(context).state.text));
  }
}

class TestState {
  TestState({this.text});
  String text;
}

class TestBloc extends Bloc<TestEvent, TestState> {
  TestBloc()
      : super(TestState(
      text: 'bah humbug'
  )) {
    print('Constructing new TestBloc');
  }


  @override
  Stream<TestState> mapEventToState(TestEvent event) async* {
    switch (event.runtimeType) {
      default:
        print('TestBloc - TestEvent not recognized');
        break;
    }
  }
}

abstract class TestEvent {
  const TestEvent();
}
```

**Comment by felangel** [comment] 2020-11-08 02:07
@CosmicPangolin I took a look and the issue is the bloc is scoped too low in this case because the widget which is providing the bloc is being unmounted from the widget tree. You need to either lift the bloc up one level or use a nested Navigator to ensure that the bloc is available even when the child is unmounted.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:bloc/bloc.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocProvider<TestBloc>(
      create: (_) => TestBloc(),
      child: MaterialApp(
        title: 'Bloc Failz',
        theme: ThemeData(
          primarySwatch: Colors.blue,
          visualDensity: VisualDensity.adaptivePlatformDensity,
        ),
        routes: routes,
      ),
    );
  }
}

Map<String, WidgetBuilder> routes = <String, WidgetBuilder>{
  '/': (_) => MyHomePage(),
  '/route_2': (_) => MyHomePage(),
};

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() => _counter++);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Why u fail me')),
      drawer: Drawer(
        child: Padding(
          padding: const EdgeInsets.only(top: 60),
          child: Column(
            children: [
              ListTile(
                title: Text('Route1'),
                onTap: () => Navigator.of(context)
                    .pushNamedAndRemoveUntil('/', (route) => false),
              ),
              ListTile(
                title: Text('Route2'),
                onTap: () => Navigator.of(context)
                    .pushNamedAndRemoveUntil('/route_2', (route) => false),
              ),
            ],
          ),
        ),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            BlahBlah(),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

class BlahBlah extends StatelessWidget {
  Widget build(BuildContext context) {
    return Container(
      child: Text(BlocProvider.of<TestBloc>(context).state.text),
    );
  }
}

class TestState {
  TestState({this.text});
  String text;
}

class TestBloc extends Bloc<TestEvent, TestState> {
  TestBloc() : super(TestState(text: 'bah humbug')) {
    print('Constructing new TestBloc');
  }

  @override
  Stream<TestState> mapEventToState(TestEvent event) async* {
    switch (event.runtimeType) {
      default:
        print('TestBloc - TestEvent not recognized');
        break;
    }
  }
}

abstract class TestEvent {
  const TestEvent();
}
```

Hope that helps 👍

**Comment by CosmicPangolin** [comment] 2020-11-09 19:25
@felangel Isn't it being mounted fresh in the new route before any calls?  The whole point is that in my real-world case I don't want that bloc globally scoped, but rather rebuilt on new routes.  Also, I believe the code I posted works fine as soon as you remove the Hero widget..

**Comment by felangel** [comment] 2020-11-13 04:46
@CosmicPangolin ah yeah you need two Hero widgets with the same tag to get the hero transition/animation. Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-11-13 04:46 UTC
Labels: question, waiting for response

**Comment by omidraha** [comment] 2021-02-01 09:38
How to use hero animation between to separated `bloc` ?
I have two page with separated bloc.
And when I use `hero` animation between them, I got this error:

```dart
 CubitProvider.of() called with a context that does not contain a Cubit
```
