### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Olaitan12** [felangel/bloc#573] opened 2019-10-13 13:36 UTC
- Issue Type: `Performance`
- Extension Name: `bloc`
- Extension Version: `0.12.2`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.39.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Olaitan\FelixAngelov.bloc-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by felangel** [comment] 2019-10-14 02:39
Hi @Olaitan12 👋 
Thanks for opening an issue!

Can you please provide some more information like what you were doing when the high cpu warning occurred? Also is it reproducible? If so what are the reproduction steps? Thanks!

**Comment by felangel** [comment] 2019-10-16 00:33
Closing for now due to lack of information/reproduction steps. Feel free to comment with additional information and I’m happy to reopen the issue 👍

**Closed by felangel** 2019-10-16 00:33 UTC
Labels: bug, extension, waiting for response
