### ISSUE TITLE
fix: integration_test fails when I run multiple testWidgets 

### ISSUE THREAD

**Issue by Bahrom2101** [felangel/bloc#3962] opened 2023-09-24 05:58 UTC
**Description**
I'm covering my app with integration tests. For state management, I'm using bloc. BlocProvider doing injection and new testWidgets trying to emit state to old state, then "Bad state: Cannot emit new states after calling close" is occurring.

My running test file is:
```
void main() async {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('end-to-end test', () {
    testWidgets('New sale base sc', (tester) async {
      await setUpApp();
      await tester.pumpWidget(const MyApp());
      await newSaleTest(tester);
      await scenarioBase(tester);
    });
    testWidgets('New sale kg sc', (tester) async {
      await setUpApp();
      await tester.pumpWidget(const MyApp());
      await newSaleTest(tester);
      await scenarioKilogram(tester);
    });
  });
} 
```

MyApp class is:
```
class MyApp extends StatelessWidget {
  const MyApp({
    Key? key,
    this.initialRoute,
  }) : super(key: key);

  final String? initialRoute;

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider<AppSettingsCubit>(
          create: (_) => AppSettingsCubit()..initialCheck(context),
        ),
        BlocProvider<MainCubit>(
          create: (_) => MainCubit(),
        ),
        BlocProvider<NewSaleCubit>(
          create: (context) => NewSaleCubit(),
        ),
        BlocProvider<NewSaleTransactionCubit>(
          create: (context) => NewSaleTransactionCubit(),
        ),
      ],
      child: BlocConsumer<AppSettingsCubit, AppSettingsState>(
        listener: (context, state) {},
        builder: (context, state) {
          final approuter = GoRouterSettings.instance(initialRoute: initialRoute);
          return ScreenUtilInit(
            useInheritedMediaQuery: true,
            designSize: const Size(390, 844),
            minTextAdapt: true,
            splitScreenMode: true,
            builder: (context, child) {
              return KeyboardDismisser(
                gestures: const [GestureType.onTap],
                child: MaterialApp.router(
                  debugShowCheckedModeBanner: false,
                  // navigatorKey: AppKeys.navigatorKey,
                  theme: appThemeData[ThemeMode.light],
                  darkTheme: appThemeData[ThemeMode.dark],
                  localizationsDelegates: context.localizationDelegates,
                  supportedLocales: context.supportedLocales,
                  locale: context.locale,
                  themeMode: state.theme,
                  // initialRoute: Routes.initial,
                  routerConfig: approuter.router,
                  builder: (context, widget) {
                    return ScrollConfiguration(
                      behavior: const _ScrollBehaviorModified(),
                      child: MediaQuery(
                        data: MediaQuery.of(context)
                            .copyWith(textScaleFactor: 1.0),
                        child: widget!,
                      ),
                    );
                  },
                ),
              );
            },
          );
        },
      ),
    );
  }
}

class _ScrollBehaviorModified extends ScrollBehavior {
  const _ScrollBehaviorModified();

  @override
  ScrollPhysics getScrollPhysics(BuildContext context) {
    return const BouncingScrollPhysics();
  }
}
```
Error is occurring in main_cubit.dart and that is: "The following StateError was thrown running a test (but after the test had completed):
Bad state: Cannot emit new states after calling close"

Please help me out whoever knows.

**Comment by felangel** [comment] 2023-10-14 21:35
Hi @Bahrom2101 👋 
Thanks for opening an issue!

Can you please share a link to a minimal reproduction sample? Thanks!

**Comment by felangel** [comment] 2023-11-07 04:13
Closing for now since there aren't any actionable next steps. If this is still an issue please provide a link to a minimal reproduction sample and I'm happy to take a look, thanks!

**Closed by felangel** 2023-11-07 04:13 UTC
Labels: question, waiting for response, needs repro info
