### ISSUE TITLE
pushNamed and new state

### ISSUE THREAD

**Issue by eliudio** [felangel/bloc#2938] opened 2021-11-11 07:15 UTC
Hi

I have a situation where I have an event in my bloc which requires:

1) a new state to be set / yielded from the bloc
2) a new page to be pushed through navigation (https://api.flutter.dev/flutter/widgets/Navigator/pushNamed.html)

Today I push the new page then yield the new state. The result is that the new page is opened with the old state then gets a new state. I want these 2 steps combined in 1 so that the new page is opened with the new state. How can this be done?

Thanks

Eliud

**Comment by narcodico** [comment] 2021-11-11 07:32
Hi @eliudio 👋

You can add the event, yield the new state and then use a `BlocListener` to check for that state and `pushNamed` your route.

**Comment by Gene-Dana** [comment] 2021-11-12 13:00
hi ! Just for clarity, it looks something like this ! 
```dart
 @override
  Widget build(BuildContext context) {
    return BlocListener<CategorySelectCubit, CategorySelectState>(
      listener: (context, state) async {
        if (state.status == CategorySelectStatus.created) {
          unawaited(
            Navigator.of(context).push(
              PlayFlow.route(state.game),
            ),
          );
        }
```

**Comment by eliudio** [comment] 2021-11-12 14:38
Thanks

I'm struggling a bit with this. I have implemented this as suggested. However, I seem to have repeated calls to the listener.

For simplifying the explain, let's say I have :

1. a MaterialApp with onGenerateRoute referring to myOnRouteGenerate
2. myOnRouteGenerate retrieves uses the arguments from the RouteSettings to return a Page widget
3. a Bloc which evaluates a "GotoPageEvent" and yields a PageState with some pageId
4. the widget "Page", 
- which shows the contents of a page with the pageId which it finds from the state, i.e. the widget retrieves this data from a firestore db with the pageId
- has a next-page button which send a GotoPageEvent(currentPage + 1)
5. the PageWidget has the BlocListener implemented and Navigator.of(context).pushNamed

When the next page is triggered:
1) the GotoPageEvent is added to the bloc 
2) the bloc yields the PageState with the page ID from the GotoPageEvent
3) the bloclistener is triggered with PageState and navigates to a new page using Navigator.of(context).pushNamed(...)
4) the myOnRouteGenerate is triggered 
5) the myOnRouteGenerate  create a new Page widget and wraps it inside a FadeRoute
6) and then sadly the bloclistener is hit again for 3, 4, and 5 to repeat, a couple of times. It's obviously slow and the fading isn't there neither. Any idea?

**Comment by eliudio** [comment] 2021-11-12 21:08
I've noticed that steps 3, 4 and 5 are triggered for all pages in the history.

A. Upon opening the app, the listener is triggered and a first pushNamed is run
B. Pressing next page, the listener is run for page where pagestate = page 1, the pushNamed is run and the listener is called ones again for page where pagestate = page 2
C. Pressing next page, the same repeats but now for page 1, page 2 and page 3
D. and so on, the next time page 1, 2, 3 and 4
C...

**Comment by eliudio** [comment] 2021-11-13 10:31
Hi,

to illustrate the issue in code form, as well as document the pattern, I've created this github repo: https://github.com/eliudio/bloc_nav

Put a breakpoint line 157 in main.dart. Debug the app. Press the '+' button a few times. You will see 
- the first time you press '+' button, the breakpoint is hit twice.
- the second time you press '+' button, the breakpoint is hit 4 times.
- the third time ... hit 9 times

This just seems to exponentially increase. Obviously in this app, you don't notice it as there's not much going on in the widget. But in case there's some processing going on, obviously this problem becomes a huge problem. 

Any thoughts?

**Comment by eliudio** [comment] 2021-11-13 20:20
Right... In my quest to try and learn from examples how to do this, I stumbled upon :

https://github.com/felangel/bloc/issues/2938

I've taken that example but rather than have "pop" I've implemented the Go to Page B. So we can simulate how a complex application could work with navigation implemented in this way. Basically you want to be able to navigate from page to page to page to page.  The result is copied below. I've added some logging as well. From the logging you can see the same unexpected / incorrect behaviour: going to pageB works fine, going back to pageA works fine as well, but then we get this funny behaviour where all the listeners of the widgets in the history gets triggered as well... I think. Basically, the output logfile is:

    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageB');
    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageA');
    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageB');
    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageB');
    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageA');
    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageA');
    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageA');
    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageB');
    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageB');
    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageB');
    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageB');
    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageB');
    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageA');
    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageA');
    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageA');
    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageA');
    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageA');
    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageA');
    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageA');
    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageA');

The output should be:

    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageB');
    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageA');
    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageB');
    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageA');
    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageB');
    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageB');
    I/flutter ( 6717): Navigator.of(context).pushNamed('/pageA');

The code:
    import 'package:flutter/material.dart';
    import 'package:meta/meta.dart';
    import 'package:bloc/bloc.dart';
    import 'package:flutter_bloc/flutter_bloc.dart';
    
    void main() {
      runApp(
        BlocProvider(
          create: (context) => MyBloc(),
          child: MyApp(),
        ),
      );
    }
    
    enum MyEvent { eventA, eventB }
    
    @immutable
    abstract class MyState {}
    
    class StateA extends MyState {}
    
    class StateB extends MyState {}
    
    class MyBloc extends Bloc<MyEvent, MyState> {
      MyBloc() : super(StateA());
    
      @override
      Stream<MyState> mapEventToState(MyEvent event) async* {
        switch (event) {
          case MyEvent.eventA:
            yield StateA();
            break;
          case MyEvent.eventB:
            yield StateB();
            break;
        }
      }
    }
    
    class MyApp extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return MaterialApp(
          routes: {
            '/': (context) => PageA(),
            '/pageB': (context) => PageB(),
            '/pageA': (context) => PageA(),
          },
          initialRoute: '/',
        );
      }
    }
    
    class PageA extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return BlocListener<MyBloc, MyState>(
          listener: (context, state) {
            if (state is StateB) {
              print("Navigator.of(context).pushNamed('/pageB');");
              Navigator.of(context).pushNamed('/pageB');
            }
          },
          child: Scaffold(
            appBar: AppBar(
              title: Text('Page A'),
            ),
            body: Center(
              child: RaisedButton(
                child: Text('Go to PageB'),
                onPressed: () {
                  BlocProvider.of<MyBloc>(context).add(MyEvent.eventB);
                },
              ),
            ),
          ),
        );
      }
    }
    
    class PageB extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return BlocListener<MyBloc, MyState>(
          listener: (context, state) {
            if (state is StateA) {
              print("Navigator.of(context).pushNamed('/pageA');");
              Navigator.of(context).pushNamed('/pageA');
            }
          },
          child: Scaffold(
            appBar: AppBar(
              title: Text('Page B'),
            ),
            body: Center(
              child: RaisedButton(
                child: Text('Go to PageA'),
                onPressed: () {
                  BlocProvider.of<MyBloc>(context).add(MyEvent.eventA);
                },
              ),
            ),
          ),
        );
      }
    }

**Comment by eliudio** [comment] 2021-11-13 20:22
This doesn't seem to be bullet proof if I may say so. I've tried this for a more complex application where we would be navigating through various pages. It seems that navigating to various pages, there's something going wrong. I've adjusted the sample code slightly to illustrate this, and commented about it here: https://github.com/felangel/bloc/issues/2938

**Comment by eliudio** [comment] 2021-11-16 15:06
Also see https://gist.github.com/felangel/6bcd4be10c046ceb33eecfeb380135dd#gistcomment-3961544

**Comment by Gene-Dana** [comment] 2021-11-19 12:26
May you share with us the repo of your example?

**Comment by eliudio** [comment] 2021-11-19 13:23
Yes, I shared it earlier: https://github.com/eliudio/bloc_nav

**Comment by eliudio** [comment] 2021-11-23 08:08
@Gene-Dana, any luck?

**Comment by chonghorizons** [comment] 2021-12-13 23:57
This is based on about 20 minutes of reading your code, so sorry if I'm not grokking it all.
I think the issue is that you have the following nested structure (in [this version](https://github.com/felangel/bloc/issues/2938#issuecomment-968023280)  which isn't illegal, but has a lot of debugging headaches:

BlocProvider for AccessState
StatefulWidget
BlocListener
BlocBuilder

any change of the Bloc state will trigger a complete rebuilding of StatefulWidget.  That will trigger a complete rebuild of the subtree. So, even when the bloc's state doesn't change, the BlocListener re-reruns because of the rebuild.

See my comments in https://github.com/felangel/bloc/issues/3008#issuecomment-993002127

This is intended behavior and not a bug. You can maybe avoid it (in a fragile way) using same globalKey to avoid re-building.

You can completely avoid it by removing the StatefulWidget.

---
tag #BestPractices. #AvoidNestedStatefulWidgetsBecauseOfUnintendedRebuilds

**Comment by chonghorizons** [comment] 2021-12-14 02:37
Update: I was mistaken... it isn't because of the nesting, not exactly.

It has to do with interaction of Navigator and the blocListeners.

I think you are intending for *only the top-of-Navigator-stack listener* to push a new page. But, in fact, every listener is pushing a new page. This is intended behavior. You might have a dashboard that wants to update for every page.

I added some debug print statements to make this clearer.

![Screen Shot 2021-12-13 at 6 15 36 PM](https://user-images.githubusercontent.com/36284839/145921392-75881c3b-4c86-43bd-8b42-0383d7089279.png)

> TIP: pay close attention to the widget tree. And count the blocListeners.

You can clone my repo or look at the diff: https://github.com/chonghorizons/bloc_nav/commit/aaf43351ef74eacdf15f0d4119ff0ef3677710dc
 
I *think* you can put the `Navigator.push` in the bloc.

### CURRENT WAY
button click
bloc gets new page event
bloc emits new page
blocListener (every one) does a `Navigator.push`
blocBuilder (every one) runs one or more times, and updates the number on each page in the stack.

> tip: builders can run multiple times so shouldn't have side effects that can't run twice.

### NEW WAY
button click
bloc gets new page event
bloc runs `Navigator.push` once.
blocListener (every one) runs exactly once, but doesn't do anything.
blocBuilder (every one) runs one or more times, and updates the number on each page in the stack.

---
Alternatively, you can use [`listenWhen`](https://pub.dev/documentation/flutter_bloc/latest/flutter_bloc/BlocListener-class.html) to only run Navigator.push for the page that is the top of the stack. You need to then implement logic so that the PageState knows which one is on top. This could be fragile and error prone.

**Comment by chonghorizons** [comment] 2021-12-14 02:39
If this addresses things (at least in terms of bloc), please consider closing the issue. If not, please clarify where I misunderstood your expected behavior vs actual behavior.

**Comment by eliudio** [comment] 2021-12-14 05:33
@chonghorizons Thanks very much looking into this.

You make it sound as if I'm using bloc in a not illegal yet unusual unintended way. I disagree with that, but let's try not to have the conversation about that, rather about the core of the issue: using listener to navigate. Hence why I've also used an EXISTING example, which I slightly changed:

https://gist.github.com/felangel/6bcd4be10c046ceb33eecfeb380135dd#gistcomment-3961544

I've changed it in a way that you explain doesn't work: I've changed the example to NOT ONLY navigate from the top level, but indeed I want to show that navigation isn't working, except from the first page / "top level". 

If one claims that the listener can be used to navigate, and it's only usable from the first page in your app, not from any other page, than surely this should be part of the description. To me, you're basically saying: don't use listener to navigate, unless it's in that rare case where you want to use it from the first page in your app. And yeah, I have implemented my app to navigate from the bloc. It's dirty, and it's not good because I have a state change and navigation change that are now handled in 2 steps sadly. But that's how it is.

I can obviously close this case, but shouldn't the documentation not clearly state "DON'T USE THIS MECHANISM UNLESS THIS IS USED FROM THE FIRST PAGE"?

thanks

**Comment by chonghorizons** [comment] 2021-12-14 06:27
I think I came off too strong for trying to give lots of details. Didn't mean to. If I came across that way, I apologize.

In Nov 13, you wrote
> Recap: the issue is that the listener is called multiple times.

The issue isn't that "the (single) listener" is called multiple times. That would be a bug. Each individual listener is called exactly once. But here there are have multiple listeners. So listeners are called more than once. In other cases, rebuilds of widgets cause things to happen more than once.

If you move the listener so that there is only one, then you will be fine. The navigation will be called only once.

The second post said:
> Hi @eliudio 👋
> 
> You can add the event, yield the new state and then use a `BlocListener` to check for that state and `pushNamed` your route.

And that can be done straightforwardly, like if you had different pages without linking/recursion. Like HomePage, DetailsPage, PreferencesPage.


Try this: Move your blocListener out of PageComponent and as the widget just under MaterialApp. There will be one blocListener. It will run once for each update.

These are tricky things, thinking about where to put the blocListener, the widget tree, and rebuilds.

**Comment by felangel** [comment] 2021-12-23 00:22
Closing for now but feel free to comment with any additional questions and I'm happy to continue the conversation 👍

**Closed by felangel** 2021-12-23 00:22 UTC
Labels: question, waiting for response

**Comment by eliudio** [comment] 2021-12-27 09:49
It is what it is, right? Basically listener pattern can not be used to navigate, unless you use it in your app at the top level and navigate to a page, but that page can never navigate to any other page. That's the only conclusion I can make from the feedback. I've used your existing example, slightly changed the pattern to actually allow to navigate from page A -> page B -> page C, my points have not been addressed and we seem to be goin in circles about multiple listeners and stuff. Case close: don't use listener to navigate (unless an extreme simple navigation).

**Comment by narcodico** [comment] 2021-12-27 10:35
`BlocListener`s are actually extremely useful for side effects like navigation. You don't necessarily have to place it on top level to be efficient with it. You could also have a look at `flow_builder`, it's great for controlling feature specific navigation.

**Comment by felangel** [comment] 2021-12-27 15:22
@eliudio this is working as expected. When you push multiple pages which each have a BlocListener that is listening to the same bloc state all BlocListener instances will be listening because all pages are still mounted in the widget tree. BlocListener only stops listening when it is no longer mounted.

**Comment by chonghorizons** [comment] 2022-02-01 12:20
> `BlocListener`s are actually extremely useful for side effects like navigation. You don't necessarily have to place it on top level to be efficient with it. You could also have a look at `flow_builder`, it's great for controlling feature specific navigation. 

@narcodico 

I agree a lot. If I recall correctly, flow_builder only keeps one page mounted in the widget tree at once for the flow. And uses popAndPush to move between pages. So blocListener works well, because only one flow is mounted at once.

 

___

I sympathize with @eliudio 's frustration about navigation. There are many ways to do it. And it is a common gotcha for both new bloc users and flutter users.

Tackling navigation has a good understanding of the widget tree as a prerequisite.

There are some nuances about Navigator.push vs Navigator.popAndPush.

---

Some people have bemoaned why Google has made navigation so complex, especially with Navigator 2.0

My outsider opinion is that it IS complex. Because Google is trying to make the same flutter codebase work for iOS, Android, mobile web (WebView), desktop web, and native. Including with deep links, and interaction with (cached) state/cookies/etc.

**Comment by narcodico** [comment] 2022-02-01 12:26
@chonghorizons flow builder keeps a stack of pages.

**Comment by eliudio** [comment] 2022-02-01 13:12
@chonghorizons ... to be honest, I've completely given up on the idea of navigating from a widget and sadly instead I'm using navigation from the bloc. It's not ideal, but I can't spend time on this now. It works as it is, actually pretty good. Not sure why you suggest this has much to do with Google. Anyway... Maybe one day I'll have the time to dig deeper into this topic. For now, I've left it as it is.

I'm mostly frustrated in assuming the suggestion of using a BlocListener to be anything that could yield into something useful. It's not. It only works in a rare condition, not in a real-world app. At least not as far as I believe I've proven in my examples. The frustration is therefore more to do with the documentation, rather than the functionality.

**Comment by chonghorizons** [comment] 2022-02-01 13:32
> @chonghorizons flow builder keeps a stack of pages.

@narcodico 

Are they all mounted to the widget tree? I think only one is mounted at a time.


Example

If the stack is [a,b,c]

Widget tree has a when flow starts,
Then pop and push to get b,
Then pop and push to get c.

**Comment by narcodico** [comment] 2022-02-01 13:35
@chonghorizons you control which pages are mounted with `onGeneratePages`

**Comment by erlangparasu** [comment] 2023-10-12 10:04
> @eliudio this is working as expected. When you push multiple pages which each have a BlocListener that is listening to the same bloc state all BlocListener instances will be listening because all pages are still mounted in the widget tree. BlocListener only stops listening when it is no longer mounted.

@felangel this is what i expect, but currently when i try using same bloc object and pass it to other page, then use it for BlocListener, the listener is not invoked after reopen the page.
