### ISSUE TITLE
Notifying more than one State will only consume the latest one.

### ISSUE THREAD

**Issue by joanpuigsanz** [felangel/bloc#173] opened 2019-03-27 12:40 UTC
**Describe the bug**
When notifying 2 consecutive state changes inside `mapEventToState` only the latest state is propagated to the `BlocBuilder`.

**To Reproduce**
Just add the following code and call `myBloc.dispathc(TestEvent1())`:
```
  @override
  Stream<MyState> mapEventToState(SectorState currentState, SectorEvent event) async* {
    if (event is TestEvent1) {
      yield TestState1();
      // await Future.delayed(Duration(milliseconds: 250), () {}); // Uncomenting this line will fire both States 
      yield TestState2();
    }
  }
```

**Expected behavior**
The `BlocBuilder` should notify both state changes.

**Comment by felangel** [comment] 2019-03-27 13:16
Hi @joanpuigsanz 👋 

Thanks for opening an issue!

Could you describe what you’d expect to see and what your use case is? 

If you yield two states consecutively there is no time for BlocBuilder to rebuild. By the time the widgets are marked for update the state will have changed again.

Hope that helps! 👍

**Comment by joanpuigsanz** [comment] 2019-03-27 15:21
I'm using the Bloc class no notify the widget when the progress dialog needs to be show, for instance:

```
  @override
  Stream<MyState> mapEventToState(SectorState currentState, SectorEvent event) async* {
    if (event is TestEvent1) {
      yield ShowLoadingState();
      // Do some async tasks
      yield HideLoadingState();
      yield DataResults(hasError);
    }
  }

```

For now the way I fix it is to `dispatch` a new internal event that creates yields the `HideLoadingState()` state. How do you recommend me to improve this issue?

**Comment by felangel** [comment] 2019-03-27 16:04
Thanks for the extra details! I'm wondering why do you even need to yield the `HideLoadingState` event? Isn't it implied that you need to hide the loader when you get the `DataResults` state?

**Comment by joanpuigsanz** [comment] 2019-03-27 16:13
What if I have two blocs and each one perform some background operations? Shall I make the presenter responsible for hiding the loading?

**Comment by felangel** [comment] 2019-03-27 16:29
Then each bloc should yield a loading state, do the async work, and yield a loaded state. The UI should be responsible for showing the loading indicator when the state is loading and removing it when the state is loaded. Let me know if that makes sense.

**Comment by felangel** [comment] 2019-03-27 18:53
Closing for now but feel free to comment with additional comments/questions and I'm happy to reopen/continue the conversation. 👍

**Comment by joanpuigsanz** [comment] 2019-03-28 07:07
Yes, it make sense but if the two blocks finish at the same time one of the states will get lost because the BlocBuilder will only process the last one. Is this a bug?

**Comment by felangel** [comment] 2019-03-28 12:34
I’m not sure I understand what you mean. BlocBuilder only reacts to changes in a single bloc so if two blocs finish at the same time it shouldn’t matter because you’d have two BlocBuilders. Does that help?

**Comment by joanpuigsanz** [comment] 2019-03-29 14:16
I have one bloc which it listens to a document in the Firestore DB. When this document is changed the bloc fires a new `DocumentUpdated` state with the new document information.

When I change the document in the app later is uploaded and a new `Loading` state is fired. When document is successfully uploaded the bloc fires a new state `DocumentLoaded` but as the bloc is also listening to any document change in the server the bloc also fires a the state `DocumentUpdated`. I would expect the BlocBuilder to receive both states as each state updates a different thing in the UI, but I'm only getting the `DocumentUpdated` state and not the `DocumentLoaded` state.

Right now I have some workaround in place to fix this issue but it doesn't fell like it is the correct way to go. I think the BlockBuilder should be able to queue all the states and process all the states, only the last one if more states have been fired at the same time.

Thanks for the info btw.

**Comment by felangel** [comment] 2019-03-29 21:52
@joanpuigsanz thanks for the additional details. I'll try to investigate this further over the next few days 👍

**Comment by felangel** [comment] 2019-03-30 19:08
@joanpuigsanz after investigating this I don't think is a bug in BlocBuilder. This is just how flutter works. If you do the following: 

```dart
setState(() {
    _state = state;
});
setState(() {
    _state = state;
});
```

You'll see the exact same behavior. I've put together a [gist](https://gist.github.com/felangel/d32a3a0982c29777b5560b3993236cba) that has nothing to do with Bloc and exhibits the same behavior you are seeing.

If you feel this is a bug with Flutter, I'd recommend opening an issue on Flutter and see what they think.

Thanks! 👍

**Closed by felangel** 2019-03-30 19:08 UTC
Labels: bug, investigating

**Comment by joanpuigsanz** [comment] 2019-04-01 08:53
Thanks for the info! very apreciated

**Comment by midhunarmid** [comment] 2019-05-24 16:46
Hi @joanpuigsanz 

Sorry if it sounds a bit off-topic, but could you please share any hint regarding how you solve this issue?
> Right now I have some workaround in place to fix this issue but it doesn't fell like it is the correct way to go.

Hi @felangel 
Sorry to trouble you but I am stuck in an application development due to the same issue.
In my case, I have a `TextField` inside the view (`Scaffold`) returned from the `builder`.
Whenever the softinput keyboard is displayed and hidden, the `build` is calling, and last reported `state` is again fired.
```
@override
  Widget build(BuildContext context) {
    return BlocBuilder<CheckinEvent, CheckinState>(
        bloc: _checkinBloc,
        builder: (BuildContext context, CheckinState state) {
          return Container(); /* Its not actual implementation, just dummy */
        }
    );
  }
```

So to solve this I tried with `yield`  an `IdleState` just after the actual state as follows:
```
    yield CheckinStateFailure(error: error.toString());
    yield CheckinStateInitial();
```

But in this case, only the second state is getting fired.

Is there any solution to trigger 2 states like above mentioned?

Thanks in advance!

**Comment by joanpuigsanz** [comment] 2019-05-25 09:27
Hello @midhunarmid
For the keyboard issue I just place a guard in the bloc to check if it is the same state to check if I need to update the data:

```
@override
Widget build(BuildContext context) {
   return BlocBuilder<GymEvent, GymState>(
        bloc: _bloc,
        builder: (BuildContext context, state) {
          // Because of the text editor we need to check if the previous state is the same
          if (_previousState != state) {
            // Update my data
          }
          _previousState = state;

          return Container();
        },
      )
```

Inside the bloc, If I have to fire 2 states, I use the method `dispatch` inside the bloc, an example would be the following:

```
class MyBloc extends Bloc<MyEvent, MyState> {

  _someOtherTask() {
   yield LoadingEvent();
  // Some calculations
  dispatch(EventWithState(MyNyewState(data)));
  }

 @override
  Stream<MyState> mapEventToState(event) async*{
  if (event is EventWithState) {
    yield event.state;
  } 
  // ...
 }
}
```

**Comment by felangel** [comment] 2019-05-25 18:02
@midhunarmid are you able to put together a sample app which illustrates the problem you're having? It would be much easier for me to help if I can run the application locally.

In general, the build method of a widget can be called hundreds of times by Flutter. It is out of your control and as a developer, you need to make sure that the build method is a pure function that has no side-effects. It sounds like in your case you have logic that should only execute once per state change; in that case you should move that logic into a `BlocListener`. You can refer to the [Snackbar Recipe](https://felangel.github.io/bloc/#/recipesfluttershowsnackbar) for an explanation of when to use `BlocBuilder` vs `BlocListener`.

Hope that helps 👍

**Comment by midhunarmid** [comment] 2019-06-07 09:43
Hi @joanpuigsanz, Thank you very much for your help. With your sample code, now it is clear how to handle the situation, it helped me out a lot. Thanks Again.

@felangel 
First of all, I am really sorry for wasting your valuable time by asking a question before completely reading your awesome tutorials out [here](https://felangel.github.io/bloc/#/flutterinfinitelisttutorial).
At the time of asking the question, I was unaware of `BlocListener` and tried to handle all the states by only using `BlocBuilder`.

Now my cloud of doubts is moving faster and I am learning things in BLoC. 👍 
BLoC is really super cool..!! Thanks for BLoC and all these quick support you are providing. 👍

**Comment by kazbeksultanov** [comment] 2020-12-11 10:59
And almost a half year later, here I am pointing to the same issue. Sorry for repeating the same stuff, but I have the following idea.

Currently, we can solve rebuilding the state by adding even `await Future.wait([]);` or`await Future.delayed(Duration.zero);` after the state, but I don't think that this is a good solution.

Maybe it will be better to create some build-in solution as invoking `RebuildState` which take state and will run one of the above code after it. This will ensure that that state started the rebuilt. So, I see it like `yield RebuildState(LoadingState());`
Existing of this `RebuildState` from the day 1 of using bloc will set in mind of the developer that yielding state one after another will not cause anything if it is not wrapped by RebuildState` or after it has some `await` function.

I have used `bloc` for several months but still some time encounter in to this situation of misunderstanding source of the bug.

I don't know how to make it in a good way. And writing `await Future.wait([]);` each time after I want to start rebuild after state, it is not an elegant solution.

What do you think about it @felangel ?

**Comment by felangel** [comment] 2021-01-06 06:16
@kazbeksultanov can you please provide a reproduction sample which illustrates the problem you're encountering? Thanks 👍

**Comment by saurabhdtu** [comment] 2021-04-09 04:58
Hi @felangel 
I am new to flutter and was stuck at a typical problem in Bloc
I have put it as a question too on [Stackoverflow](https://stackoverflow.com/questions/67006145/how-to-update-a-sliverappbar-widget-on-state-change-in-blocbuilder).
Basically, I want to update content in SliverAppBar which is not part of BlocBuilder on state updates inside the BlocBuilder. How to publish the changes to widgets that are outside? You can find more details on the question

**Comment by saurabhdtu** [comment] 2021-04-09 07:41
> Hi @felangel
> I am new to flutter and was stuck at a typical problem in Bloc
> I have put it as a question too on [Stackoverflow](https://stackoverflow.com/questions/67006145/how-to-update-a-sliverappbar-widget-outside-of-blocbuilder-on-state-change).
> Basically, I want to update content in SliverAppBar which is not part of BlocBuilder on state updates inside the BlocBuilder. How to publish the changes to widgets that are outside? You can find more details on the question

Solved it by using BlocConsumer
