### ISSUE TITLE
feat: HydratedBloc: make it work only on state restoration?

### ISSUE THREAD

**Issue by ksiom** [felangel/bloc#3900] opened 2023-07-07 11:52 UTC
**Description**

Hi, thanks for making such a great library and I enjoy using it. However, I have a case where process kill occurs due to insufficient memory or etc. while using the app, so when I looked it up, I found many answers that I can use hydrated_bloc for bloc.
 However, this hydrated_bloc library seems to keep saving the state even if the app is closed by the user. I want to restore the state only at the moment when it is restored by the RestorationManager.

 I've been looking for a guide or example on how to do this, but it doesn't seem to exist - how can I do this?

**Desired Solution**

Documentation on how to restore state only from process kill by OS.

**Comment by ksiom** [comment] 2023-07-07 11:57
Maybe I should change the enclosing widget to stateful & restorationmixin to set the initial state for the bloc?

**Comment by felangel** [comment] 2023-07-15 05:42
Hi @ksiom 👋 
Thanks for opening an issue!

> Maybe I should change the enclosing widget to stateful & restorationmixin to set the initial state for the bloc?

This seems like a reasonable place to start. Were you able to resolve your issue? If not, could you please provide a link to a minimal reproduction sample with more context regarding what you're trying to achieve and I'm more than happy to take a closer look 👍

**Comment by felangel** [comment] 2023-07-18 15:21
Closing for now since there appear to be no actionable next steps. Feel free to comment with additional info/questions and I'm happy to continue the conversation 👍

**Closed by felangel** 2023-07-18 15:21 UTC
Labels: question, waiting for response
