### ISSUE TITLE
chore: Persisting state having a model

### ISSUE THREAD

**Issue by mado-bohsali** [felangel/bloc#2804] opened 2021-09-27 19:43 UTC
How can I persist a state having a model? Example, a user opens a quiz app (question model and answer model) then force closes it. I wanna restore the question and its options.

Efforts appreciated!

**Comment by marcossevilla** [comment] 2021-09-27 19:48
hi @mado-bohsali! have you tried using [hydrated_bloc](https://pub.dev/packages/hydrated_bloc)?

**Comment by mado-bohsali** [comment] 2021-09-27 19:51
I tried it with the basic counter project. But when it comes to complex models I get confused a bit.

**Comment by mado-bohsali** [comment] 2021-09-27 19:51
How do I emit a question or answer model?

**Comment by marcossevilla** [comment] 2021-09-27 20:06
> I tried it with the basic counter project. But when it comes to complex models I get confused a bit.

You can take a look at [this](https://github.com/NoScopeDevs/bloc_samples/blob/af4095a8cf2ec824da5c3c649a6a394126793c58/examples/launch_analytics/lib/app/bloc/app_bloc.dart#L32) small example which has different states that can be persisted.

It should be straightforward from then, you need to define your models into a specific state class and define its (de)serialization on your bloc.

Is the following example similar to what you have?

```dart
class QuizInProgress extends QuizState {
    QuizInProgress({
        required this.answer, 
        required this.question,
    });

    final Question question;
    final Answer answer;
}
```

If you're still confused, you can share a code snippet of your state classes and your bloc so I can give you better advice. 👍

**Comment by mado-bohsali** [comment] 2021-09-27 20:20
<img width="733" alt="Screen Shot 2021-09-27 at 11 16 52 PM" src="https://user-images.githubusercontent.com/18421260/134979161-c7693b7e-74e5-4ed5-a3ba-078fdcd9c654.png">
<img width="769" alt="Screen Shot 2021-09-27 at 11 17 46 PM" src="https://user-images.githubusercontent.com/18421260/134979188-a54c5d1b-48a1-424f-b627-a1bd715b8939.png">
<img width="587" alt="Screen Shot 2021-09-27 at 11 17 17 PM" src="https://user-images.githubusercontent.com/18421260/134979206-7233f8a2-f81e-463b-b50b-e88048cf2718.png">

Why did you make QuizInProgress extend QuizState? Shouldn't QuizState contain a reference to answer and option? But the trick is that how do you do the emit part?

**Comment by marcossevilla** [comment] 2021-09-27 20:31
@mado-bohsali I made QuizInProgress because I thought you had more than one state class. 

HydratedCubit persists your state automatically, so what you have should be saved on storage when your app is closed. You just need to emit the state with the properties you want to save before.

Can you explain exactly what isn't working and the desired behavior you want? I can see the saveQuestion method just emits the same state you specify as the initial state, so that can be the issue.

**Comment by felangel** [comment] 2021-10-04 20:00
@mado-bohsali closing for now since there isn’t enough information to take actionable next steps. Feel free to provide additional information and/or a link to a reproduction sample and I’m happy to continue the conversation 👍

**Closed by felangel** 2021-10-04 20:00 UTC
Labels: question
