### ISSUE TITLE
bloc/examples/flutter_firebase_login/lib/register/register_form.dart fails

### ISSUE THREAD

**Issue by nicktran29** [felangel/bloc#544] opened 2019-09-30 10:26 UTC
**Describe the bug**
After successfully registering a new user, the form is unable to access AuthenticationBloc.
bloc/examples/flutter_firebase_login/lib/register/register_form.dart
```
if (state.isSuccess) {
          BlocProvider.of<AuthenticationBloc>(context).dispatch(LoggedIn());
          Navigator.of(context).pop();
        }
```

This is because navigating to this page from the login page has result in the loss of the current context.
https://github.com/felangel/bloc/blob/master/examples/flutter_firebase_login/lib/login/create_account_button.dart
```
Navigator.of(context).push(
          MaterialPageRoute(builder: (context) {
            return RegisterScreen(userRepository: _userRepository);
          }),
        );
```

**To Reproduce**
1. Go to Login
2. Click on Create an Account
3. Fill out the form and click create

**Expected behavior**
After registering user should see the home page

**Comment by felangel** [comment] 2019-10-01 03:28
Hi @nicktran29 👋 
Thanks for opening an issue!

Unfortunately, I was unable to reproduce the issue you're describing. There shouldn't be a problem accessing the `AuthenticationBloc` because it is provided above the `MaterialApp` making it globally accessible (even across routes).

Can you please confirm that you're running the example app without any local modifications?

Closing for now but feel free to comment with additional information and I'm happy to continue the conversation 👍

**Closed by felangel** 2019-10-01 03:28 UTC

**Comment by nicktran29** [comment] 2019-10-04 01:48
Hi @felangel,

Thanks for looking into this.

My issue was I provided the bloc inside MaterialApp. So I guess my question is what do I need to do in order to access a bloc provided to a widget that I'm navigating away from?

Cheers.

**Comment by nicktran29** [comment] 2019-10-04 01:59
Don't mind me I found the way in your recipe. Great lib and documentation! https://felangel.github.io/bloc/#/recipesflutterblocaccess
