### ISSUE TITLE
feat: discriminate same type of blocs

### ISSUE THREAD

**Issue by Jaew00Shin** [felangel/bloc#3872] opened 2023-06-10 12:29 UTC
**Description**

```
final first = BlocA();
final second = BlocA();
return MultiBlocProvider(
  providers: [
    BlocProvider(create: (_) => first),
    BlocProvider(create: (_) => second),
  ],
  child: ...,
);
```

When we try to provide same type but different two blocs, 
we can only find onlly second object and cannot find first object 
from BlocListener or BlocBuilder at child.

**Desired Solution**

I want to discriminate them by naming as well as just type.

```
final first = BlocA();
final second = BlocA();
return MultiBlocProvider(
  providers: [
    BlocProvider(create: (_) => first, name: 'first',),
    BlocProvider(create: (_) => second, name: 'second'),
  ],
  child: ...,
);
```

```
return BlocBuilder<BlocA, StateA>(
    name: 'first'
    builder: ...
  );
```

**Comment by felangel** [comment] 2023-06-28 05:11
Hi @Jaew00Shin 👋 
Thanks for opening an issue!

Can you please provide more context regarding why you would want to provide multiple instances of the same bloc to the same sub-tree? Thanks!

**Comment by felangel** [comment] 2023-07-15 05:45
Closing for now since there is no reproduction sample. Feel free to provide a link to a minimal reproduction sample and I'm happy to take a closer look 👍

**Closed by felangel** 2023-07-15 05:45 UTC
Labels: question, waiting for response
