### ISSUE TITLE
State yield issue

### ISSUE THREAD

**Issue by Sandesh-Solabannavar** [felangel/bloc#966] opened 2020-03-17 07:39 UTC
i have called multiple events as below.
![image](https://user-images.githubusercontent.com/23529429/76832701-de546780-684f-11ea-9737-cb126dd2fd56.png)

one the event is called based on event im doing yield as below
![image](https://user-images.githubusercontent.com/23529429/76832985-73576080-6850-11ea-9475-328d4495213d.png)

Sample code for single yield
![image](https://user-images.githubusercontent.com/23529429/76832793-1360ba00-6850-11ea-9e82-38f0d219a780.png)

The issue im facing is im getting  Loaded yield for all events, im getting only loaded yield for last event.

**Comment by felangel** [comment] 2020-03-17 15:49
Hi @Sandesh-Solabannavar 👋 
Thanks for opening an issue!

I'm not sure I fully understand the question. Are you able to provide a link to a sample app which illustrates the problem you're facing?

A quick note based on the code snippets you provided, I would highly recommend breaking this logic out into separate, smaller blocs rather than having one "MasterBloc".

**Comment by felangel** [comment] 2020-03-19 15:29
Closing for now since there is no reproduction steps/sample app. Feel free to add additional information/a link to a sample app and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-03-19 15:29 UTC
Labels: question, waiting for response
