### ISSUE TITLE
Using landing page before login page, state update but page not redirected

### ISSUE THREAD

**Issue by hipimy** [felangel/bloc#83] opened 2019-01-29 18:42 UTC
Based on original example for not authorize user will see a login page, but i did little bit modified instead of not authenticate user will see a landing page. User now pick button option for login (consist many option for login email/google/etc) then it will open login page. The problem is after login success the page still at login page not redirected to authenticate page i set. Only work if i click back button of restart app
`class LandingPage extends StatelessWidget {
final UserRepository userRepository;

LandingPage({Key key, this.userRepository}) : super(key: key);

@override
Widget build(BuildContext context) {

 return Scaffold(
  body: Container(
    child: Center(
      child: RaisedButton(
          onPressed: (){

            Navigator.push(context, MaterialPageRoute(
                builder: (context) => LoginPage(userRepository: userRepository,)
            ));
          },
      ),
    ),
  ),
) ;
}

}`

**Comment by felangel** [comment] 2019-01-29 19:16
@hipimy Hello! Can you please share the full source code so that I am better able to understand the issue?

**Comment by hipimy** [comment] 2019-01-29 19:34
` class App extends StatefulWidget {
  final UserRepository userRepository;

  App({Key key, @required this.userRepository}) : super(key: key);

  @override
  State<App> createState() => _AppState();
}
class _AppState extends State<App> {
  AuthenticationBloc authenticationBloc;
  UserRepository get userRepository => widget.userRepository;

  @override
  void initState() {
    authenticationBloc = AuthenticationBloc(userRepository: userRepository);
    authenticationBloc.dispatch(AppStarted());
    super.initState();
  }

  @override
  void dispose() {
    authenticationBloc.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return BlocProvider<AuthenticationBloc>(
      bloc: authenticationBloc,
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        home: BlocBuilder<AuthenticationEvent, AuthenticationState>(
          bloc: authenticationBloc,
          builder: (BuildContext context, AuthenticationState state) {
            if (state is AuthenticationUninitialized) {
              //when first app started
                return SplashScreen();
            }
            if(state is AuthenticationCheckingVerifiedEmail){
              return VerificationPage(userRepository: userRepository);
//              return MyAccount();
            }
            if (state is AuthenticationAuthenticated) {
              //when user authenticated to login
                return MyAccount();
            }
            if (state is AuthenticationUnauthenticated){
              return LandingPage(userRepository: userRepository,);
            }
            if (state is AuthenticationLoading) {
              return LoadingIndicator();
            }
            if (state is VerificationLoading){
              return LoadingIndicator();
            }
          },
        ),
      ),
    );
  }
}
  `

**Comment by felangel** [comment] 2019-01-29 22:47
@hipimy the problem is you are pushing the LoginPage on top of the navigation stack so the App widget is underneath. When you dispatch LoggedIn you need to execute `Navigator.pop(context)`.

Hope that helps!

**Comment by felangel** [comment] 2019-01-30 02:57
Closing this for now but feel free to comment and I'll reopen it 👍

**Closed by felangel** 2019-01-30 02:57 UTC
Labels: question, waiting for response
